{
  "hash": "6f3119a1072b870822e9644f2b7fcd10",
  "result": {
    "markdown": "---\ntitle: \"Homework 3\"\nauthor: \"Danny Holt\"\ndate: \"6/29/2023\"\nformat:\n  html:\n    df-print: paged\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - HW3\n  - strikes\nbibliography: FinalBib_DannyHolt.bib\nnocite: |\n  @*\n...\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(readxl)\n\nknitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# First, we'll read in the data from the Excel sheet `monthly-listing.xlsx`.\n\n  # read in data\n  strike <- read_excel(\"_data/monthly-listing.xlsx\", skip=1)\n\n  # filter out footnotes\n  strike <- head(strike, -6)\n\n# Next, we'll clean the data. First, we'll remove redundant and unnecessary variables. Then, we'll rename some variables with cumbersome or confusing titles.\n\n  # remove redundant and unnecessary variables\n  strike <- strike %>%\n    select(\"Organizations involved\",\"States\",\"Areas\",\"Ownership\",\"Union acronym\",\"Work stoppage beginning date\",\"Work stoppage ending date\",\"Number of workers[2]\",\"Days idle, cumulative for this work stoppage[3]\")\n\n  # rename variables\n  strike <- strike %>%\n    rename(\n      \"Employer\"=\"Organizations involved\",\n      \"Union\"=\"Union acronym\",\n      \"Start date\"=\"Work stoppage beginning date\",\n      \"End date\"=\"Work stoppage ending date\",\n      \"Workers\"=\"Number of workers[2]\",\n      \"Days struck\"=\"Days idle, cumulative for this work stoppage[3]\"\n    )\n```\n:::\n\n\n## Description of the data\n\nThis dataset, `monthly-listing.xlsx`, shows data on work stoppages (strikes) from the Bureau of Labor Statistics, part of the U.S. Department of Labor, from 1993 to 2023 (Bureau of Labor Statistics 2023a). Each case represents a distinct strike. Workers under Work Stoppages program of the Bureau of Labor Statistics track all strikes in the U.S.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# view data\nstrike\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"Employer\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"States\"],\"name\":[2],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Areas\"],\"name\":[3],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Ownership\"],\"name\":[4],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Union\"],\"name\":[5],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Start date\"],\"name\":[6],\"type\":[\"dttm\"],\"align\":[\"right\"]},{\"label\":[\"End date\"],\"name\":[7],\"type\":[\"dttm\"],\"align\":[\"right\"]},{\"label\":[\"Workers\"],\"name\":[8],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Days struck\"],\"name\":[9],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"Marine Towing and Transportation Employers' Association\",\"2\":\"NY\",\"3\":\"New York\",\"4\":\"Private industry\",\"5\":\"ILA\",\"6\":\"1988-02-16\",\"7\":\"1993-12-20\",\"8\":\"2500\",\"9\":\"2879500\"},{\"1\":\"Boeing Company\",\"2\":\"WA\",\"3\":\"Seattle\",\"4\":\"Private industry\",\"5\":\"SPEEA\",\"6\":\"1993-01-19\",\"7\":\"1993-01-19\",\"8\":\"21000\",\"9\":\"21000\"},{\"1\":\"Boston Gas Company\",\"2\":\"MA\",\"3\":\"Boston\",\"4\":\"Private industry\",\"5\":\"USW\",\"6\":\"1993-01-24\",\"7\":\"1993-05-20\",\"8\":\"1000\",\"9\":\"83000\"},{\"1\":\"Bituminous Coal Operators Association\",\"2\":\"IN, IL, KY, WV\",\"3\":\"Multiple states\",\"4\":\"Private industry\",\"5\":\"UMWA\",\"6\":\"1993-02-02\",\"7\":\"1993-03-02\",\"8\":\"6700\",\"9\":\"103400\"},{\"1\":\"Douglas Aircraft\",\"2\":\"CA\",\"3\":\"NA\",\"4\":\"Private industry\",\"5\":\"IAM\",\"6\":\"1993-03-02\",\"7\":\"1993-03-03\",\"8\":\"6800\",\"9\":\"13600\"},{\"1\":\"Allied Signal Corp.\",\"2\":\"VA\",\"3\":\"Hopewell\",\"4\":\"Private industry\",\"5\":\"IBT\",\"6\":\"1993-03-22\",\"7\":\"1993-04-21\",\"8\":\"1600\",\"9\":\"36800\"},{\"1\":\"Dayton Board of Education\",\"2\":\"OH\",\"3\":\"Dayton\",\"4\":\"Local government\",\"5\":\"NEA\",\"6\":\"1993-03-25\",\"7\":\"1993-04-09\",\"8\":\"1900\",\"9\":\"22800\"},{\"1\":\"University of Cincinnati\",\"2\":\"OH\",\"3\":\"Cincinnati\",\"4\":\"State government\",\"5\":\"AAUP\",\"6\":\"1993-03-30\",\"7\":\"1993-04-05\",\"8\":\"1900\",\"9\":\"7600\"},{\"1\":\"Kaiser Permanente\",\"2\":\"CA\",\"3\":\"Southern\",\"4\":\"Private industry\",\"5\":\"SEIU\",\"6\":\"1993-04-01\",\"7\":\"1993-04-01\",\"8\":\"12000\",\"9\":\"12000\"},{\"1\":\"Vallejo Board of Education\",\"2\":\"CA\",\"3\":\"Vallejo\",\"4\":\"Local government\",\"5\":\"NEA\",\"6\":\"1993-04-16\",\"7\":\"1993-04-17\",\"8\":\"1000\",\"9\":\"2000\"},{\"1\":\"Retail food stores - Shoprite, Pathmark, Grand Union, Foodtown\",\"2\":\"NJ, NY\",\"3\":\"Multiple states\",\"4\":\"Private industry\",\"5\":\"UFCW\",\"6\":\"1993-05-07\",\"7\":\"1993-05-29\",\"8\":\"23800\",\"9\":\"246200\"},{\"1\":\"PPG Industries, Inc.\",\"2\":\"CA, PA\",\"3\":\"Multiple states\",\"4\":\"Private industry\",\"5\":\"ABGW\",\"6\":\"1993-05-08\",\"7\":\"1993-07-14\",\"8\":\"1600\",\"9\":\"73200\"},{\"1\":\"Bituminous Coal Operators Association\",\"2\":\"IL, IN, PA,WV, OH, VA, KY\",\"3\":\"Multiple states\",\"4\":\"Private industry\",\"5\":\"UMWA\",\"6\":\"1993-05-10\",\"7\":\"1993-12-14\",\"8\":\"16800\",\"9\":\"2203000\"},{\"1\":\"Fieldcrest Cannon, Inc.\",\"2\":\"NC, VA\",\"3\":\"Multiple states\",\"4\":\"Private industry\",\"5\":\"ACTWU\",\"6\":\"1993-05-17\",\"7\":\"1993-05-18\",\"8\":\"2000\",\"9\":\"4000\"},{\"1\":\"Central Illinois Public Service Company\",\"2\":\"IL\",\"3\":\"Statewide\",\"4\":\"Private industry\",\"5\":\"IBEW, IUOE\",\"6\":\"1993-05-20\",\"7\":\"1993-08-30\",\"8\":\"1600\",\"9\":\"113600\"},{\"1\":\"NBC Merchants, Inc.\",\"2\":\"IN\",\"3\":\"Evansville\",\"4\":\"Private industry\",\"5\":\"ILGWU\",\"6\":\"1993-06-02\",\"7\":\"1993-06-06\",\"8\":\"1300\",\"9\":\"3900\"},{\"1\":\"Frigidaire Company\",\"2\":\"IA\",\"3\":\"Webster City\",\"4\":\"Private industry\",\"5\":\"UAW\",\"6\":\"1993-06-13\",\"7\":\"1993-07-08\",\"8\":\"1200\",\"9\":\"21600\"},{\"1\":\"General Contractors of New York, Inc.\",\"2\":\"NY\",\"3\":\"New York\",\"4\":\"Private industry\",\"5\":\"IUOE\",\"6\":\"1993-07-01\",\"7\":\"1993-07-14\",\"8\":\"4000\",\"9\":\"36000\"},{\"1\":\"Sanitation companies\",\"2\":\"NJ\",\"3\":\"Wayne\",\"4\":\"Private industry\",\"5\":\"IBT\",\"6\":\"1993-07-01\",\"7\":\"1993-07-12\",\"8\":\"1800\",\"9\":\"12600\"},{\"1\":\"Independent Bituminous Coal Bargaining Alliance\",\"2\":\"AL\",\"3\":\"Birmingham\",\"4\":\"Private industry\",\"5\":\"UMWA\",\"6\":\"1993-07-13\",\"7\":\"1993-07-19\",\"8\":\"1200\",\"9\":\"6000\"},{\"1\":\"Cleveland Cliffs, Inc.\",\"2\":\"MI, MN\",\"3\":\"Multiple states\",\"4\":\"Private industry\",\"5\":\"USW\",\"6\":\"1993-08-01\",\"7\":\"1993-09-08\",\"8\":\"2900\",\"9\":\"78300\"},{\"1\":\"Best Form Foundations\",\"2\":\"PA\",\"3\":\"Statewide\",\"4\":\"Private industry\",\"5\":\"ILGWU\",\"6\":\"1993-08-02\",\"7\":\"1993-08-03\",\"8\":\"1000\",\"9\":\"2000\"},{\"1\":\"Greater St. Louis Automotive Assn.\",\"2\":\"MO\",\"3\":\"St. Louis\",\"4\":\"Private industry\",\"5\":\"IAM\",\"6\":\"1993-08-03\",\"7\":\"1993-08-07\",\"8\":\"1700\",\"9\":\"6800\"},{\"1\":\"Philadelphia Gas Works\",\"2\":\"PA\",\"3\":\"Philadelphia\",\"4\":\"Private industry\",\"5\":\"SEIU\",\"6\":\"1993-08-06\",\"7\":\"1993-10-26\",\"8\":\"1800\",\"9\":\"99000\"},{\"1\":\"City Markets, Inc.\",\"2\":\"CO\",\"3\":\"Grand Junction\",\"4\":\"Private industry\",\"5\":\"UFCW\",\"6\":\"1993-08-07\",\"7\":\"1993-09-04\",\"8\":\"1100\",\"9\":\"22000\"},{\"1\":\"Los Angeles Department of Water and Power\",\"2\":\"CA\",\"3\":\"Los Angeles County\",\"4\":\"Local government\",\"5\":\"IBEW, EAA\",\"6\":\"1993-09-01\",\"7\":\"1993-09-09\",\"8\":\"9000\",\"9\":\"54000\"},{\"1\":\"Youngstown Public Schools\",\"2\":\"OH\",\"3\":\"Youngstown\",\"4\":\"Local government\",\"5\":\"NEA\",\"6\":\"1993-09-08\",\"7\":\"1993-10-05\",\"8\":\"1000\",\"9\":\"20000\"},{\"1\":\"Pacific Maritime Association\",\"2\":\"CA\",\"3\":\"San Francisco, Oakland, Sacramento\",\"4\":\"Private industry\",\"5\":\"ILWU\",\"6\":\"1993-09-10\",\"7\":\"1993-09-10\",\"8\":\"1500\",\"9\":\"1500\"},{\"1\":\"Blue Cross Blue Shield of Michigan\",\"2\":\"MI\",\"3\":\"Detroit\",\"4\":\"Private industry\",\"5\":\"UAW\",\"6\":\"1993-09-20\",\"7\":\"1993-11-05\",\"8\":\"3400\",\"9\":\"115600\"},{\"1\":\"Southern California Gas Company\",\"2\":\"CA\",\"3\":\"Southern\",\"4\":\"Private industry\",\"5\":\"UWUA, ICWU\",\"6\":\"1993-10-01\",\"7\":\"1993-10-01\",\"8\":\"6000\",\"9\":\"6000\"},{\"1\":\"Liquor and wine distributors\",\"2\":\"NJ\",\"3\":\"Union County\",\"4\":\"Private industry\",\"5\":\"DWU\",\"6\":\"1993-10-04\",\"7\":\"1993-10-22\",\"8\":\"1000\",\"9\":\"14000\"},{\"1\":\"Dyeing, finishing, and printing companies\",\"2\":\"NY\",\"3\":\"New York\",\"4\":\"Private industry\",\"5\":\"ACTWU\",\"6\":\"1993-10-23\",\"7\":\"1993-12-14\",\"8\":\"2000\",\"9\":\"70000\"},{\"1\":\"Boston Public Schools\",\"2\":\"MA\",\"3\":\"Boston\",\"4\":\"Local government\",\"5\":\"AFT\",\"6\":\"1993-10-27\",\"7\":\"1993-10-27\",\"8\":\"5700\",\"9\":\"5700\"},{\"1\":\"Elevator Industries, Inc.\",\"2\":\"NY\",\"3\":\"Flushing\",\"4\":\"Private industry\",\"5\":\"IBEW\",\"6\":\"1993-11-05\",\"7\":\"1993-11-15\",\"8\":\"1600\",\"9\":\"9600\"},{\"1\":\"Caterpillar, Inc.\",\"2\":\"IL, CO, PA\",\"3\":\"Multiple states\",\"4\":\"Private industry\",\"5\":\"UAW\",\"6\":\"1993-11-11\",\"7\":\"1993-11-14\",\"8\":\"14000\",\"9\":\"14000\"},{\"1\":\"American Airlines\",\"2\":\"Interstate\",\"3\":\"NA\",\"4\":\"Private industry\",\"5\":\"APFA\",\"6\":\"1993-11-18\",\"7\":\"1993-11-22\",\"8\":\"19000\",\"9\":\"57000\"},{\"1\":\"General Motors Corp.\",\"2\":\"LA\",\"3\":\"Shreveport\",\"4\":\"Private industry\",\"5\":\"UAW\",\"6\":\"1994-01-11\",\"7\":\"1994-01-17\",\"8\":\"2500\",\"9\":\"12500\"},{\"1\":\"Continental Baking Company\",\"2\":\"CA\",\"3\":\"Northern\",\"4\":\"Private industry\",\"5\":\"IBT\",\"6\":\"1994-02-04\",\"7\":\"1994-02-11\",\"8\":\"1100\",\"9\":\"6600\"},{\"1\":\"United Parcel Service\",\"2\":\"Interstate\",\"3\":\"NA\",\"4\":\"Private industry\",\"5\":\"IBT\",\"6\":\"1994-02-07\",\"7\":\"1994-02-07\",\"8\":\"40000\",\"9\":\"40000\"},{\"1\":\"Wheeling Pittsburgh Steel Corp.\",\"2\":\"PA, OH, WV\",\"3\":\"Multiple states\",\"4\":\"Private industry\",\"5\":\"USW\",\"6\":\"1994-03-01\",\"7\":\"1994-03-03\",\"8\":\"4700\",\"9\":\"14100\"},{\"1\":\"General Motors Corp.\",\"2\":\"OH\",\"3\":\"Dayton\",\"4\":\"Private industry\",\"5\":\"UAW\",\"6\":\"1994-03-14\",\"7\":\"1994-03-16\",\"8\":\"10900\",\"9\":\"16900\"},{\"1\":\"Health-Tex Inc.\",\"2\":\"VA, AL, GA\",\"3\":\"Multiple states\",\"4\":\"Private industry\",\"5\":\"ACTWU\",\"6\":\"1994-03-14\",\"7\":\"1994-03-16\",\"8\":\"1200\",\"9\":\"3600\"},{\"1\":\"Allegheny Ludlum Corp.\",\"2\":\"Interstate\",\"3\":\"NA\",\"4\":\"Private industry\",\"5\":\"USW\",\"6\":\"1994-04-01\",\"7\":\"1994-06-09\",\"8\":\"3500\",\"9\":\"171500\"},{\"1\":\"Trucking Management Inc.\",\"2\":\"Interstate\",\"3\":\"NA\",\"4\":\"Private industry\",\"5\":\"IBT\",\"6\":\"1994-04-06\",\"7\":\"1994-04-29\",\"8\":\"71000\",\"9\":\"1180500\"},{\"1\":\"Grinnell Fire Protection Systems Company\",\"2\":\"NH\",\"3\":\"Exeter\",\"4\":\"Private industry\",\"5\":\"PPF\",\"6\":\"1994-04-15\",\"7\":\"1994-05-01\",\"8\":\"1000\",\"9\":\"11000\"},{\"1\":\"Hawaii-State and county government\",\"2\":\"HI\",\"3\":\"Statewide\",\"4\":\"State and local government\",\"5\":\"AFSCME\",\"6\":\"1994-04-18\",\"7\":\"1994-04-29\",\"8\":\"15800\",\"9\":\"136500\"},{\"1\":\"Caterpillar, Inc.\",\"2\":\"IL\",\"3\":\"Aurora, Decatur\",\"4\":\"Private industry\",\"5\":\"UAW\",\"6\":\"1994-04-26\",\"7\":\"1994-04-26\",\"8\":\"2800\",\"9\":\"2800\"},{\"1\":\"Meijer Inc.\",\"2\":\"OH\",\"3\":\"Toledo\",\"4\":\"Private industry\",\"5\":\"UFCW\",\"6\":\"1994-05-07\",\"7\":\"1994-06-30\",\"8\":\"1000\",\"9\":\"38000\"},{\"1\":\"Caterpillar, Inc.\",\"2\":\"PA\",\"3\":\"York\",\"4\":\"Private industry\",\"5\":\"UAW\",\"6\":\"1994-05-12\",\"7\":\"1994-05-15\",\"8\":\"1500\",\"9\":\"3000\"},{\"1\":\"Caterpillar, Inc.\",\"2\":\"IL\",\"3\":\"Mossville\",\"4\":\"Private industry\",\"5\":\"UAW\",\"6\":\"1994-05-16\",\"7\":\"1994-05-20\",\"8\":\"7500\",\"9\":\"37500\"},{\"1\":\"Conrail\",\"2\":\"Interstate\",\"3\":\"NA\",\"4\":\"Private industry\",\"5\":\"BMWE\",\"6\":\"1994-05-20\",\"7\":\"1994-05-20\",\"8\":\"3500\",\"9\":\"3500\"},{\"1\":\"Leslie Fay Companies Inc.\",\"2\":\"NY, NJ, PA\",\"3\":\"Multiple states\",\"4\":\"Private industry\",\"5\":\"ILGWU\",\"6\":\"1994-06-01\",\"7\":\"1994-07-14\",\"8\":\"1800\",\"9\":\"55800\"},{\"1\":\"General Motors Corp., Technical Center\",\"2\":\"MI\",\"3\":\"Warren\",\"4\":\"Private industry\",\"5\":\"UAW\",\"6\":\"1994-06-02\",\"7\":\"1994-06-08\",\"8\":\"3500\",\"9\":\"17500\"},{\"1\":\"Connecticut Construction Contractors\",\"2\":\"CT\",\"3\":\"NA\",\"4\":\"Private industry\",\"5\":\"IBT\",\"6\":\"1994-06-06\",\"7\":\"1994-06-18\",\"8\":\"6000\",\"9\":\"60000\"},{\"1\":\"Caterpillar, Inc.\",\"2\":\"IL\",\"3\":\"Aurora\",\"4\":\"Private industry\",\"5\":\"UAW\",\"6\":\"1994-06-07\",\"7\":\"1994-06-15\",\"8\":\"2000\",\"9\":\"14000\"},{\"1\":\"Monon Corp.\",\"2\":\"IN\",\"3\":\"Monon\",\"4\":\"Private industry\",\"5\":\"UBC\",\"6\":\"1994-06-07\",\"7\":\"1994-07-01\",\"8\":\"2000\",\"9\":\"38000\"},{\"1\":\"Long Island Rail Road\",\"2\":\"NY\",\"3\":\"Long Island\",\"4\":\"Local government\",\"5\":\"UTU\",\"6\":\"1994-06-17\",\"7\":\"1994-06-18\",\"8\":\"5400\",\"9\":\"5400\"},{\"1\":\"Caterpillar, Inc.\",\"2\":\"IL, MI, PA, CO\",\"3\":\"Multiple states\",\"4\":\"Private industry\",\"5\":\"UAW\",\"6\":\"1994-06-20\",\"7\":\"1995-12-03\",\"8\":\"14000\",\"9\":\"4063000\"},{\"1\":\"General Dynamics\",\"2\":\"MI, OH, PA\",\"3\":\"Multiple states\",\"4\":\"Private industry\",\"5\":\"UAW\",\"6\":\"1994-06-20\",\"7\":\"1994-07-22\",\"8\":\"2000\",\"9\":\"48000\"},{\"1\":\"Dunlop Tire Company\",\"2\":\"AL\",\"3\":\"Madison\",\"4\":\"Private industry\",\"5\":\"URW\",\"6\":\"1994-06-21\",\"7\":\"1994-09-24\",\"8\":\"2000\",\"9\":\"134000\"},{\"1\":\"Bridgestone/Firestone Inc.\",\"2\":\"OH, IN, IL, OK, IA\",\"3\":\"Multiple states\",\"4\":\"Private industry\",\"5\":\"URW\",\"6\":\"1994-07-12\",\"7\":\"1995-05-22\",\"8\":\"4200\",\"9\":\"806400\"},{\"1\":\"Soo Line Railroad\",\"2\":\"Interstate\",\"3\":\"NA\",\"4\":\"Private industry\",\"5\":\"UTU\",\"6\":\"1994-07-14\",\"7\":\"1994-08-29\",\"8\":\"3500\",\"9\":\"87900\"},{\"1\":\"Pirelli Armstrong Tire Corp.\",\"2\":\"TN, IA, CA\",\"3\":\"Multiple states\",\"4\":\"Private industry\",\"5\":\"URW\",\"6\":\"1994-07-15\",\"7\":\"1995-03-12\",\"8\":\"1700\",\"9\":\"184000\"},{\"1\":\"Los Angeles Metropolitan Transportation Authority\",\"2\":\"CA\",\"3\":\"Los Angeles\",\"4\":\"Local government\",\"5\":\"ATU\",\"6\":\"1994-07-25\",\"7\":\"1994-08-02\",\"8\":\"7200\",\"9\":\"50400\"},{\"1\":\"Chicago Automotive Trade Association\",\"2\":\"IL\",\"3\":\"Chicago\",\"4\":\"Private industry\",\"5\":\"IAM\",\"6\":\"1994-08-02\",\"7\":\"1994-08-10\",\"8\":\"3000\",\"9\":\"21000\"},{\"1\":\"Food Employers Inc.\",\"2\":\"OR, WA\",\"3\":\"Portland, OR; Vancouver, WA\",\"4\":\"Private industry\",\"5\":\"UFCW\",\"6\":\"1994-08-18\",\"7\":\"1994-11-12\",\"8\":\"7000\",\"9\":\"413000\"},{\"1\":\"General Motors Corp., Inland Fisher Guide Plant\",\"2\":\"IN\",\"3\":\"Anderson\",\"4\":\"Private industry\",\"5\":\"UAW\",\"6\":\"1994-08-23\",\"7\":\"1994-08-25\",\"8\":\"46400\",\"9\":\"63300\"},{\"1\":\"Ann Arbor Board of Education\",\"2\":\"MI\",\"3\":\"Ann Arbor\",\"4\":\"Local government\",\"5\":\"NEA\",\"6\":\"1994-08-29\",\"7\":\"1994-09-11\",\"8\":\"1100\",\"9\":\"9900\"},{\"1\":\"Eagle Electric Manufacturing Company\",\"2\":\"NY\",\"3\":\"Long Island\",\"4\":\"Private industry\",\"5\":\"UAW\",\"6\":\"1994-08-31\",\"7\":\"1994-09-15\",\"8\":\"1100\",\"9\":\"12100\"},{\"1\":\"General Electric Corp., Industrial and Power Systems\",\"2\":\"NY\",\"3\":\"Schenectady\",\"4\":\"Private industry\",\"5\":\"IUE\",\"6\":\"1994-09-01\",\"7\":\"1994-09-01\",\"8\":\"4000\",\"9\":\"4000\"},{\"1\":\"Livonia Board of Education\",\"2\":\"MI\",\"3\":\"Livonia\",\"4\":\"Local government\",\"5\":\"NEA\",\"6\":\"1994-09-01\",\"7\":\"1994-09-06\",\"8\":\"1000\",\"9\":\"3000\"},{\"1\":\"SNE Corp.\",\"2\":\"WI\",\"3\":\"Mosinee\",\"4\":\"Private industry\",\"5\":\"UBC\",\"6\":\"1994-09-01\",\"7\":\"1994-09-10\",\"8\":\"1000\",\"9\":\"6000\"},{\"1\":\"Federal Way Board of Education\",\"2\":\"WA\",\"3\":\"Federal Way\",\"4\":\"Local government\",\"5\":\"NEA\",\"6\":\"1994-09-06\",\"7\":\"1994-09-13\",\"8\":\"1000\",\"9\":\"6000\"},{\"1\":\"Alameda County\",\"2\":\"CA\",\"3\":\"Alameda County\",\"4\":\"Local government\",\"5\":\"SEIU\",\"6\":\"1994-09-20\",\"7\":\"1994-09-20\",\"8\":\"1200\",\"9\":\"1200\"},{\"1\":\"Philips Display Components Company\",\"2\":\"OH\",\"3\":\"Findlay\",\"4\":\"Private industry\",\"5\":\"IBEW\",\"6\":\"1994-09-26\",\"7\":\"1994-10-02\",\"8\":\"1500\",\"9\":\"7500\"},{\"1\":\"General Motors Corp., Buick City facility\",\"2\":\"MI\",\"3\":\"Flint\",\"4\":\"Private industry\",\"5\":\"UAW\",\"6\":\"1994-09-27\",\"7\":\"1994-09-30\",\"8\":\"22300\",\"9\":\"74000\"},{\"1\":\"Legal Aid Society\",\"2\":\"NY\",\"3\":\"New York\",\"4\":\"Private industry\",\"5\":\"ALAA\",\"6\":\"1994-10-01\",\"7\":\"1994-10-04\",\"8\":\"1100\",\"9\":\"2200\"},{\"1\":\"North American Rayon Company\",\"2\":\"TN\",\"3\":\"Elizabethton\",\"4\":\"Private industry\",\"5\":\"ACTWU\",\"6\":\"1994-10-04\",\"7\":\"1994-12-02\",\"8\":\"1000\",\"9\":\"41000\"},{\"1\":\"Denver Public Schools\",\"2\":\"CO\",\"3\":\"Denver\",\"4\":\"Local government\",\"5\":\"NEA\",\"6\":\"1994-10-10\",\"7\":\"1994-10-15\",\"8\":\"3000\",\"9\":\"12000\"},{\"1\":\"Anchorage School District\",\"2\":\"AK\",\"3\":\"Anchorage\",\"4\":\"Local government\",\"5\":\"NEA\",\"6\":\"1994-10-12\",\"7\":\"1994-10-14\",\"8\":\"2900\",\"9\":\"8700\"},{\"1\":\"San Francisco Newspapers\",\"2\":\"CA\",\"3\":\"San Francisco\",\"4\":\"Private industry\",\"5\":\"CNU\",\"6\":\"1994-11-01\",\"7\":\"1994-11-12\",\"8\":\"2600\",\"9\":\"20800\"},{\"1\":\"General Motors Corp.\",\"2\":\"MI\",\"3\":\"Flint\",\"4\":\"Private industry\",\"5\":\"UAW\",\"6\":\"1995-01-18\",\"7\":\"1995-01-20\",\"8\":\"37700\",\"9\":\"64500\"},{\"1\":\"Kaiser Aluminum and Chemical Corp.\",\"2\":\"LA, OH, WA\",\"3\":\"Multiple states\",\"4\":\"Private industry\",\"5\":\"USW\",\"6\":\"1995-02-20\",\"7\":\"1995-02-28\",\"8\":\"3000\",\"9\":\"18000\"},{\"1\":\"Group Health Cooperative of Puget Sound\",\"2\":\"WA\",\"3\":\"Seattle\",\"4\":\"Private industry\",\"5\":\"SEIU\",\"6\":\"1995-03-22\",\"7\":\"1995-03-23\",\"8\":\"1200\",\"9\":\"1200\"},{\"1\":\"Southeastern Pennsylvania Transportation Authority\",\"2\":\"PA\",\"3\":\"Philadelphia area\",\"4\":\"State government\",\"5\":\"TWU\",\"6\":\"1995-03-28\",\"7\":\"1995-04-10\",\"8\":\"5200\",\"9\":\"52000\"},{\"1\":\"Chrysler Corp.\",\"2\":\"IN\",\"3\":\"Kokomo\",\"4\":\"Private industry\",\"5\":\"UAW\",\"6\":\"1995-03-31\",\"7\":\"1995-03-31\",\"8\":\"5700\",\"9\":\"5700\"},{\"1\":\"General Motors Corp, Pontiac East Truck Plant\",\"2\":\"MI\",\"3\":\"Pontiac\",\"4\":\"Private industry\",\"5\":\"UAW\",\"6\":\"1995-03-31\",\"7\":\"1995-04-05\",\"8\":\"5500\",\"9\":\"22000\"},{\"1\":\"Construction industry\",\"2\":\"CA\",\"3\":\"Southern\",\"4\":\"Private industry\",\"5\":\"NA\",\"6\":\"1995-04-03\",\"7\":\"1995-06-15\",\"8\":\"3000\",\"9\":\"108000\"},{\"1\":\"Retail grocery chains - Safeway, Lucky Stores, Save Mart\",\"2\":\"CA\",\"3\":\"Northern\",\"4\":\"Private industry\",\"5\":\"UFCW\",\"6\":\"1995-04-07\",\"7\":\"1995-04-15\",\"8\":\"32000\",\"9\":\"192000\"},{\"1\":\"University of California, Los Angeles\",\"2\":\"CA\",\"3\":\"Los Angeles\",\"4\":\"State government\",\"5\":\"SAGEU\",\"6\":\"1995-04-26\",\"7\":\"1995-04-27\",\"8\":\"3000\",\"9\":\"6000\"},{\"1\":\"Oregon State\",\"2\":\"OR\",\"3\":\"Statewide\",\"4\":\"State government\",\"5\":\"SEIU\",\"6\":\"1995-05-08\",\"7\":\"1995-05-14\",\"8\":\"14000\",\"9\":\"50000\"},{\"1\":\"Washington Gas Light Company\",\"2\":\"DC, MD, VA\",\"3\":\"Washington DC Metro Area\",\"4\":\"Private industry\",\"5\":\"NA\",\"6\":\"1995-06-10\",\"7\":\"1995-09-07\",\"8\":\"1100\",\"9\":\"77000\"},{\"1\":\"Pepsi Cola Bottling Company\",\"2\":\"CA\",\"3\":\"Statewide\",\"4\":\"Private industry\",\"5\":\"IBT\",\"6\":\"1995-06-26\",\"7\":\"1995-06-28\",\"8\":\"1000\",\"9\":\"3000\"},{\"1\":\"New Jersey Turnpike Authority\",\"2\":\"NJ\",\"3\":\"Statewide\",\"4\":\"State government\",\"5\":\"IFPTE\",\"6\":\"1995-07-03\",\"7\":\"1995-07-04\",\"8\":\"1600\",\"9\":\"3200\"},{\"1\":\"Detroit Newspapers\",\"2\":\"MI\",\"3\":\"Detroit\",\"4\":\"Private industry\",\"5\":\"IBT. TNG, CWA. GCIU\",\"6\":\"1995-07-13\",\"7\":\"1997-02-19\",\"8\":\"2500\",\"9\":\"1012500\"},{\"1\":\"Chrysler Corp.\",\"2\":\"IA\",\"3\":\"Dodge City\",\"4\":\"Private industry\",\"5\":\"UAW\",\"6\":\"1995-07-31\",\"7\":\"1995-07-31\",\"8\":\"3900\",\"9\":\"3900\"},{\"1\":\"Pacific Maritime Association\",\"2\":\"CA, OR, WA\",\"3\":\"Multiple states\",\"4\":\"Private industry\",\"5\":\"ILWU\",\"6\":\"1995-08-07\",\"7\":\"1995-08-07\",\"8\":\"7500\",\"9\":\"7500\"},{\"1\":\"CSX Corp.\",\"2\":\"Interstate\",\"3\":\"NA\",\"4\":\"Private industry\",\"5\":\"BMWE\",\"6\":\"1995-08-17\",\"7\":\"1995-08-17\",\"8\":\"1200\",\"9\":\"1200\"},{\"1\":\"Bell Atlantic Corp.\",\"2\":\"Interstate\",\"3\":\"NA\",\"4\":\"Private industry\",\"5\":\"CWA\",\"6\":\"1995-08-31\",\"7\":\"1995-08-31\",\"8\":\"2000\",\"9\":\"2000\"},{\"1\":\"WCI Steel, Inc.\",\"2\":\"OH\",\"3\":\"Warren\",\"4\":\"Private industry\",\"5\":\"USW\",\"6\":\"1995-08-31\",\"7\":\"1995-10-24\",\"8\":\"1700\",\"9\":\"68000\"},{\"1\":\"Providence Public Schools\",\"2\":\"RI\",\"3\":\"Providence\",\"4\":\"Local government\",\"5\":\"AFT\",\"6\":\"1995-09-05\",\"7\":\"1995-09-14\",\"8\":\"1600\",\"9\":\"12800\"},{\"1\":\"Ryder Systems Inc.\",\"2\":\"Interstate\",\"3\":\"NA\",\"4\":\"Private industry\",\"5\":\"IBT\",\"6\":\"1995-09-07\",\"7\":\"1995-10-07\",\"8\":\"5000\",\"9\":\"110000\"},{\"1\":\"Oregon Health and Sciences University\",\"2\":\"OR\",\"3\":\"Portland\",\"4\":\"State government\",\"5\":\"AFSCME\",\"6\":\"1995-09-19\",\"7\":\"1995-09-22\",\"8\":\"3200\",\"9\":\"12800\"},{\"1\":\"Amana Refrigeration Inc.\",\"2\":\"IA\",\"3\":\"Cedar Rapids\",\"4\":\"Private industry\",\"5\":\"IAM\",\"6\":\"1995-09-24\",\"7\":\"1995-09-28\",\"8\":\"2000\",\"9\":\"8000\"},{\"1\":\"Inter City Products\",\"2\":\"TN\",\"3\":\"Lewisburg\",\"4\":\"Private industry\",\"5\":\"BBF\",\"6\":\"1995-10-05\",\"7\":\"1995-10-20\",\"8\":\"2000\",\"9\":\"22000\"},{\"1\":\"Boeing Company\",\"2\":\"WA, KS, OR\",\"3\":\"Multiple states\",\"4\":\"Private industry\",\"5\":\"IAM\",\"6\":\"1995-10-06\",\"7\":\"1995-12-14\",\"8\":\"33000\",\"9\":\"1551000\"},{\"1\":\"Metropolitan Council/Metro Transit\",\"2\":\"MN\",\"3\":\"Minneapolis-St. Paul\",\"4\":\"Local government\",\"5\":\"ATU\",\"6\":\"1995-10-09\",\"7\":\"1995-10-29\",\"8\":\"2000\",\"9\":\"38000\"},{\"1\":\"Amphenol Corp.\",\"2\":\"NY\",\"3\":\"Sidney\",\"4\":\"Private industry\",\"5\":\"IAM\",\"6\":\"1995-10-21\",\"7\":\"1995-10-28\",\"8\":\"1000\",\"9\":\"5000\"},{\"1\":\"General Electric Corp.\",\"2\":\"PA\",\"3\":\"Erie\",\"4\":\"Private industry\",\"5\":\"UE\",\"6\":\"1995-10-26\",\"7\":\"1995-10-30\",\"8\":\"3200\",\"9\":\"9600\"},{\"1\":\"Chrysler Corp., McGraw Glass Division\",\"2\":\"MI\",\"3\":\"Detroit\",\"4\":\"Private industry\",\"5\":\"UAW\",\"6\":\"1995-11-01\",\"7\":\"1995-11-04\",\"8\":\"1000\",\"9\":\"3000\"},{\"1\":\"Oakland Unified School District\",\"2\":\"CA\",\"3\":\"Oakland\",\"4\":\"Local government\",\"5\":\"NEA\",\"6\":\"1995-11-28\",\"7\":\"1995-11-29\",\"8\":\"3500\",\"9\":\"7000\"},{\"1\":\"Commercial Building Realty Advisory Board\",\"2\":\"NY\",\"3\":\"New York\",\"4\":\"Private industry\",\"5\":\"SEIU\",\"6\":\"1996-01-04\",\"7\":\"1996-02-04\",\"8\":\"30000\",\"9\":\"630000\"},{\"1\":\"Trailmobile Manufacturing Company\",\"2\":\"IL\",\"3\":\"Charleston\",\"4\":\"Private industry\",\"5\":\"UPIU\",\"6\":\"1996-01-21\",\"7\":\"1996-07-03\",\"8\":\"1100\",\"9\":\"127600\"},{\"1\":\"Oakland Public Schools\",\"2\":\"CA\",\"3\":\"Oakland\",\"4\":\"Local government\",\"5\":\"NEA\",\"6\":\"1996-01-30\",\"7\":\"1996-01-30\",\"8\":\"3500\",\"9\":\"3500\"},{\"1\":\"San Diego Public Schools\",\"2\":\"CA\",\"3\":\"San Diego\",\"4\":\"Local government\",\"5\":\"NEA\",\"6\":\"1996-02-01\",\"7\":\"1996-02-08\",\"8\":\"5000\",\"9\":\"30000\"},{\"1\":\"Los Angeles and Long Beach Ports\",\"2\":\"CA\",\"3\":\"Los Angeles, Long Beach\",\"4\":\"Private industry\",\"5\":\"ILWU\",\"6\":\"1996-02-05\",\"7\":\"1996-02-05\",\"8\":\"3000\",\"9\":\"3000\"},{\"1\":\"Yale University\",\"2\":\"CT\",\"3\":\"New Haven\",\"4\":\"Private industry\",\"5\":\"HERE\",\"6\":\"1996-02-07\",\"7\":\"1996-03-05\",\"8\":\"1200\",\"9\":\"22800\"},{\"1\":\"Ingalls Shipbuilding Inc.\",\"2\":\"MS\",\"3\":\"Pascagoula\",\"4\":\"Private industry\",\"5\":\"MTC\",\"6\":\"1996-02-14\",\"7\":\"1996-02-15\",\"8\":\"7600\",\"9\":\"14200\"},{\"1\":\"Oakland Unified School District\",\"2\":\"CA\",\"3\":\"Oakland\",\"4\":\"Local government\",\"5\":\"NEA\",\"6\":\"1996-02-15\",\"7\":\"1996-03-20\",\"8\":\"3500\",\"9\":\"84000\"},{\"1\":\"Chrysler Corp.\",\"2\":\"MI\",\"3\":\"Warren\",\"4\":\"Private industry\",\"5\":\"UAW\",\"6\":\"1996-02-17\",\"7\":\"1996-02-19\",\"8\":\"1800\",\"9\":\"1800\"},{\"1\":\"Nursing home industry\",\"2\":\"WV\",\"3\":\"Statewide\",\"4\":\"Private industry\",\"5\":\"SEIU\",\"6\":\"1996-03-04\",\"7\":\"1996-03-04\",\"8\":\"1000\",\"9\":\"1000\"},{\"1\":\"General Motors Corp.\",\"2\":\"OH\",\"3\":\"Dayton\",\"4\":\"Private industry\",\"5\":\"UAW\",\"6\":\"1996-03-08\",\"7\":\"1996-03-22\",\"8\":\"136000\",\"9\":\"1260000\"},{\"1\":\"Yale University\",\"2\":\"CT\",\"3\":\"New Haven\",\"4\":\"Private industry\",\"5\":\"HERE\",\"6\":\"1996-03-27\",\"7\":\"1996-04-23\",\"8\":\"1100\",\"9\":\"22000\"},{\"1\":\"Beverly Enterprises\",\"2\":\"Interstate\",\"3\":\"NA\",\"4\":\"Private industry\",\"5\":\"SEIU\",\"6\":\"1996-04-01\",\"7\":\"1996-04-03\",\"8\":\"1200\",\"9\":\"3600\"},{\"1\":\"Maryland Heavy-Highway Contractors Association\",\"2\":\"MD\",\"3\":\"Baltimore\",\"4\":\"Private industry\",\"5\":\"IUOE\",\"6\":\"1996-04-09\",\"7\":\"1996-04-10\",\"8\":\"1000\",\"9\":\"2000\"},{\"1\":\"General Motors Corp.\",\"2\":\"OH\",\"3\":\"Lordstown\",\"4\":\"Private industry\",\"5\":\"UAW\",\"6\":\"1996-04-15\",\"7\":\"1996-04-16\",\"8\":\"1500\",\"9\":\"3000\"},{\"1\":\"Crown Cork and Seal Company\",\"2\":\"WA, NE, OR, ID, MD, WI\",\"3\":\"Multiple states\",\"4\":\"Private industry\",\"5\":\"IAM\",\"6\":\"1996-04-19\",\"7\":\"1996-06-08\",\"8\":\"1000\",\"9\":\"35000\"},{\"1\":\"Grocery industry-- Safeway and King Soopers\",\"2\":\"CO\",\"3\":\"Denver area\",\"4\":\"Private industry\",\"5\":\"UFCW\",\"6\":\"1996-05-14\",\"7\":\"1996-06-26\",\"8\":\"12000\",\"9\":\"372000\"},{\"1\":\"NBC Merchants, Inc.\",\"2\":\"IN\",\"3\":\"Evansville\",\"4\":\"Private industry\",\"5\":\"UNITE\",\"6\":\"1996-06-01\",\"7\":\"1996-06-14\",\"8\":\"1300\",\"9\":\"13000\"},{\"1\":\"Northern Illinois Mason Employers Council\",\"2\":\"IL\",\"3\":\"Chicago\",\"4\":\"Private industry\",\"5\":\"BAC\",\"6\":\"1996-06-01\",\"7\":\"1996-06-12\",\"8\":\"6500\",\"9\":\"52000\"},{\"1\":\"Bay Area cleaning companies\",\"2\":\"CA\",\"3\":\"Alameda, Contra Costa, Santa Clara, San Mateo Counties\",\"4\":\"Private industry\",\"5\":\"SEIU\",\"6\":\"1996-06-03\",\"7\":\"1996-07-02\",\"8\":\"4900\",\"9\":\"107800\"},{\"1\":\"McDonnell Douglas Aerospace\",\"2\":\"MO\",\"3\":\"St. Louis\",\"4\":\"Private industry\",\"5\":\"IAM\",\"6\":\"1996-06-05\",\"7\":\"1996-09-16\",\"8\":\"6700\",\"9\":\"482400\"},{\"1\":\"Compton Public Schools\",\"2\":\"CA\",\"3\":\"Compton\",\"4\":\"Local government\",\"5\":\"NEA\",\"6\":\"1996-06-10\",\"7\":\"1996-06-10\",\"8\":\"1100\",\"9\":\"1100\"},{\"1\":\"League of Voluntary Hospitals\",\"2\":\"NY\",\"3\":\"New York\",\"4\":\"Private industry\",\"5\":\"SEIU\",\"6\":\"1996-06-24\",\"7\":\"1996-08-28\",\"8\":\"5800\",\"9\":\"272600\"},{\"1\":\"Contra Costa County Public Schools District\",\"2\":\"CA\",\"3\":\"Contra Costa County\",\"4\":\"Local government\",\"5\":\"CNA, AFSME, SEIU, AA\",\"6\":\"1996-06-26\",\"7\":\"1996-06-26\",\"8\":\"4100\",\"9\":\"4100\"},{\"1\":\"National Steel and Shipbuilding Company\",\"2\":\"CA\",\"3\":\"San Diego\",\"4\":\"Private industry\",\"5\":\"BSOIW, IAM, IBT, IBEW, IUPAT, UBC, IUOE\",\"6\":\"1996-07-17\",\"7\":\"1996-08-16\",\"8\":\"2500\",\"9\":\"49100\"},{\"1\":\"Pemco Aeroplex Inc.\",\"2\":\"AL\",\"3\":\"Birmingham\",\"4\":\"Private industry\",\"5\":\"UAW\",\"6\":\"1996-07-22\",\"7\":\"1997-03-21\",\"8\":\"1100\",\"9\":\"183700\"},{\"1\":\"East St. Louis School District\",\"2\":\"IL\",\"3\":\"East St. Louis\",\"4\":\"Local government\",\"5\":\"AFT\",\"6\":\"1996-09-03\",\"7\":\"1996-09-15\",\"8\":\"1200\",\"9\":\"10800\"},{\"1\":\"Aluminum Company of America\",\"2\":\"OH\",\"3\":\"Cleveland\",\"4\":\"Private industry\",\"5\":\"UAW\",\"6\":\"1996-09-05\",\"7\":\"1996-09-29\",\"8\":\"1300\",\"9\":\"22100\"},{\"1\":\"Boise Cascade Corp.\",\"2\":\"Interstate\",\"3\":\"NA\",\"4\":\"Private industry\",\"5\":\"SCIW\",\"6\":\"1996-09-12\",\"7\":\"1996-10-12\",\"8\":\"3800\",\"9\":\"45600\"},{\"1\":\"Wheeling Pittsburgh Steel Corp.\",\"2\":\"Interstate\",\"3\":\"NA\",\"4\":\"Private industry\",\"5\":\"USW\",\"6\":\"1996-10-01\",\"7\":\"1997-08-12\",\"8\":\"4800\",\"9\":\"1142400\"},{\"1\":\"Holt Cargo Systems Inc.\",\"2\":\"PA\",\"3\":\"Philadelphia\",\"4\":\"Private industry\",\"5\":\"ILA\",\"6\":\"1996-10-07\",\"7\":\"1996-10-24\",\"8\":\"1200\",\"9\":\"15600\"},{\"1\":\"Kennecott Utah Copper Corp.\",\"2\":\"UT\",\"3\":\"Salt Lake County\",\"4\":\"Private industry\",\"5\":\"NA\",\"6\":\"1996-10-16\",\"7\":\"1996-10-18\",\"8\":\"1700\",\"9\":\"5100\"},{\"1\":\"General Motors Corp.\",\"2\":\"IN\",\"3\":\"Indianapolis\",\"4\":\"Private industry\",\"5\":\"UAW\",\"6\":\"1996-10-30\",\"7\":\"1996-11-03\",\"8\":\"2700\",\"9\":\"8100\"},{\"1\":\"General Motors Corp.\",\"2\":\"WI\",\"3\":\"Janesville\",\"4\":\"Private industry\",\"5\":\"UAW\",\"6\":\"1996-10-30\",\"7\":\"1996-11-06\",\"8\":\"5100\",\"9\":\"30600\"},{\"1\":\"Elevator Industry\",\"2\":\"NY\",\"3\":\"Flushing\",\"4\":\"Private industry\",\"5\":\"IBEW\",\"6\":\"1996-11-01\",\"7\":\"1997-03-02\",\"8\":\"1500\",\"9\":\"120000\"},{\"1\":\"IBP Inc.\",\"2\":\"IL\",\"3\":\"Joslin\",\"4\":\"Private industry\",\"5\":\"UFCW\",\"6\":\"1996-11-12\",\"7\":\"1996-11-29\",\"8\":\"1800\",\"9\":\"23400\"},{\"1\":\"Giant Food Inc.\",\"2\":\"MD\",\"3\":\"Landover\",\"4\":\"Private industry\",\"5\":\"IBT\",\"6\":\"1996-12-18\",\"7\":\"1997-01-19\",\"8\":\"2100\",\"9\":\"41100\"},{\"1\":\"General Motors Corp.\",\"2\":\"OH\",\"3\":\"Moraine\",\"4\":\"Private industry\",\"5\":\"IUE\",\"6\":\"1997-01-25\",\"7\":\"1997-01-28\",\"8\":\"4300\",\"9\":\"8600\"},{\"1\":\"General Motors Corp.\",\"2\":\"IN\",\"3\":\"Fort Wayne\",\"4\":\"Private industry\",\"5\":\"UAW\",\"6\":\"1997-03-14\",\"7\":\"1997-03-27\",\"8\":\"2700\",\"9\":\"27000\"},{\"1\":\"General Motors Corp.\",\"2\":\"OK\",\"3\":\"Oklahoma City\",\"4\":\"Private industry\",\"5\":\"UAW\",\"6\":\"1997-04-04\",\"7\":\"1997-05-24\",\"8\":\"3500\",\"9\":\"126000\"},{\"1\":\"Chrysler Corp.\",\"2\":\"MI, MO, OH\",\"3\":\"Interstate\",\"4\":\"Private industry\",\"5\":\"UAW\",\"6\":\"1997-04-10\",\"7\":\"1997-05-09\",\"8\":\"15100\",\"9\":\"306800\"},{\"1\":\"Kaiser Permanente\",\"2\":\"CA\",\"3\":\"Northern\",\"4\":\"Private industry\",\"5\":\"CNA\",\"6\":\"1997-04-16\",\"7\":\"1997-04-16\",\"8\":\"17000\",\"9\":\"17000\"},{\"1\":\"Goodyear Tire and Rubber Company\",\"2\":\"Interstate\",\"3\":\"NA\",\"4\":\"Private industry\",\"5\":\"USW\",\"6\":\"1997-04-20\",\"7\":\"1997-05-08\",\"8\":\"12000\",\"9\":\"168000\"},{\"1\":\"Goodyear/Kelly-Springfield Tire Company\",\"2\":\"SC\",\"3\":\"Fayetteville\",\"4\":\"Private industry\",\"5\":\"USW\",\"6\":\"1997-04-22\",\"7\":\"1997-05-08\",\"8\":\"2300\",\"9\":\"29900\"},{\"1\":\"General Motors Corp.\",\"2\":\"MI\",\"3\":\"Pontiac\",\"4\":\"Private industry\",\"5\":\"UAW\",\"6\":\"1997-04-23\",\"7\":\"1997-07-19\",\"8\":\"5900\",\"9\":\"359900\"},{\"1\":\"Carrier Air Conditioning Company\",\"2\":\"TN\",\"3\":\"McMinnville\",\"4\":\"Private industry\",\"5\":\"SMW\",\"6\":\"1997-05-01\",\"7\":\"1997-06-08\",\"8\":\"1300\",\"9\":\"33800\"},{\"1\":\"Construction Employers Association\",\"2\":\"OH\",\"3\":\"Cleveland area\",\"4\":\"Private industry\",\"5\":\"LIUNA\",\"6\":\"1997-05-01\",\"7\":\"1997-05-09\",\"8\":\"2000\",\"9\":\"14000\"},{\"1\":\"General Building Contractors Association\",\"2\":\"PA\",\"3\":\"Eastern\",\"4\":\"Private industry\",\"5\":\"UBC\",\"6\":\"1997-05-01\",\"7\":\"1997-05-19\",\"8\":\"1000\",\"9\":\"13000\"},{\"1\":\"Interior Finish Contractors Association of Delaware Valley\",\"2\":\"PA\",\"3\":\"Eastern\",\"4\":\"Private industry\",\"5\":\"UBC\",\"6\":\"1997-05-01\",\"7\":\"1997-05-07\",\"8\":\"3000\",\"9\":\"15000\"},{\"1\":\"General Motors Corp., Delphi Packard Electric Division\",\"2\":\"OH\",\"3\":\"Warren\",\"4\":\"Private industry\",\"5\":\"IUE\",\"6\":\"1997-05-13\",\"7\":\"1997-05-14\",\"8\":\"8000\",\"9\":\"16000\"},{\"1\":\"Blue Cross Blue Shield of New Jersey\",\"2\":\"NJ\",\"3\":\"Newark\",\"4\":\"Private industry\",\"5\":\"OPEIU\",\"6\":\"1997-05-27\",\"7\":\"1997-05-30\",\"8\":\"1600\",\"9\":\"6400\"},{\"1\":\"Kaiser Permanente\",\"2\":\"CA\",\"3\":\"Northern\",\"4\":\"Private industry\",\"5\":\"CNA\",\"6\":\"1997-07-17\",\"7\":\"1997-07-18\",\"8\":\"10500\",\"9\":\"21000\"},{\"1\":\"General Motors Corp.\",\"2\":\"MI\",\"3\":\"Warren, Flint, Orion Township, Lansing\",\"4\":\"Private industry\",\"5\":\"UAW\",\"6\":\"1997-07-23\",\"7\":\"1997-07-27\",\"8\":\"14100\",\"9\":\"25200\"},{\"1\":\"Shaw's Supermarkets Inc.\",\"2\":\"MA, RI\",\"3\":\"Multiple states\",\"4\":\"Private industry\",\"5\":\"UFCW\",\"6\":\"1997-07-28\",\"7\":\"1997-07-30\",\"8\":\"6200\",\"9\":\"18600\"},{\"1\":\"United Parcel Service\",\"2\":\"Interstate\",\"3\":\"NA\",\"4\":\"Private industry\",\"5\":\"IBT\",\"6\":\"1997-08-04\",\"7\":\"1997-08-21\",\"8\":\"180000\",\"9\":\"2032500\"},{\"1\":\"State of Ohio\",\"2\":\"OH\",\"3\":\"Statewide\",\"4\":\"State government\",\"5\":\"SEIU\",\"6\":\"1997-08-05\",\"7\":\"1997-08-05\",\"8\":\"4500\",\"9\":\"4500\"},{\"1\":\"Kaiser Permanente\",\"2\":\"OR, WA\",\"3\":\"Multiple states\",\"4\":\"Private industry\",\"5\":\"SEIU\",\"6\":\"1997-09-02\",\"7\":\"1997-10-04\",\"8\":\"2000\",\"9\":\"48000\"},{\"1\":\"Painting and Decorating Contractors Association\",\"2\":\"MO\",\"3\":\"St. Louis\",\"4\":\"Private industry\",\"5\":\"IUPAT\",\"6\":\"1997-09-02\",\"7\":\"1997-09-18\",\"8\":\"2200\",\"9\":\"28600\"},{\"1\":\"Bay Area Rapid Transit\",\"2\":\"CA\",\"3\":\"San Francisco area\",\"4\":\"Local government\",\"5\":\"ATU; AFSCME; SEIU\",\"6\":\"1997-09-07\",\"7\":\"1997-09-13\",\"8\":\"2600\",\"9\":\"13000\"},{\"1\":\"Kaiser Permanente\",\"2\":\"CA\",\"3\":\"Northern\",\"4\":\"Private industry\",\"5\":\"CNA\",\"6\":\"1997-09-08\",\"7\":\"1997-09-09\",\"8\":\"20300\",\"9\":\"40600\"},{\"1\":\"Vickers Inc.\",\"2\":\"NE\",\"3\":\"Omaha\",\"4\":\"Private industry\",\"5\":\"UPIU\",\"6\":\"1997-09-15\",\"7\":\"1997-09-16\",\"8\":\"1000\",\"9\":\"2000\"},{\"1\":\"Los Angeles County\",\"2\":\"CA\",\"3\":\"Los Angeles County\",\"4\":\"Local government\",\"5\":\"SEIU\",\"6\":\"1997-09-30\",\"7\":\"1997-10-02\",\"8\":\"2200\",\"9\":\"6600\"},{\"1\":\"Colorado Fuel and Iron Company\",\"2\":\"CO\",\"3\":\"Pueblo\",\"4\":\"Private industry\",\"5\":\"USW\",\"6\":\"1997-10-03\",\"7\":\"1997-12-30\",\"8\":\"1000\",\"9\":\"59000\"},{\"1\":\"Foster Farms Poultry\",\"2\":\"CA\",\"3\":\"Livingston\",\"4\":\"Private industry\",\"5\":\"UFCW\",\"6\":\"1997-10-08\",\"7\":\"1997-10-23\",\"8\":\"2200\",\"9\":\"26400\"},{\"1\":\"Uniroyal Goodrich Tire Company\",\"2\":\"IN\",\"3\":\"Woodburn\",\"4\":\"Private industry\",\"5\":\"USW\",\"6\":\"1997-10-24\",\"7\":\"1997-12-27\",\"8\":\"1200\",\"9\":\"51600\"},{\"1\":\"Kaiser Permanente\",\"2\":\"CA\",\"3\":\"Northern\",\"4\":\"Private industry\",\"5\":\"CNA\",\"6\":\"1997-11-10\",\"7\":\"1997-11-10\",\"8\":\"8900\",\"9\":\"8900\"},{\"1\":\"Kaiser Permanente\",\"2\":\"CA\",\"3\":\"Northern\",\"4\":\"Private industry\",\"5\":\"CNA\",\"6\":\"1998-01-28\",\"7\":\"1998-01-29\",\"8\":\"8000\",\"9\":\"16000\"},{\"1\":\"Honeywell Inc.\",\"2\":\"MN\",\"3\":\"Minneapolis area\",\"4\":\"Private industry\",\"5\":\"IBT\",\"6\":\"1998-02-01\",\"7\":\"1998-02-15\",\"8\":\"2600\",\"9\":\"26000\"},{\"1\":\"Trane Company\",\"2\":\"KY\",\"3\":\"Lexington\",\"4\":\"Private industry\",\"5\":\"UAW\",\"6\":\"1998-02-23\",\"7\":\"1998-03-20\",\"8\":\"1100\",\"9\":\"22000\"},{\"1\":\"Kaiser Permanente\",\"2\":\"CA\",\"3\":\"Northern\",\"4\":\"Private industry\",\"5\":\"CNA\",\"6\":\"1998-02-24\",\"7\":\"1998-02-24\",\"8\":\"7100\",\"9\":\"7100\"},{\"1\":\"Community College of Philadelphia\",\"2\":\"PA\",\"3\":\"Philadelphia\",\"4\":\"Local government\",\"5\":\"AFT\",\"6\":\"1998-03-10\",\"7\":\"1998-03-16\",\"8\":\"1000\",\"9\":\"5000\"},{\"1\":\"Construction companies\",\"2\":\"IA\",\"3\":\"Central\",\"4\":\"Private industry\",\"5\":\"UBC\",\"6\":\"1998-05-01\",\"7\":\"1998-05-13\",\"8\":\"1800\",\"9\":\"16200\"},{\"1\":\"Wheland Foundry, Division of North American Royalties\",\"2\":\"TN\",\"3\":\"Chattanooga\",\"4\":\"Private industry\",\"5\":\"USW\",\"6\":\"1998-05-02\",\"7\":\"1998-06-19\",\"8\":\"1300\",\"9\":\"44200\"},{\"1\":\"Peterbilt Motors Company\",\"2\":\"TN\",\"3\":\"Madison\",\"4\":\"Private industry\",\"5\":\"UAW\",\"6\":\"1998-05-03\",\"7\":\"1998-11-24\",\"8\":\"1200\",\"9\":\"170400\"},{\"1\":\"Quad City Builders Association, Inc.\",\"2\":\"IL\",\"3\":\"Rock Island\",\"4\":\"Private industry\",\"5\":\"UBC\",\"6\":\"1998-05-21\",\"7\":\"1998-05-28\",\"8\":\"1800\",\"9\":\"9000\"},{\"1\":\"Associated General Contractors; Great Lakes Fabricators and Erectors Association\",\"2\":\"MI\",\"3\":\"Detroit area\",\"4\":\"Private industry\",\"5\":\"BSOIW\",\"6\":\"1998-06-01\",\"7\":\"1998-06-01\",\"8\":\"2500\",\"9\":\"2500\"},{\"1\":\"Southeastern Pennsylvania Transportation Authority\",\"2\":\"PA\",\"3\":\"Philadelphia\",\"4\":\"State government\",\"5\":\"ATU\",\"6\":\"1998-06-01\",\"7\":\"1998-07-10\",\"8\":\"4200\",\"9\":\"121800\"},{\"1\":\"Michigan Road Builders Association\",\"2\":\"MI\",\"3\":\"Statewide\",\"4\":\"Private industry\",\"5\":\"IUOE\",\"6\":\"1998-06-04\",\"7\":\"1998-06-05\",\"8\":\"4000\",\"9\":\"8000\"},{\"1\":\"General Motors Corp.\",\"2\":\"Interstate\",\"3\":\"NA\",\"4\":\"Private industry\",\"5\":\"UAW\",\"6\":\"1998-06-05\",\"7\":\"1998-07-29\",\"8\":\"152200\",\"9\":\"3313000\"},{\"1\":\"Tecumseh Products Company\",\"2\":\"WI\",\"3\":\"New Holstein\",\"4\":\"Private industry\",\"5\":\"IAM\",\"6\":\"1998-07-01\",\"7\":\"1998-07-18\",\"8\":\"1800\",\"9\":\"21600\"},{\"1\":\"Lucent Technologies Inc.\",\"2\":\"OH\",\"3\":\"Columbus\",\"4\":\"Private industry\",\"5\":\"IBEW\",\"6\":\"1998-07-06\",\"7\":\"1998-07-22\",\"8\":\"2500\",\"9\":\"32500\"},{\"1\":\"BeefAmerica\",\"2\":\"NE\",\"3\":\"Norfolk\",\"4\":\"Private industry\",\"5\":\"UFCW\",\"6\":\"1998-07-13\",\"7\":\"1998-07-28\",\"8\":\"1200\",\"9\":\"14400\"},{\"1\":\"Bell Atlantic Corp.\",\"2\":\"Interstate\",\"3\":\"NA\",\"4\":\"Private industry\",\"5\":\"CWA\",\"6\":\"1998-08-09\",\"7\":\"1998-08-11\",\"8\":\"73000\",\"9\":\"146000\"},{\"1\":\"Trinity Industries Inc.\",\"2\":\"PA\",\"3\":\"Greenville\",\"4\":\"Private industry\",\"5\":\"UAW\",\"6\":\"1998-08-12\",\"7\":\"1998-08-12\",\"8\":\"1700\",\"9\":\"1700\"},{\"1\":\"Consolidated Rail Company\",\"2\":\"Interstate\",\"3\":\"NA\",\"4\":\"Private industry\",\"5\":\"BMWE\",\"6\":\"1998-08-14\",\"7\":\"1998-08-14\",\"8\":\"23500\",\"9\":\"23500\"},{\"1\":\"US West Corp.\",\"2\":\"Interstate\",\"3\":\"NA\",\"4\":\"Private industry\",\"5\":\"CWA\",\"6\":\"1998-08-16\",\"7\":\"1998-08-30\",\"8\":\"34000\",\"9\":\"340000\"},{\"1\":\"Southern New England Telecommunications Company\",\"2\":\"Interstate\",\"3\":\"NA\",\"4\":\"Private industry\",\"5\":\"CWA\",\"6\":\"1998-08-23\",\"7\":\"1998-09-17\",\"8\":\"6300\",\"9\":\"113400\"},{\"1\":\"Northwest Airlines\",\"2\":\"Interstate\",\"3\":\"NA\",\"4\":\"Private industry\",\"5\":\"ALPA\",\"6\":\"1998-08-29\",\"7\":\"1998-09-10\",\"8\":\"33700\",\"9\":\"214600\"},{\"1\":\"Continental General Tire Company\",\"2\":\"NC\",\"3\":\"Charlotte\",\"4\":\"Private industry\",\"5\":\"USW\",\"6\":\"1998-09-21\",\"7\":\"1999-09-19\",\"8\":\"1400\",\"9\":\"348600\"},{\"1\":\"Kaiser Aluminum Corp.\",\"2\":\"LA, OH, WA\",\"3\":\"Multiple states\",\"4\":\"Private industry\",\"5\":\"USW\",\"6\":\"1998-10-01\",\"7\":\"2000-09-18\",\"8\":\"3000\",\"9\":\"1479000\"},{\"1\":\"Libbey Inc.\",\"2\":\"OH\",\"3\":\"Toledo\",\"4\":\"Private industry\",\"5\":\"GMP\",\"6\":\"1998-10-01\",\"7\":\"1998-10-11\",\"8\":\"1100\",\"9\":\"7700\"},{\"1\":\"Rheem Manufacturing Company\",\"2\":\"AR\",\"3\":\"Fort Smith\",\"4\":\"Private industry\",\"5\":\"USW\",\"6\":\"1998-10-01\",\"7\":\"1998-10-07\",\"8\":\"1200\",\"9\":\"6000\"},{\"1\":\"Fedders Air Conditioning\",\"2\":\"IL\",\"3\":\"Effingham\",\"4\":\"Private industry\",\"5\":\"BBF\",\"6\":\"1998-10-12\",\"7\":\"1998-11-02\",\"8\":\"1000\",\"9\":\"15000\"},{\"1\":\"Anheuser-Busch Inc.\",\"2\":\"MO\",\"3\":\"St. Louis\",\"4\":\"Private industry\",\"5\":\"IBT\",\"6\":\"1998-10-22\",\"7\":\"1998-10-23\",\"8\":\"1700\",\"9\":\"3400\"},{\"1\":\"American Broadcasting System\",\"2\":\"NY, CA, DC, IL\",\"3\":\"Multiple states\",\"4\":\"Private industry\",\"5\":\"CWA\",\"6\":\"1998-11-02\",\"7\":\"1999-01-15\",\"8\":\"2200\",\"9\":\"112200\"},{\"1\":\"Albert Einstein College of Medicine\",\"2\":\"NY\",\"3\":\"Bronx\",\"4\":\"Private industry\",\"5\":\"NHHSEU\",\"6\":\"1998-11-10\",\"7\":\"1998-11-13\",\"8\":\"1100\",\"9\":\"3300\"},{\"1\":\"Jersey City Public Schools\",\"2\":\"NJ\",\"3\":\"Jersey City\",\"4\":\"Local government\",\"5\":\"JCEA\",\"6\":\"1998-11-19\",\"7\":\"1998-11-23\",\"8\":\"3800\",\"9\":\"11400\"},{\"1\":\"University of California\",\"2\":\"CA\",\"3\":\"Statewide\",\"4\":\"State government\",\"5\":\"CWA\",\"6\":\"1998-12-01\",\"7\":\"1998-12-06\",\"8\":\"1200\",\"9\":\"4800\"},{\"1\":\"ANR Advance Transportation Company\",\"2\":\"OH, WI, IL, NY, MI, OH, MO, TX, IA, IN, KS, KY, TN, MN\",\"3\":\"Multiple states\",\"4\":\"Private industry\",\"5\":\"IBT\",\"6\":\"1998-12-08\",\"7\":\"1998-12-18\",\"8\":\"1400\",\"9\":\"12600\"},{\"1\":\"Women and Infants Hospital\",\"2\":\"RI\",\"3\":\"Providence\",\"4\":\"Private industry\",\"5\":\"NEHE\",\"6\":\"1998-12-22\",\"7\":\"1999-01-14\",\"8\":\"1200\",\"9\":\"19200\"},{\"1\":\"Anchorage School District\",\"2\":\"AK\",\"3\":\"Anchorage\",\"4\":\"Local government\",\"5\":\"TAESP\",\"6\":\"1999-01-15\",\"7\":\"1999-01-21\",\"8\":\"1000\",\"9\":\"4000\"},{\"1\":\"Trane Company\",\"2\":\"TN\",\"3\":\"Clarksville\",\"4\":\"Private industry\",\"5\":\"IAM\",\"6\":\"1999-01-16\",\"7\":\"1999-02-07\",\"8\":\"1800\",\"9\":\"25200\"},{\"1\":\"American Airlines\",\"2\":\"Interstate\",\"3\":\"NA\",\"4\":\"Private industry\",\"5\":\"APA\",\"6\":\"1999-02-06\",\"7\":\"1999-02-16\",\"8\":\"2900\",\"9\":\"10300\"},{\"1\":\"Women and Infants Hospital\",\"2\":\"RI\",\"3\":\"Providence\",\"4\":\"Private industry\",\"5\":\"NEHE\",\"6\":\"1999-02-27\",\"7\":\"1999-02-27\",\"8\":\"1200\",\"9\":\"1200\"},{\"1\":\"University of Michigan\",\"2\":\"MI\",\"3\":\"Ann Arbor\",\"4\":\"State government\",\"5\":\"GEO\",\"6\":\"1999-03-10\",\"7\":\"1999-03-11\",\"8\":\"1100\",\"9\":\"2200\"},{\"1\":\"Newport News Shipbuilding and Drydock Company\",\"2\":\"VA\",\"3\":\"Newport News\",\"4\":\"Private industry\",\"5\":\"USW\",\"6\":\"1999-04-05\",\"7\":\"1999-07-30\",\"8\":\"8000\",\"9\":\"622500\"},{\"1\":\"State of Washington\",\"2\":\"WA\",\"3\":\"Statewide\",\"4\":\"State government\",\"5\":\"WEA\",\"6\":\"1999-04-14\",\"7\":\"1999-04-23\",\"8\":\"11000\",\"9\":\"25600\"},{\"1\":\"SMARCA Inc.\",\"2\":\"MN\",\"3\":\"Minneapolis-St. Paul area\",\"4\":\"Private industry\",\"5\":\"SMW\",\"6\":\"1999-05-05\",\"7\":\"1999-05-10\",\"8\":\"1600\",\"9\":\"4800\"},{\"1\":\"Ingalls Shipbuilding Inc.\",\"2\":\"MS\",\"3\":\"Pascagoula\",\"4\":\"Private industry\",\"5\":\"MTC\",\"6\":\"1999-05-16\",\"7\":\"1999-06-04\",\"8\":\"7000\",\"9\":\"98000\"},{\"1\":\"Independent Contractors\",\"2\":\"CA\",\"3\":\"San Mateo County\",\"4\":\"Private industry\",\"5\":\"UBC\",\"6\":\"1999-05-20\",\"7\":\"1999-05-21\",\"8\":\"1000\",\"9\":\"2000\"},{\"1\":\"IBP Inc.\",\"2\":\"WA\",\"3\":\"Pasco\",\"4\":\"Private industry\",\"5\":\"IBT\",\"6\":\"1999-06-04\",\"7\":\"1999-07-07\",\"8\":\"1000\",\"9\":\"19200\"},{\"1\":\"Buckeye Steel Castings Company\",\"2\":\"OH\",\"3\":\"Columbus\",\"4\":\"Private industry\",\"5\":\"USW\",\"6\":\"1999-06-27\",\"7\":\"1999-07-11\",\"8\":\"1200\",\"9\":\"10800\"},{\"1\":\"Overnite Transportation Co.\",\"2\":\"TN, IN, GA, KS, LA, MN, OH, MI, FL\",\"3\":\"Multiple states\",\"4\":\"Private industry\",\"5\":\"IBT\",\"6\":\"1999-07-05\",\"7\":\"1999-07-09\",\"8\":\"1700\",\"9\":\"6100\"},{\"1\":\"Board of Education of the School District of the City of Detroit\",\"2\":\"MI\",\"3\":\"Detroit\",\"4\":\"Local government\",\"5\":\"AFT\",\"6\":\"1999-08-30\",\"7\":\"1999-09-07\",\"8\":\"11000\",\"9\":\"66000\"},{\"1\":\"Atlantic City Casino Hotels\",\"2\":\"NJ\",\"3\":\"Atlantic City\",\"4\":\"Private industry\",\"5\":\"HERE\",\"6\":\"1999-09-15\",\"7\":\"1999-09-16\",\"8\":\"12000\",\"9\":\"24000\"},{\"1\":\"Bruno's Inc.\",\"2\":\"AL\",\"3\":\"Statewide\",\"4\":\"Private industry\",\"5\":\"UFCW\",\"6\":\"1999-09-26\",\"7\":\"1999-10-02\",\"8\":\"7100\",\"9\":\"35500\"},{\"1\":\"Board of Education of the School District of the School District of the City of Birmingham\",\"2\":\"AL\",\"3\":\"Birmingham\",\"4\":\"Local government\",\"5\":\"NEA\",\"6\":\"1999-11-15\",\"7\":\"1999-11-16\",\"8\":\"2000\",\"9\":\"3600\"},{\"1\":\"Boeing Company\",\"2\":\"WA, OR, KS\",\"3\":\"Multiple states\",\"4\":\"Private industry\",\"5\":\"SPEEA\",\"6\":\"2000-02-09\",\"7\":\"2000-03-19\",\"8\":\"17000\",\"9\":\"459000\"},{\"1\":\"Kaiser Permanente\",\"2\":\"CO\",\"3\":\"Denver area\",\"4\":\"Private industry\",\"5\":\"UFCW\",\"6\":\"2000-03-02\",\"7\":\"2000-03-21\",\"8\":\"1100\",\"9\":\"15400\"},{\"1\":\"Interstate Brands Corp.\",\"2\":\"ME, NY, PA, NJ, MA, RI, CT, NH, VT\",\"3\":\"Multiple states\",\"4\":\"Private industry\",\"5\":\"IBT\",\"6\":\"2000-03-16\",\"7\":\"2000-03-23\",\"8\":\"4600\",\"9\":\"22200\"},{\"1\":\"Associated Wholesale Grocers\",\"2\":\"MO, OK\",\"3\":\"Kansas City; Springfield; Oklahoma City\",\"4\":\"Private industry\",\"5\":\"IBT\",\"6\":\"2000-04-02\",\"7\":\"2000-06-02\",\"8\":\"1400\",\"9\":\"61600\"},{\"1\":\"Los Angeles janitorial maintenance contractors\",\"2\":\"CA\",\"3\":\"Los Angeles County\",\"4\":\"Private industry\",\"5\":\"SEIU\",\"6\":\"2000-04-03\",\"7\":\"2000-04-24\",\"8\":\"8500\",\"9\":\"103800\"},{\"1\":\"Lockheed Martin Aeronautics Company\",\"2\":\"TX\",\"3\":\"Fort Worth\",\"4\":\"Private industry\",\"5\":\"IAM\",\"6\":\"2000-04-10\",\"7\":\"2000-04-26\",\"8\":\"2300\",\"9\":\"29900\"},{\"1\":\"Building Owners and Managers Association\",\"2\":\"IL\",\"3\":\"Chicago\",\"4\":\"Private industry\",\"5\":\"SEIU\",\"6\":\"2000-04-17\",\"7\":\"2000-04-17\",\"8\":\"5000\",\"9\":\"5000\"},{\"1\":\"Cleaning Contractors Association\",\"2\":\"IL\",\"3\":\"Chicago\",\"4\":\"Private industry\",\"5\":\"SEIU\",\"6\":\"2000-04-18\",\"7\":\"2000-04-28\",\"8\":\"4500\",\"9\":\"40500\"},{\"1\":\"University of California\",\"2\":\"CA\",\"3\":\"NA\",\"4\":\"State government\",\"5\":\"UAW\",\"6\":\"2000-04-18\",\"7\":\"2000-04-18\",\"8\":\"5000\",\"9\":\"5000\"},{\"1\":\"Association of National Advertisers; American Association of Advertising Agencies\",\"2\":\"AR, MA, IL, OH, TX, CO, NV, NM, UT, MI, FL, GA, HI, MN, MO, TN, NC, PA, OR, CA, WA, DC, MD\",\"3\":\"Multiple states\",\"4\":\"Private industry\",\"5\":\"AFTRA, SAG\",\"6\":\"2000-05-01\",\"7\":\"2000-10-30\",\"8\":\"135000\",\"9\":\"17280000\"},{\"1\":\"Ohio State University\",\"2\":\"OH\",\"3\":\"Statewide\",\"4\":\"State government\",\"5\":\"CWA\",\"6\":\"2000-05-01\",\"7\":\"2000-05-19\",\"8\":\"1900\",\"9\":\"28500\"},{\"1\":\"Association of Master Painters and Decorators of New York\",\"2\":\"NY\",\"3\":\"New York City, Long Island, and Westchester County\",\"4\":\"Private industry\",\"5\":\"IUPAT\",\"6\":\"2000-06-01\",\"7\":\"2000-06-09\",\"8\":\"4000\",\"9\":\"28000\"},{\"1\":\"Stanford Hospital and Clinics and Lucile Salter Packard Children's Hospital\",\"2\":\"CA\",\"3\":\"Palo Alto\",\"4\":\"Private industry\",\"5\":\"CRONA\",\"6\":\"2000-06-07\",\"7\":\"2000-07-27\",\"8\":\"1700\",\"9\":\"61200\"},{\"1\":\"Maytag Herrin Laundry Products\",\"2\":\"IL\",\"3\":\"Herrin\",\"4\":\"Private industry\",\"5\":\"IAM\",\"6\":\"2000-06-12\",\"7\":\"2000-06-17\",\"8\":\"1200\",\"9\":\"6000\"},{\"1\":\"Northern Illinois Ready Mix and Materials Association; Prairie Materials; and Ozinga Brothers\",\"2\":\"IL\",\"3\":\"Cook County\",\"4\":\"Private industry\",\"5\":\"IBT\",\"6\":\"2000-06-15\",\"7\":\"2000-06-24\",\"8\":\"3400\",\"9\":\"23800\"},{\"1\":\"Hotel employers\",\"2\":\"MN\",\"3\":\"Minneapolis and Bloomington\",\"4\":\"Private industry\",\"5\":\"HERE\",\"6\":\"2000-06-16\",\"7\":\"2000-06-27\",\"8\":\"1100\",\"9\":\"6800\"},{\"1\":\"Hospitals - 10\",\"2\":\"CA\",\"3\":\"Bay and Northern areas\",\"4\":\"Private industry\",\"5\":\"SEIU\",\"6\":\"2000-07-06\",\"7\":\"2000-07-06\",\"8\":\"3800\",\"9\":\"3800\"},{\"1\":\"Associated General Contractors and others\",\"2\":\"NJ\",\"3\":\"Northern\",\"4\":\"Private industry\",\"5\":\"BSOIW\",\"6\":\"2000-07-10\",\"7\":\"2000-07-13\",\"8\":\"2200\",\"9\":\"8800\"},{\"1\":\"Rhode Island Correctional Facilities\",\"2\":\"RI\",\"3\":\"Providence\",\"4\":\"State government\",\"5\":\"RIBCO\",\"6\":\"2000-07-26\",\"7\":\"2000-07-26\",\"8\":\"1200\",\"9\":\"1200\"},{\"1\":\"Northern California Drywall Contractors Association\",\"2\":\"CA\",\"3\":\"Northern\",\"4\":\"Private industry\",\"5\":\"IUPAT\",\"6\":\"2000-08-01\",\"7\":\"2000-08-16\",\"8\":\"1200\",\"9\":\"14400\"},{\"1\":\"Hospitals - 8\",\"2\":\"CA\",\"3\":\"Bay and Northern areas\",\"4\":\"Private industry\",\"5\":\"SEIU\",\"6\":\"2000-08-02\",\"7\":\"2000-08-03\",\"8\":\"3500\",\"9\":\"7000\"},{\"1\":\"Verizon Communications\",\"2\":\"ME, NH, VT, MA, RI, NY, NJ, DE, PA, MD, VA, WV, DC\",\"3\":\"Multiple states\",\"4\":\"Private industry\",\"5\":\"CWA, IBEW\",\"6\":\"2000-08-06\",\"7\":\"2000-08-23\",\"8\":\"85000\",\"9\":\"955000\"},{\"1\":\"Earthgrain Company\",\"2\":\"AL, GA, TN, KY, IL, CO, IA, MS, TX, CA, WI\",\"3\":\"Multiple states\",\"4\":\"Private industry\",\"5\":\"BCTGM\",\"6\":\"2000-08-26\",\"7\":\"2000-09-22\",\"8\":\"4100\",\"9\":\"51500\"},{\"1\":\"Raytheon Company\",\"2\":\"MA\",\"3\":\"Eastern\",\"4\":\"Private industry\",\"5\":\"IBEW\",\"6\":\"2000-08-27\",\"7\":\"2000-10-02\",\"8\":\"3100\",\"9\":\"77500\"},{\"1\":\"Bath Iron Works\",\"2\":\"ME\",\"3\":\"Bath\",\"4\":\"Private industry\",\"5\":\"IAM\",\"6\":\"2000-08-28\",\"7\":\"2000-10-22\",\"8\":\"4800\",\"9\":\"182400\"},{\"1\":\"Board of Education, City of Buffalo\",\"2\":\"NY\",\"3\":\"Buffalo\",\"4\":\"Local government\",\"5\":\"NEA\",\"6\":\"2000-09-07\",\"7\":\"2000-09-07\",\"8\":\"3900\",\"9\":\"3900\"},{\"1\":\"Board of Education, City of Buffalo\",\"2\":\"NY\",\"3\":\"Buffalo\",\"4\":\"Local government\",\"5\":\"NEA\",\"6\":\"2000-09-14\",\"7\":\"2000-09-14\",\"8\":\"3900\",\"9\":\"3900\"},{\"1\":\"Los Angeles County Metropolitan Transportation Authority\",\"2\":\"CA\",\"3\":\"Los Angeles County\",\"4\":\"Local government\",\"5\":\"UTU\",\"6\":\"2000-09-16\",\"7\":\"2000-10-17\",\"8\":\"7400\",\"9\":\"148000\"},{\"1\":\"Hospitals - 3\",\"2\":\"CA\",\"3\":\"Bay area\",\"4\":\"Private industry\",\"5\":\"SEIU\",\"6\":\"2000-09-20\",\"7\":\"2000-09-20\",\"8\":\"1600\",\"9\":\"1600\"},{\"1\":\"Washington Hospital Center\",\"2\":\"DC\",\"3\":\"Washington\",\"4\":\"Private industry\",\"5\":\"DCNA\",\"6\":\"2000-09-20\",\"7\":\"2000-11-08\",\"8\":\"1000\",\"9\":\"35000\"},{\"1\":\"Building and Realty Institute\",\"2\":\"NY\",\"3\":\"Westchester County\",\"4\":\"Private industry\",\"5\":\"SEIU\",\"6\":\"2000-10-04\",\"7\":\"2000-10-10\",\"8\":\"4000\",\"9\":\"16000\"},{\"1\":\"Kroger Company\",\"2\":\"OH, WV\",\"3\":\"Multiple states\",\"4\":\"Private industry\",\"5\":\"UFCW\",\"6\":\"2000-10-11\",\"7\":\"2000-10-11\",\"8\":\"1400\",\"9\":\"1400\"},{\"1\":\"Los Angeles County\",\"2\":\"CA\",\"3\":\"Los Angeles County\",\"4\":\"Local government\",\"5\":\"SEIU\",\"6\":\"2000-10-11\",\"7\":\"2000-10-11\",\"8\":\"47000\",\"9\":\"47000\"},{\"1\":\"Rhode Island Hospital\",\"2\":\"RI\",\"3\":\"Providence\",\"4\":\"Local government\",\"5\":\"IBT\",\"6\":\"2000-10-16\",\"7\":\"2000-10-16\",\"8\":\"1200\",\"9\":\"1200\"},{\"1\":\"Summit Logistics Inc.\",\"2\":\"CA\",\"3\":\"Tracy\",\"4\":\"Private industry\",\"5\":\"IBT\",\"6\":\"2000-10-18\",\"7\":\"2000-12-01\",\"8\":\"1900\",\"9\":\"55300\"},{\"1\":\"Hospitals - 8\",\"2\":\"CA\",\"3\":\"Bay and Northern areas\",\"4\":\"Private industry\",\"5\":\"SEIU\",\"6\":\"2000-10-25\",\"7\":\"2000-10-25\",\"8\":\"3500\",\"9\":\"3500\"},{\"1\":\"Frigidaire Freezer Products\",\"2\":\"MN\",\"3\":\"St. Cloud\",\"4\":\"Private industry\",\"5\":\"IAM\",\"6\":\"2000-10-28\",\"7\":\"2000-11-18\",\"8\":\"1600\",\"9\":\"24000\"},{\"1\":\"Olin Corporation\",\"2\":\"IL\",\"3\":\"East Alton\",\"4\":\"Private industry\",\"5\":\"IAM\",\"6\":\"2000-12-04\",\"7\":\"2001-01-21\",\"8\":\"2700\",\"9\":\"86400\"},{\"1\":\"Hospitals - 18\",\"2\":\"CA\",\"3\":\"Statewide\",\"4\":\"Private industry\",\"5\":\"SEIU\",\"6\":\"2000-12-14\",\"7\":\"2000-12-14\",\"8\":\"6000\",\"9\":\"6000\"},{\"1\":\"Baltimore hospitals - 3\",\"2\":\"MD\",\"3\":\"Baltimore\",\"4\":\"Private industry\",\"5\":\"SEIU\",\"6\":\"2001-01-31\",\"7\":\"2001-02-01\",\"8\":\"2000\",\"9\":\"2000\"},{\"1\":\"Trane Company\",\"2\":\"KY\",\"3\":\"Lexington\",\"4\":\"Private industry\",\"5\":\"UAW\",\"6\":\"2001-02-26\",\"7\":\"2001-03-23\",\"8\":\"1200\",\"9\":\"24000\"},{\"1\":\"Baltimore hospitals - 3\",\"2\":\"MD\",\"3\":\"Baltimore\",\"4\":\"Private industry\",\"5\":\"SEIU\",\"6\":\"2001-03-15\",\"7\":\"2001-03-16\",\"8\":\"2000\",\"9\":\"2000\"},{\"1\":\"Connecticut nursing homes\",\"2\":\"CT\",\"3\":\"Statewide\",\"4\":\"Private industry\",\"5\":\"SEIU\",\"6\":\"2001-03-20\",\"7\":\"2001-03-21\",\"8\":\"4500\",\"9\":\"4500\"},{\"1\":\"Comair\",\"2\":\"Interstate\",\"3\":\"NA\",\"4\":\"Private industry\",\"5\":\"ALPA\",\"6\":\"2001-03-26\",\"7\":\"2001-06-14\",\"8\":\"3300\",\"9\":\"116600\"},{\"1\":\"Mechanical Contractors Association of Southern Indiana and others\",\"2\":\"IN, IL\",\"3\":\"Southern areas\",\"4\":\"Private industry\",\"5\":\"PPF\",\"6\":\"2001-04-02\",\"7\":\"2001-04-12\",\"8\":\"1000\",\"9\":\"9000\"},{\"1\":\"Hawaii Department of Education\",\"2\":\"HI\",\"3\":\"Statewide\",\"4\":\"State government\",\"5\":\"NEA\",\"6\":\"2001-04-05\",\"7\":\"2001-04-23\",\"8\":\"12400\",\"9\":\"161200\"},{\"1\":\"University of Hawaii\",\"2\":\"HI\",\"3\":\"Statewide\",\"4\":\"State government\",\"5\":\"NEA\",\"6\":\"2001-04-05\",\"7\":\"2001-04-17\",\"8\":\"2500\",\"9\":\"22500\"},{\"1\":\"Hospitals\",\"2\":\"CA\",\"3\":\"Northern\",\"4\":\"Private industry\",\"5\":\"SEIU\",\"6\":\"2001-04-16\",\"7\":\"2001-04-19\",\"8\":\"3500\",\"9\":\"10500\"},{\"1\":\"Associated General Contractors and others\",\"2\":\"MN\",\"3\":\"Minneapolis-St. Paul\",\"4\":\"Private industry\",\"5\":\"BAC\",\"6\":\"2001-05-01\",\"7\":\"2001-05-29\",\"8\":\"1000\",\"9\":\"20000\"},{\"1\":\"Des Moines Construction Council\",\"2\":\"IA\",\"3\":\"Des Moines\",\"4\":\"Private industry\",\"5\":\"UBC\",\"6\":\"2001-05-01\",\"7\":\"2001-05-05\",\"8\":\"1200\",\"9\":\"4800\"},{\"1\":\"Seattle Public Schools District\",\"2\":\"WA\",\"3\":\"Seattle\",\"4\":\"Local government\",\"5\":\"NEA\",\"6\":\"2001-05-01\",\"7\":\"2001-05-01\",\"8\":\"6900\",\"9\":\"6900\"},{\"1\":\"Connecticut nursing homes\",\"2\":\"CT\",\"3\":\"Statewide\",\"4\":\"Private industry\",\"5\":\"SEIU\",\"6\":\"2001-05-02\",\"7\":\"2001-05-24\",\"8\":\"4600\",\"9\":\"69700\"},{\"1\":\"Associated General Contractors and others\",\"2\":\"MN\",\"3\":\"Minneapolis-St. Paul\",\"4\":\"Private industry\",\"5\":\"LIUNA\",\"6\":\"2001-05-07\",\"7\":\"2001-05-11\",\"8\":\"4000\",\"9\":\"20000\"},{\"1\":\"Weyerhaeuser Company\",\"2\":\"WA, OR\",\"3\":\"Multiple states\",\"4\":\"Private industry\",\"5\":\"UBC, WPPW\",\"6\":\"2001-05-09\",\"7\":\"2001-05-31\",\"8\":\"1400\",\"9\":\"22400\"},{\"1\":\"Peoples Gas Company\",\"2\":\"IL\",\"3\":\"Chicago\",\"4\":\"Private industry\",\"5\":\"UWUA\",\"6\":\"2001-05-19\",\"7\":\"2001-06-08\",\"8\":\"1000\",\"9\":\"14000\"},{\"1\":\"Minnesota Hospital Healthcare Partnership\",\"2\":\"MN\",\"3\":\"Minneapolis\",\"4\":\"Private industry\",\"5\":\"MNA\",\"6\":\"2001-06-03\",\"7\":\"2001-06-23\",\"8\":\"1400\",\"9\":\"21000\"},{\"1\":\"Northwest Wall and Ceiling Contractors Association\",\"2\":\"WA\",\"3\":\"Seattle\",\"4\":\"Private industry\",\"5\":\"UBC\",\"6\":\"2001-06-12\",\"7\":\"2001-06-18\",\"8\":\"2200\",\"9\":\"11000\"},{\"1\":\"Midwest Generation Company\",\"2\":\"IL\",\"3\":\"Chicago\",\"4\":\"Private industry\",\"5\":\"IBEW\",\"6\":\"2001-06-28\",\"7\":\"2001-10-16\",\"8\":\"1100\",\"9\":\"88000\"},{\"1\":\"Northern California Painters and Finishing Contractors\",\"2\":\"CA\",\"3\":\"San Francisco area\",\"4\":\"Private industry\",\"5\":\"PAT\",\"6\":\"2001-07-01\",\"7\":\"2001-07-30\",\"8\":\"1000\",\"9\":\"21000\"},{\"1\":\"Painters and Decorators Joint Committee\",\"2\":\"CA\",\"3\":\"Oakland area\",\"4\":\"Private industry\",\"5\":\"PAT\",\"6\":\"2001-07-01\",\"7\":\"2001-07-23\",\"8\":\"1200\",\"9\":\"18000\"},{\"1\":\"Automobile Dealers Association\",\"2\":\"MO\",\"3\":\"St. Louis\",\"4\":\"Private industry\",\"5\":\"IAM\",\"6\":\"2001-08-01\",\"7\":\"2001-08-27\",\"8\":\"1700\",\"9\":\"32300\"},{\"1\":\"Sheet Metal Contractors Association\",\"2\":\"MA\",\"3\":\"Boston area\",\"4\":\"Private industry\",\"5\":\"SMW\",\"6\":\"2001-08-01\",\"7\":\"2001-08-12\",\"8\":\"1400\",\"9\":\"11200\"},{\"1\":\"Mitsubishi Manufacturing Co.\",\"2\":\"IL\",\"3\":\"Normal\",\"4\":\"Private industry\",\"5\":\"UAW\",\"6\":\"2001-08-24\",\"7\":\"2001-08-24\",\"8\":\"2700\",\"9\":\"2700\"},{\"1\":\"Shop Rite Supermarkets\",\"2\":\"NJ\",\"3\":\"Southern\",\"4\":\"Private industry\",\"5\":\"UFCW\",\"6\":\"2001-09-07\",\"7\":\"2001-10-28\",\"8\":\"1400\",\"9\":\"49000\"},{\"1\":\"Maytag Company\",\"2\":\"IA\",\"3\":\"Amana\",\"4\":\"Private industry\",\"5\":\"IAM\",\"6\":\"2001-09-23\",\"7\":\"2001-11-11\",\"8\":\"1600\",\"9\":\"54400\"},{\"1\":\"State of Minnesota\",\"2\":\"MN\",\"3\":\"Statewide\",\"4\":\"State government\",\"5\":\"AFSCME; MAPE\",\"6\":\"2001-10-01\",\"7\":\"2001-10-14\",\"8\":\"24900\",\"9\":\"242500\"},{\"1\":\"Pratt and Whitney Division, United Technologies Corp.\",\"2\":\"CT\",\"3\":\"Statewide\",\"4\":\"Private industry\",\"5\":\"IAM\",\"6\":\"2001-12-03\",\"7\":\"2001-12-13\",\"8\":\"5000\",\"9\":\"45000\"},{\"1\":\"Oregon Health and Sciences University\",\"2\":\"OR\",\"3\":\"Portland\",\"4\":\"Private industry\",\"5\":\"ONA\",\"6\":\"2001-12-17\",\"7\":\"2002-02-10\",\"8\":\"1000\",\"9\":\"37000\"},{\"1\":\"Queens bus lines - 3\",\"2\":\"NY\",\"3\":\"Queens\",\"4\":\"Local government\",\"5\":\"TWU\",\"6\":\"2002-02-27\",\"7\":\"2002-02-28\",\"8\":\"1500\",\"9\":\"3000\"},{\"1\":\"Lockheed Martin Corporation\",\"2\":\"GA, MS, WV\",\"3\":\"Multiple states\",\"4\":\"Private industry\",\"5\":\"IAM\",\"6\":\"2002-03-11\",\"7\":\"2002-04-28\",\"8\":\"2900\",\"9\":\"101500\"},{\"1\":\"Group Health, Inc.\",\"2\":\"NY\",\"3\":\"New York\",\"4\":\"Private industry\",\"5\":\"OPEIU\",\"6\":\"2002-04-16\",\"7\":\"2002-05-17\",\"8\":\"1300\",\"9\":\"31200\"},{\"1\":\"Hershey Foods Corporation\",\"2\":\"PA\",\"3\":\"Hershey\",\"4\":\"Private industry\",\"5\":\"BCTGM\",\"6\":\"2002-04-26\",\"7\":\"2002-06-08\",\"8\":\"2800\",\"9\":\"84000\"},{\"1\":\"Connecticut Construction Industry Association\",\"2\":\"CT\",\"3\":\"Hartford\",\"4\":\"Private industry\",\"5\":\"UBC\",\"6\":\"2002-05-01\",\"7\":\"2002-05-14\",\"8\":\"3000\",\"9\":\"30000\"},{\"1\":\"Twin Cities Roofing Contractors Association\",\"2\":\"MN\",\"3\":\"Minneapolis\",\"4\":\"Private industry\",\"5\":\"RWAW\",\"6\":\"2002-05-01\",\"7\":\"2002-06-11\",\"8\":\"1000\",\"9\":\"29000\"},{\"1\":\"Carrier Corporation\",\"2\":\"IN\",\"3\":\"Indianapolis\",\"4\":\"Private industry\",\"5\":\"USW\",\"6\":\"2002-05-03\",\"7\":\"2002-05-13\",\"8\":\"1100\",\"9\":\"7700\"},{\"1\":\"Queens bus lines - 3\",\"2\":\"NY\",\"3\":\"Queens\",\"4\":\"Local government\",\"5\":\"TWU\",\"6\":\"2002-06-17\",\"7\":\"2002-08-06\",\"8\":\"1500\",\"9\":\"54000\"},{\"1\":\"Mechanical Contractors Association of New York\",\"2\":\"NY\",\"3\":\"New York\",\"4\":\"Private industry\",\"5\":\"PPF\",\"6\":\"2002-07-01\",\"7\":\"2002-07-05\",\"8\":\"1700\",\"9\":\"6800\"},{\"1\":\"Cook County\",\"2\":\"IL\",\"3\":\"Chicago\",\"4\":\"Local government\",\"5\":\"AFSCME\",\"6\":\"2002-07-11\",\"7\":\"2002-07-11\",\"8\":\"3800\",\"9\":\"3800\"},{\"1\":\"Delta Dental\",\"2\":\"CA\",\"3\":\"Northern\",\"4\":\"Private industry\",\"5\":\"IBT\",\"6\":\"2002-07-19\",\"7\":\"2002-08-12\",\"8\":\"1200\",\"9\":\"20400\"},{\"1\":\"Dominion - Dominion Energy, Dominion North Carolina Power, Dominion Virginia Power\",\"2\":\"VA, NC, WV\",\"3\":\"Multiple states\",\"4\":\"Private industry\",\"5\":\"IBEW\",\"6\":\"2002-08-02\",\"7\":\"2002-08-15\",\"8\":\"3500\",\"9\":\"35000\"},{\"1\":\"Boeing Company\",\"2\":\"PA\",\"3\":\"Philadelphia\",\"4\":\"Private industry\",\"5\":\"UAW\",\"6\":\"2002-09-14\",\"7\":\"2002-09-22\",\"8\":\"1400\",\"9\":\"7000\"},{\"1\":\"Pacific Maritime Association\",\"2\":\"CA, OR, WA\",\"3\":\"Multiple states\",\"4\":\"Private industry\",\"5\":\"ILWU\",\"6\":\"2002-09-27\",\"7\":\"2002-10-09\",\"8\":\"10500\",\"9\":\"129500\"},{\"1\":\"Maintenance Contractors of New England\",\"2\":\"MA\",\"3\":\"Boston\",\"4\":\"Private industry\",\"5\":\"SEIU\",\"6\":\"2002-09-30\",\"7\":\"2002-10-23\",\"8\":\"1800\",\"9\":\"32400\"},{\"1\":\"Plainfield Community Consolidated Schools District\",\"2\":\"IL\",\"3\":\"Plainfield\",\"4\":\"Local government\",\"5\":\"NEA\",\"6\":\"2002-10-28\",\"7\":\"2002-10-31\",\"8\":\"1200\",\"9\":\"4800\"},{\"1\":\"General Electric Corporation\",\"2\":\"MA\",\"3\":\"Lynn\",\"4\":\"Private industry\",\"5\":\"IUE\",\"6\":\"2002-11-01\",\"7\":\"2002-11-04\",\"8\":\"3200\",\"9\":\"9600\"},{\"1\":\"Billings Board of Education\",\"2\":\"MT\",\"3\":\"Billings\",\"4\":\"Local government\",\"5\":\"NEA\",\"6\":\"2002-11-07\",\"7\":\"2002-11-26\",\"8\":\"1100\",\"9\":\"14300\"},{\"1\":\"Kuakini Medical Center; Queen's Medical Center; St. Francis Medical Center\",\"2\":\"HI\",\"3\":\"Honolulu\",\"4\":\"Private industry\",\"5\":\"HNA\",\"6\":\"2002-12-03\",\"7\":\"2003-01-16\",\"8\":\"1400\",\"9\":\"42400\"},{\"1\":\"General Electric Corp.\",\"2\":\"KY, PA, NY, OH, CA, CT\",\"3\":\"Multiple states\",\"4\":\"Private industry\",\"5\":\"IUE, UE\",\"6\":\"2003-01-14\",\"7\":\"2003-01-15\",\"8\":\"17500\",\"9\":\"35000\"},{\"1\":\"Yale University\",\"2\":\"CT\",\"3\":\"New Haven\",\"4\":\"Private industry\",\"5\":\"HERE\",\"6\":\"2003-03-03\",\"7\":\"2003-03-07\",\"8\":\"2500\",\"9\":\"12500\"},{\"1\":\"League of American Theaters and Producers\",\"2\":\"NY\",\"3\":\"New York\",\"4\":\"Private industry\",\"5\":\"AFM\",\"6\":\"2003-03-07\",\"7\":\"2003-03-10\",\"8\":\"1500\",\"9\":\"6000\"},{\"1\":\"Lockheed Martin Aeronautics Company\",\"2\":\"TX\",\"3\":\"Fort Worth\",\"4\":\"Private industry\",\"5\":\"IAM\",\"6\":\"2003-04-14\",\"7\":\"2003-04-27\",\"8\":\"4000\",\"9\":\"40000\"},{\"1\":\"Dow Chemical Company\",\"2\":\"TX\",\"3\":\"Freeport\",\"4\":\"Private industry\",\"5\":\"IUOE\",\"6\":\"2003-05-20\",\"7\":\"2003-05-28\",\"8\":\"1300\",\"9\":\"7800\"},{\"1\":\"Associated General Contractors of Washington\",\"2\":\"WA\",\"3\":\"Statewide\",\"4\":\"Private industry\",\"5\":\"UBC\",\"6\":\"2003-06-25\",\"7\":\"2003-07-03\",\"8\":\"4000\",\"9\":\"28000\"},{\"1\":\"San Joaquin County\",\"2\":\"CA\",\"3\":\"Stockton\",\"4\":\"Local government\",\"5\":\"SEIU\",\"6\":\"2003-08-04\",\"7\":\"2003-08-08\",\"8\":\"5000\",\"9\":\"25000\"},{\"1\":\"Oahu Transit Services Inc.\",\"2\":\"HI\",\"3\":\"Honolulu\",\"4\":\"Private industry\",\"5\":\"IBT\",\"6\":\"2003-08-26\",\"7\":\"2003-09-27\",\"8\":\"1300\",\"9\":\"29900\"},{\"1\":\"Yale University\",\"2\":\"CT\",\"3\":\"New Haven\",\"4\":\"Private industry\",\"5\":\"HERE\",\"6\":\"2003-08-27\",\"7\":\"2003-09-19\",\"8\":\"1900\",\"9\":\"32300\"},{\"1\":\"Chicago Area Refuse Haulers Association\",\"2\":\"IL\",\"3\":\"Chicago\",\"4\":\"Private industry\",\"5\":\"IBT\",\"6\":\"2003-10-01\",\"7\":\"2003-10-09\",\"8\":\"3300\",\"9\":\"23100\"},{\"1\":\"Dierbergs, Schnucks, and Shop 'N Save Markets\",\"2\":\"MO\",\"3\":\"St. Louis\",\"4\":\"Private industry\",\"5\":\"UFCW\",\"6\":\"2003-10-07\",\"7\":\"2003-10-31\",\"8\":\"10200\",\"9\":\"183600\"},{\"1\":\"Albertsons, Ralphs, and Vons Markets\",\"2\":\"CA\",\"3\":\"Southern CA\",\"4\":\"Private industry\",\"5\":\"UFCW\",\"6\":\"2003-10-12\",\"7\":\"2004-02-29\",\"8\":\"67300\",\"9\":\"5718100\"},{\"1\":\"Kroger Company\",\"2\":\"KY, OH, WV\",\"3\":\"Multiple states\",\"4\":\"Private industry\",\"5\":\"UFCW\",\"6\":\"2003-10-13\",\"7\":\"2003-12-11\",\"8\":\"3200\",\"9\":\"131200\"},{\"1\":\"Los Angeles County Metropolitan Transportation Authority\",\"2\":\"CA\",\"3\":\"Los Angeles\",\"4\":\"Local government\",\"5\":\"ATU\",\"6\":\"2003-10-14\",\"7\":\"2003-11-17\",\"8\":\"6200\",\"9\":\"148600\"},{\"1\":\"American Axle and Manufacturing, Inc.\",\"2\":\"MI, NY\",\"3\":\"Multiple states\",\"4\":\"Private industry\",\"5\":\"UAW\",\"6\":\"2004-02-26\",\"7\":\"2004-02-26\",\"8\":\"6700\",\"9\":\"6700\"},{\"1\":\"Metropolitan Council/Metro Transit\",\"2\":\"MN\",\"3\":\"Minneapolis-St. Paul\",\"4\":\"Local government\",\"5\":\"ATU\",\"6\":\"2004-03-04\",\"7\":\"2004-04-16\",\"8\":\"2200\",\"9\":\"70400\"},{\"1\":\"SBC Communications Inc.\",\"2\":\"Nationwide\",\"3\":\"NA\",\"4\":\"Private industry\",\"5\":\"CWA\",\"6\":\"2004-05-21\",\"7\":\"2004-05-24\",\"8\":\"102000\",\"9\":\"204000\"},{\"1\":\"Visteon Corporation\",\"2\":\"IN\",\"3\":\"Bedford\",\"4\":\"Private industry\",\"5\":\"CWA-IUE\",\"6\":\"2004-05-30\",\"7\":\"2004-06-13\",\"8\":\"1000\",\"9\":\"9000\"},{\"1\":\"Home Health Care Agencies\",\"2\":\"NY\",\"3\":\"New York\",\"4\":\"Private industry\",\"5\":\"SEIU\",\"6\":\"2004-06-07\",\"7\":\"2004-06-09\",\"8\":\"23000\",\"9\":\"57000\"},{\"1\":\"City of New York\",\"2\":\"NY\",\"3\":\"New York\",\"4\":\"Local government\",\"5\":\"AFSCME\",\"6\":\"2004-06-09\",\"7\":\"2004-06-11\",\"8\":\"7000\",\"9\":\"21000\"},{\"1\":\"Maytag Corporation\",\"2\":\"IA\",\"3\":\"Newton\",\"4\":\"Private industry\",\"5\":\"UAW\",\"6\":\"2004-06-10\",\"7\":\"2004-07-02\",\"8\":\"1600\",\"9\":\"27200\"},{\"1\":\"Automotive Dealers Association\",\"2\":\"MO\",\"3\":\"St. Louis\",\"4\":\"Private industry\",\"5\":\"IAM, IBT\",\"6\":\"2004-08-02\",\"7\":\"2004-10-14\",\"8\":\"2000\",\"9\":\"104000\"},{\"1\":\"Group Health Cooperative of Puget Sound\",\"2\":\"WA\",\"3\":\"Seattle\",\"4\":\"Private industry\",\"5\":\"SEIU\",\"6\":\"2004-08-23\",\"7\":\"2004-08-27\",\"8\":\"1700\",\"9\":\"8500\"},{\"1\":\"Las Vegas Convention Center Service Providers\",\"2\":\"NV\",\"3\":\"Las Vegas\",\"4\":\"Private industry\",\"5\":\"IBT\",\"6\":\"2004-09-04\",\"7\":\"2004-09-11\",\"8\":\"3000\",\"9\":\"12000\"},{\"1\":\"San Francisco Multi-Employer Group\",\"2\":\"CA\",\"3\":\"San Francisco\",\"4\":\"Private industry\",\"5\":\"UNITE HERE\",\"6\":\"2004-09-29\",\"7\":\"2004-11-23\",\"8\":\"1500\",\"9\":\"154700\"},{\"1\":\"Hotel/Casino Employers\",\"2\":\"NJ\",\"3\":\"Atlantic City\",\"4\":\"Private industry\",\"5\":\"UNITE HERE\",\"6\":\"2004-10-01\",\"7\":\"2004-11-03\",\"8\":\"10000\",\"9\":\"230000\"},{\"1\":\"Ormet\",\"2\":\"OH\",\"3\":\"Hannibal\",\"4\":\"Private industry\",\"5\":\"USW\",\"6\":\"2004-11-22\",\"7\":\"2006-07-16\",\"8\":\"1200\",\"9\":\"522600\"},{\"1\":\"Turnpike Workers\",\"2\":\"PA\",\"3\":\"Fort Washington\",\"4\":\"State government\",\"5\":\"IBT\",\"6\":\"2004-11-24\",\"7\":\"2004-11-30\",\"8\":\"2000\",\"9\":\"8000\"},{\"1\":\"Sutter Healthcare Hospitals\",\"2\":\"CA\",\"3\":\"San Francisco\",\"4\":\"Private industry\",\"5\":\"SEIU\",\"6\":\"2004-12-06\",\"7\":\"2004-12-10\",\"8\":\"7000\",\"9\":\"35000\"},{\"1\":\"New Jersey Central Power and Light\",\"2\":\"NJ\",\"3\":\"Central New Jersey\",\"4\":\"Private industry\",\"5\":\"IBEW\",\"6\":\"2004-12-08\",\"7\":\"2005-03-15\",\"8\":\"1300\",\"9\":\"85800\"},{\"1\":\"St. John's Mercy Medical Center\",\"2\":\"MO\",\"3\":\"St. Louis\",\"4\":\"Private industry\",\"5\":\"UFCW\",\"6\":\"2004-12-15\",\"7\":\"2004-12-31\",\"8\":\"1500\",\"9\":\"16500\"},{\"1\":\"Lockheed Martin Corporation\",\"2\":\"GA\",\"3\":\"Marietta\",\"4\":\"Private industry\",\"5\":\"IAM\",\"6\":\"2005-03-08\",\"7\":\"2005-03-15\",\"8\":\"3000\",\"9\":\"18000\"},{\"1\":\"Cooper Tire and Rubber Company\",\"2\":\"AR\",\"3\":\"Texarkana\",\"4\":\"Private industry\",\"5\":\"USW\",\"6\":\"2005-03-14\",\"7\":\"2005-04-11\",\"8\":\"1700\",\"9\":\"34000\"},{\"1\":\"Elevator Manufacturers Association of New York - Kane Inc.; Otis Elevator Co.; Schindler Elevator Corp.\",\"2\":\"NY\",\"3\":\"New York City\",\"4\":\"Private industry\",\"5\":\"IUEC\",\"6\":\"2005-03-17\",\"7\":\"2005-06-26\",\"8\":\"1200\",\"9\":\"85200\"},{\"1\":\"Plumbing and Mechanical Contractors Association\",\"2\":\"IL\",\"3\":\"Chicago\",\"4\":\"Private industry\",\"5\":\"UA\",\"6\":\"2005-04-14\",\"7\":\"2005-05-02\",\"8\":\"1800\",\"9\":\"23400\"},{\"1\":\"University of California\",\"2\":\"CA\",\"3\":\"Oakland\",\"4\":\"State government\",\"5\":\"NA\",\"6\":\"2005-04-14\",\"7\":\"2005-04-15\",\"8\":\"2000\",\"9\":\"2000\"},{\"1\":\"University of California\",\"2\":\"CA\",\"3\":\"Oakland\",\"4\":\"State government\",\"5\":\"AFSME\",\"6\":\"2005-04-14\",\"7\":\"2005-04-15\",\"8\":\"7000\",\"9\":\"7000\"},{\"1\":\"University of California\",\"2\":\"CA\",\"3\":\"Oakland\",\"4\":\"State government\",\"5\":\"NA\",\"6\":\"2005-04-14\",\"7\":\"2005-04-15\",\"8\":\"2000\",\"9\":\"2000\"},{\"1\":\"Mechanical Contractors Association\",\"2\":\"PA\",\"3\":\"Philadelphia\",\"4\":\"Private industry\",\"5\":\"UA\",\"6\":\"2005-05-01\",\"7\":\"2005-05-04\",\"8\":\"2700\",\"9\":\"8100\"},{\"1\":\"Construction Employers Association\",\"2\":\"OH\",\"3\":\"Cleveland\",\"4\":\"Private industry\",\"5\":\"LIUNA\",\"6\":\"2005-05-02\",\"7\":\"2005-05-11\",\"8\":\"2100\",\"9\":\"16800\"},{\"1\":\"NSTAR\",\"2\":\"MA\",\"3\":\"Braintree\",\"4\":\"Private industry\",\"5\":\"UWUA\",\"6\":\"2005-05-15\",\"7\":\"2005-06-01\",\"8\":\"1900\",\"9\":\"22800\"},{\"1\":\"Coca-Cola Bottlers\",\"2\":\"CA, CT\",\"3\":\"Southern California and Windsor, Connecticut\",\"4\":\"Private industry\",\"5\":\"IBT\",\"6\":\"2005-05-23\",\"7\":\"2005-06-03\",\"8\":\"1900\",\"9\":\"17100\"},{\"1\":\"Moving and Storage Companies\",\"2\":\"NY\",\"3\":\"New York City area\",\"4\":\"Private industry\",\"5\":\"IBT\",\"6\":\"2005-05-25\",\"7\":\"2005-06-13\",\"8\":\"1000\",\"9\":\"12000\"},{\"1\":\"Mechanical Contractors Association\",\"2\":\"PA\",\"3\":\"Pittsburgh\",\"4\":\"Private industry\",\"5\":\"UA\",\"6\":\"2005-06-01\",\"7\":\"2005-06-09\",\"8\":\"1000\",\"9\":\"7000\"},{\"1\":\"Mid-Michigan Mechanical Contractors Association\",\"2\":\"MI\",\"3\":\"Central\",\"4\":\"Private industry\",\"5\":\"UA\",\"6\":\"2005-06-01\",\"7\":\"2005-06-03\",\"8\":\"1000\",\"9\":\"3000\"},{\"1\":\"Los Angeles Hotel Employer's Council\",\"2\":\"CA\",\"3\":\"Los Angeles\",\"4\":\"Private industry\",\"5\":\"UNITE HERE\",\"6\":\"2005-06-09\",\"7\":\"2005-06-11\",\"8\":\"2400\",\"9\":\"7200\"},{\"1\":\"Asarco, Inc.\",\"2\":\"AZ\",\"3\":\"Tucson\",\"4\":\"Private industry\",\"5\":\"USW\",\"6\":\"2005-06-30\",\"7\":\"2005-11-15\",\"8\":\"1500\",\"9\":\"134100\"},{\"1\":\"Allied Building Metals Industries, Inc.\",\"2\":\"NY\",\"3\":\"New York City\",\"4\":\"Private industry\",\"5\":\"BSOIW\",\"6\":\"2005-07-08\",\"7\":\"2005-07-22\",\"8\":\"1500\",\"9\":\"16500\"},{\"1\":\"Northwest Airlines Corporation\",\"2\":\"MN\",\"3\":\"Eagan\",\"4\":\"Private industry\",\"5\":\"AMFA\",\"6\":\"2005-08-20\",\"7\":\"2006-11-06\",\"8\":\"3000\",\"9\":\"1183800\"},{\"1\":\"Boeing Company\",\"2\":\"OR, KS\",\"3\":\"Puget Sound area and Wichita\",\"4\":\"Private industry\",\"5\":\"IAM\",\"6\":\"2005-09-02\",\"7\":\"2005-09-30\",\"8\":\"18300\",\"9\":\"366000\"},{\"1\":\"Southeastern Pennsylvania Transit Authority\",\"2\":\"PA\",\"3\":\"Philadelphia\",\"4\":\"Private industry\",\"5\":\"TWU 234, UTU 1594\",\"6\":\"2005-10-31\",\"7\":\"2005-11-07\",\"8\":\"5300\",\"9\":\"31800\"},{\"1\":\"Boeing Company\",\"2\":\"CA, FL, AL\",\"3\":\"Huntington Beach, Torrance, Vandenberg, and Edwards Air force Base, CA; Cape Canaveral, FL; Huntsville and Decatur, AL\",\"4\":\"Private industry\",\"5\":\"IAM\",\"6\":\"2005-11-02\",\"7\":\"2006-02-06\",\"8\":\"1500\",\"9\":\"87200\"},{\"1\":\"New York City Metropolitan Transit Authority\",\"2\":\"NY\",\"3\":\"New York\",\"4\":\"Local government\",\"5\":\"TWU\",\"6\":\"2005-12-20\",\"7\":\"2005-12-23\",\"8\":\"35000\",\"9\":\"105000\"},{\"1\":\"Sikorsky Aircraft Corporation\",\"2\":\"CT, FL\",\"3\":\"Stratford, West Palm Beach\",\"4\":\"Private industry\",\"5\":\"IBT\",\"6\":\"2006-02-20\",\"7\":\"2006-04-03\",\"8\":\"3600\",\"9\":\"108000\"},{\"1\":\"AK Steel Corp.\",\"2\":\"OH\",\"3\":\"Middletown\",\"4\":\"Private industry\",\"5\":\"IAM\",\"6\":\"2006-03-01\",\"7\":\"2007-03-14\",\"8\":\"1800\",\"9\":\"556200\"},{\"1\":\"Santa Cruz County Government\",\"2\":\"CA\",\"3\":\"Santa Cruz\",\"4\":\"Local government\",\"5\":\"SEIU\",\"6\":\"2006-03-14\",\"7\":\"2006-03-15\",\"8\":\"1600\",\"9\":\"1600\"},{\"1\":\"Denver Regional Transit District\",\"2\":\"CO\",\"3\":\"Denver\",\"4\":\"Local government\",\"5\":\"ATU\",\"6\":\"2006-04-03\",\"7\":\"2006-04-09\",\"8\":\"1700\",\"9\":\"8500\"},{\"1\":\"Greater Metropolitan Automotive Dealers Association of Minnesota\",\"2\":\"MN\",\"3\":\"Minneapolis\",\"4\":\"Private industry\",\"5\":\"IBT\",\"6\":\"2006-04-17\",\"7\":\"2006-05-09\",\"8\":\"1400\",\"9\":\"23800\"},{\"1\":\"General Building Contractors Association\",\"2\":\"PA\",\"3\":\"Philadelphia\",\"4\":\"Private industry\",\"5\":\"UBC\",\"6\":\"2006-05-01\",\"7\":\"2006-05-02\",\"8\":\"5000\",\"9\":\"5000\"},{\"1\":\"Mason Contractors Association and Independent Employers\",\"2\":\"MO\",\"3\":\"St. Louis area\",\"4\":\"Private industry\",\"5\":\"IUBAC\",\"6\":\"2006-06-01\",\"7\":\"2006-06-08\",\"8\":\"1200\",\"9\":\"7200\"},{\"1\":\"MidAmerica Regional Bargaining Association\",\"2\":\"IL\",\"3\":\"Chicago\",\"4\":\"Private industry\",\"5\":\"LIUNA\",\"6\":\"2006-06-01\",\"7\":\"2006-06-04\",\"8\":\"2000\",\"9\":\"4000\"},{\"1\":\"Grove Masonry Maintenance, Inc. and Tuckpointing Contractors Association\",\"2\":\"IL\",\"3\":\"Chicago\",\"4\":\"Private industry\",\"5\":\"IUBAC\",\"6\":\"2006-06-12\",\"7\":\"2006-06-17\",\"8\":\"1600\",\"9\":\"8000\"},{\"1\":\"Contra Costa County\",\"2\":\"CA\",\"3\":\"Danville\",\"4\":\"Local government\",\"5\":\"SEIU, AFSME\",\"6\":\"2006-06-27\",\"7\":\"2006-06-28\",\"8\":\"6000\",\"9\":\"6000\"},{\"1\":\"General Contractors Association of Greater New York, NY\",\"2\":\"NY\",\"3\":\"New York\",\"4\":\"Private industry\",\"5\":\"IUOE\",\"6\":\"2006-07-01\",\"7\":\"2006-07-07\",\"8\":\"3000\",\"9\":\"12000\"},{\"1\":\"Gary School District\",\"2\":\"IN\",\"3\":\"Gary\",\"4\":\"Local government\",\"5\":\"GTU\",\"6\":\"2006-08-21\",\"7\":\"2006-09-01\",\"8\":\"1400\",\"9\":\"14000\"},{\"1\":\"City of Los Angeles\",\"2\":\"CA\",\"3\":\"Los Angeles\",\"4\":\"Local government\",\"5\":\"EAA\",\"6\":\"2006-08-22\",\"7\":\"2006-08-23\",\"8\":\"7500\",\"9\":\"15000\"},{\"1\":\"Robert Wood Johnson University Hospital\",\"2\":\"NJ\",\"3\":\"New Brunswick\",\"4\":\"Local government\",\"5\":\"USW\",\"6\":\"2006-08-24\",\"7\":\"2006-09-21\",\"8\":\"1200\",\"9\":\"24000\"},{\"1\":\"Detroit School District\",\"2\":\"MI\",\"3\":\"Detroit\",\"4\":\"Local government\",\"5\":\"DFT\",\"6\":\"2006-08-28\",\"7\":\"2006-09-13\",\"8\":\"9500\",\"9\":\"104500\"},{\"1\":\"Sacramento County\",\"2\":\"CA\",\"3\":\"Sacramento\",\"4\":\"Local government\",\"5\":\"AFSCME\",\"6\":\"2006-09-05\",\"7\":\"2006-09-18\",\"8\":\"3900\",\"9\":\"39000\"},{\"1\":\"Bombardier Learjet\",\"2\":\"KS\",\"3\":\"Wichita\",\"4\":\"Private industry\",\"5\":\"IAM\",\"6\":\"2006-10-02\",\"7\":\"2006-10-23\",\"8\":\"1100\",\"9\":\"16500\"},{\"1\":\"Goodyear Tire and Rubber Co.\",\"2\":\"AL, NE, NY, NC, OH, KS, TN, TX, VA, WI\",\"3\":\"Multiple states\",\"4\":\"Private industry\",\"5\":\"USW\",\"6\":\"2006-10-06\",\"7\":\"2006-12-29\",\"8\":\"12600\",\"9\":\"718200\"},{\"1\":\"ABM Janitorial Services, GCA Services Group, Sanitors Services of Texas, Pritchard Industries Southwest\",\"2\":\"TX\",\"3\":\"Houston\",\"4\":\"Private industry\",\"5\":\"SEIU\",\"6\":\"2006-10-23\",\"7\":\"2006-11-20\",\"8\":\"1300\",\"9\":\"26000\"},{\"1\":\"Raytheon Missile Systems\",\"2\":\"AZ\",\"3\":\"Tucson\",\"4\":\"Private industry\",\"5\":\"IAM\",\"6\":\"2006-11-06\",\"7\":\"2007-01-19\",\"8\":\"1900\",\"9\":\"93100\"},{\"1\":\"Harley-Davidson Motor Company\",\"2\":\"PA\",\"3\":\"York\",\"4\":\"Private industry\",\"5\":\"IAM\",\"6\":\"2007-02-02\",\"7\":\"2007-02-22\",\"8\":\"2800\",\"9\":\"39200\"},{\"1\":\"Northrop Grumman Ship Systems, Ingalls Shipyard\",\"2\":\"MS\",\"3\":\"Pascagoula\",\"4\":\"Private industry\",\"5\":\"IBEW, OPEIU\",\"6\":\"2007-03-08\",\"7\":\"2007-04-04\",\"8\":\"6500\",\"9\":\"130000\"},{\"1\":\"Community College of Philadelphia\",\"2\":\"PA\",\"3\":\"Philadelphia\",\"4\":\"Local government\",\"5\":\"FSFCCP\",\"6\":\"2007-03-13\",\"7\":\"2007-03-27\",\"8\":\"1300\",\"9\":\"14300\"},{\"1\":\"National Fire Sprinkler Association\",\"2\":\"Nationwide\",\"3\":\"NA\",\"4\":\"Private industry\",\"5\":\"RSF\",\"6\":\"2007-04-01\",\"7\":\"2007-04-16\",\"8\":\"3000\",\"9\":\"33000\"},{\"1\":\"Foundation Coal Holdings\",\"2\":\"PA\",\"3\":\"Waynesburg\",\"4\":\"Private industry\",\"5\":\"UMW\",\"6\":\"2007-04-04\",\"7\":\"2007-04-13\",\"8\":\"1200\",\"9\":\"9600\"},{\"1\":\"Hayward School District\",\"2\":\"CA\",\"3\":\"Hayward\",\"4\":\"Local government\",\"5\":\"NA\",\"6\":\"2007-04-05\",\"7\":\"2007-04-25\",\"8\":\"1300\",\"9\":\"19500\"},{\"1\":\"Associated Wall and Ceiling Contractors of Oregon and Southwest Washington, Inc.\",\"2\":\"OR, WA\",\"3\":\"Multiple states\",\"4\":\"Private industry\",\"5\":\"NA\",\"6\":\"2007-06-01\",\"7\":\"2007-06-19\",\"8\":\"1200\",\"9\":\"15600\"},{\"1\":\"National Electrical Contractors of America\",\"2\":\"WA\",\"3\":\"Puget Sound\",\"4\":\"Private industry\",\"5\":\"IBEW\",\"6\":\"2007-06-01\",\"7\":\"2007-06-01\",\"8\":\"2800\",\"9\":\"2800\"},{\"1\":\"Orange County Transportation Authority\",\"2\":\"CA\",\"3\":\"Orange County area\",\"4\":\"Local government\",\"5\":\"IBT\",\"6\":\"2007-07-07\",\"7\":\"2007-07-16\",\"8\":\"1100\",\"9\":\"6600\"},{\"1\":\"Harlem Consolidated Schools, District 122\",\"2\":\"IL\",\"3\":\"Machesney Park\",\"4\":\"Local government\",\"5\":\"AFT\",\"6\":\"2007-08-21\",\"7\":\"2007-09-01\",\"8\":\"1000\",\"9\":\"9000\"},{\"1\":\"New York City Taxi and Limousine Commission\",\"2\":\"NY\",\"3\":\"New York\",\"4\":\"Local government\",\"5\":\"NA\",\"6\":\"2007-09-05\",\"7\":\"2007-09-07\",\"8\":\"26000\",\"9\":\"52000\"},{\"1\":\"Philadelphia Parking Authority\",\"2\":\"PA\",\"3\":\"Philadelphia\",\"4\":\"Local government\",\"5\":\"NA\",\"6\":\"2007-09-05\",\"7\":\"2007-09-06\",\"8\":\"1200\",\"9\":\"1200\"},{\"1\":\"University of Minnesota\",\"2\":\"MN\",\"3\":\"Duluth\",\"4\":\"Local government\",\"5\":\"AFSCME\",\"6\":\"2007-09-05\",\"7\":\"2007-09-21\",\"8\":\"3100\",\"9\":\"40300\"},{\"1\":\"General Motors Corporation\",\"2\":\"Nationwide\",\"3\":\"NA\",\"4\":\"Private industry\",\"5\":\"UAW\",\"6\":\"2007-09-24\",\"7\":\"2007-09-26\",\"8\":\"74000\",\"9\":\"148000\"},{\"1\":\"San Francisco Bay Area Security Officers\",\"2\":\"CA\",\"3\":\"San Francisco\",\"4\":\"Private industry\",\"5\":\"SEIU\",\"6\":\"2007-09-24\",\"7\":\"2007-09-28\",\"8\":\"4000\",\"9\":\"20000\"},{\"1\":\"Sutter Hospitals\",\"2\":\"CA\",\"3\":\"NA\",\"4\":\"Private industry\",\"5\":\"CNA\",\"6\":\"2007-10-10\",\"7\":\"2007-10-12\",\"8\":\"5000\",\"9\":\"15000\"},{\"1\":\"New York City Taxi and Limousine Commission\",\"2\":\"NY\",\"3\":\"New York\",\"4\":\"Local government\",\"5\":\"NA\",\"6\":\"2007-10-22\",\"7\":\"2007-10-23\",\"8\":\"33000\",\"9\":\"33000\"},{\"1\":\"International Truck and Engine Corporation\",\"2\":\"OH, IN, IL, GA, PA, TX\",\"3\":\"Multiple states\",\"4\":\"Private industry\",\"5\":\"UAW\",\"6\":\"2007-10-23\",\"7\":\"2007-12-13\",\"8\":\"3700\",\"9\":\"133200\"},{\"1\":\"Alliance of Motion Picture and Television Producers\",\"2\":\"Nationwide\",\"3\":\"NA\",\"4\":\"Private industry\",\"5\":\"NA\",\"6\":\"2007-11-05\",\"7\":\"2008-02-12\",\"8\":\"10500\",\"9\":\"714000\"},{\"1\":\"Paratransit Operators Coalition\",\"2\":\"NY\",\"3\":\"New York\",\"4\":\"Local government\",\"5\":\"ATU\",\"6\":\"2007-12-10\",\"7\":\"2007-12-19\",\"8\":\"1500\",\"9\":\"12000\"},{\"1\":\"Sutter Hospitals\",\"2\":\"CA\",\"3\":\"NA\",\"4\":\"Private industry\",\"5\":\"CNA\",\"6\":\"2007-12-13\",\"7\":\"2007-12-14\",\"8\":\"5000\",\"9\":\"10000\"},{\"1\":\"Volvo Trucks North America\",\"2\":\"VA\",\"3\":\"Dublin\",\"4\":\"Private industry\",\"5\":\"UAW\",\"6\":\"2008-02-01\",\"7\":\"2008-03-17\",\"8\":\"2500\",\"9\":\"77500\"},{\"1\":\"American Axel and Manufacturing, Inc.\",\"2\":\"NY, MI\",\"3\":\"Cheektowaga and Tonawanda, NY; Detroit, Hamtramck, and Three Rivers, MI\",\"4\":\"Private industry\",\"5\":\"UAW\",\"6\":\"2008-02-26\",\"7\":\"2008-05-22\",\"8\":\"3600\",\"9\":\"226800\"},{\"1\":\"Sutter Hospitals\",\"2\":\"CA\",\"3\":\"San Francisco Bay Area\",\"4\":\"Private industry\",\"5\":\"CNA\",\"6\":\"2008-03-21\",\"7\":\"2008-03-30\",\"8\":\"4000\",\"9\":\"24000\"},{\"1\":\"University of Michigan\",\"2\":\"MI\",\"3\":\"Ann Arbor\",\"4\":\"State government\",\"5\":\"NA\",\"6\":\"2008-03-25\",\"7\":\"2008-03-25\",\"8\":\"1700\",\"9\":\"1700\"},{\"1\":\"General Motors Corporation\",\"2\":\"MI\",\"3\":\"Lansing\",\"4\":\"Private industry\",\"5\":\"UAW\",\"6\":\"2008-04-17\",\"7\":\"2008-05-16\",\"8\":\"2300\",\"9\":\"50600\"},{\"1\":\"General Motors Corporation\",\"2\":\"MO\",\"3\":\"Kansas City\",\"4\":\"Private industry\",\"5\":\"UAW\",\"6\":\"2008-05-05\",\"7\":\"2008-05-21\",\"8\":\"2400\",\"9\":\"31200\"},{\"1\":\"Bay Area Maintenance Contractors\",\"2\":\"CA\",\"3\":\"San Francisco Bay Area\",\"4\":\"Private industry\",\"5\":\"SEIU\",\"6\":\"2008-05-19\",\"7\":\"2008-05-28\",\"8\":\"1800\",\"9\":\"12600\"},{\"1\":\"Indiana Construction Association\",\"2\":\"IN\",\"3\":\"NA\",\"4\":\"Private industry\",\"5\":\"LIUNA\",\"6\":\"2008-06-04\",\"7\":\"2008-06-05\",\"8\":\"2900\",\"9\":\"5800\"},{\"1\":\"Performance Transportation Services\",\"2\":\"AZ, CA, DE, IL, IN, KY, MA, MI, MN, NJ, NM, NY, OH, PA, TX, UT\",\"3\":\"Multiple states\",\"4\":\"Private industry\",\"5\":\"IBT\",\"6\":\"2008-06-09\",\"7\":\"2008-06-13\",\"8\":\"1300\",\"9\":\"6500\"},{\"1\":\"University of California\",\"2\":\"CA\",\"3\":\"Statewide\",\"4\":\"State government\",\"5\":\"AFSCME\",\"6\":\"2008-07-14\",\"7\":\"2008-07-18\",\"8\":\"8500\",\"9\":\"42500\"},{\"1\":\"Hawker Beechcraft, Inc.\",\"2\":\"KS\",\"3\":\"Wichita, Salinas\",\"4\":\"Private industry\",\"5\":\"IAM\",\"6\":\"2008-08-04\",\"7\":\"2008-08-28\",\"8\":\"5200\",\"9\":\"98800\"},{\"1\":\"Daughters of Charity Health System\",\"2\":\"CA\",\"3\":\"San Francisco\",\"4\":\"Private industry\",\"5\":\"SEIU\",\"6\":\"2008-08-28\",\"7\":\"2008-08-29\",\"8\":\"1800\",\"9\":\"1800\"},{\"1\":\"Bellevue School District\",\"2\":\"WA\",\"3\":\"Bellevue\",\"4\":\"Local government\",\"5\":\"NA\",\"6\":\"2008-09-02\",\"7\":\"2008-09-12\",\"8\":\"1200\",\"9\":\"10800\"},{\"1\":\"The Boeing Company\",\"2\":\"WA, OR, KS\",\"3\":\"Puget Sound Area, Gresham, Wichita\",\"4\":\"Private industry\",\"5\":\"IAM\",\"6\":\"2008-09-06\",\"7\":\"2008-11-01\",\"8\":\"27000\",\"9\":\"1053000\"},{\"1\":\"Sutter Hospitals, Daughters of Charity and Alliance Clinic\",\"2\":\"CA\",\"3\":\"San Francisco Bay Area\",\"4\":\"Private industry\",\"5\":\"SEIU\",\"6\":\"2008-10-29\",\"7\":\"2008-10-29\",\"8\":\"6000\",\"9\":\"6000\"},{\"1\":\"Bell Helicopter Textron, Inc.\",\"2\":\"TX\",\"3\":\"Fort Worth\",\"4\":\"Private industry\",\"5\":\"UAW\",\"6\":\"2009-06-15\",\"7\":\"2009-07-22\",\"8\":\"2500\",\"9\":\"67500\"},{\"1\":\"Interior Demolition Contractors Association\",\"2\":\"NY\",\"3\":\"New York\",\"4\":\"Private industry\",\"5\":\"LIUNA\",\"6\":\"2009-07-01\",\"7\":\"2009-07-07\",\"8\":\"1500\",\"9\":\"6000\"},{\"1\":\"Kent Public School District\",\"2\":\"WA\",\"3\":\"Kent\",\"4\":\"Local government\",\"5\":\"NA\",\"6\":\"2009-08-27\",\"7\":\"2009-09-13\",\"8\":\"1900\",\"9\":\"20900\"},{\"1\":\"Southeastern Pennsylvania Transportation Authority\",\"2\":\"PA\",\"3\":\"Philadelphia\",\"4\":\"Local government\",\"5\":\"TWU\",\"6\":\"2009-11-03\",\"7\":\"2009-11-09\",\"8\":\"5500\",\"9\":\"27500\"},{\"1\":\"University of Illinois\",\"2\":\"IL\",\"3\":\"Champaign - Urbana\",\"4\":\"State government\",\"5\":\"AFT\",\"6\":\"2009-11-16\",\"7\":\"2009-11-17\",\"8\":\"1100\",\"9\":\"2200\"},{\"1\":\"Temple University Hospital\",\"2\":\"PA\",\"3\":\"Philadelphia\",\"4\":\"State government\",\"5\":\"NA\",\"6\":\"2010-03-31\",\"7\":\"2010-04-28\",\"8\":\"1500\",\"9\":\"31500\"},{\"1\":\"North Penn School District\",\"2\":\"PA\",\"3\":\"Montgomery County\",\"4\":\"Local government\",\"5\":\"NA\",\"6\":\"2010-04-19\",\"7\":\"2010-04-26\",\"8\":\"1100\",\"9\":\"6600\"},{\"1\":\"Capistrano Unified School District\",\"2\":\"CA\",\"3\":\"San Juan Capistrano Area\",\"4\":\"Local government\",\"5\":\"NA\",\"6\":\"2010-04-22\",\"7\":\"2010-04-26\",\"8\":\"1800\",\"9\":\"5400\"},{\"1\":\"Oakland Unified School District\",\"2\":\"CA\",\"3\":\"Oakland\",\"4\":\"Local government\",\"5\":\"NA\",\"6\":\"2010-04-29\",\"7\":\"2010-04-29\",\"8\":\"2500\",\"9\":\"2500\"},{\"1\":\"The Boeing Company\",\"2\":\"CA\",\"3\":\"Long Beach\",\"4\":\"Private industry\",\"5\":\"UAW\",\"6\":\"2010-05-11\",\"7\":\"2010-06-04\",\"8\":\"1700\",\"9\":\"30600\"},{\"1\":\"Allina Health System / United Hospital, Children's Hospitals and Clinics, Fairview Health Services, HealthEast Care System, Mercy Hospital, North Memorial Hospital, Park Nicollete Methodist Hospital\",\"2\":\"MN\",\"3\":\"Minneapolis -St. Paul\",\"4\":\"Private industry\",\"5\":\"NA\",\"6\":\"2010-06-10\",\"7\":\"2010-06-10\",\"8\":\"12000\",\"9\":\"12000\"},{\"1\":\"Sheet Metal and Air Conditioning Contractors Association of Milwaukee\",\"2\":\"WI\",\"3\":\"Milwaukee\",\"4\":\"Private industry\",\"5\":\"SMART\",\"6\":\"2010-06-14\",\"7\":\"2010-06-25\",\"8\":\"1800\",\"9\":\"18000\"},{\"1\":\"Mid-America Regional Bargaining Association\",\"2\":\"IL\",\"3\":\"Chicago area\",\"4\":\"Private industry\",\"5\":\"LIUNA, IUOE, UBC\",\"6\":\"2010-07-01\",\"7\":\"2010-07-19\",\"8\":\"15000\",\"9\":\"180000\"},{\"1\":\"New York Shipping Association/New Jersey\",\"2\":\"NY, NJ\",\"3\":\"New York City area\",\"4\":\"Private industry\",\"5\":\"ILA\",\"6\":\"2010-09-28\",\"7\":\"2010-09-29\",\"8\":\"4500\",\"9\":\"9000\"},{\"1\":\"Hilton Hotels Hawaiian Village Beach Resort and Spa\",\"2\":\"HI\",\"3\":\"Honolulu\",\"4\":\"Private industry\",\"5\":\"UNITE HERE\",\"6\":\"2010-10-14\",\"7\":\"2010-10-18\",\"8\":\"1500\",\"9\":\"4500\"},{\"1\":\"HCA Corporation, Riverside Community Hospital and West Hills Hospital and Medical Center\",\"2\":\"CA\",\"3\":\"Riverside and West Hills\",\"4\":\"Private industry\",\"5\":\"SEIU\",\"6\":\"2010-12-23\",\"7\":\"2010-12-28\",\"8\":\"1100\",\"9\":\"2200\"},{\"1\":\"Kaiser Permanente Los Angeles Medical Center\",\"2\":\"CA\",\"3\":\"Los Angeles\",\"4\":\"Private industry\",\"5\":\"NA\",\"6\":\"2011-03-02\",\"7\":\"2011-03-02\",\"8\":\"1000\",\"9\":\"1000\"},{\"1\":\"Hawaiian Electric, Maui Electric, Hawaii Electric Light Company\",\"2\":\"HI\",\"3\":\"Statewide\",\"4\":\"Private industry\",\"5\":\"IBEW\",\"6\":\"2011-03-04\",\"7\":\"2011-03-07\",\"8\":\"1300\",\"9\":\"2600\"},{\"1\":\"Washington Hospital Center\",\"2\":\"DC\",\"3\":\"Washington\",\"4\":\"Private industry\",\"5\":\"NNU\",\"6\":\"2011-03-04\",\"7\":\"2011-03-08\",\"8\":\"1100\",\"9\":\"3300\"},{\"1\":\"National Football League\",\"2\":\"Nationwide\",\"3\":\"NA\",\"4\":\"Private industry\",\"5\":\"NFLPA\",\"6\":\"2011-03-12\",\"7\":\"2011-07-25\",\"8\":\"1900\",\"9\":\"178600\"},{\"1\":\"Plumbing and Piping Industry Council Inc. dba Plumbing and Mechanical Contractors Association\",\"2\":\"OR\",\"3\":\"Tualatin\",\"4\":\"Private industry\",\"5\":\"UA\",\"6\":\"2011-04-11\",\"7\":\"2011-04-25\",\"8\":\"1500\",\"9\":\"16500\"},{\"1\":\"General Building Contractors Association\",\"2\":\"PA, DE\",\"3\":\"Philadelphia and Delaware areas\",\"4\":\"Private industry\",\"5\":\"NA\",\"6\":\"2011-05-04\",\"7\":\"2011-05-12\",\"8\":\"3000\",\"9\":\"21000\"},{\"1\":\"Interior Finish Contractors Association\",\"2\":\"PA\",\"3\":\"Philadelphia\",\"4\":\"Private industry\",\"5\":\"NA\",\"6\":\"2011-05-04\",\"7\":\"2011-05-12\",\"8\":\"2500\",\"9\":\"17500\"},{\"1\":\"Kaiser Permanente Los Angeles Medical Center\",\"2\":\"CA\",\"3\":\"Los Angeles\",\"4\":\"Private industry\",\"5\":\"NA\",\"6\":\"2011-05-18\",\"7\":\"2011-05-18\",\"8\":\"2000\",\"9\":\"2000\"},{\"1\":\"Mason Contractors Association\",\"2\":\"MO\",\"3\":\"St. Louis\",\"4\":\"Private industry\",\"5\":\"BAC\",\"6\":\"2011-06-01\",\"7\":\"2011-07-20\",\"8\":\"1000\",\"9\":\"35000\"},{\"1\":\"Mechanical Contractors Association\",\"2\":\"MO\",\"3\":\"Kansas City\",\"4\":\"Private industry\",\"5\":\"UA\",\"6\":\"2011-06-01\",\"7\":\"2011-06-08\",\"8\":\"1500\",\"9\":\"9000\"},{\"1\":\"Plumbing and Mechanical Contractors' Association of Milwaukee\",\"2\":\"WI\",\"3\":\"Milwaukee\",\"4\":\"Private industry\",\"5\":\"UA\",\"6\":\"2011-06-30\",\"7\":\"2011-07-22\",\"8\":\"2500\",\"9\":\"40000\"},{\"1\":\"American Crystal Sugar Company\",\"2\":\"MN, IA, ND\",\"3\":\"Multiple states\",\"4\":\"Private industry\",\"5\":\"BCTGM\",\"6\":\"2011-08-01\",\"7\":\"2012-12-01\",\"8\":\"1300\",\"9\":\"444600\"},{\"1\":\"Verizon Communications\",\"2\":\"East Coast States\",\"3\":\"Multiple states\",\"4\":\"Private industry\",\"5\":\"CWA, IBEW\",\"6\":\"2011-08-07\",\"7\":\"2011-08-20\",\"8\":\"45000\",\"9\":\"450000\"},{\"1\":\"Hyatt Hotels\",\"2\":\"IL, CA, HI\",\"3\":\"Multiple states\",\"4\":\"Private industry\",\"5\":\"UNITE HERE\",\"6\":\"2011-09-08\",\"7\":\"2011-09-14\",\"8\":\"3000\",\"9\":\"15000\"},{\"1\":\"City of Tacoma\",\"2\":\"WA\",\"3\":\"Tacoma\",\"4\":\"Local government\",\"5\":\"NA\",\"6\":\"2011-09-13\",\"7\":\"2011-09-22\",\"8\":\"1900\",\"9\":\"15200\"},{\"1\":\"Sutter Hospitals, Kaiser Permanente Hospitals, Children's Hospital and Research Center\",\"2\":\"CA\",\"3\":\"NA\",\"4\":\"Private industry\",\"5\":\"CNA, NUHW, IUOE\",\"6\":\"2011-09-22\",\"7\":\"2011-09-22\",\"8\":\"29000\",\"9\":\"29000\"},{\"1\":\"Sutter Hospitals, Children's Hospital and Research Center\",\"2\":\"CA\",\"3\":\"NA\",\"4\":\"Private industry\",\"5\":\"CNA, NNU\",\"6\":\"2011-09-23\",\"7\":\"2011-09-26\",\"8\":\"6000\",\"9\":\"12000\"},{\"1\":\"Cooper Tire and Rubber Company\",\"2\":\"OH\",\"3\":\"Findlay\",\"4\":\"Private industry\",\"5\":\"USW\",\"6\":\"2011-11-28\",\"7\":\"2012-02-27\",\"8\":\"1000\",\"9\":\"62000\"},{\"1\":\"Sutter Hospitals, Memorial Care Hospitals\",\"2\":\"CA\",\"3\":\"Los Angeles, San Francisco Bay Area\",\"4\":\"Private industry\",\"5\":\"CNA, NNU\",\"6\":\"2011-12-22\",\"7\":\"2011-12-23\",\"8\":\"6000\",\"9\":\"12000\"},{\"1\":\"Kaiser Permanente Hospitals\",\"2\":\"CA\",\"3\":\"Statewide\",\"4\":\"Private industry\",\"5\":\"CNA, NNU, IUOE\",\"6\":\"2012-01-31\",\"7\":\"2012-01-31\",\"8\":\"21000\",\"9\":\"21000\"},{\"1\":\"Riverside County Regional Medical Center\",\"2\":\"CA\",\"3\":\"Riverside\",\"4\":\"Local government\",\"5\":\"SEIU\",\"6\":\"2012-01-31\",\"7\":\"2012-01-31\",\"8\":\"5600\",\"9\":\"5600\"},{\"1\":\"Rockford School District 205\",\"2\":\"IL\",\"3\":\"Rockford\",\"4\":\"Local government\",\"5\":\"NA\",\"6\":\"2012-03-29\",\"7\":\"2012-03-30\",\"8\":\"1900\",\"9\":\"3800\"},{\"1\":\"Lockheed Martin Corporation\",\"2\":\"TX\",\"3\":\"Fort Worth\",\"4\":\"Private industry\",\"5\":\"IAM\",\"6\":\"2012-04-23\",\"7\":\"2012-06-28\",\"8\":\"3600\",\"9\":\"172800\"},{\"1\":\"Sutter Health Hospitals\",\"2\":\"CA\",\"3\":\"San Francisco Bay Area\",\"4\":\"Private industry\",\"5\":\"CNA\",\"6\":\"2012-05-01\",\"7\":\"2012-05-05\",\"8\":\"4500\",\"9\":\"18000\"},{\"1\":\"AT&T, Inc.\",\"2\":\"CA, NV\",\"3\":\"Multiple states\",\"4\":\"Private industry\",\"5\":\"CWA\",\"6\":\"2012-06-08\",\"7\":\"2012-06-08\",\"8\":\"14000\",\"9\":\"14000\"},{\"1\":\"Sutter Health Hospitals\",\"2\":\"CA\",\"3\":\"San Francisco Bay Area\",\"4\":\"Private industry\",\"5\":\"CNA\",\"6\":\"2012-06-13\",\"7\":\"2012-06-17\",\"8\":\"4500\",\"9\":\"13500\"},{\"1\":\"Consolidated Edison\",\"2\":\"NY\",\"3\":\"New York City and Westchester County\",\"4\":\"Private industry\",\"5\":\"UWA\",\"6\":\"2012-07-01\",\"7\":\"2012-07-26\",\"8\":\"8000\",\"9\":\"144000\"},{\"1\":\"Sutter Health Hospitals\",\"2\":\"CA\",\"3\":\"Alameda and San Mateo Counties\",\"4\":\"Private industry\",\"5\":\"CNA\",\"6\":\"2012-07-03\",\"7\":\"2012-07-07\",\"8\":\"3700\",\"9\":\"11100\"},{\"1\":\"AT&T, Inc.\",\"2\":\"CA, CT, NV\",\"3\":\"Multiple states\",\"4\":\"Private industry\",\"5\":\"CWA\",\"6\":\"2012-08-07\",\"7\":\"2012-08-08\",\"8\":\"21200\",\"9\":\"42400\"},{\"1\":\"City of Chicago Public School District 299\",\"2\":\"IL\",\"3\":\"Chicago\",\"4\":\"Local government\",\"5\":\"CTU\",\"6\":\"2012-09-10\",\"7\":\"2012-09-18\",\"8\":\"26500\",\"9\":\"185500\"},{\"1\":\"Sutter Health Hospitals\",\"2\":\"CA\",\"3\":\"San Francisco Bay Area\",\"4\":\"Private industry\",\"5\":\"CNA\",\"6\":\"2012-11-01\",\"7\":\"2012-11-05\",\"8\":\"3300\",\"9\":\"9900\"},{\"1\":\"Raley's, Nob Hill Stores\",\"2\":\"CA, NV\",\"3\":\"Northern CA and Northern NV areas\",\"4\":\"Private industry\",\"5\":\"UFCWU\",\"6\":\"2012-11-04\",\"7\":\"2012-11-13\",\"8\":\"7400\",\"9\":\"44400\"},{\"1\":\"Hostess Brands\",\"2\":\"Nationwide\",\"3\":\"NA\",\"4\":\"Private industry\",\"5\":\"BCTGM\",\"6\":\"2012-11-09\",\"7\":\"2012-11-21\",\"8\":\"5000\",\"9\":\"40000\"},{\"1\":\"Sutter Health Hospitals and Hospital Corporation of America\",\"2\":\"CA\",\"3\":\"San Francisco Bay Area\",\"4\":\"Private industry\",\"5\":\"CNA\",\"6\":\"2012-11-20\",\"7\":\"2012-11-24\",\"8\":\"5000\",\"9\":\"15000\"},{\"1\":\"Pacific Maritime Association\",\"2\":\"CA\",\"3\":\"Ports of Los Angeles and Long Beach\",\"4\":\"Private industry\",\"5\":\"ILWU\",\"6\":\"2012-11-27\",\"7\":\"2012-12-04\",\"8\":\"5500\",\"9\":\"33000\"},{\"1\":\"Community Unit School District 300\",\"2\":\"IL\",\"3\":\"Carpentersville\",\"4\":\"Local government\",\"5\":\"LEAD\",\"6\":\"2012-12-04\",\"7\":\"2012-12-04\",\"8\":\"1300\",\"9\":\"1300\"},{\"1\":\"Goodman Manufacturing Company\",\"2\":\"TN\",\"3\":\"Fayetteville\",\"4\":\"Private industry\",\"5\":\"IAM\",\"6\":\"2012-12-09\",\"7\":\"2012-12-13\",\"8\":\"1100\",\"9\":\"4400\"},{\"1\":\"Sutter Health Hospitals and Hospital Corporation of America\",\"2\":\"CA\",\"3\":\"San Francisco Bay Area\",\"4\":\"Private industry\",\"5\":\"CNA\",\"6\":\"2012-12-24\",\"7\":\"2012-12-24\",\"8\":\"5000\",\"9\":\"5000\"},{\"1\":\"New York City Public Schools\",\"2\":\"NY\",\"3\":\"New York\",\"4\":\"Local government\",\"5\":\"ATU\",\"6\":\"2013-01-16\",\"7\":\"2013-02-15\",\"8\":\"8000\",\"9\":\"176000\"},{\"1\":\"G4S, Allied Barton, Securitas, Viking Security, ABM Security, and Whelan Security\",\"2\":\"MN\",\"3\":\"Minneapolis - St. Paul\",\"4\":\"Private industry\",\"5\":\"SEIU\",\"6\":\"2013-02-27\",\"7\":\"2013-02-27\",\"8\":\"2000\",\"9\":\"2000\"},{\"1\":\"Sheet Metal Contractors Association of Philadelphia and Vicinity\",\"2\":\"PA, NJ\",\"3\":\"Philadelphia Metropolitan Area\",\"4\":\"Private industry\",\"5\":\"SMWU\",\"6\":\"2013-05-01\",\"7\":\"2013-05-02\",\"8\":\"1300\",\"9\":\"2600\"},{\"1\":\"Sutter Health Hospitals, Hospital Corporation of America\",\"2\":\"CA\",\"3\":\"San Francisco Bay Area\",\"4\":\"Private industry\",\"5\":\"CNA, NNU\",\"6\":\"2013-05-17\",\"7\":\"2013-05-24\",\"8\":\"4200\",\"9\":\"25200\"},{\"1\":\"University of California Medical Centers\",\"2\":\"CA\",\"3\":\"Sacramento, San Francisco, Los Angeles, Irvine, and San Diego\",\"4\":\"State government\",\"5\":\"AFSCME, UPTEU\",\"6\":\"2013-05-21\",\"7\":\"2013-05-22\",\"8\":\"18800\",\"9\":\"34300\"},{\"1\":\"Bay Area Rapid Transit - BART\",\"2\":\"CA\",\"3\":\"San Francisco Bay Area\",\"4\":\"Local government\",\"5\":\"SEIU, ATU\",\"6\":\"2013-07-01\",\"7\":\"2013-07-05\",\"8\":\"2400\",\"9\":\"9600\"},{\"1\":\"City of Oakland\",\"2\":\"CA\",\"3\":\"Oakland\",\"4\":\"Local government\",\"5\":\"IFPTE\",\"6\":\"2013-07-01\",\"7\":\"2013-07-01\",\"8\":\"2500\",\"9\":\"2500\"},{\"1\":\"Bell Helicopter Textron, Inc.\",\"2\":\"TX\",\"3\":\"Hurst\",\"4\":\"Private industry\",\"5\":\"UAW\",\"6\":\"2013-09-06\",\"7\":\"2013-09-06\",\"8\":\"2600\",\"9\":\"2600\"},{\"1\":\"Los Angeles County, CA\",\"2\":\"CA\",\"3\":\"Los Angeles County\",\"4\":\"Local government\",\"5\":\"SEIU\",\"6\":\"2013-10-01\",\"7\":\"2013-10-01\",\"8\":\"2500\",\"9\":\"2500\"},{\"1\":\"Steamship Trade Association of Baltimore, Maryland Port Administration\",\"2\":\"MD\",\"3\":\"Baltimore\",\"4\":\"Private industry\",\"5\":\"ILA\",\"6\":\"2013-10-16\",\"7\":\"2013-10-18\",\"8\":\"2000\",\"9\":\"6000\"},{\"1\":\"Bay Area Rapid Transit - BART\",\"2\":\"CA\",\"3\":\"San Francisco Bay Area\",\"4\":\"Local government\",\"5\":\"SEIU, ATU\",\"6\":\"2013-10-18\",\"7\":\"2013-10-21\",\"8\":\"2300\",\"9\":\"4600\"},{\"1\":\"Will County\",\"2\":\"IL\",\"3\":\"Joliet\",\"4\":\"Local government\",\"5\":\"AFSCME\",\"6\":\"2013-11-18\",\"7\":\"2013-12-04\",\"8\":\"1000\",\"9\":\"12000\"},{\"1\":\"University of California Medical Centers\",\"2\":\"CA\",\"3\":\"Statewide\",\"4\":\"State government\",\"5\":\"AFSCME, UCSW\",\"6\":\"2013-11-20\",\"7\":\"2013-11-20\",\"8\":\"2100\",\"9\":\"2100\"},{\"1\":\"Deaconess Medical Center, Valley Hospital\",\"2\":\"WA\",\"3\":\"Spokane\",\"4\":\"Private industry\",\"5\":\"SEIU\",\"6\":\"2013-12-04\",\"7\":\"2013-12-04\",\"8\":\"1100\",\"9\":\"1100\"},{\"1\":\"Los Angeles County\",\"2\":\"CA\",\"3\":\"Los Angeles County\",\"4\":\"Local government\",\"5\":\"SEIU\",\"6\":\"2013-12-05\",\"7\":\"2013-12-10\",\"8\":\"1700\",\"9\":\"6800\"},{\"1\":\"University of Illinois at Chicago\",\"2\":\"IL\",\"3\":\"Chicago\",\"4\":\"State government\",\"5\":\"UICUF\",\"6\":\"2014-02-18\",\"7\":\"2014-02-19\",\"8\":\"1100\",\"9\":\"2200\"},{\"1\":\"Johns Hopkins Hospital\",\"2\":\"MD\",\"3\":\"Baltimore\",\"4\":\"Private industry\",\"5\":\"SEIU\",\"6\":\"2014-04-09\",\"7\":\"2014-04-11\",\"8\":\"2000\",\"9\":\"6000\"},{\"1\":\"Army Fleet Support, LLC\",\"2\":\"AL\",\"3\":\"Fort Rucker\",\"4\":\"Private industry\",\"5\":\"IAM\",\"6\":\"2014-04-28\",\"7\":\"2014-05-04\",\"8\":\"3000\",\"9\":\"15000\"},{\"1\":\"Queen of the Valley Medical Center, Sutter Tracy Community Hospital, Watsonville, Community Hospital\",\"2\":\"CA\",\"3\":\"Central\",\"4\":\"Private industry\",\"5\":\"CNA, NNU\",\"6\":\"2014-08-14\",\"7\":\"2014-08-15\",\"8\":\"1000\",\"9\":\"1000\"},{\"1\":\"Zodiac Seats US\",\"2\":\"TX\",\"3\":\"Gainesville\",\"4\":\"Private industry\",\"5\":\"UBT\",\"6\":\"2014-09-23\",\"7\":\"2014-10-25\",\"8\":\"1300\",\"9\":\"29900\"},{\"1\":\"Waukegan School District 60\",\"2\":\"IL\",\"3\":\"Waukegan\",\"4\":\"Local government\",\"5\":\"LCFT\",\"6\":\"2014-10-02\",\"7\":\"2014-10-30\",\"8\":\"1200\",\"9\":\"24000\"},{\"1\":\"Fairpoint Communications\",\"2\":\"ME, NH, VT\",\"3\":\"Multiple states in New England\",\"4\":\"Private industry\",\"5\":\"IBEW, CWA\",\"6\":\"2014-10-17\",\"7\":\"2015-02-19\",\"8\":\"1700\",\"9\":\"142800\"},{\"1\":\"Kaiser Permanente Hospitals - CA, Sutter Hospitals - CA, Providence Hospital - DC\",\"2\":\"CA, DC\",\"3\":\"Multiple states\",\"4\":\"Private industry\",\"5\":\"CNA, NNU\",\"6\":\"2014-11-11\",\"7\":\"2014-11-12\",\"8\":\"19000\",\"9\":\"19000\"},{\"1\":\"St. Joseph Medical Center, St. Clare Hospital\",\"2\":\"WA\",\"3\":\"Tacoma, Lakewood\",\"4\":\"Private industry\",\"5\":\"SEIU\",\"6\":\"2014-11-18\",\"7\":\"2014-11-19\",\"8\":\"1100\",\"9\":\"1100\"},{\"1\":\"SFO Airport Restaurant Employer Council\",\"2\":\"CA\",\"3\":\"San Francisco International Airport\",\"4\":\"Private industry\",\"5\":\"UNITE HERE\",\"6\":\"2014-12-11\",\"7\":\"2014-12-12\",\"8\":\"1000\",\"9\":\"2000\"},{\"1\":\"Medstar Washington Hospital Center\",\"2\":\"DC\",\"3\":\"Washington\",\"4\":\"Private industry\",\"5\":\"NNU\",\"6\":\"2014-12-22\",\"7\":\"2014-12-31\",\"8\":\"1900\",\"9\":\"13300\"},{\"1\":\"Kaiser Permanente Hospitals\",\"2\":\"CA\",\"3\":\"Statewide\",\"4\":\"Private industry\",\"5\":\"NA\",\"6\":\"2015-01-12\",\"7\":\"2015-01-19\",\"8\":\"3500\",\"9\":\"17500\"},{\"1\":\"Royal Dutch Shell Oil and Other Refineries\",\"2\":\"CA,IN,KY, LA,OH,TX, WA\",\"3\":\"NA\",\"4\":\"Private industry\",\"5\":\"USS\",\"6\":\"2015-02-01\",\"7\":\"2015-06-23\",\"8\":\"6600\",\"9\":\"322100\"},{\"1\":\"Washington State Legislature\",\"2\":\"WA\",\"3\":\"Statewide\",\"4\":\"State government\",\"5\":\"NA\",\"6\":\"2015-04-22\",\"7\":\"2015-06-03\",\"8\":\"16900\",\"9\":\"16900\"},{\"1\":\"Sutter Auburn Faith Hospital, Mills-Peninsula Health Services, Sutter Tracy Community Hospital, Sutter Roseville Medical Center, Sutter Santa Rosa Medical Center\",\"2\":\"CA\",\"3\":\"Central CA\",\"4\":\"Private industry\",\"5\":\"CNN\",\"6\":\"2015-04-30\",\"7\":\"2015-05-05\",\"8\":\"1700\",\"9\":\"5100\"},{\"1\":\"Allegheny Technologies Incorporated\",\"2\":\"OH,PA,WV\",\"3\":\"NA\",\"4\":\"Private industry\",\"5\":\"USS\",\"6\":\"2015-08-15\",\"7\":\"2016-02-22\",\"8\":\"2200\",\"9\":\"281600\"},{\"1\":\"Consolidated Nuclear Security\",\"2\":\"TX\",\"3\":\"Amarillo\",\"4\":\"Private industry\",\"5\":\"OPEIU\",\"6\":\"2015-08-29\",\"7\":\"2015-10-03\",\"8\":\"1200\",\"9\":\"28800\"},{\"1\":\"Pasco School District\",\"2\":\"WA\",\"3\":\"Pasco\",\"4\":\"Local government\",\"5\":\"NA\",\"6\":\"2015-09-01\",\"7\":\"2015-09-13\",\"8\":\"1100\",\"9\":\"8800\"},{\"1\":\"Seattle School District\",\"2\":\"WA\",\"3\":\"Seattle\",\"4\":\"Local government\",\"5\":\"NA\",\"6\":\"2015-09-09\",\"7\":\"2015-09-15\",\"8\":\"5000\",\"9\":\"25000\"},{\"1\":\"Kohler Company\",\"2\":\"WI\",\"3\":\"Sheboygan\",\"4\":\"Private industry\",\"5\":\"UAW\",\"6\":\"2015-11-15\",\"7\":\"2015-12-15\",\"8\":\"2100\",\"9\":\"44100\"},{\"1\":\"Solano County Municipal Government\",\"2\":\"CA\",\"3\":\"Solano County\",\"4\":\"Local government\",\"5\":\"SEIU\",\"6\":\"2015-11-17\",\"7\":\"2015-11-18\",\"8\":\"1800\",\"9\":\"3600\"},{\"1\":\"Sonoma County Municipal Government\",\"2\":\"CA\",\"3\":\"Sonoma County\",\"4\":\"Local government\",\"5\":\"SEIU\",\"6\":\"2015-11-17\",\"7\":\"2015-11-17\",\"8\":\"2000\",\"9\":\"2000\"},{\"1\":\"Nexteer Automotive\",\"2\":\"MI\",\"3\":\"Buena Vista\",\"4\":\"Private industry\",\"5\":\"UAW\",\"6\":\"2015-12-08\",\"7\":\"2015-12-08\",\"8\":\"3200\",\"9\":\"3200\"},{\"1\":\"Port Authority of New York and New Jersey, New York Shipping Association\",\"2\":\"NY, NJ\",\"3\":\"Multiple states\",\"4\":\"Local government\",\"5\":\"ILA\",\"6\":\"2016-01-29\",\"7\":\"2016-01-29\",\"8\":\"1000\",\"9\":\"1000\"},{\"1\":\"Minneapolis-St. Paul Contract Cleaners Association\",\"2\":\"MN\",\"3\":\"Minneapolis- St. Paul\",\"4\":\"Private industry\",\"5\":\"SEIU\",\"6\":\"2016-02-17\",\"7\":\"2016-02-18\",\"8\":\"4200\",\"9\":\"4200\"},{\"1\":\"Kaiser Permanente Los Angeles Medical Center\",\"2\":\"CA\",\"3\":\"Los Angeles\",\"4\":\"Private industry\",\"5\":\"CNA\",\"6\":\"2016-03-15\",\"7\":\"2016-03-22\",\"8\":\"1200\",\"9\":\"6000\"},{\"1\":\"City of Chicago Public School District\",\"2\":\"IL\",\"3\":\"Chicago\",\"4\":\"Local government\",\"5\":\"CTU\",\"6\":\"2016-04-01\",\"7\":\"2016-04-01\",\"8\":\"27000\",\"9\":\"27000\"},{\"1\":\"Verizon Communications Inc.\",\"2\":\"NA\",\"3\":\"Multiple east coast states\",\"4\":\"Private industry\",\"5\":\"CWA, IBEW\",\"6\":\"2016-04-13\",\"7\":\"2016-05-27\",\"8\":\"36500\",\"9\":\"1204500\"},{\"1\":\"Detroit Public Schools\",\"2\":\"MI\",\"3\":\"Detroit\",\"4\":\"Local government\",\"5\":\"DFT\",\"6\":\"2016-05-02\",\"7\":\"2016-05-03\",\"8\":\"1500\",\"9\":\"3000\"},{\"1\":\"AT&T Inc.\",\"2\":\"CA\",\"3\":\"San Diego\",\"4\":\"Private industry\",\"5\":\"CWA\",\"6\":\"2016-05-19\",\"7\":\"2016-05-25\",\"8\":\"1700\",\"9\":\"6800\"},{\"1\":\"Allina Health\",\"2\":\"MN\",\"3\":\"Minneapolis- St. Paul\",\"4\":\"Private industry\",\"5\":\"MNA, NNU\",\"6\":\"2016-06-19\",\"7\":\"2016-06-26\",\"8\":\"4800\",\"9\":\"24000\"},{\"1\":\"Kaiser Permanente Los Angeles Hospital Center\",\"2\":\"CA\",\"3\":\"Los Angeles\",\"4\":\"Private industry\",\"5\":\"CNA, NNU\",\"6\":\"2016-06-23\",\"7\":\"2016-06-26\",\"8\":\"1300\",\"9\":\"2600\"},{\"1\":\"San Joaquin County\",\"2\":\"CA\",\"3\":\"San Joaquin County\",\"4\":\"Local government\",\"5\":\"SEIU\",\"6\":\"2016-07-05\",\"7\":\"2016-07-07\",\"8\":\"2600\",\"9\":\"7800\"},{\"1\":\"Painting and Decorating Foundation\",\"2\":\"MO\",\"3\":\"St. Louis\",\"4\":\"Private industry\",\"5\":\"IUPAT\",\"6\":\"2016-09-01\",\"7\":\"2016-10-02\",\"8\":\"1400\",\"9\":\"4200\"},{\"1\":\"Allina Health\",\"2\":\"MN\",\"3\":\"Minneapolis- St. Paul\",\"4\":\"Private industry\",\"5\":\"MNA, NNU\",\"6\":\"2016-09-05\",\"7\":\"2016-10-13\",\"8\":\"4800\",\"9\":\"129600\"},{\"1\":\"Contra Costa County\",\"2\":\"CA\",\"3\":\"Contra Costa County\",\"4\":\"Local government\",\"5\":\"SEIU\",\"6\":\"2016-09-30\",\"7\":\"2016-10-07\",\"8\":\"1100\",\"9\":\"6600\"},{\"1\":\"Pennsylvania State System of Higher Education\",\"2\":\"PA\",\"3\":\"Statewide\",\"4\":\"State government\",\"5\":\"APSCUF\",\"6\":\"2016-10-19\",\"7\":\"2016-10-21\",\"8\":\"5100\",\"9\":\"15300\"},{\"1\":\"Southeastern Pennsylvania Transportation Authority\",\"2\":\"PA\",\"3\":\"Philadelphia\",\"4\":\"Local government\",\"5\":\"TWU\",\"6\":\"2016-11-01\",\"7\":\"2016-11-07\",\"8\":\"5200\",\"9\":\"26000\"},{\"1\":\"University of California\",\"2\":\"CA\",\"3\":\"Statewide\",\"4\":\"State government\",\"5\":\"IBT\",\"6\":\"2017-01-10\",\"7\":\"2017-01-10\",\"8\":\"2200\",\"9\":\"2200\"},{\"1\":\"AT&T Inc.\",\"2\":\"CA, NV\",\"3\":\"Los Angeles\",\"4\":\"Private industry\",\"5\":\"CWA\",\"6\":\"2017-03-22\",\"7\":\"2017-03-22\",\"8\":\"13200\",\"9\":\"13200\"},{\"1\":\"Charter Communications Inc.\",\"2\":\"NY, NJ\",\"3\":\"Statewide\",\"4\":\"Private industry\",\"5\":\"IBEW\",\"6\":\"2017-03-28\",\"7\":\"2022-04-18\",\"8\":\"1800\",\"9\":\"2284200\"},{\"1\":\"Tufts Medical Center\",\"2\":\"MA\",\"3\":\"Boston\",\"4\":\"Private industry\",\"5\":\"MNA\",\"6\":\"2017-07-12\",\"7\":\"2017-07-17\",\"8\":\"1200\",\"9\":\"3600\"},{\"1\":\"Chicago New Car Dealer Committee\",\"2\":\"IL\",\"3\":\"Chicago\",\"4\":\"Private industry\",\"5\":\"IAMAW\",\"6\":\"2017-08-01\",\"7\":\"2017-09-15\",\"8\":\"1700\",\"9\":\"56100\"},{\"1\":\"Riverside County Municipal Government\",\"2\":\"CA\",\"3\":\"Riverside\",\"4\":\"Local government\",\"5\":\"SEIU\",\"6\":\"2017-09-06\",\"7\":\"2017-09-07\",\"8\":\"2300\",\"9\":\"4600\"},{\"1\":\"City of Oakland\",\"2\":\"CA\",\"3\":\"Oakland\",\"4\":\"Local government\",\"5\":\"SEIU\",\"6\":\"2017-12-05\",\"7\":\"2017-12-11\",\"8\":\"2900\",\"9\":\"14500\"},{\"1\":\"West Virginia Legislature\",\"2\":\"WV\",\"3\":\"Statewide\",\"4\":\"State government\",\"5\":\"WVEA\",\"6\":\"2018-02-16\",\"7\":\"2018-03-06\",\"8\":\"35000\",\"9\":\"318600\"},{\"1\":\"Frontier Communications\",\"2\":\"WV, VA\",\"3\":\"Statewide\",\"4\":\"Private industry\",\"5\":\"CWA\",\"6\":\"2018-03-04\",\"7\":\"2018-03-25\",\"8\":\"1400\",\"9\":\"21000\"},{\"1\":\"Jersey City School District\",\"2\":\"NJ\",\"3\":\"Jersey City\",\"4\":\"Local government\",\"5\":\"NA\",\"6\":\"2018-03-16\",\"7\":\"2018-03-16\",\"8\":\"3800\",\"9\":\"3800\"},{\"1\":\"Kentucky State Legislature\",\"2\":\"KY\",\"3\":\"Statewide\",\"4\":\"State government\",\"5\":\"NA\",\"6\":\"2018-04-02\",\"7\":\"2018-04-13\",\"8\":\"26000\",\"9\":\"52000\"},{\"1\":\"Oklahoma State Legislature\",\"2\":\"OK\",\"3\":\"Statewide\",\"4\":\"State government\",\"5\":\"NA\",\"6\":\"2018-04-02\",\"7\":\"2018-04-12\",\"8\":\"45000\",\"9\":\"405000\"},{\"1\":\"Arizona State Legislature\",\"2\":\"AZ\",\"3\":\"Statewide\",\"4\":\"State government\",\"5\":\"NA\",\"6\":\"2018-04-26\",\"7\":\"2018-05-03\",\"8\":\"81000\",\"9\":\"486000\"},{\"1\":\"Colorado State Legislature\",\"2\":\"CO\",\"3\":\"Statewide\",\"4\":\"State government\",\"5\":\"NA\",\"6\":\"2018-04-26\",\"7\":\"2018-04-27\",\"8\":\"63000\",\"9\":\"126000\"},{\"1\":\"University of California Medical Centers\",\"2\":\"CA\",\"3\":\"Statewide\",\"4\":\"State government\",\"5\":\"AFSCME, CNA, UPTE\",\"6\":\"2018-05-07\",\"7\":\"2018-05-09\",\"8\":\"53000\",\"9\":\"159000\"},{\"1\":\"North Carolina State Legislature\",\"2\":\"NC\",\"3\":\"Statewide\",\"4\":\"State government\",\"5\":\"NA\",\"6\":\"2018-05-16\",\"7\":\"2018-05-16\",\"8\":\"123000\",\"9\":\"123000\"},{\"1\":\"AT&T Inc.\",\"2\":\"IL, IN, MI, OH, WI\",\"3\":\"NA\",\"4\":\"Private industry\",\"5\":\"CWA\",\"6\":\"2018-06-01\",\"7\":\"2018-06-05\",\"8\":\"9700\",\"9\":\"29100\"},{\"1\":\"National Grid\",\"2\":\"MA\",\"3\":\"Waltham\",\"4\":\"Private industry\",\"5\":\"NA\",\"6\":\"2018-06-25\",\"7\":\"2019-01-02\",\"8\":\"1200\",\"9\":\"157200\"},{\"1\":\"University of Vermont Medical Center\",\"2\":\"VT\",\"3\":\"Burlington\",\"4\":\"State government\",\"5\":\"NA\",\"6\":\"2018-07-12\",\"7\":\"2018-07-13\",\"8\":\"1800\",\"9\":\"3600\"},{\"1\":\"Rhode Island and Hasbro Children's Hospital\",\"2\":\"RI\",\"3\":\"Providence\",\"4\":\"Private industry\",\"5\":\"NA\",\"6\":\"2018-07-23\",\"7\":\"2018-07-27\",\"8\":\"2400\",\"9\":\"12000\"},{\"1\":\"Association General Contractors of Washington\",\"2\":\"WA\",\"3\":\"Statewide\",\"4\":\"Private industry\",\"5\":\"NA\",\"6\":\"2018-08-21\",\"7\":\"2018-09-06\",\"8\":\"5000\",\"9\":\"60000\"},{\"1\":\"Michigan Infrastructure and Transportation Association\",\"2\":\"MI\",\"3\":\"Statewide\",\"4\":\"Private industry\",\"5\":\"NA\",\"6\":\"2018-09-04\",\"7\":\"2018-09-27\",\"8\":\"1000\",\"9\":\"18000\"},{\"1\":\"Tacoma School District\",\"2\":\"WA\",\"3\":\"Tacoma\",\"4\":\"Local government\",\"5\":\"NA\",\"6\":\"2018-09-06\",\"7\":\"2018-09-14\",\"8\":\"2400\",\"9\":\"16800\"},{\"1\":\"Chicago Downtown Hotels\",\"2\":\"IL\",\"3\":\"Chicago\",\"4\":\"Private industry\",\"5\":\"NA\",\"6\":\"2018-09-07\",\"7\":\"2018-10-03\",\"8\":\"5500\",\"9\":\"91000\"},{\"1\":\"Marriott Corporation\",\"2\":\"CA, HI, MA, MI\",\"3\":\"NA\",\"4\":\"Private industry\",\"5\":\"NA\",\"6\":\"2018-10-03\",\"7\":\"2018-12-03\",\"8\":\"6000\",\"9\":\"215900\"},{\"1\":\"University of California Medical Centers\",\"2\":\"CA\",\"3\":\"NA\",\"4\":\"State government\",\"5\":\"AFSCME\",\"6\":\"2018-10-23\",\"7\":\"2018-10-25\",\"8\":\"15000\",\"9\":\"45000\"},{\"1\":\"Kaiser Permanente\",\"2\":\"CA\",\"3\":\"NA\",\"4\":\"Private industry\",\"5\":\"NUHW\",\"6\":\"2018-12-10\",\"7\":\"2018-12-14\",\"8\":\"4000\",\"9\":\"20000\"},{\"1\":\"Los Angeles Unified School District\",\"2\":\"CA\",\"3\":\"Los Angeles\",\"4\":\"Local government\",\"5\":\"NA\",\"6\":\"2019-01-14\",\"7\":\"2019-01-22\",\"8\":\"33000\",\"9\":\"198000\"},{\"1\":\"Denver Public Schools\",\"2\":\"CO\",\"3\":\"Denver\",\"4\":\"Local government\",\"5\":\"NA\",\"6\":\"2019-02-11\",\"7\":\"2019-02-14\",\"8\":\"3900\",\"9\":\"11700\"},{\"1\":\"West Virginia Legislature\",\"2\":\"WV\",\"3\":\"Statewide\",\"4\":\"State government\",\"5\":\"NA\",\"6\":\"2019-02-19\",\"7\":\"2019-02-20\",\"8\":\"36400\",\"9\":\"72800\"},{\"1\":\"Oakland Unified School District\",\"2\":\"CA\",\"3\":\"Oakland\",\"4\":\"Local government\",\"5\":\"NA\",\"6\":\"2019-02-21\",\"7\":\"2019-03-01\",\"8\":\"2300\",\"9\":\"16100\"},{\"1\":\"Wabtec Corp.\",\"2\":\"PA\",\"3\":\"Erie\",\"4\":\"Private industry\",\"5\":\"UE\",\"6\":\"2019-02-26\",\"7\":\"2019-03-07\",\"8\":\"1700\",\"9\":\"13600\"},{\"1\":\"Kentucky State Legislature\",\"2\":\"KY\",\"3\":\"Statewide\",\"4\":\"State government\",\"5\":\"NA\",\"6\":\"2019-02-28\",\"7\":\"2019-03-07\",\"8\":\"22900\",\"9\":\"39500\"},{\"1\":\"University of Illinois at Chicago\",\"2\":\"IL\",\"3\":\"Chicago\",\"4\":\"State government\",\"5\":\"GEO\",\"6\":\"2019-03-19\",\"7\":\"2019-04-05\",\"8\":\"1400\",\"9\":\"12600\"},{\"1\":\"University of California Medical Centers\",\"2\":\"CA\",\"3\":\"Statewide\",\"4\":\"State government\",\"5\":\"UPTE-CWA\",\"6\":\"2019-03-20\",\"7\":\"2019-03-21\",\"8\":\"14000\",\"9\":\"14000\"},{\"1\":\"University of California Medical Centers\",\"2\":\"CA\",\"3\":\"Statewide\",\"4\":\"State government\",\"5\":\"AFSCME\",\"6\":\"2019-04-10\",\"7\":\"2019-11-13\",\"8\":\"25000\",\"9\":\"75000\"},{\"1\":\"Sacramento City Unified School District\",\"2\":\"CA\",\"3\":\"Sacramento\",\"4\":\"Local government\",\"5\":\"SCTA\",\"6\":\"2019-04-11\",\"7\":\"2019-04-11\",\"8\":\"1900\",\"9\":\"1900\"},{\"1\":\"Stop & Shop Supermarket Co.\",\"2\":\"CT, RI, MA\",\"3\":\"Statewide\",\"4\":\"Local government\",\"5\":\"UFCW\",\"6\":\"2019-04-11\",\"7\":\"2019-04-21\",\"8\":\"31000\",\"9\":\"217000\"},{\"1\":\"North Carolina State Legislature\",\"2\":\"NC\",\"3\":\"Statewide\",\"4\":\"State government\",\"5\":\"NA\",\"6\":\"2019-05-01\",\"7\":\"2019-05-01\",\"8\":\"92700\",\"9\":\"92700\"},{\"1\":\"South Carolina State Legislature\",\"2\":\"SC\",\"3\":\"Statewide\",\"4\":\"State government\",\"5\":\"NA\",\"6\":\"2019-05-01\",\"7\":\"2019-05-01\",\"8\":\"18900\",\"9\":\"18900\"},{\"1\":\"Mercy Health St. Vincent Medical Center\",\"2\":\"OH\",\"3\":\"Toledo\",\"4\":\"Private industry\",\"5\":\"UAW\",\"6\":\"2019-05-06\",\"7\":\"2019-06-02\",\"8\":\"2000\",\"9\":\"36000\"},{\"1\":\"Oregon State Legislature\",\"2\":\"OR\",\"3\":\"Statewide\",\"4\":\"State government\",\"5\":\"NA\",\"6\":\"2019-05-08\",\"7\":\"2019-05-08\",\"8\":\"20400\",\"9\":\"20400\"},{\"1\":\"AT&T Inc.\",\"2\":\"AL, FL, GA, KY, LA, MS, NC, SC, TN\",\"3\":\"Statewide\",\"4\":\"Private industry\",\"5\":\"NA\",\"6\":\"2019-08-24\",\"7\":\"2019-08-28\",\"8\":\"20000\",\"9\":\"40000\"},{\"1\":\"Kennewick School District\",\"2\":\"WA\",\"3\":\"Kennewick\",\"4\":\"Local government\",\"5\":\"NA\",\"6\":\"2019-08-27\",\"7\":\"2019-08-30\",\"8\":\"1800\",\"9\":\"7200\"},{\"1\":\"General Motors\",\"2\":\"MI\",\"3\":\"Statewide\",\"4\":\"Private industry\",\"5\":\"UAW\",\"6\":\"2019-09-16\",\"7\":\"2019-10-25\",\"8\":\"46000\",\"9\":\"1334000\"},{\"1\":\"Tenet Healthcare\",\"2\":\"CA, AZ, FL\",\"3\":\"Statewide\",\"4\":\"Private industry\",\"5\":\"NA\",\"6\":\"2019-09-20\",\"7\":\"2019-09-25\",\"8\":\"4300\",\"9\":\"12900\"},{\"1\":\"University of Chicago Nurses\",\"2\":\"IL\",\"3\":\"Chicago\",\"4\":\"Private industry\",\"5\":\"NA\",\"6\":\"2019-09-20\",\"7\":\"2019-09-25\",\"8\":\"2200\",\"9\":\"6600\"},{\"1\":\"Mack Trucks\",\"2\":\"PA, MD, FL\",\"3\":\"Statewide\",\"4\":\"Private industry\",\"5\":\"UAW\",\"6\":\"2019-10-12\",\"7\":\"2019-10-25\",\"8\":\"3500\",\"9\":\"28000\"},{\"1\":\"Asarco\",\"2\":\"AZ, TX\",\"3\":\"Multiple\",\"4\":\"Private industry\",\"5\":\"USW\",\"6\":\"2019-10-13\",\"7\":\"2020-07-06\",\"8\":\"1800\",\"9\":\"325800\"},{\"1\":\"Chicago Public Schools\",\"2\":\"IL\",\"3\":\"Chicago\",\"4\":\"Local government\",\"5\":\"CTU, SEIU\",\"6\":\"2019-10-17\",\"7\":\"2019-10-31\",\"8\":\"32000\",\"9\":\"352000\"},{\"1\":\"Harvard University\",\"2\":\"MA\",\"3\":\"Statewide\",\"4\":\"Private industry\",\"5\":\"HGSU, UAW\",\"6\":\"2019-12-03\",\"7\":\"2019-12-31\",\"8\":\"2400\",\"9\":\"48000\"},{\"1\":\"Kaiser Permanente\",\"2\":\"CA\",\"3\":\"Statewide\",\"4\":\"Private industry\",\"5\":\"NUHW\",\"6\":\"2019-12-16\",\"7\":\"2019-12-21\",\"8\":\"4000\",\"9\":\"20000\"},{\"1\":\"Swedish Medical Centers\",\"2\":\"WA\",\"3\":\"Seattle Metropolitan Area\",\"4\":\"Private industry\",\"5\":\"SEIU\",\"6\":\"2020-01-28\",\"7\":\"2020-01-31\",\"8\":\"7800\",\"9\":\"23400\"},{\"1\":\"San Joaquin County\",\"2\":\"CA\",\"3\":\"San Joaquin County\",\"4\":\"Local government\",\"5\":\"CNA, SEIU\",\"6\":\"2020-03-05\",\"7\":\"2020-03-07\",\"8\":\"1000\",\"9\":\"2000\"},{\"1\":\"St. Paul Public Schools\",\"2\":\"MN\",\"3\":\"St. Paul\",\"4\":\"Local government\",\"5\":\"SPFE\",\"6\":\"2020-03-10\",\"7\":\"2020-03-13\",\"8\":\"3600\",\"9\":\"10800\"},{\"1\":\"Bath Iron Works\",\"2\":\"ME\",\"3\":\"Bath\",\"4\":\"Private industry\",\"5\":\"IAM\",\"6\":\"2020-06-22\",\"7\":\"2020-08-23\",\"8\":\"4300\",\"9\":\"189200\"},{\"1\":\"University of Michigan\",\"2\":\"MI\",\"3\":\"Ann Arbor\",\"4\":\"State government\",\"5\":\"GEO\",\"6\":\"2020-09-08\",\"7\":\"2020-09-16\",\"8\":\"1200\",\"9\":\"8400\"},{\"1\":\"University of Illinois\",\"2\":\"IL\",\"3\":\"Chicago\",\"4\":\"State government\",\"5\":\"SEIU, INA\",\"6\":\"2020-09-14\",\"7\":\"2020-09-24\",\"8\":\"4500\",\"9\":\"37300\"},{\"1\":\"Cook County\",\"2\":\"IL\",\"3\":\"Chicago\",\"4\":\"Local government\",\"5\":\"SEIU\",\"6\":\"2020-12-22\",\"7\":\"2020-12-22\",\"8\":\"1600\",\"9\":\"1600\"},{\"1\":\"Hunts Point Produce Market\",\"2\":\"NY\",\"3\":\"New York City\",\"4\":\"Private industry\",\"5\":\"IBT\",\"6\":\"2021-01-17\",\"7\":\"2021-01-23\",\"8\":\"1400\",\"9\":\"5600\"},{\"1\":\"Columbia University\",\"2\":\"NY\",\"3\":\"New York City\",\"4\":\"Private industry\",\"5\":\"GWC-UAW\",\"6\":\"2021-03-15\",\"7\":\"2022-01-07\",\"8\":\"3000\",\"9\":\"177000\"},{\"1\":\"Allegheny Technologies Incorporated\",\"2\":\"PA\",\"3\":\"Multiple\",\"4\":\"Private industry\",\"5\":\"USW\",\"6\":\"2021-03-30\",\"7\":\"2021-07-13\",\"8\":\"1300\",\"9\":\"94900\"},{\"1\":\"Warrior Met Coal, Inc.\",\"2\":\"AL\",\"3\":\"Brookwood\",\"4\":\"Private industry\",\"5\":\"UMWA\",\"6\":\"2021-04-01\",\"7\":\"2022-03-31\",\"8\":\"1100\",\"9\":\"273900\"},{\"1\":\"New York University\",\"2\":\"NY\",\"3\":\"New York City\",\"4\":\"Private industry\",\"5\":\"GSOC-UAW\",\"6\":\"2021-04-26\",\"7\":\"2021-05-15\",\"8\":\"2200\",\"9\":\"33000\"},{\"1\":\"Cook County\",\"2\":\"IL\",\"3\":\"Chicago\",\"4\":\"Local government\",\"5\":\"SEIU\",\"6\":\"2021-06-25\",\"7\":\"2021-07-12\",\"8\":\"2000\",\"9\":\"22000\"},{\"1\":\"Volvo Trucks North America\",\"2\":\"VA\",\"3\":\"Dublin\",\"4\":\"Private industry\",\"5\":\"UAW\",\"6\":\"2021-04-17\",\"7\":\"2021-07-14\",\"8\":\"2900\",\"9\":\"101500\"},{\"1\":\"University of Southern California\",\"2\":\"CA\",\"3\":\"Los Angeles\",\"4\":\"Private industry\",\"5\":\"CNA/NNOC\",\"6\":\"2021-07-13\",\"7\":\"2021-07-14\",\"8\":\"1400\",\"9\":\"2800\"},{\"1\":\"Nabisco\",\"2\":\"OR, IL, CO, GA, VA\",\"3\":\"Multiple\",\"4\":\"Private industry\",\"5\":\"BCTGM\",\"6\":\"2021-08-19\",\"7\":\"2021-09-18\",\"8\":\"1000\",\"9\":\"21000\"},{\"1\":\"Associated General Contractors of Washington\",\"2\":\"WA\",\"3\":\"Multiple\",\"4\":\"Private industry\",\"5\":\"NWCU\",\"6\":\"2021-09-16\",\"7\":\"2021-10-11\",\"8\":\"2000\",\"9\":\"34000\"},{\"1\":\"Harvard University\",\"2\":\"CA\",\"3\":\"Cambridge, MA\",\"4\":\"Private industry\",\"5\":\"HGSU-UAW\",\"6\":\"2021-10-27\",\"7\":\"2021-10-29\",\"8\":\"2000\",\"9\":\"6000\"},{\"1\":\"Mercy Hospital\",\"2\":\"NY\",\"3\":\"Buffalo\",\"4\":\"Private industry\",\"5\":\"CWA\",\"6\":\"2021-10-01\",\"7\":\"2021-11-09\",\"8\":\"2000\",\"9\":\"54000\"},{\"1\":\"Kellogg's\",\"2\":\"MI, PA, TN, NE\",\"3\":\"Multiple\",\"4\":\"Private industry\",\"5\":\"BCTGM\",\"6\":\"2021-10-05\",\"7\":\"2021-12-21\",\"8\":\"1400\",\"9\":\"74200\"},{\"1\":\"John Deere\",\"2\":\"CO, GA, IL, IA, KS\",\"3\":\"Multiple\",\"4\":\"Private industry\",\"5\":\"UAW\",\"6\":\"2021-10-14\",\"7\":\"2021-11-17\",\"8\":\"10000\",\"9\":\"240000\"},{\"1\":\"Kaiser Permanente\",\"2\":\"CA\",\"3\":\"Oakland, CA\",\"4\":\"Private industry\",\"5\":\"SEIU-UHW, OPEIU, IFPTE, NUHW\",\"6\":\"2021-11-18\",\"7\":\"2021-11-19\",\"8\":\"40000\",\"9\":\"40000\"},{\"1\":\"Fred Meyer - Kroger\",\"2\":\"OR\",\"3\":\"Portland, Bend, Newburg and Klamath\",\"4\":\"Private industry\",\"5\":\"UFCW\",\"6\":\"2021-12-17\",\"7\":\"2021-12-17\",\"8\":\"7000\",\"9\":\"7000\"},{\"1\":\"Kroger - King Soopers\",\"2\":\"CO\",\"3\":\"Denver\",\"4\":\"Private industry\",\"5\":\"UFCW\",\"6\":\"2022-01-12\",\"7\":\"2022-01-25\",\"8\":\"8000\",\"9\":\"72000\"},{\"1\":\"Minneapolis Public Schools\",\"2\":\"MN\",\"3\":\"Minneapolis\",\"4\":\"Local government\",\"5\":\"MFT, ESP\",\"6\":\"2022-03-08\",\"7\":\"2022-03-28\",\"8\":\"4500\",\"9\":\"67500\"},{\"1\":\"Sacramento City Unified School District\",\"2\":\"CA\",\"3\":\"Sacramento\",\"4\":\"Local government\",\"5\":\"SCTA, SEIU\",\"6\":\"2022-03-23\",\"7\":\"2022-04-03\",\"8\":\"4600\",\"9\":\"36800\"},{\"1\":\"Sutter Health Hospitals\",\"2\":\"CA\",\"3\":\"Northern California\",\"4\":\"Private industry\",\"5\":\"CNA\",\"6\":\"2022-04-18\",\"7\":\"2022-04-22\",\"8\":\"8000\",\"9\":\"40000\"},{\"1\":\"University of Illinois Chicago\",\"2\":\"IL\",\"3\":\"Chicago\",\"4\":\"State government\",\"5\":\"GEO\",\"6\":\"2022-04-18\",\"7\":\"2022-04-25\",\"8\":\"1500\",\"9\":\"9000\"},{\"1\":\"Stanford Health Care and Lucile Packard Children's Hospital Stanford\",\"2\":\"CA\",\"3\":\"Stanford, Palo Alto\",\"4\":\"Private industry\",\"5\":\"CRONA\",\"6\":\"2022-04-25\",\"7\":\"2022-05-02\",\"8\":\"5000\",\"9\":\"30000\"},{\"1\":\"Oakland Unified School District\",\"2\":\"CA\",\"3\":\"Oakland\",\"4\":\"Local government\",\"5\":\"OEA\",\"6\":\"2022-04-29\",\"7\":\"2022-04-29\",\"8\":\"2000\",\"9\":\"2000\"},{\"1\":\"CNH Industrial\",\"2\":\"IA, WI\",\"3\":\"Burlington, IA; Racine, WI\",\"4\":\"Private industry\",\"5\":\"UAW\",\"6\":\"2022-05-02\",\"7\":\"2023-01-21\",\"8\":\"1000\",\"9\":\"180000\"},{\"1\":\"Cedars-Sinai Medical Center\",\"2\":\"CA\",\"3\":\"Los Angeles\",\"4\":\"Private industry\",\"5\":\"SEIU\",\"6\":\"2022-05-09\",\"7\":\"2022-05-13\",\"8\":\"2000\",\"9\":\"10000\"},{\"1\":\"Brookline Public Schools\",\"2\":\"MA\",\"3\":\"Brookline\",\"4\":\"Local government\",\"5\":\"BEU\",\"6\":\"2022-05-16\",\"7\":\"2022-05-16\",\"8\":\"1000\",\"9\":\"1000\"},{\"1\":\"Kaiser Permanente LA Medical Center\",\"2\":\"CA\",\"3\":\"Los Angeles\",\"4\":\"Private industry\",\"5\":\"CNA\",\"6\":\"2022-06-23\",\"7\":\"2022-06-24\",\"8\":\"1200\",\"9\":\"1200\"},{\"1\":\"Kaiser Permanente Northern California Facilities\",\"2\":\"CA\",\"3\":\"Northern California\",\"4\":\"Private industry\",\"5\":\"NUHW\",\"6\":\"2022-08-15\",\"7\":\"2022-10-18\",\"8\":\"2000\",\"9\":\"90000\"},{\"1\":\"Frontier Communications\",\"2\":\"CA\",\"3\":\"Southern California\",\"4\":\"Private industry\",\"5\":\"CWA\",\"6\":\"2022-08-19\",\"7\":\"2022-08-24\",\"8\":\"2000\",\"9\":\"8000\"},{\"1\":\"Columbus City Schools\",\"2\":\"OH\",\"3\":\"Columbus\",\"4\":\"Local government\",\"5\":\"CEA\",\"6\":\"2022-08-22\",\"7\":\"2022-08-26\",\"8\":\"4500\",\"9\":\"22500\"},{\"1\":\"Kent School District\",\"2\":\"WA\",\"3\":\"Kent\",\"4\":\"Local government\",\"5\":\"KEA\",\"6\":\"2022-08-25\",\"7\":\"2022-09-07\",\"8\":\"1700\",\"9\":\"15300\"},{\"1\":\"Twin Cities Hospitals Group, Essentia Health, Allina Health, St. Luke's\",\"2\":\"MN\",\"3\":\"Multiple\",\"4\":\"Private industry\",\"5\":\"MNA\",\"6\":\"2022-09-12\",\"7\":\"2022-09-14\",\"8\":\"15000\",\"9\":\"45000\"},{\"1\":\"Weyerhaeuser Company\",\"2\":\"OR, WA\",\"3\":\"Multiple\",\"4\":\"Private industry\",\"5\":\"IAM\",\"6\":\"2022-09-13\",\"7\":\"2022-10-28\",\"8\":\"1200\",\"9\":\"39600\"},{\"1\":\"San Francisco International Airport\",\"2\":\"CA\",\"3\":\"San Francisco\",\"4\":\"Local government\",\"5\":\"UNITE HERE\",\"6\":\"2022-09-26\",\"7\":\"2022-09-28\",\"8\":\"1000\",\"9\":\"3000\"},{\"1\":\"Sutter Health Hospitals\",\"2\":\"CA\",\"3\":\"Berkeley\",\"4\":\"Private industry\",\"5\":\"CNA/NNU\",\"6\":\"2022-10-24\",\"7\":\"2022-10-29\",\"8\":\"1800\",\"9\":\"9000\"},{\"1\":\"University of California\",\"2\":\"CA\",\"3\":\"Statewide\",\"4\":\"State government\",\"5\":\"UAW\",\"6\":\"2022-11-14\",\"7\":\"2022-12-23\",\"8\":\"48000\",\"9\":\"1272000\"},{\"1\":\"The New School\",\"2\":\"NY\",\"3\":\"NY\",\"4\":\"Private industry\",\"5\":\"ACT-UAW\",\"6\":\"2022-11-16\",\"7\":\"2022-12-10\",\"8\":\"1700\",\"9\":\"28900\"},{\"1\":\"New York Times\",\"2\":\"NY\",\"3\":\"NY\",\"4\":\"Private industry\",\"5\":\"TNG-CWA\",\"6\":\"2022-12-08\",\"7\":\"2022-12-08\",\"8\":\"1100\",\"9\":\"1100\"},{\"1\":\"Alta Bates Summit\",\"2\":\"CA\",\"3\":\"Oakland and Berkeley\",\"4\":\"Private industry\",\"5\":\"NNU\",\"6\":\"2022-12-24\",\"7\":\"2023-01-01\",\"8\":\"1800\",\"9\":\"7200\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n\n```{.r .cell-code}\n# view number of rows\nnrow(strike)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 629\n```\n:::\n:::\n\nThere are 629 rows in the cleaned dataset, representing 629 strikes.\n\n### Variables\n\n#### `Employer`\nShows the employer of the workers striking. This variable is categorical. \n\n::: {.cell}\n\n```{.r .cell-code}\n# number of distinct employers\nn_distinct(strike$Employer)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 485\n```\n:::\n:::\n\nThere are 485 distinct employers in the dataset.\n\nHere are some of the employers with the most strikes in the period:\n\n::: {.cell}\n\n```{.r .cell-code}\n# create factor levels (by occurrences)\nem_levels = names(sort(table(strike$Employer), decreasing = TRUE))\n\n# sort employers\ncount_em <- strike %>%\n  mutate(Employer = factor(Employer, em_levels))\n\n# view\nhead(em_levels)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"General Motors Corp.\"     \"Kaiser Permanente\"       \n[3] \"University of California\" \"Boeing Company\"          \n[5] \"Caterpillar, Inc.\"        \"Sutter Health Hospitals\" \n```\n:::\n:::\n\n\nLet's visualize the frequency. Because there are so many employers, I've chosen not to label them all for visibility reasons. Instead, I'll sort employers from most strikes in the period to least, with a simple numerical marker. The bar for each distinct employer will be colored to show distinct unions that have struck.\n\n::: {.cell}\n\n```{.r .cell-code}\n# spacing for graph\nspaces_em <- function(x) x[seq_along(x) %% 80 == 0]\n\n# bar graph\nggplot(count_em, aes(Employer)) +\n  geom_bar(aes(fill=Union)) +\n  scale_y_continuous(n.breaks=20) +\n  labs(title=\"Employers in descending order of strikes\",subtitle=\"1993 - 2023\",x=\"Employers\",y=\"Strikes\") +\n  scale_x_discrete(breaks=spaces_em,labels=c(\"80\",\"160\",\"240\",\"320\",\"400\",\"480\")) + \n  theme_minimal() +\n  guides(fill = FALSE)\n```\n\n::: {.cell-output-display}\n![](dannyholt_hw3_new_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\nWe can see that a few employers were struck many times, but most were only struck one or two times.\n\nThe colors show that most employers with many strikes were struck by multiple different unions. One thing this can signal is a high level of militancy across different types of workers employed by the employer. For instance, an employer like the University of California, which had the third-most strikes in the period, employs many different types of workers belonging to different unions, including CWA, the UAW, AFSCME, and the IBT. See here:\n\n::: {.cell}\n\n```{.r .cell-code}\nstrike %>%\n  filter(Employer == \"University of California\")\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"Employer\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"States\"],\"name\":[2],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Areas\"],\"name\":[3],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Ownership\"],\"name\":[4],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Union\"],\"name\":[5],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Start date\"],\"name\":[6],\"type\":[\"dttm\"],\"align\":[\"right\"]},{\"label\":[\"End date\"],\"name\":[7],\"type\":[\"dttm\"],\"align\":[\"right\"]},{\"label\":[\"Workers\"],\"name\":[8],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Days struck\"],\"name\":[9],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"University of California\",\"2\":\"CA\",\"3\":\"Statewide\",\"4\":\"State government\",\"5\":\"CWA\",\"6\":\"1998-12-01\",\"7\":\"1998-12-06\",\"8\":\"1200\",\"9\":\"4800\"},{\"1\":\"University of California\",\"2\":\"CA\",\"3\":\"NA\",\"4\":\"State government\",\"5\":\"UAW\",\"6\":\"2000-04-18\",\"7\":\"2000-04-18\",\"8\":\"5000\",\"9\":\"5000\"},{\"1\":\"University of California\",\"2\":\"CA\",\"3\":\"Oakland\",\"4\":\"State government\",\"5\":\"NA\",\"6\":\"2005-04-14\",\"7\":\"2005-04-15\",\"8\":\"2000\",\"9\":\"2000\"},{\"1\":\"University of California\",\"2\":\"CA\",\"3\":\"Oakland\",\"4\":\"State government\",\"5\":\"AFSME\",\"6\":\"2005-04-14\",\"7\":\"2005-04-15\",\"8\":\"7000\",\"9\":\"7000\"},{\"1\":\"University of California\",\"2\":\"CA\",\"3\":\"Oakland\",\"4\":\"State government\",\"5\":\"NA\",\"6\":\"2005-04-14\",\"7\":\"2005-04-15\",\"8\":\"2000\",\"9\":\"2000\"},{\"1\":\"University of California\",\"2\":\"CA\",\"3\":\"Statewide\",\"4\":\"State government\",\"5\":\"AFSCME\",\"6\":\"2008-07-14\",\"7\":\"2008-07-18\",\"8\":\"8500\",\"9\":\"42500\"},{\"1\":\"University of California\",\"2\":\"CA\",\"3\":\"Statewide\",\"4\":\"State government\",\"5\":\"IBT\",\"6\":\"2017-01-10\",\"7\":\"2017-01-10\",\"8\":\"2200\",\"9\":\"2200\"},{\"1\":\"University of California\",\"2\":\"CA\",\"3\":\"Statewide\",\"4\":\"State government\",\"5\":\"UAW\",\"6\":\"2022-11-14\",\"7\":\"2022-12-23\",\"8\":\"48000\",\"9\":\"1272000\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\nHowever, the presence of strikes by multiple unions at a single employer can also signal turf disputes. This is the case with Kaiser Permanente, the employer with the second-most strikes in the period, which saw strikes from separate healthcare workers’ unions, including SEIU, CNA, and NUHW (in addition to UFCW, which represents non-healthcare workers). See here:\n\n::: {.cell}\n\n```{.r .cell-code}\nstrike %>%\n  filter(Employer == \"Kaiser Permanente\")\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"Employer\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"States\"],\"name\":[2],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Areas\"],\"name\":[3],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Ownership\"],\"name\":[4],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Union\"],\"name\":[5],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Start date\"],\"name\":[6],\"type\":[\"dttm\"],\"align\":[\"right\"]},{\"label\":[\"End date\"],\"name\":[7],\"type\":[\"dttm\"],\"align\":[\"right\"]},{\"label\":[\"Workers\"],\"name\":[8],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Days struck\"],\"name\":[9],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"Kaiser Permanente\",\"2\":\"CA\",\"3\":\"Southern\",\"4\":\"Private industry\",\"5\":\"SEIU\",\"6\":\"1993-04-01\",\"7\":\"1993-04-01\",\"8\":\"12000\",\"9\":\"12000\"},{\"1\":\"Kaiser Permanente\",\"2\":\"CA\",\"3\":\"Northern\",\"4\":\"Private industry\",\"5\":\"CNA\",\"6\":\"1997-04-16\",\"7\":\"1997-04-16\",\"8\":\"17000\",\"9\":\"17000\"},{\"1\":\"Kaiser Permanente\",\"2\":\"CA\",\"3\":\"Northern\",\"4\":\"Private industry\",\"5\":\"CNA\",\"6\":\"1997-07-17\",\"7\":\"1997-07-18\",\"8\":\"10500\",\"9\":\"21000\"},{\"1\":\"Kaiser Permanente\",\"2\":\"OR, WA\",\"3\":\"Multiple states\",\"4\":\"Private industry\",\"5\":\"SEIU\",\"6\":\"1997-09-02\",\"7\":\"1997-10-04\",\"8\":\"2000\",\"9\":\"48000\"},{\"1\":\"Kaiser Permanente\",\"2\":\"CA\",\"3\":\"Northern\",\"4\":\"Private industry\",\"5\":\"CNA\",\"6\":\"1997-09-08\",\"7\":\"1997-09-09\",\"8\":\"20300\",\"9\":\"40600\"},{\"1\":\"Kaiser Permanente\",\"2\":\"CA\",\"3\":\"Northern\",\"4\":\"Private industry\",\"5\":\"CNA\",\"6\":\"1997-11-10\",\"7\":\"1997-11-10\",\"8\":\"8900\",\"9\":\"8900\"},{\"1\":\"Kaiser Permanente\",\"2\":\"CA\",\"3\":\"Northern\",\"4\":\"Private industry\",\"5\":\"CNA\",\"6\":\"1998-01-28\",\"7\":\"1998-01-29\",\"8\":\"8000\",\"9\":\"16000\"},{\"1\":\"Kaiser Permanente\",\"2\":\"CA\",\"3\":\"Northern\",\"4\":\"Private industry\",\"5\":\"CNA\",\"6\":\"1998-02-24\",\"7\":\"1998-02-24\",\"8\":\"7100\",\"9\":\"7100\"},{\"1\":\"Kaiser Permanente\",\"2\":\"CO\",\"3\":\"Denver area\",\"4\":\"Private industry\",\"5\":\"UFCW\",\"6\":\"2000-03-02\",\"7\":\"2000-03-21\",\"8\":\"1100\",\"9\":\"15400\"},{\"1\":\"Kaiser Permanente\",\"2\":\"CA\",\"3\":\"NA\",\"4\":\"Private industry\",\"5\":\"NUHW\",\"6\":\"2018-12-10\",\"7\":\"2018-12-14\",\"8\":\"4000\",\"9\":\"20000\"},{\"1\":\"Kaiser Permanente\",\"2\":\"CA\",\"3\":\"Statewide\",\"4\":\"Private industry\",\"5\":\"NUHW\",\"6\":\"2019-12-16\",\"7\":\"2019-12-21\",\"8\":\"4000\",\"9\":\"20000\"},{\"1\":\"Kaiser Permanente\",\"2\":\"CA\",\"3\":\"Oakland, CA\",\"4\":\"Private industry\",\"5\":\"SEIU-UHW, OPEIU, IFPTE, NUHW\",\"6\":\"2021-11-18\",\"7\":\"2021-11-19\",\"8\":\"40000\",\"9\":\"40000\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n#### `States`\nShows the state or state(s) in which the strike took place. This variable is categorical.\n\n::: {.cell}\n\n```{.r .cell-code}\n# break out entries with multiple states\nstrike_st <- separate_rows(strike,States,sep=\", \")\nstrike_st <- separate_rows(strike_st,States,sep=\",\")\n\n# filter out data without valid state information\nstrike_st <- strike_st %>%\n  filter(!grepl(\"Interstate\", States)) %>%\n  filter(!grepl(\"East Coast States\", States)) %>%\n  filter(!grepl(\"Nationwide\", States))\n\n# convert states to factors\nst_levels <- c(\"WY\", \"WI\", \"WV\", \"WA\", \"VA\", \"VT\", \"UT\", \"TX\", \"TN\", \"SD\", \"SC\", \"RI\", \"PA\", \"OR\", \"OK\", \"OH\", \"ND\", \"NC\", \"NY\", \"NM\", \"NJ\", \"NH\", \"NV\", \"NE\", \"MT\", \"MO\", \"MS\", \"MN\", \"MI\", \"MA\", \"MD\", \"ME\", \"LA\", \"KY\", \"KS\", \"IA\", \"IN\", \"IL\", \"ID\", \"HI\", \"GA\", \"FL\", \"DE\", \"CT\", \"CO\", \"CA\", \"AR\", \"AZ\", \"AK\", \"AL\")\nstrike_st <- strike_st %>%\n  mutate(States=factor(States,levels=st_levels))\n\n# drop NA\nstrike_st <- strike_st %>%\n  drop_na(States)\n```\n:::\n\nLet's look at the frequency of strikes across the states. Here is a visualization:\n\n::: {.cell}\n\n```{.r .cell-code}\n# visualize frequency\nggplot(strike_st,aes(States, fill=States)) +\n  geom_bar() +\n  scale_fill_manual(values=rep(c(\"darkgreen\",\"darkblue\"), ceiling(length(strike_st$States)/2))[1:length(strike_st$States)]) +\n  coord_flip() +\n  scale_x_discrete(guide = guide_axis(n.dodge=1)) +\n  labs(title=\"Number of strikes by state\",subtitle=\"1993 - 2023\",x=\"State\",y=\"Strikes\") +\n  theme(axis.text.y = element_text(colour = c(rep(c(\"darkgreen\",\"darkblue\"))))) +\n  options(repr.plot.width=15, repr.plot.height=15) +\n  guides(fill = FALSE)\n```\n\n::: {.cell-output-display}\n![](dannyholt_hw3_new_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\nFirst, I will note that the vertical spacing of this graph could be improved.\n\nWe can see that the states with the most strikes in the period are: California, Illinois, New York, Pennsylvania, Ohio, and Washington. This makes perfect sense, based on the economic and political conditions of those states. Illinois, Pennsylvania, and Ohio are all home to large automotive and other manufacturing unions. Meanwhile, California, New York, and Washington all have high union density overall, with long and storied histories of labor activism. Additionally, all six of these states have above-average populations.\n\n#### `Areas`\nShows a more specific location of the strike, at a lower level than the state(s). This variable is categorical.\n\nBecause the areas are written to be geographically overlapping and range in size from cities to entire regions, the frequency information for this variable is relatively meaningless.\n\n#### `Ownership`\nShows what type of entity the employer is of the following options: private industry, local and/or state government. This variable is categorical.\n\nLet's visualize the frequency of ownership types in strikes.\n\n::: {.cell}\n\n```{.r .cell-code}\n# break out state and local government into state government and local government,\nstrike_own <- separate_rows(strike,Ownership,sep=\" and \")\nstrike_own <- strike_own %>%\n  mutate(Ownership=case_when(\n    Ownership == \"State\" ~ \"State government\",\n    Ownership == \"State government\" ~ \"State government\",\n    Ownership == \"Local government\" ~ \"Local government\",\n    Ownership == \"local government\" ~ \"Local government\",\n    Ownership == \"Private industry\" ~ \"Private industry\"),\n    # code colors for ggplot\n    Color=case_when(\n      Ownership == \"State government\" ~ \"darkred\",\n      Ownership == \"Local government\" ~ \"darkblue\",\n      Ownership == \"Private industry\" ~ \"darkgreen\",\n    )\n    )\n\n# filter out data without valid information\nstrike_own <- strike_own %>%\n  drop_na(Ownership)\n\n# convert ownership types to factors\nown_levels <- c(\"Private industry\", \"State government\", \"Local government\")\nstrike_own <- strike_own %>%\n  mutate(Ownership=factor(Ownership,levels=own_levels))\n\n# bar graph\nggplot(strike_own, aes(Ownership, fill=Color)) +\n  guides(fill = FALSE) +\n  geom_bar() +\n  labs(title=\"Number of strikes by employer ownership type\",subtitle=\"1993 - 2023\",x=\"Ownership type\",y=\"Strikes\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](dannyholt_hw3_new_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\nThis chart shows, more than anything else, the vastness of the private sector compared with the public sector in the U.S. Indeed, the fact that the bars for local and state government strikes are as large as they are is a testament to a much higher unionization rate in the public sector than in the private sector—33.1% in the public sector versus 6.0% in the private sector (Bureau of Labor Statistics 2023b).\n\n#### `Union`\nShows the acronym of the union to which the striking workers belonged. This variable is categorical.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# separate cells with multiple unions\nstrike_un <- separate_rows(strike,Union,sep=\", \")\nstrike_un <- separate_rows(strike_un,Union,sep=\"; \")\nstrike_un <- separate_rows(strike_un,Union,sep=\". \")\n\n# filter out separate entries for union local numbers (redundant)\nstrike_un <- strike_un %>%\n  filter(!grepl(\"234\", Union)) %>%\n  filter(!grepl(\"1594\", Union))\n\n# drop NA\nstrike_un <- strike_un %>%\n  drop_na(Union)\n\n# create factor levels (by occurrences)\nun_levels = names(sort(table(strike_un$Union), decreasing = TRUE))\n\n# sort employers\nstrike_un <- strike_un %>%\n  mutate(Union = factor(Union, levels=un_levels))\n\n# number of unions\nn_distinct(strike_un$Union)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 131\n```\n:::\n:::\n\nThere are 131 distinct unions in the dataset. Here are some of the Unions with the most strikes in the period:\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(un_levels)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"SEIU\" \"UAW\"  \"IAM\"  \"IBT\"  \"CNA\"  \"USW\" \n```\n:::\n:::\n\n\nLet's visualize the frequency. Because there are so many unions, I've chosen not to label them all for visibility reasons. Instead, I'll sort unions from most strikes in the period to least, with a simple numerical marker. The bar for each distinct union will be colored to show distinct employers struck.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# spacing for graph\nspaces_un <- function(x) x[seq_along(x) %% 26 == 0]\n\n# bar graph\nggplot(strike_un, aes(Union)) +\n  geom_bar(aes(fill=Employer)) +\n  labs(title=\"Unions in descending order of strikes\",subtitle=\"1993 - 2023\",x=\"Unions\",y=\"Strikes\") +\n  theme_minimal() +\n  guides(fill = FALSE) +\n  scale_x_discrete(breaks=spaces_un,labels=c(\"26\",\"52\",\"78\",\"104\",\"130\"))\n```\n\n::: {.cell-output-display}\n![](dannyholt_hw3_new_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\nThe graph shows us a few things. Perhaps most apparent is that most unions in the dataset only engaged in one strike over these three decades.\n\nWe also see that most unions with multiple strikes, like SEIU and the UAW, struck multiple employers. This may seem obvious—unions with more striking bargaining units will have more total strikes. However, the presence of strikes in one bargaining unit, I suspect, is likely to encourage action in other units (at other employers) in the same union.\n\n#### `Start date` and `End date`\n`Start date` shows the date on which the strike began. This column contains numerical, discrete, interval data.\n\n`End date` shows the date on which the strike ended. This column contains numerical, discrete, interval data.\n\nLet's visualize the distribution of each.\n\n::: {.cell}\n\n```{.r .cell-code}\n# pivot to create new date type variable\nstrike_date <- strike %>%\n  pivot_longer(c(`Start date`,`End date`),names_to=\"Type\",values_to=\"Date\")\n\n# boxplot\nggplot(strike_date, aes(x=Type, y=Date, fill =Type)) +\n  geom_boxplot() +\n  coord_flip() +\n  theme_minimal() +\n  labs(title=\"Distribution of start and and end dates of strikes\", subtitle=\"1993 - 2023\", y=\"Date\", x=\"\") +\n  guides(fill = FALSE)\n```\n\n::: {.cell-output-display}\n![](dannyholt_hw3_new_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\nWe can see that the left whisker of the start date box is dragged out earlier in time because the data includes one strike that began in 1988, well before the rest of the data.\n\n#### `Workers`\nShows the number of workers who went on strike. This column contains numerical, discrete, ratio data.\n\nLet's look at some measures of central tendency.\n\n::: {.cell}\n\n```{.r .cell-code}\n# median\nstrike %>%\n  summarize(Median=median(Workers, na.rm=TRUE))\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"Median\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"2300\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n\n```{.r .cell-code}\n# mean\nstrike %>%\n  summarize(Mean=mean(Workers, na.rm=TRUE))\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"Mean\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"7561.844\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n\n```{.r .cell-code}\n#std dev\nstrike %>%\n  summarize(\"Standard Deviation\"=sd(Workers, na.rm=TRUE))\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"Standard Deviation\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"17294.49\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\nHere, we see how the presence of many relatively small strikes brings down the median far below the mean.\n\n#### `Days struck`\nShows the total number of hours of labor workers withheld during the strike. This is distinct from the difference between `Start date` and `End date` because, in some strikes, some workers go back to work before the strike ends. This column contains numerical, discrete, ratio data.\n\nLet's look at some measures of central tendency.\n\n::: {.cell}\n\n```{.r .cell-code}\n# median\nstrike %>%\n  summarize(Median=median(`Days struck`, na.rm=TRUE))\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"Median\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"20400\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n\n```{.r .cell-code}\n# mean\nstrike %>%\n  summarize(Mean=mean(`Days struck`, na.rm=TRUE))\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"Mean\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"139380.3\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n\n```{.r .cell-code}\n#std dev\nstrike %>%\n  summarize(\"Standard Deviation\"=sd(`Days struck`, na.rm=TRUE))\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"Standard Deviation\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"793317.8\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\nHere, we see how the presence of many relatively short and small strikes brings down the median far below the mean.\n\n## How has labor militancy changed over the past 30 years?\nMy goal here is to gain a better understanding of the contemporary labor movement in the U.S. by looking at changes in its most significant activity—strikes.\n\n### Measures of central tendency\nTo get closer to an answer, we will create a new data frame, combining strikes that start in the same year and view some measures of central tendency.\n\n::: {.cell}\n\n```{.r .cell-code}\n# select relevant variables\nstrike_yr <- strike %>%\n  select(\n    \"Start date\",\n    \"Workers\",\n    \"Days struck\",\n    \"Ownership\",\n    \"States\")\n\n# truncate start date to year\nstrike_yr$\"Start date\" <- as.numeric(format(strike_yr$\"Start date\", \"%Y\"))\n  \n# rename start date to year\nstrike_yr <- strike_yr %>%\n  rename(\"Year\"=\"Start date\") %>%\n  rename(\"Days\" = \"Days struck\")\n  \n# condense rows by year and remove problematic rows\n  strike_yr_sum <- strike_yr %>%\n    filter(Year>1990) %>%\n    group_by(Year)\n  #create condensed view\n  strike_yr_sum_cond <- strike_yr_sum %>%\n    summarize(\n      Workers=sum(Workers, na.rm=TRUE),\n      `Days Struck`=sum(Days, na.rm=TRUE),\n    )\n  #create less condensed view\n  strike_yr_sum <- strike_yr_sum %>%\n    summarize(\n      Workers=sum(Workers, na.rm=TRUE),\n      `Days Struck`=sum(Days, na.rm=TRUE),\n      Ownership=Ownership,\n      States=States\n    )\n```\n:::\n\n\nFor the number of workers involved in strikes each year:\n\n::: {.cell}\n\n```{.r .cell-code}\n# median\nstrike_yr_sum_cond %>%\n  summarize(Median=median(Workers, na.rm=TRUE))\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"Median\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"105950\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n\n```{.r .cell-code}\n# mean\nstrike_yr_sum_cond %>%\n  summarize(Mean=mean(Workers, na.rm=TRUE))\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"Mean\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"158463.3\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n\n```{.r .cell-code}\n#std dev\nstrike_yr_sum_cond %>%\n  summarize(\"Standard Deviation\"=sd(Workers, na.rm=TRUE))\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"Standard Deviation\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"134757.7\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\nThen, for the number of days struck each year:\n\n::: {.cell}\n\n```{.r .cell-code}\n# median\nstrike_yr_sum_cond %>%\n  summarize(Median=median(`Days Struck`, na.rm=TRUE))\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"Median\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"1611000\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n\n```{.r .cell-code}\n# mean\nstrike_yr_sum_cond %>%\n  summarize(Mean=mean(`Days Struck`, na.rm=TRUE))\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"Mean\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"2826357\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n\n```{.r .cell-code}\n#std dev\nstrike_yr_sum_cond %>%\n  summarize(\"Standard Deviation\"=sd(`Days Struck`, na.rm=TRUE))\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"Standard Deviation\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"3806644\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\nAs was the case with measures of central tendency for data on individual strikes, the medians are well below the means because of the presence of many relatively small, short strikes.\n\n### Changes in annual strike magnitude\nHow have numbers of workers on strike and number of days struck changed over time in the past 30 years?\n\nLet's view the years in order from most workers on strike to least.\n\n::: {.cell}\n\n```{.r .cell-code}\nstrike_yr_sum_cond%>%\n  arrange(desc(Workers))\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"Year\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Workers\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Days Struck\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"2018\",\"2\":\"485200\",\"3\":\"2363000\"},{\"1\":\"2019\",\"2\":\"425500\",\"3\":\"3014700\"},{\"1\":\"2000\",\"2\":\"393700\",\"3\":\"19911500\"},{\"1\":\"1998\",\"2\":\"386800\",\"3\":\"6692100\"},{\"1\":\"1997\",\"2\":\"338600\",\"3\":\"3527900\"},{\"1\":\"1994\",\"2\":\"324500\",\"3\":\"7948100\"},{\"1\":\"1996\",\"2\":\"272700\",\"3\":\"5246100\"},{\"1\":\"1995\",\"2\":\"190300\",\"3\":\"3476900\"},{\"1\":\"2007\",\"2\":\"189200\",\"3\":\"1458300\"},{\"1\":\"1993\",\"2\":\"181900\",\"3\":\"3597800\"},{\"1\":\"2004\",\"2\":\"174700\",\"3\":\"1572400\"},{\"1\":\"2012\",\"2\":\"148100\",\"3\":\"784700\"},{\"1\":\"2003\",\"2\":\"129200\",\"3\":\"6421100\"},{\"1\":\"2022\",\"2\":\"120600\",\"3\":\"1991100\"},{\"1\":\"2011\",\"2\":\"112500\",\"3\":\"1366300\"},{\"1\":\"2016\",\"2\":\"99400\",\"3\":\"1468600\"},{\"1\":\"2001\",\"2\":\"99100\",\"3\":\"1143200\"},{\"1\":\"2005\",\"2\":\"98800\",\"3\":\"2190000\"},{\"1\":\"2021\",\"2\":\"80700\",\"3\":\"1186900\"},{\"1\":\"1999\",\"2\":\"72600\",\"3\":\"961000\"},{\"1\":\"2008\",\"2\":\"72200\",\"3\":\"1649600\"},{\"1\":\"2006\",\"2\":\"69300\",\"3\":\"1790600\"},{\"1\":\"2013\",\"2\":\"54500\",\"3\":\"289900\"},{\"1\":\"2015\",\"2\":\"47300\",\"3\":\"758700\"},{\"1\":\"2002\",\"2\":\"45900\",\"3\":\"646400\"},{\"1\":\"2010\",\"2\":\"44500\",\"3\":\"302300\"},{\"1\":\"2014\",\"2\":\"34300\",\"3\":\"256300\"},{\"1\":\"2017\",\"2\":\"25300\",\"3\":\"2378400\"},{\"1\":\"2020\",\"2\":\"24000\",\"3\":\"272700\"},{\"1\":\"2009\",\"2\":\"12500\",\"3\":\"124100\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\nNext, we'll view the years in order from most days struck to least.\n\n::: {.cell}\n\n```{.r .cell-code}\nstrike_yr_sum_cond%>%\n  arrange(desc(`Days Struck`))\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"Year\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Workers\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Days Struck\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"2000\",\"2\":\"393700\",\"3\":\"19911500\"},{\"1\":\"1994\",\"2\":\"324500\",\"3\":\"7948100\"},{\"1\":\"1998\",\"2\":\"386800\",\"3\":\"6692100\"},{\"1\":\"2003\",\"2\":\"129200\",\"3\":\"6421100\"},{\"1\":\"1996\",\"2\":\"272700\",\"3\":\"5246100\"},{\"1\":\"1993\",\"2\":\"181900\",\"3\":\"3597800\"},{\"1\":\"1997\",\"2\":\"338600\",\"3\":\"3527900\"},{\"1\":\"1995\",\"2\":\"190300\",\"3\":\"3476900\"},{\"1\":\"2019\",\"2\":\"425500\",\"3\":\"3014700\"},{\"1\":\"2017\",\"2\":\"25300\",\"3\":\"2378400\"},{\"1\":\"2018\",\"2\":\"485200\",\"3\":\"2363000\"},{\"1\":\"2005\",\"2\":\"98800\",\"3\":\"2190000\"},{\"1\":\"2022\",\"2\":\"120600\",\"3\":\"1991100\"},{\"1\":\"2006\",\"2\":\"69300\",\"3\":\"1790600\"},{\"1\":\"2008\",\"2\":\"72200\",\"3\":\"1649600\"},{\"1\":\"2004\",\"2\":\"174700\",\"3\":\"1572400\"},{\"1\":\"2016\",\"2\":\"99400\",\"3\":\"1468600\"},{\"1\":\"2007\",\"2\":\"189200\",\"3\":\"1458300\"},{\"1\":\"2011\",\"2\":\"112500\",\"3\":\"1366300\"},{\"1\":\"2021\",\"2\":\"80700\",\"3\":\"1186900\"},{\"1\":\"2001\",\"2\":\"99100\",\"3\":\"1143200\"},{\"1\":\"1999\",\"2\":\"72600\",\"3\":\"961000\"},{\"1\":\"2012\",\"2\":\"148100\",\"3\":\"784700\"},{\"1\":\"2015\",\"2\":\"47300\",\"3\":\"758700\"},{\"1\":\"2002\",\"2\":\"45900\",\"3\":\"646400\"},{\"1\":\"2010\",\"2\":\"44500\",\"3\":\"302300\"},{\"1\":\"2013\",\"2\":\"54500\",\"3\":\"289900\"},{\"1\":\"2020\",\"2\":\"24000\",\"3\":\"272700\"},{\"1\":\"2014\",\"2\":\"34300\",\"3\":\"256300\"},{\"1\":\"2009\",\"2\":\"12500\",\"3\":\"124100\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\nLet's also visualize this. First, we'll look at the change in workers on strike each year over time.\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(strike_yr_sum,aes(x=Year, y=Workers,fill=Ownership)) +\n  geom_area() +\n  labs(title=\"Change in number of striking workers by year\",subtitle=\"1993 - 2023\",x=\"Year\",y=\"Workers\") +\n  scale_x_continuous(breaks = seq(1993,2023,by=3),\n                     minor_breaks = seq(1993, 2023, by = 1)) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](dannyholt_hw3_new_files/figure-html/unnamed-chunk-23-1.png){width=672}\n:::\n:::\n\n\nNow, we'll take a look at the change in days struck by year.\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(strike_yr_sum,aes(x=Year, y=`Days Struck`, fill=Ownership)) +\n  geom_area() +\n  labs(title=\"Change in number of days struck by year\",subtitle=\"1993 - 2023\",x=\"Year\",y=\"Days struck\") +\n  scale_x_continuous(breaks = seq(1993,2023,by=3),\n                     minor_breaks = seq(1993, 2023, by = 1)) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](dannyholt_hw3_new_files/figure-html/unnamed-chunk-24-1.png){width=672}\n:::\n:::\n\n\nIn both graphs, we see relatively significant activity through the 1990s, until a sharp drop in 1999, followed by a large spike in 2000. Note that the 2000 spike is particularly massive in the `Days struck` visualization, suggesting the presence of many very long strikes in that year.\n\nAfter 2000, we see a period of decline with relatively little activity through the mid-2010s. Then, however, we find the largest spike in the `Workers` graph in 2018 and 2019, with a large but not quite as significant spike at that time in the `Days struck` graph, suggesting the presence of very many relatively short strikes in these years. From there, we see a sharp drop in 2020—likely the result of the COVID-19 pandemic—followed by rises in the years after.\n\n#### Highlight: 2000\nTo reiterate, 2000 features high in these views. Let's go back to the un-condensed data and filter to strikes in 2000 with more than 5000 workers, sorted from most to least workers involved, to look at the most significant contributors.\n\n::: {.cell}\n\n```{.r .cell-code}\n# create new data frame\nstrike00 <- strike\n\n# change date to year\nstrike00$\"Start date\" <- as.numeric(format(strike00$\"Start date\", \"%Y\"))\nstrike00 <- strike00 %>%\n  rename(\"Year\" = \"Start date\") %>%\n    \n# filter to 2000, large strikes\n  filter(Year==2000,Workers>5000) %>%\n  select(Union,Employer,States,Areas,Workers,\"Days struck\")\nstrike00workers <- arrange(strike00, desc(Workers))\n\n# view data\nstrike00workers\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"Union\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Employer\"],\"name\":[2],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"States\"],\"name\":[3],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Areas\"],\"name\":[4],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Workers\"],\"name\":[5],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Days struck\"],\"name\":[6],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"AFTRA, SAG\",\"2\":\"Association of National Advertisers; American Association of Advertising Agencies\",\"3\":\"AR, MA, IL, OH, TX, CO, NV, NM, UT, MI, FL, GA, HI, MN, MO, TN, NC, PA, OR, CA, WA, DC, MD\",\"4\":\"Multiple states\",\"5\":\"135000\",\"6\":\"17280000\"},{\"1\":\"CWA, IBEW\",\"2\":\"Verizon Communications\",\"3\":\"ME, NH, VT, MA, RI, NY, NJ, DE, PA, MD, VA, WV, DC\",\"4\":\"Multiple states\",\"5\":\"85000\",\"6\":\"955000\"},{\"1\":\"SEIU\",\"2\":\"Los Angeles County\",\"3\":\"CA\",\"4\":\"Los Angeles County\",\"5\":\"47000\",\"6\":\"47000\"},{\"1\":\"SPEEA\",\"2\":\"Boeing Company\",\"3\":\"WA, OR, KS\",\"4\":\"Multiple states\",\"5\":\"17000\",\"6\":\"459000\"},{\"1\":\"SEIU\",\"2\":\"Los Angeles janitorial maintenance contractors\",\"3\":\"CA\",\"4\":\"Los Angeles County\",\"5\":\"8500\",\"6\":\"103800\"},{\"1\":\"UTU\",\"2\":\"Los Angeles County Metropolitan Transportation Authority\",\"3\":\"CA\",\"4\":\"Los Angeles County\",\"5\":\"7400\",\"6\":\"148000\"},{\"1\":\"SEIU\",\"2\":\"Hospitals - 18\",\"3\":\"CA\",\"4\":\"Statewide\",\"5\":\"6000\",\"6\":\"6000\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\nBy far the largest strike in 2000, we see, was the commercial actors strike by the Screen Actors Guild (SAG) and the American Federation of Television and Radio Artists (AFTRA) against the American Association of Advertising Agencies, across most of the country.\n\nThe next largest strike in 2000 was by the Communication Workers of America (CWA) and the International Brotherhood of Electrical Workers (IBEW) against Verizon in the Northeast and Mid-Atlantic regions of the U.S.\n\n#### Highlight: 2018 - 2019\nLet's do the same thing we did for 2000 with 2018 and 2019.\n\n::: {.cell}\n\n```{.r .cell-code}\n# create new data frame\nstrike1819 <- strike\n\n# change date to year\nstrike1819$\"Start date\" <- as.numeric(format(strike1819$\"Start date\", \"%Y\"))\nstrike1819 <- strike1819 %>%\n  rename(\"Year\" = \"Start date\") %>%\n    \n# filter to 2018, large strikes\n  filter(Year==2018 | Year==2019,Workers>5000) %>%\n  select(Union,Employer,States,Areas,Workers,\"Days struck\")\nstrike1819workers <- arrange(strike1819, desc(Workers))\n\n# view data\nstrike1819workers\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"Union\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Employer\"],\"name\":[2],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"States\"],\"name\":[3],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Areas\"],\"name\":[4],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Workers\"],\"name\":[5],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Days struck\"],\"name\":[6],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"NA\",\"2\":\"North Carolina State Legislature\",\"3\":\"NC\",\"4\":\"Statewide\",\"5\":\"123000\",\"6\":\"123000\"},{\"1\":\"NA\",\"2\":\"North Carolina State Legislature\",\"3\":\"NC\",\"4\":\"Statewide\",\"5\":\"92700\",\"6\":\"92700\"},{\"1\":\"NA\",\"2\":\"Arizona State Legislature\",\"3\":\"AZ\",\"4\":\"Statewide\",\"5\":\"81000\",\"6\":\"486000\"},{\"1\":\"NA\",\"2\":\"Colorado State Legislature\",\"3\":\"CO\",\"4\":\"Statewide\",\"5\":\"63000\",\"6\":\"126000\"},{\"1\":\"AFSCME, CNA, UPTE\",\"2\":\"University of California Medical Centers\",\"3\":\"CA\",\"4\":\"Statewide\",\"5\":\"53000\",\"6\":\"159000\"},{\"1\":\"UAW\",\"2\":\"General Motors\",\"3\":\"MI\",\"4\":\"Statewide\",\"5\":\"46000\",\"6\":\"1334000\"},{\"1\":\"NA\",\"2\":\"Oklahoma State Legislature\",\"3\":\"OK\",\"4\":\"Statewide\",\"5\":\"45000\",\"6\":\"405000\"},{\"1\":\"NA\",\"2\":\"West Virginia Legislature\",\"3\":\"WV\",\"4\":\"Statewide\",\"5\":\"36400\",\"6\":\"72800\"},{\"1\":\"WVEA\",\"2\":\"West Virginia Legislature\",\"3\":\"WV\",\"4\":\"Statewide\",\"5\":\"35000\",\"6\":\"318600\"},{\"1\":\"NA\",\"2\":\"Los Angeles Unified School District\",\"3\":\"CA\",\"4\":\"Los Angeles\",\"5\":\"33000\",\"6\":\"198000\"},{\"1\":\"CTU, SEIU\",\"2\":\"Chicago Public Schools\",\"3\":\"IL\",\"4\":\"Chicago\",\"5\":\"32000\",\"6\":\"352000\"},{\"1\":\"UFCW\",\"2\":\"Stop & Shop Supermarket Co.\",\"3\":\"CT, RI, MA\",\"4\":\"Statewide\",\"5\":\"31000\",\"6\":\"217000\"},{\"1\":\"NA\",\"2\":\"Kentucky State Legislature\",\"3\":\"KY\",\"4\":\"Statewide\",\"5\":\"26000\",\"6\":\"52000\"},{\"1\":\"AFSCME\",\"2\":\"University of California Medical Centers\",\"3\":\"CA\",\"4\":\"Statewide\",\"5\":\"25000\",\"6\":\"75000\"},{\"1\":\"NA\",\"2\":\"Kentucky State Legislature\",\"3\":\"KY\",\"4\":\"Statewide\",\"5\":\"22900\",\"6\":\"39500\"},{\"1\":\"NA\",\"2\":\"Oregon State Legislature\",\"3\":\"OR\",\"4\":\"Statewide\",\"5\":\"20400\",\"6\":\"20400\"},{\"1\":\"NA\",\"2\":\"AT&T Inc.\",\"3\":\"AL, FL, GA, KY, LA, MS, NC, SC, TN\",\"4\":\"Statewide\",\"5\":\"20000\",\"6\":\"40000\"},{\"1\":\"NA\",\"2\":\"South Carolina State Legislature\",\"3\":\"SC\",\"4\":\"Statewide\",\"5\":\"18900\",\"6\":\"18900\"},{\"1\":\"AFSCME\",\"2\":\"University of California Medical Centers\",\"3\":\"CA\",\"4\":\"NA\",\"5\":\"15000\",\"6\":\"45000\"},{\"1\":\"UPTE-CWA\",\"2\":\"University of California Medical Centers\",\"3\":\"CA\",\"4\":\"Statewide\",\"5\":\"14000\",\"6\":\"14000\"},{\"1\":\"CWA\",\"2\":\"AT&T Inc.\",\"3\":\"IL, IN, MI, OH, WI\",\"4\":\"NA\",\"5\":\"9700\",\"6\":\"29100\"},{\"1\":\"NA\",\"2\":\"Marriott Corporation\",\"3\":\"CA, HI, MA, MI\",\"4\":\"NA\",\"5\":\"6000\",\"6\":\"215900\"},{\"1\":\"NA\",\"2\":\"Chicago Downtown Hotels\",\"3\":\"IL\",\"4\":\"Chicago\",\"5\":\"5500\",\"6\":\"91000\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\nWe see that many of the largest strikes in 2018 and 2019 were against state legislatures—particularly those of North Carolina, Arizona, Colorado, Oklahoma, West Virginia, Kentucky, Oregon, and South Carolina. These strikes, along with the strike against the Los Angeles Unified School District, made up the “#RedForEd” wave of teacher strikes in these years, named for the social media hashtag that accompanied it, referring to the red shirts striking teachers wore.\n\n### Changes in individual strike magnitude\nLet's look at the data in un-grouped form create a scatter lot of number of workers in strikes by start date.\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(strike, aes(x=as.Date(`Start date`))) +\n  geom_point(aes(y=Workers),color=\"red\") +\n  scale_x_date(limits = as.Date(c(\"1993-01-01\", \"2023-01-01\"))) +\n  labs(title=\"Change in size of individual strikes by number of workers\",subtitle=\"1993 - 2023\",x=\"Year\",y=\"Workers\")\n```\n\n::: {.cell-output-display}\n![](dannyholt_hw3_new_files/figure-html/unnamed-chunk-27-1.png){width=672}\n:::\n:::\n\n\nThere is not much of a visible trend, though mid-size to large strikes do seem more concentrated before the early 2000s compared with after.\n\n### Private vs. public sector\nHow have strikes changed in size within the private sector and within the public sector (state government and local government), viewed separately? Let's look at the same data as above but faceted by ownership type.\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(strike_own, aes(x=as.Date(`Start date`))) +\n  geom_point(aes(y=Workers),color=\"red\") +\n  scale_x_date(limits = as.Date(c(\"1993-01-01\", \"2023-01-01\"))) +\n  facet_wrap(vars(Ownership)) +\n  labs(title=\"Change in size of individual strikes by number of workers\",subtitle=\"Separated by employer ownership type; 1993 - 2023\",x=\"Year\",y=\"Workers\")\n```\n\n::: {.cell-output-display}\n![](dannyholt_hw3_new_files/figure-html/unnamed-chunk-28-1.png){width=672}\n:::\n:::\n\n\nThere appears to be a decrease in larger strikes in the private sector in the late 2000s, along with a sharp increase in larger strikes in state government in the late 2010s.",
    "supporting": [
      "dannyholt_hw3_new_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\n<script src=\"../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}