{
  "hash": "8575be9719de3b42ad68774c257c9b54",
  "result": {
    "markdown": "---\ntitle: \"Challenge 1 Solutions\"\nauthor: \"Lakshmi Deepthi Kurugundla\"\ndescription: \"Reading in data and creating a post\"\ndate: \"5/30/2023\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - challenge_1\n  - railroads\n  - faostat\n  - wildbirds\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n\nknitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)\n```\n:::\n\n\n## Challenge Overview\n\nToday's challenge is to\n\n1)  read in a dataset, and\n\n2)  describe the dataset using both words and any supporting information (e.g., tables, etc)\n\n## Read in the Data\n\nRead in one (or more) of the following data sets, using the correct R package and command.\n\n-   railroad_2012_clean_county.csv ⭐\n-   birds.csv ⭐⭐\n-   FAOstat\\*.csv ⭐⭐\n-   wild_bird_data.xlsx ⭐⭐⭐\n-   StateCounty2012.xls ⭐⭐⭐⭐\n\nFind the `_data` folder, located inside the `posts` folder. Then you can read in the data, using either one of the `readr` standard tidy read commands, or a specialized package such as `readxl`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlist.files(\"_data\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n [1] \"AB_NYC_2019.csv\"                                                                                 \n [2] \"abc_poll_2021.csv\"                                                                               \n [3] \"ActiveDuty_MaritalStatus.xls\"                                                                    \n [4] \"animal_weight.csv\"                                                                               \n [5] \"australian_marriage_law_postal_survey_2017_-_response_final.xls\"                                 \n [6] \"australian_marriage_tidy.csv\"                                                                    \n [7] \"birds.csv\"                                                                                       \n [8] \"cereal.csv\"                                                                                      \n [9] \"cwc.csv\"                                                                                         \n[10] \"Data_Extract_From_World_Development_Indicators.xlsx\"                                             \n[11] \"Data_Extract_FromWorld Development Indicators.xlsx\"                                              \n[12] \"debt_in_trillions.xlsx\"                                                                          \n[13] \"eggs_tidy.csv\"                                                                                   \n[14] \"FAOSTAT_cattle_dairy.csv\"                                                                        \n[15] \"FAOSTAT_country_groups.csv\"                                                                      \n[16] \"FAOSTAT_egg_chicken.csv\"                                                                         \n[17] \"FAOSTAT_livestock.csv\"                                                                           \n[18] \"FedFundsRate.csv\"                                                                                \n[19] \"FRBNY-SCE-Public-Microdata-Complete-13-16.xlsx\"                                                  \n[20] \"hotel_bookings.csv\"                                                                              \n[21] \"organiceggpoultry.xls\"                                                                           \n[22] \"poultry_tidy.csv\"                                                                                \n[23] \"poultry_tidy.RData\"                                                                              \n[24] \"poultry_tidy.xlsx\"                                                                               \n[25] \"Public_School_Characteristics_2017-18.csv\"                                                       \n[26] \"railroad_2012_clean_county.csv\"                                                                  \n[27] \"sce-labor-chart-data-public.xlsx\"                                                                \n[28] \"snl_actors.csv\"                                                                                  \n[29] \"snl_casts.csv\"                                                                                   \n[30] \"snl_seasons.csv\"                                                                                 \n[31] \"starwars1.RData\"                                                                                 \n[32] \"StateCounty2012.xls\"                                                                             \n[33] \"test_objs.RData\"                                                                                 \n[34] \"Total_cost_for_top_15_pathogens_2018.xlsx\"                                                       \n[35] \"USA Households by Total Money Income, Race, and Hispanic Origin of Householder 1967 to 2019.xlsx\"\n[36] \"wild_bird_data.xlsx\"                                                                             \n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nrailroad_csv <- read_csv(\"_data/railroad_2012_clean_county.csv\") \nbirds_from_csv <- read_csv(\"_data/birds.csv\")\nrailroad_csv \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2,930 × 3\n   state county               total_employees\n   <chr> <chr>                          <dbl>\n 1 AE    APO                                2\n 2 AK    ANCHORAGE                          7\n 3 AK    FAIRBANKS NORTH STAR               2\n 4 AK    JUNEAU                             3\n 5 AK    MATANUSKA-SUSITNA                  2\n 6 AK    SITKA                              1\n 7 AK    SKAGWAY MUNICIPALITY              88\n 8 AL    AUTAUGA                          102\n 9 AL    BALDWIN                          143\n10 AL    BARBOUR                            1\n# ℹ 2,920 more rows\n```\n:::\n\n```{.r .cell-code}\nbirds_from_csv\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 30,977 × 14\n   `Domain Code` Domain     `Area Code` Area  `Element Code` Element `Item Code`\n   <chr>         <chr>            <dbl> <chr>          <dbl> <chr>         <dbl>\n 1 QA            Live Anim…           2 Afgh…           5112 Stocks         1057\n 2 QA            Live Anim…           2 Afgh…           5112 Stocks         1057\n 3 QA            Live Anim…           2 Afgh…           5112 Stocks         1057\n 4 QA            Live Anim…           2 Afgh…           5112 Stocks         1057\n 5 QA            Live Anim…           2 Afgh…           5112 Stocks         1057\n 6 QA            Live Anim…           2 Afgh…           5112 Stocks         1057\n 7 QA            Live Anim…           2 Afgh…           5112 Stocks         1057\n 8 QA            Live Anim…           2 Afgh…           5112 Stocks         1057\n 9 QA            Live Anim…           2 Afgh…           5112 Stocks         1057\n10 QA            Live Anim…           2 Afgh…           5112 Stocks         1057\n# ℹ 30,967 more rows\n# ℹ 7 more variables: Item <chr>, `Year Code` <dbl>, Year <dbl>, Unit <chr>,\n#   Value <dbl>, Flag <chr>, `Flag Description` <chr>\n```\n:::\n:::\n\n\nAdd any comments or documentation as needed. More challenging data sets may require additional code chunks and documentation.\n\n## Describe the data\n\nUsing a combination of words and results of R commands, can you provide a high level description of the data? Describe as efficiently as possible where/how the data was (likely) gathered, indicate the cases and variables (both the interpretation and any details you deem useful to the reader to fully understand your chosen data).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(railroad_csv) \n```\n\n::: {.cell-output .cell-output-stdout}\n```\nRows: 2,930\nColumns: 3\n$ state           <chr> \"AE\", \"AK\", \"AK\", \"AK\", \"AK\", \"AK\", \"AK\", \"AL\", \"AL\", …\n$ county          <chr> \"APO\", \"ANCHORAGE\", \"FAIRBANKS NORTH STAR\", \"JUNEAU\", …\n$ total_employees <dbl> 2, 7, 2, 3, 2, 1, 88, 102, 143, 1, 25, 154, 13, 29, 45…\n```\n:::\n\n```{.r .cell-code}\nspec(railroad_csv)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\ncols(\n  state = col_character(),\n  county = col_character(),\n  total_employees = col_double()\n)\n```\n:::\n\n```{.r .cell-code}\ntypeof(railroad_csv$state)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"character\"\n```\n:::\n\n```{.r .cell-code}\ntypeof(railroad_csv$county)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"character\"\n```\n:::\n\n```{.r .cell-code}\ntypeof(railroad_csv$total_employees)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"double\"\n```\n:::\n:::\n\nIn the railroad_2012_clean_county dataset we have 2930 rows and 3 columns(state, county and total_employees). With the data given in this dataset we can only know about the total number of employees in  a county is and what state that county belongs to. And the types of the variables state, county and total_employees are character, character and double.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(birds_from_csv) \n```\n\n::: {.cell-output .cell-output-stdout}\n```\nRows: 30,977\nColumns: 14\n$ `Domain Code`      <chr> \"QA\", \"QA\", \"QA\", \"QA\", \"QA\", \"QA\", \"QA\", \"QA\", \"QA…\n$ Domain             <chr> \"Live Animals\", \"Live Animals\", \"Live Animals\", \"Li…\n$ `Area Code`        <dbl> 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, …\n$ Area               <chr> \"Afghanistan\", \"Afghanistan\", \"Afghanistan\", \"Afgha…\n$ `Element Code`     <dbl> 5112, 5112, 5112, 5112, 5112, 5112, 5112, 5112, 511…\n$ Element            <chr> \"Stocks\", \"Stocks\", \"Stocks\", \"Stocks\", \"Stocks\", \"…\n$ `Item Code`        <dbl> 1057, 1057, 1057, 1057, 1057, 1057, 1057, 1057, 105…\n$ Item               <chr> \"Chickens\", \"Chickens\", \"Chickens\", \"Chickens\", \"Ch…\n$ `Year Code`        <dbl> 1961, 1962, 1963, 1964, 1965, 1966, 1967, 1968, 196…\n$ Year               <dbl> 1961, 1962, 1963, 1964, 1965, 1966, 1967, 1968, 196…\n$ Unit               <chr> \"1000 Head\", \"1000 Head\", \"1000 Head\", \"1000 Head\",…\n$ Value              <dbl> 4700, 4900, 5000, 5300, 5500, 5800, 6600, 6290, 630…\n$ Flag               <chr> \"F\", \"F\", \"F\", \"F\", \"F\", \"F\", \"F\", NA, \"F\", \"F\", \"F…\n$ `Flag Description` <chr> \"FAO estimate\", \"FAO estimate\", \"FAO estimate\", \"FA…\n```\n:::\n\n```{.r .cell-code}\nspec(birds_from_csv) # To check data types of columns \n```\n\n::: {.cell-output .cell-output-stdout}\n```\ncols(\n  `Domain Code` = col_character(),\n  Domain = col_character(),\n  `Area Code` = col_double(),\n  Area = col_character(),\n  `Element Code` = col_double(),\n  Element = col_character(),\n  `Item Code` = col_double(),\n  Item = col_character(),\n  `Year Code` = col_double(),\n  Year = col_double(),\n  Unit = col_character(),\n  Value = col_double(),\n  Flag = col_character(),\n  `Flag Description` = col_character()\n)\n```\n:::\n\n```{.r .cell-code}\ntypeof(birds_from_csv$'Domain Code') \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"character\"\n```\n:::\n\n```{.r .cell-code}\ntypeof(birds_from_csv$Domain) \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"character\"\n```\n:::\n\n```{.r .cell-code}\ntypeof(birds_from_csv$'Area Code') \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"double\"\n```\n:::\n\n```{.r .cell-code}\ntypeof(birds_from_csv$Area) \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"character\"\n```\n:::\n\n```{.r .cell-code}\ntypeof(birds_from_csv$'Element Code') \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"double\"\n```\n:::\n\n```{.r .cell-code}\ntypeof(birds_from_csv$Element) \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"character\"\n```\n:::\n\n```{.r .cell-code}\ntypeof(birds_from_csv$'Item Code') \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"double\"\n```\n:::\n\n```{.r .cell-code}\ntypeof(birds_from_csv$Item) \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"character\"\n```\n:::\n\n```{.r .cell-code}\ntypeof(birds_from_csv$'Year Code') \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"double\"\n```\n:::\n\n```{.r .cell-code}\ntypeof(birds_from_csv$Year) \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"double\"\n```\n:::\n\n```{.r .cell-code}\ntypeof(birds_from_csv$Unit) \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"character\"\n```\n:::\n\n```{.r .cell-code}\ntypeof(birds_from_csv$Value) \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"double\"\n```\n:::\n\n```{.r .cell-code}\ntypeof(birds_from_csv$Flag) \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"character\"\n```\n:::\n\n```{.r .cell-code}\ntypeof(birds_from_csv$'Flag Description')\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"character\"\n```\n:::\n:::\n\nIn the birds dataset we have 30977 rows and 14 columns(Domain, Area, Element, Year etc). \nIn this dataset , the data is recorded form 1961 - 2018 , about the region(Area) and different types of birds(like chicken and duck) in that region and information about birds like count(Unit), Value and flag. This information is liekly gathered to know the inforamtion of number of birds in each area for every year from 1961 to 2018 or it may also be the information of buying live animals(birds) every year from each area. ",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}