{
  "hash": "20beebcb9b56dcc5d203e6f1bc2f0e3e",
  "result": {
    "markdown": "---\ntitle: \"Challenge 2 - Hotel Bookings\"\nauthor: \"Srujan Kagitala\"\ndescription: \"Data wrangling: using group() and summarise()\"\ndate: \"6/26/2023\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - challenge_2\n  - hotel_bookings\n  - srujan_kagitala\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n\nknitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)\n```\n:::\n\n\n## Challenge Overview\n\nToday's challenge is to\n\n1)  read in a data set, and describe the data using both words and any supporting information (e.g., tables, etc)\n2)  provide summary statistics for different interesting groups within the data, and interpret those statistics\n\n## Read in the Data\n\nRead in one (or more) of the following data sets, available in the `posts/_data` folder, using the correct R package and command.\n\n-   hotel_bookings.csv ⭐⭐⭐⭐\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbooking_data <- read.csv(\"_data/hotel_bookings.csv\")\nhead(booking_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n         hotel is_canceled lead_time arrival_date_year arrival_date_month\n1 Resort Hotel           0       342              2015               July\n2 Resort Hotel           0       737              2015               July\n3 Resort Hotel           0         7              2015               July\n4 Resort Hotel           0        13              2015               July\n5 Resort Hotel           0        14              2015               July\n6 Resort Hotel           0        14              2015               July\n  arrival_date_week_number arrival_date_day_of_month stays_in_weekend_nights\n1                       27                         1                       0\n2                       27                         1                       0\n3                       27                         1                       0\n4                       27                         1                       0\n5                       27                         1                       0\n6                       27                         1                       0\n  stays_in_week_nights adults children babies meal country market_segment\n1                    0      2        0      0   BB     PRT         Direct\n2                    0      2        0      0   BB     PRT         Direct\n3                    1      1        0      0   BB     GBR         Direct\n4                    1      1        0      0   BB     GBR      Corporate\n5                    2      2        0      0   BB     GBR      Online TA\n6                    2      2        0      0   BB     GBR      Online TA\n  distribution_channel is_repeated_guest previous_cancellations\n1               Direct                 0                      0\n2               Direct                 0                      0\n3               Direct                 0                      0\n4            Corporate                 0                      0\n5                TA/TO                 0                      0\n6                TA/TO                 0                      0\n  previous_bookings_not_canceled reserved_room_type assigned_room_type\n1                              0                  C                  C\n2                              0                  C                  C\n3                              0                  A                  C\n4                              0                  A                  A\n5                              0                  A                  A\n6                              0                  A                  A\n  booking_changes deposit_type agent company days_in_waiting_list customer_type\n1               3   No Deposit  NULL    NULL                    0     Transient\n2               4   No Deposit  NULL    NULL                    0     Transient\n3               0   No Deposit  NULL    NULL                    0     Transient\n4               0   No Deposit   304    NULL                    0     Transient\n5               0   No Deposit   240    NULL                    0     Transient\n6               0   No Deposit   240    NULL                    0     Transient\n  adr required_car_parking_spaces total_of_special_requests reservation_status\n1   0                           0                         0          Check-Out\n2   0                           0                         0          Check-Out\n3  75                           0                         0          Check-Out\n4  75                           0                         0          Check-Out\n5  98                           0                         1          Check-Out\n6  98                           0                         1          Check-Out\n  reservation_status_date\n1              2015-07-01\n2              2015-07-01\n3              2015-07-02\n4              2015-07-02\n5              2015-07-03\n6              2015-07-03\n```\n:::\n:::\n\n\nAdd any comments or documentation as needed. More challenging data may require additional code chunks and documentation.\n\n## Describe the data\n\nUsing a combination of words and results of R commands, can you provide a high level description of the data? Describe as efficiently as possible where/how the data was (likely) gathered, indicate the cases and variables (both the interpretation and any details you deem useful to the reader to fully understand your chosen data).\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Number of bookings per hotel.\nno_bookings_by_hotel <- booking_data %>%\n  group_by(hotel) %>%\n  summarise(count = n())\n```\n:::\n\n\nThis data set contains booking data of City Hotel, Resort Hotel. It contains 119390 bookings information. 79330 and 40060 observations are respectively captured from City Hotel and Resort Hotel. The information available per booking are hotel, is_canceled, lead_time, arrival_date_year, arrival_date_month, arrival_date_week_number, arrival_date_day_of_month, stays_in_weekend_nights, stays_in_week_nights, adults, children, babies, meal, country, market_segment, distribution_channel, is_repeated_guest, previous_cancellations, previous_bookings_not_canceled, reserved_room_type, assigned_room_type, booking_changes, deposit_type, agent, company, days_in_waiting_list, customer_type, adr, required_car_parking_spaces, total_of_special_requests, reservation_status, reservation_status_date.\n\n## Provide Grouped Summary Statistics\n\nConduct some exploratory data analysis, using dplyr commands such as `group_by()`, `select()`, `filter()`, and `summarise()`. Find the central tendency (mean, median, mode) and dispersion (standard deviation, mix/max/quantile) for different subgroups within the data set.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Number of bookings cancelled versus not cancelled \n# per hotel across years \n(hotel_booking_by_year <- booking_data %>%\n  group_by(hotel, arrival_date_year, is_canceled) %>%\n  summarise(no_bookings = n()))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 12 × 4\n# Groups:   hotel, arrival_date_year [6]\n   hotel        arrival_date_year is_canceled no_bookings\n   <chr>                    <int>       <int>       <int>\n 1 City Hotel                2015           0        7678\n 2 City Hotel                2015           1        6004\n 3 City Hotel                2016           0       22733\n 4 City Hotel                2016           1       15407\n 5 City Hotel                2017           0       15817\n 6 City Hotel                2017           1       11691\n 7 Resort Hotel              2015           0        6176\n 8 Resort Hotel              2015           1        2138\n 9 Resort Hotel              2016           0       13637\n10 Resort Hotel              2016           1        4930\n11 Resort Hotel              2017           0        9125\n12 Resort Hotel              2017           1        4054\n```\n:::\n\n```{.r .cell-code}\ntotal_hotel_bookings_by_year <- hotel_booking_by_year %>%\n  group_by(hotel, arrival_date_year) %>%\n  summarise(no_bookings = sum(no_bookings))\n\nggplot(data = total_hotel_bookings_by_year, aes(x= arrival_date_year, y=no_bookings)) +\n  geom_bar(stat = \"identity\", mapping = aes(fill = hotel), position = \"dodge\") +\n  ggtitle(\"Total bookings across hotels\") +\n  ylab(\"bookings\") +\n  xlab(\"year\")\n```\n\n::: {.cell-output-display}\n![](challenge2_srujankagitala_files/figure-html/analysis-1.png){width=672}\n:::\n\n```{.r .cell-code}\ncancelled_bookings_by_year <- hotel_booking_by_year %>% \n  filter(is_canceled == 1) %>%\n  select(hotel, arrival_date_year, no_bookings)\n\nggplot(data = cancelled_bookings_by_year, aes(x= arrival_date_year, y=no_bookings)) +\n  geom_bar(stat = \"identity\", mapping = aes(fill = hotel), position = \"dodge\") +\n  ggtitle(\"Cancelled bookings across hotels\") +\n  ylab(\"bookings\") +\n  xlab(\"year\")\n```\n\n::: {.cell-output-display}\n![](challenge2_srujankagitala_files/figure-html/analysis-2.png){width=672}\n:::\n\n```{.r .cell-code}\nnot_cancelled_bookings_by_year <- hotel_booking_by_year %>% \n  filter(is_canceled == 0) %>%\n  select(hotel, arrival_date_year, no_bookings)\n\nggplot(data = not_cancelled_bookings_by_year, aes(x= arrival_date_year, y=no_bookings)) +\n  geom_bar(stat = \"identity\", mapping = aes(fill = hotel), position = \"dodge\") +\n  ggtitle(\"Active bookings across hotels\") +\n  ylab(\"bookings\") +\n  xlab(\"year\")\n```\n\n::: {.cell-output-display}\n![](challenge2_srujankagitala_files/figure-html/analysis-3.png){width=672}\n:::\n\n```{.r .cell-code}\n# Total number of bookings that are not cancelled per hotel\n(actual_hotel_booking <- hotel_booking_by_year %>%\n  filter(is_canceled == 0) %>%\n  group_by(hotel) %>%\n  summarise(no_bookings = sum(no_bookings)))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2 × 2\n  hotel        no_bookings\n  <chr>              <int>\n1 City Hotel         46228\n2 Resort Hotel       28938\n```\n:::\n\n```{.r .cell-code}\n# Mean, median and standard deviation of night stays\n# during the week and weekends per hotel\n(stay_pattern <- booking_data %>% \n  group_by(hotel) %>%\n  summarise(mean_stay_week_nights = mean(stays_in_week_nights),\n            median_stay_week_nights = median(stays_in_week_nights),\n            sd_stay_week_nights = sd(stays_in_week_nights),\n            mean_stay_weekend_nights = mean(stays_in_weekend_nights),\n            median_stay_weekend_nights = median(stays_in_weekend_nights),\n            sd_stay_weekend_nights = sd(stays_in_weekend_nights)))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2 × 7\n  hotel        mean_stay_week_nights median_stay_week_nights sd_stay_week_nights\n  <chr>                        <dbl>                   <dbl>               <dbl>\n1 City Hotel                    2.18                       2                1.46\n2 Resort Hotel                  3.13                       3                2.46\n# ℹ 3 more variables: mean_stay_weekend_nights <dbl>,\n#   median_stay_weekend_nights <dbl>, sd_stay_weekend_nights <dbl>\n```\n:::\n\n```{.r .cell-code}\n# Number of repeated guests who didn't cancel per hotel.\n(repeated_guests <- booking_data %>%\n  filter(is_repeated_guest == 1, is_canceled == 0) %>%\n  group_by(hotel) %>%\n  summarise(count = n()))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2 × 2\n  hotel        count\n  <chr>        <int>\n1 City Hotel    1591\n2 Resort Hotel  1667\n```\n:::\n:::\n\n\n### Explain and Interpret\n\nBe sure to explain why you choose a specific group. Comment on the interpretation of any interesting differences between groups that you uncover. This section can be integrated with the exploratory data analysis, just be sure it is included.\n\nCompared the number of booking across hotels on a yearly basis and tried to observe the retention rate among customers.We can see that in the period of 3 years, City Hotel has 46228 bookings that aren't cancelled whereas Resort Hotel has 28938. Out of these, 3.4416371% and 5.7605916% are repeated bookings for City Hotel and Resort Hotel respectively. Although the number of bookings for City Hotel were higher, Resort Hotel has a  better customer retention rate compared to City Hotel.",
    "supporting": [
      "challenge2_srujankagitala_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}