{
  "hash": "2b53770e03117d522174c96bcedfe51b",
  "result": {
    "markdown": "---\ntitle: \"Challenge 3 Submission\"\nauthor: \"Xinpeng Liu\"\ndescription: \"Tidy Data: Pivoting\"\ndate: \"5/30/2023\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - challenge_3\n  - animal_weights\n  - eggs\n  - australian_marriage\n  - usa_households\n  - sce_labor\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n\nknitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)\n```\n:::\n\n\n## Challenge Overview\n\nToday's challenge is to:\n\n1.  read in a data set, and describe the data set using both words and any supporting information (e.g., tables, etc)\n2.  identify what needs to be done to tidy the current data\n3.  anticipate the shape of pivoted data\n4.  pivot the data into tidy format using `pivot_longer`\n\n## Read in data\n\nRead in one (or more) of the following datasets, using the correct R package and command.\n\n-   animal_weights.csv ⭐\n-   eggs_tidy.csv ⭐⭐ or organiceggpoultry.xls ⭐⭐⭐\n-   australian_marriage\\*.xls ⭐⭐⭐\n-   USA Households\\*.xlsx ⭐⭐⭐⭐\n-   sce_labor_chart_data_public.xlsx 🌟🌟🌟🌟🌟\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata<- read_csv(\"_data/animal_weight.csv\")\n```\n:::\n\n\n### Briefly describe the data\n\nDescribe the data, and be sure to comment on why you are planning to pivot it to make it \"tidy\"\n\nwe choose -   animal_weights.csv ⭐\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(data)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nRows: 9\nColumns: 17\n$ `IPCC Area`          <chr> \"Indian Subcontinent\", \"Eastern Europe\", \"Africa\"…\n$ `Cattle - dairy`     <dbl> 275, 550, 275, 500, 600, 400, 350, 275, 604\n$ `Cattle - non-dairy` <dbl> 110, 391, 173, 330, 420, 305, 391, 173, 389\n$ Buffaloes            <dbl> 295, 380, 380, 380, 380, 380, 380, 380, 380\n$ `Swine - market`     <dbl> 28, 50, 28, 45, 50, 28, 50, 28, 46\n$ `Swine - breeding`   <dbl> 28, 180, 28, 180, 198, 28, 180, 28, 198\n$ `Chicken - Broilers` <dbl> 0.9, 0.9, 0.9, 0.9, 0.9, 0.9, 0.9, 0.9, 0.9\n$ `Chicken - Layers`   <dbl> 1.8, 1.8, 1.8, 1.8, 1.8, 1.8, 1.8, 1.8, 1.8\n$ Ducks                <dbl> 2.7, 2.7, 2.7, 2.7, 2.7, 2.7, 2.7, 2.7, 2.7\n$ Turkeys              <dbl> 6.8, 6.8, 6.8, 6.8, 6.8, 6.8, 6.8, 6.8, 6.8\n$ Sheep                <dbl> 28.0, 48.5, 28.0, 48.5, 48.5, 28.0, 48.5, 28.0, 4…\n$ Goats                <dbl> 30.0, 38.5, 30.0, 38.5, 38.5, 30.0, 38.5, 30.0, 3…\n$ Horses               <dbl> 238, 377, 238, 377, 377, 238, 377, 238, 377\n$ Asses                <dbl> 130, 130, 130, 130, 130, 130, 130, 130, 130\n$ Mules                <dbl> 130, 130, 130, 130, 130, 130, 130, 130, 130\n$ Camels               <dbl> 217, 217, 217, 217, 217, 217, 217, 217, 217\n$ Llamas               <dbl> 217, 217, 217, 217, 217, 217, 217, 217, 217\n```\n:::\n:::\n\n\nwe would have three columns: 'IPCC Area', 'Animal Type', and 'Average Weight'. Each row would then represent the average weight of a particular type of animal in a specific region. For example, one row might be 'Eastern Europe', 'Cattle - dairy', '550'.\n\nPivoting the data in this way makes it \"tidy\" as per Hadley Wickham's principles:\n\nEach variable forms a column.\nEach observation forms a row.\nEach type of observational unit forms a table.\n\n\n## Anticipate the End Result\n\n::: {.cell}\n\n```{.r .cell-code}\n#existing rows/cases\nnrow(data)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 9\n```\n:::\n\n```{.r .cell-code}\n#existing columns/cases\nncol(data)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 17\n```\n:::\n\n```{.r .cell-code}\n#expected rows/cases\nnrow(data) * (ncol(data)-1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 144\n```\n:::\n\n```{.r .cell-code}\n# expected columns \n2 + 1\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 3\n```\n:::\n:::\n\n\n## Pivot the Data\n\nNow we will pivot the data, and compare our pivoted data dimensions to the dimensions calculated above as a \"sanity\" check.\nFrom the data provided, we can see that there are 9 IPCC areas (or rows) and 17 columns. One of these columns is used to identify a case, that is, 'IPCC Area'. So, we have 17 columns that are actual variables (each representing a different animal type).\n\nIn this case, after pivoting, we should have n*(k-1) rows in the pivoted dataframe.\n\nHere n is the number of rows (9 IPCC Areas) and k is the number of columns (17). So, the dimensions of the pivoted dataframe should be $9*(17-1)$, which equals 144 rows.\n\nIn the pivoted dataframe, we would have three columns: 'IPCC Area', 'Animal Type', and 'Average Weight'. So the total number of data points in the dataframe should remain the same: $9 * 17 (original dataframe) = 144 * 3 (pivoted dataframe)$.\n\n### Challenge: Pivot the Chosen Data\n\nDocument your work here. What will a new \"case\" be once you have pivoted the data? How does it meet requirements for tidy data?\n\n::: {.cell}\n\n```{.r .cell-code}\n# Pivoting the data to a tidy format\nanimal_weight_pivoted <- pivot_longer(data, \n                                      cols = 'Cattle - dairy':'Llamas', \n                                      names_to = \"Animal Type\",\n                                      values_to = \"Average Weight\")\nprint(animal_weight_pivoted, n = nrow(animal_weight_pivoted))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 144 × 3\n    `IPCC Area`         `Animal Type`      `Average Weight`\n    <chr>               <chr>                         <dbl>\n  1 Indian Subcontinent Cattle - dairy                275  \n  2 Indian Subcontinent Cattle - non-dairy            110  \n  3 Indian Subcontinent Buffaloes                     295  \n  4 Indian Subcontinent Swine - market                 28  \n  5 Indian Subcontinent Swine - breeding               28  \n  6 Indian Subcontinent Chicken - Broilers              0.9\n  7 Indian Subcontinent Chicken - Layers                1.8\n  8 Indian Subcontinent Ducks                           2.7\n  9 Indian Subcontinent Turkeys                         6.8\n 10 Indian Subcontinent Sheep                          28  \n 11 Indian Subcontinent Goats                          30  \n 12 Indian Subcontinent Horses                        238  \n 13 Indian Subcontinent Asses                         130  \n 14 Indian Subcontinent Mules                         130  \n 15 Indian Subcontinent Camels                        217  \n 16 Indian Subcontinent Llamas                        217  \n 17 Eastern Europe      Cattle - dairy                550  \n 18 Eastern Europe      Cattle - non-dairy            391  \n 19 Eastern Europe      Buffaloes                     380  \n 20 Eastern Europe      Swine - market                 50  \n 21 Eastern Europe      Swine - breeding              180  \n 22 Eastern Europe      Chicken - Broilers              0.9\n 23 Eastern Europe      Chicken - Layers                1.8\n 24 Eastern Europe      Ducks                           2.7\n 25 Eastern Europe      Turkeys                         6.8\n 26 Eastern Europe      Sheep                          48.5\n 27 Eastern Europe      Goats                          38.5\n 28 Eastern Europe      Horses                        377  \n 29 Eastern Europe      Asses                         130  \n 30 Eastern Europe      Mules                         130  \n 31 Eastern Europe      Camels                        217  \n 32 Eastern Europe      Llamas                        217  \n 33 Africa              Cattle - dairy                275  \n 34 Africa              Cattle - non-dairy            173  \n 35 Africa              Buffaloes                     380  \n 36 Africa              Swine - market                 28  \n 37 Africa              Swine - breeding               28  \n 38 Africa              Chicken - Broilers              0.9\n 39 Africa              Chicken - Layers                1.8\n 40 Africa              Ducks                           2.7\n 41 Africa              Turkeys                         6.8\n 42 Africa              Sheep                          28  \n 43 Africa              Goats                          30  \n 44 Africa              Horses                        238  \n 45 Africa              Asses                         130  \n 46 Africa              Mules                         130  \n 47 Africa              Camels                        217  \n 48 Africa              Llamas                        217  \n 49 Oceania             Cattle - dairy                500  \n 50 Oceania             Cattle - non-dairy            330  \n 51 Oceania             Buffaloes                     380  \n 52 Oceania             Swine - market                 45  \n 53 Oceania             Swine - breeding              180  \n 54 Oceania             Chicken - Broilers              0.9\n 55 Oceania             Chicken - Layers                1.8\n 56 Oceania             Ducks                           2.7\n 57 Oceania             Turkeys                         6.8\n 58 Oceania             Sheep                          48.5\n 59 Oceania             Goats                          38.5\n 60 Oceania             Horses                        377  \n 61 Oceania             Asses                         130  \n 62 Oceania             Mules                         130  \n 63 Oceania             Camels                        217  \n 64 Oceania             Llamas                        217  \n 65 Western Europe      Cattle - dairy                600  \n 66 Western Europe      Cattle - non-dairy            420  \n 67 Western Europe      Buffaloes                     380  \n 68 Western Europe      Swine - market                 50  \n 69 Western Europe      Swine - breeding              198  \n 70 Western Europe      Chicken - Broilers              0.9\n 71 Western Europe      Chicken - Layers                1.8\n 72 Western Europe      Ducks                           2.7\n 73 Western Europe      Turkeys                         6.8\n 74 Western Europe      Sheep                          48.5\n 75 Western Europe      Goats                          38.5\n 76 Western Europe      Horses                        377  \n 77 Western Europe      Asses                         130  \n 78 Western Europe      Mules                         130  \n 79 Western Europe      Camels                        217  \n 80 Western Europe      Llamas                        217  \n 81 Latin America       Cattle - dairy                400  \n 82 Latin America       Cattle - non-dairy            305  \n 83 Latin America       Buffaloes                     380  \n 84 Latin America       Swine - market                 28  \n 85 Latin America       Swine - breeding               28  \n 86 Latin America       Chicken - Broilers              0.9\n 87 Latin America       Chicken - Layers                1.8\n 88 Latin America       Ducks                           2.7\n 89 Latin America       Turkeys                         6.8\n 90 Latin America       Sheep                          28  \n 91 Latin America       Goats                          30  \n 92 Latin America       Horses                        238  \n 93 Latin America       Asses                         130  \n 94 Latin America       Mules                         130  \n 95 Latin America       Camels                        217  \n 96 Latin America       Llamas                        217  \n 97 Asia                Cattle - dairy                350  \n 98 Asia                Cattle - non-dairy            391  \n 99 Asia                Buffaloes                     380  \n100 Asia                Swine - market                 50  \n101 Asia                Swine - breeding              180  \n102 Asia                Chicken - Broilers              0.9\n103 Asia                Chicken - Layers                1.8\n104 Asia                Ducks                           2.7\n105 Asia                Turkeys                         6.8\n106 Asia                Sheep                          48.5\n107 Asia                Goats                          38.5\n108 Asia                Horses                        377  \n109 Asia                Asses                         130  \n110 Asia                Mules                         130  \n111 Asia                Camels                        217  \n112 Asia                Llamas                        217  \n113 Middle east         Cattle - dairy                275  \n114 Middle east         Cattle - non-dairy            173  \n115 Middle east         Buffaloes                     380  \n116 Middle east         Swine - market                 28  \n117 Middle east         Swine - breeding               28  \n118 Middle east         Chicken - Broilers              0.9\n119 Middle east         Chicken - Layers                1.8\n120 Middle east         Ducks                           2.7\n121 Middle east         Turkeys                         6.8\n122 Middle east         Sheep                          28  \n123 Middle east         Goats                          30  \n124 Middle east         Horses                        238  \n125 Middle east         Asses                         130  \n126 Middle east         Mules                         130  \n127 Middle east         Camels                        217  \n128 Middle east         Llamas                        217  \n129 Northern America    Cattle - dairy                604  \n130 Northern America    Cattle - non-dairy            389  \n131 Northern America    Buffaloes                     380  \n132 Northern America    Swine - market                 46  \n133 Northern America    Swine - breeding              198  \n134 Northern America    Chicken - Broilers              0.9\n135 Northern America    Chicken - Layers                1.8\n136 Northern America    Ducks                           2.7\n137 Northern America    Turkeys                         6.8\n138 Northern America    Sheep                          48.5\n139 Northern America    Goats                          38.5\n140 Northern America    Horses                        377  \n141 Northern America    Asses                         130  \n142 Northern America    Mules                         130  \n143 Northern America    Camels                        217  \n144 Northern America    Llamas                        217  \n```\n:::\n:::\n\nThe data is now in a tidy format. This fulfills the three principles of tidy data:\n\n1. Each variable forms a column.\n2. Each observation forms a row.\n3. Each type of observational unit forms a table.\n\nThus, in this context, a new \"case\" corresponds to an observation of the average weight for a specific type of animal in a specific area. For instance, the first row tells us that the average weight of dairy cattle in the Indian Subcontinent is 275 units (presumably kilograms or pounds, although the data doesn't specify).\n\nThis tidy format makes it easier to perform subsequent data analyses. For instance, we can now easily calculate the overall average weight for each animal type, compare average weights across different areas, or examine the distribution of weights for each animal type, among other analyses.\n\n",
    "supporting": [
      "challenge3_solution_Xinpeng_Liu_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}