{
  "hash": "b72ac499d990ad3a1ffaeee5d779eb18",
  "result": {
    "markdown": "---\ntitle: \"Challenge 4 Submission\"\nauthor: \"Xinpeng Liu\"\ndescription: \"More data wrangling: pivoting\"\ndate: 6/13/2023\"\nformat:\n  html:\n    df-print: paged\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - challenge_4\n  - abc_poll\n  - eggs\n  - fed_rates\n  - hotel_bookings\n  - debt\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n\nknitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)\n```\n:::\n\n\n## Challenge Overview\n\nToday's challenge is to:\n\n1)  read in a data set, and describe the data set using both words and any supporting information (e.g., tables, etc)\n2)  tidy data (as needed, including sanity checks)\n3)  identify variables that need to be mutated\n4)  mutate variables and sanity check all mutations\n\n## Read in data\n\nRead in one (or more) of the following datasets, using the correct R package and command.\n\n-   abc_poll.csv ⭐\n-   poultry_tidy.xlsx or organiceggpoultry.xls⭐⭐\n-   FedFundsRate.csv⭐⭐⭐\n-   hotel_bookings.csv⭐⭐⭐⭐\n-   debt_in_trillions.xlsx ⭐⭐⭐⭐⭐\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(lubridate)\nlibrary(readxl)\nlibrary(tidyr)\nlibrary(dplyr)\n```\n:::\n\n\n### Briefly describe the data\n\nwe choose - poultry_tidy.xlsx⭐⭐\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata <- read_excel(\"_data/poultry_tidy.xlsx\")\ndata\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"Product\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Year\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Month\"],\"name\":[3],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Price_Dollar\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"Whole\",\"2\":\"2013\",\"3\":\"January\",\"4\":\"2.38500\"},{\"1\":\"Whole\",\"2\":\"2013\",\"3\":\"February\",\"4\":\"2.38500\"},{\"1\":\"Whole\",\"2\":\"2013\",\"3\":\"March\",\"4\":\"2.38500\"},{\"1\":\"Whole\",\"2\":\"2013\",\"3\":\"April\",\"4\":\"2.38500\"},{\"1\":\"Whole\",\"2\":\"2013\",\"3\":\"May\",\"4\":\"2.38500\"},{\"1\":\"Whole\",\"2\":\"2013\",\"3\":\"June\",\"4\":\"2.38500\"},{\"1\":\"Whole\",\"2\":\"2013\",\"3\":\"July\",\"4\":\"2.38500\"},{\"1\":\"Whole\",\"2\":\"2013\",\"3\":\"August\",\"4\":\"2.38500\"},{\"1\":\"Whole\",\"2\":\"2013\",\"3\":\"September\",\"4\":\"2.38500\"},{\"1\":\"Whole\",\"2\":\"2013\",\"3\":\"October\",\"4\":\"2.38500\"},{\"1\":\"Whole\",\"2\":\"2013\",\"3\":\"November\",\"4\":\"2.38500\"},{\"1\":\"Whole\",\"2\":\"2013\",\"3\":\"December\",\"4\":\"2.38500\"},{\"1\":\"B/S Breast\",\"2\":\"2013\",\"3\":\"January\",\"4\":\"7.03750\"},{\"1\":\"B/S Breast\",\"2\":\"2013\",\"3\":\"February\",\"4\":\"7.03750\"},{\"1\":\"B/S Breast\",\"2\":\"2013\",\"3\":\"March\",\"4\":\"7.03750\"},{\"1\":\"B/S Breast\",\"2\":\"2013\",\"3\":\"April\",\"4\":\"7.03750\"},{\"1\":\"B/S Breast\",\"2\":\"2013\",\"3\":\"May\",\"4\":\"7.03750\"},{\"1\":\"B/S Breast\",\"2\":\"2013\",\"3\":\"June\",\"4\":\"7.03750\"},{\"1\":\"B/S Breast\",\"2\":\"2013\",\"3\":\"July\",\"4\":\"7.03750\"},{\"1\":\"B/S Breast\",\"2\":\"2013\",\"3\":\"August\",\"4\":\"7.03750\"},{\"1\":\"B/S Breast\",\"2\":\"2013\",\"3\":\"September\",\"4\":\"7.03750\"},{\"1\":\"B/S Breast\",\"2\":\"2013\",\"3\":\"October\",\"4\":\"7.03750\"},{\"1\":\"B/S Breast\",\"2\":\"2013\",\"3\":\"November\",\"4\":\"7.03750\"},{\"1\":\"B/S Breast\",\"2\":\"2013\",\"3\":\"December\",\"4\":\"7.03750\"},{\"1\":\"Bone-in Breast\",\"2\":\"2013\",\"3\":\"January\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2013\",\"3\":\"February\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2013\",\"3\":\"March\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2013\",\"3\":\"April\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2013\",\"3\":\"May\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2013\",\"3\":\"June\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2013\",\"3\":\"July\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2013\",\"3\":\"August\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2013\",\"3\":\"September\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2013\",\"3\":\"October\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2013\",\"3\":\"November\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2013\",\"3\":\"December\",\"4\":\"3.90500\"},{\"1\":\"Whole Legs\",\"2\":\"2013\",\"3\":\"January\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2013\",\"3\":\"February\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2013\",\"3\":\"March\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2013\",\"3\":\"April\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2013\",\"3\":\"May\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2013\",\"3\":\"June\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2013\",\"3\":\"July\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2013\",\"3\":\"August\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2013\",\"3\":\"September\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2013\",\"3\":\"October\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2013\",\"3\":\"November\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2013\",\"3\":\"December\",\"4\":\"2.03500\"},{\"1\":\"Thighs\",\"2\":\"2013\",\"3\":\"January\",\"4\":\"2.16250\"},{\"1\":\"Thighs\",\"2\":\"2013\",\"3\":\"February\",\"4\":\"2.16250\"},{\"1\":\"Thighs\",\"2\":\"2013\",\"3\":\"March\",\"4\":\"2.16250\"},{\"1\":\"Thighs\",\"2\":\"2013\",\"3\":\"April\",\"4\":\"2.16250\"},{\"1\":\"Thighs\",\"2\":\"2013\",\"3\":\"May\",\"4\":\"2.16250\"},{\"1\":\"Thighs\",\"2\":\"2013\",\"3\":\"June\",\"4\":\"2.16250\"},{\"1\":\"Thighs\",\"2\":\"2013\",\"3\":\"July\",\"4\":\"2.16250\"},{\"1\":\"Thighs\",\"2\":\"2013\",\"3\":\"August\",\"4\":\"2.16250\"},{\"1\":\"Thighs\",\"2\":\"2013\",\"3\":\"September\",\"4\":\"2.16250\"},{\"1\":\"Thighs\",\"2\":\"2013\",\"3\":\"October\",\"4\":\"2.16250\"},{\"1\":\"Thighs\",\"2\":\"2013\",\"3\":\"November\",\"4\":\"2.16250\"},{\"1\":\"Thighs\",\"2\":\"2013\",\"3\":\"December\",\"4\":\"2.16250\"},{\"1\":\"Whole\",\"2\":\"2012\",\"3\":\"January\",\"4\":\"2.35000\"},{\"1\":\"Whole\",\"2\":\"2012\",\"3\":\"February\",\"4\":\"2.38500\"},{\"1\":\"Whole\",\"2\":\"2012\",\"3\":\"March\",\"4\":\"2.38500\"},{\"1\":\"Whole\",\"2\":\"2012\",\"3\":\"April\",\"4\":\"2.38500\"},{\"1\":\"Whole\",\"2\":\"2012\",\"3\":\"May\",\"4\":\"2.38500\"},{\"1\":\"Whole\",\"2\":\"2012\",\"3\":\"June\",\"4\":\"2.38500\"},{\"1\":\"Whole\",\"2\":\"2012\",\"3\":\"July\",\"4\":\"2.38500\"},{\"1\":\"Whole\",\"2\":\"2012\",\"3\":\"August\",\"4\":\"2.38500\"},{\"1\":\"Whole\",\"2\":\"2012\",\"3\":\"September\",\"4\":\"2.38500\"},{\"1\":\"Whole\",\"2\":\"2012\",\"3\":\"October\",\"4\":\"2.38500\"},{\"1\":\"Whole\",\"2\":\"2012\",\"3\":\"November\",\"4\":\"2.38500\"},{\"1\":\"Whole\",\"2\":\"2012\",\"3\":\"December\",\"4\":\"2.38500\"},{\"1\":\"B/S Breast\",\"2\":\"2012\",\"3\":\"January\",\"4\":\"6.37500\"},{\"1\":\"B/S Breast\",\"2\":\"2012\",\"3\":\"February\",\"4\":\"7.00000\"},{\"1\":\"B/S Breast\",\"2\":\"2012\",\"3\":\"March\",\"4\":\"7.00000\"},{\"1\":\"B/S Breast\",\"2\":\"2012\",\"3\":\"April\",\"4\":\"7.00000\"},{\"1\":\"B/S Breast\",\"2\":\"2012\",\"3\":\"May\",\"4\":\"7.00000\"},{\"1\":\"B/S Breast\",\"2\":\"2012\",\"3\":\"June\",\"4\":\"7.00000\"},{\"1\":\"B/S Breast\",\"2\":\"2012\",\"3\":\"July\",\"4\":\"7.00000\"},{\"1\":\"B/S Breast\",\"2\":\"2012\",\"3\":\"August\",\"4\":\"7.00000\"},{\"1\":\"B/S Breast\",\"2\":\"2012\",\"3\":\"September\",\"4\":\"7.00000\"},{\"1\":\"B/S Breast\",\"2\":\"2012\",\"3\":\"October\",\"4\":\"7.00000\"},{\"1\":\"B/S Breast\",\"2\":\"2012\",\"3\":\"November\",\"4\":\"7.03750\"},{\"1\":\"B/S Breast\",\"2\":\"2012\",\"3\":\"December\",\"4\":\"7.03750\"},{\"1\":\"Bone-in Breast\",\"2\":\"2012\",\"3\":\"January\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2012\",\"3\":\"February\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2012\",\"3\":\"March\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2012\",\"3\":\"April\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2012\",\"3\":\"May\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2012\",\"3\":\"June\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2012\",\"3\":\"July\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2012\",\"3\":\"August\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2012\",\"3\":\"September\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2012\",\"3\":\"October\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2012\",\"3\":\"November\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2012\",\"3\":\"December\",\"4\":\"3.90500\"},{\"1\":\"Whole Legs\",\"2\":\"2012\",\"3\":\"January\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2012\",\"3\":\"February\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2012\",\"3\":\"March\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2012\",\"3\":\"April\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2012\",\"3\":\"May\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2012\",\"3\":\"June\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2012\",\"3\":\"July\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2012\",\"3\":\"August\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2012\",\"3\":\"September\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2012\",\"3\":\"October\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2012\",\"3\":\"November\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2012\",\"3\":\"December\",\"4\":\"2.03500\"},{\"1\":\"Thighs\",\"2\":\"2012\",\"3\":\"January\",\"4\":\"2.15000\"},{\"1\":\"Thighs\",\"2\":\"2012\",\"3\":\"February\",\"4\":\"2.15000\"},{\"1\":\"Thighs\",\"2\":\"2012\",\"3\":\"March\",\"4\":\"2.15000\"},{\"1\":\"Thighs\",\"2\":\"2012\",\"3\":\"April\",\"4\":\"2.15000\"},{\"1\":\"Thighs\",\"2\":\"2012\",\"3\":\"May\",\"4\":\"2.15000\"},{\"1\":\"Thighs\",\"2\":\"2012\",\"3\":\"June\",\"4\":\"2.15000\"},{\"1\":\"Thighs\",\"2\":\"2012\",\"3\":\"July\",\"4\":\"2.15000\"},{\"1\":\"Thighs\",\"2\":\"2012\",\"3\":\"August\",\"4\":\"2.16250\"},{\"1\":\"Thighs\",\"2\":\"2012\",\"3\":\"September\",\"4\":\"2.16250\"},{\"1\":\"Thighs\",\"2\":\"2012\",\"3\":\"October\",\"4\":\"2.16250\"},{\"1\":\"Thighs\",\"2\":\"2012\",\"3\":\"November\",\"4\":\"2.16250\"},{\"1\":\"Thighs\",\"2\":\"2012\",\"3\":\"December\",\"4\":\"2.16250\"},{\"1\":\"Whole\",\"2\":\"2011\",\"3\":\"January\",\"4\":\"2.35000\"},{\"1\":\"Whole\",\"2\":\"2011\",\"3\":\"February\",\"4\":\"2.35000\"},{\"1\":\"Whole\",\"2\":\"2011\",\"3\":\"March\",\"4\":\"2.35000\"},{\"1\":\"Whole\",\"2\":\"2011\",\"3\":\"April\",\"4\":\"2.35000\"},{\"1\":\"Whole\",\"2\":\"2011\",\"3\":\"May\",\"4\":\"2.35000\"},{\"1\":\"Whole\",\"2\":\"2011\",\"3\":\"June\",\"4\":\"2.35000\"},{\"1\":\"Whole\",\"2\":\"2011\",\"3\":\"July\",\"4\":\"2.35000\"},{\"1\":\"Whole\",\"2\":\"2011\",\"3\":\"August\",\"4\":\"2.35000\"},{\"1\":\"Whole\",\"2\":\"2011\",\"3\":\"September\",\"4\":\"2.35000\"},{\"1\":\"Whole\",\"2\":\"2011\",\"3\":\"October\",\"4\":\"2.35000\"},{\"1\":\"Whole\",\"2\":\"2011\",\"3\":\"November\",\"4\":\"2.35000\"},{\"1\":\"Whole\",\"2\":\"2011\",\"3\":\"December\",\"4\":\"2.35000\"},{\"1\":\"B/S Breast\",\"2\":\"2011\",\"3\":\"January\",\"4\":\"6.37500\"},{\"1\":\"B/S Breast\",\"2\":\"2011\",\"3\":\"February\",\"4\":\"6.37500\"},{\"1\":\"B/S Breast\",\"2\":\"2011\",\"3\":\"March\",\"4\":\"6.37500\"},{\"1\":\"B/S Breast\",\"2\":\"2011\",\"3\":\"April\",\"4\":\"6.37500\"},{\"1\":\"B/S Breast\",\"2\":\"2011\",\"3\":\"May\",\"4\":\"6.37500\"},{\"1\":\"B/S Breast\",\"2\":\"2011\",\"3\":\"June\",\"4\":\"6.37500\"},{\"1\":\"B/S Breast\",\"2\":\"2011\",\"3\":\"July\",\"4\":\"6.37500\"},{\"1\":\"B/S Breast\",\"2\":\"2011\",\"3\":\"August\",\"4\":\"6.37500\"},{\"1\":\"B/S Breast\",\"2\":\"2011\",\"3\":\"September\",\"4\":\"6.37500\"},{\"1\":\"B/S Breast\",\"2\":\"2011\",\"3\":\"October\",\"4\":\"6.37500\"},{\"1\":\"B/S Breast\",\"2\":\"2011\",\"3\":\"November\",\"4\":\"6.37500\"},{\"1\":\"B/S Breast\",\"2\":\"2011\",\"3\":\"December\",\"4\":\"6.37500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2011\",\"3\":\"January\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2011\",\"3\":\"February\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2011\",\"3\":\"March\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2011\",\"3\":\"April\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2011\",\"3\":\"May\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2011\",\"3\":\"June\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2011\",\"3\":\"July\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2011\",\"3\":\"August\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2011\",\"3\":\"September\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2011\",\"3\":\"October\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2011\",\"3\":\"November\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2011\",\"3\":\"December\",\"4\":\"3.90500\"},{\"1\":\"Whole Legs\",\"2\":\"2011\",\"3\":\"January\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2011\",\"3\":\"February\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2011\",\"3\":\"March\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2011\",\"3\":\"April\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2011\",\"3\":\"May\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2011\",\"3\":\"June\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2011\",\"3\":\"July\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2011\",\"3\":\"August\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2011\",\"3\":\"September\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2011\",\"3\":\"October\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2011\",\"3\":\"November\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2011\",\"3\":\"December\",\"4\":\"2.03500\"},{\"1\":\"Thighs\",\"2\":\"2011\",\"3\":\"January\",\"4\":\"2.15000\"},{\"1\":\"Thighs\",\"2\":\"2011\",\"3\":\"February\",\"4\":\"2.15000\"},{\"1\":\"Thighs\",\"2\":\"2011\",\"3\":\"March\",\"4\":\"2.15000\"},{\"1\":\"Thighs\",\"2\":\"2011\",\"3\":\"April\",\"4\":\"2.15000\"},{\"1\":\"Thighs\",\"2\":\"2011\",\"3\":\"May\",\"4\":\"2.15000\"},{\"1\":\"Thighs\",\"2\":\"2011\",\"3\":\"June\",\"4\":\"2.15000\"},{\"1\":\"Thighs\",\"2\":\"2011\",\"3\":\"July\",\"4\":\"2.15000\"},{\"1\":\"Thighs\",\"2\":\"2011\",\"3\":\"August\",\"4\":\"2.15000\"},{\"1\":\"Thighs\",\"2\":\"2011\",\"3\":\"September\",\"4\":\"2.15000\"},{\"1\":\"Thighs\",\"2\":\"2011\",\"3\":\"October\",\"4\":\"2.15000\"},{\"1\":\"Thighs\",\"2\":\"2011\",\"3\":\"November\",\"4\":\"2.15000\"},{\"1\":\"Thighs\",\"2\":\"2011\",\"3\":\"December\",\"4\":\"2.15000\"},{\"1\":\"Whole\",\"2\":\"2010\",\"3\":\"January\",\"4\":\"2.48000\"},{\"1\":\"Whole\",\"2\":\"2010\",\"3\":\"February\",\"4\":\"2.48000\"},{\"1\":\"Whole\",\"2\":\"2010\",\"3\":\"March\",\"4\":\"2.48000\"},{\"1\":\"Whole\",\"2\":\"2010\",\"3\":\"April\",\"4\":\"2.41500\"},{\"1\":\"Whole\",\"2\":\"2010\",\"3\":\"May\",\"4\":\"2.35000\"},{\"1\":\"Whole\",\"2\":\"2010\",\"3\":\"June\",\"4\":\"2.35000\"},{\"1\":\"Whole\",\"2\":\"2010\",\"3\":\"July\",\"4\":\"2.41500\"},{\"1\":\"Whole\",\"2\":\"2010\",\"3\":\"August\",\"4\":\"2.35000\"},{\"1\":\"Whole\",\"2\":\"2010\",\"3\":\"September\",\"4\":\"2.35000\"},{\"1\":\"Whole\",\"2\":\"2010\",\"3\":\"October\",\"4\":\"2.35000\"},{\"1\":\"Whole\",\"2\":\"2010\",\"3\":\"November\",\"4\":\"2.35000\"},{\"1\":\"Whole\",\"2\":\"2010\",\"3\":\"December\",\"4\":\"2.35000\"},{\"1\":\"B/S Breast\",\"2\":\"2010\",\"3\":\"January\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2010\",\"3\":\"February\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2010\",\"3\":\"March\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2010\",\"3\":\"April\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2010\",\"3\":\"May\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2010\",\"3\":\"June\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2010\",\"3\":\"July\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2010\",\"3\":\"August\",\"4\":\"6.42300\"},{\"1\":\"B/S Breast\",\"2\":\"2010\",\"3\":\"September\",\"4\":\"6.37500\"},{\"1\":\"B/S Breast\",\"2\":\"2010\",\"3\":\"October\",\"4\":\"6.37500\"},{\"1\":\"B/S Breast\",\"2\":\"2010\",\"3\":\"November\",\"4\":\"6.37500\"},{\"1\":\"B/S Breast\",\"2\":\"2010\",\"3\":\"December\",\"4\":\"6.37500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2010\",\"3\":\"January\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2010\",\"3\":\"February\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2010\",\"3\":\"March\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2010\",\"3\":\"April\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2010\",\"3\":\"May\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2010\",\"3\":\"June\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2010\",\"3\":\"July\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2010\",\"3\":\"August\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2010\",\"3\":\"September\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2010\",\"3\":\"October\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2010\",\"3\":\"November\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2010\",\"3\":\"December\",\"4\":\"3.90500\"},{\"1\":\"Whole Legs\",\"2\":\"2010\",\"3\":\"January\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2010\",\"3\":\"February\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2010\",\"3\":\"March\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2010\",\"3\":\"April\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2010\",\"3\":\"May\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2010\",\"3\":\"June\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2010\",\"3\":\"July\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2010\",\"3\":\"August\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2010\",\"3\":\"September\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2010\",\"3\":\"October\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2010\",\"3\":\"November\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2010\",\"3\":\"December\",\"4\":\"2.03500\"},{\"1\":\"Thighs\",\"2\":\"2010\",\"3\":\"January\",\"4\":\"2.22000\"},{\"1\":\"Thighs\",\"2\":\"2010\",\"3\":\"February\",\"4\":\"2.22000\"},{\"1\":\"Thighs\",\"2\":\"2010\",\"3\":\"March\",\"4\":\"2.22000\"},{\"1\":\"Thighs\",\"2\":\"2010\",\"3\":\"April\",\"4\":\"2.22000\"},{\"1\":\"Thighs\",\"2\":\"2010\",\"3\":\"May\",\"4\":\"2.22000\"},{\"1\":\"Thighs\",\"2\":\"2010\",\"3\":\"June\",\"4\":\"2.22000\"},{\"1\":\"Thighs\",\"2\":\"2010\",\"3\":\"July\",\"4\":\"2.22000\"},{\"1\":\"Thighs\",\"2\":\"2010\",\"3\":\"August\",\"4\":\"2.19200\"},{\"1\":\"Thighs\",\"2\":\"2010\",\"3\":\"September\",\"4\":\"2.15000\"},{\"1\":\"Thighs\",\"2\":\"2010\",\"3\":\"October\",\"4\":\"2.15000\"},{\"1\":\"Thighs\",\"2\":\"2010\",\"3\":\"November\",\"4\":\"2.15000\"},{\"1\":\"Thighs\",\"2\":\"2010\",\"3\":\"December\",\"4\":\"2.15000\"},{\"1\":\"Whole\",\"2\":\"2009\",\"3\":\"January\",\"4\":\"2.48000\"},{\"1\":\"Whole\",\"2\":\"2009\",\"3\":\"February\",\"4\":\"2.48000\"},{\"1\":\"Whole\",\"2\":\"2009\",\"3\":\"March\",\"4\":\"2.48000\"},{\"1\":\"Whole\",\"2\":\"2009\",\"3\":\"April\",\"4\":\"2.48000\"},{\"1\":\"Whole\",\"2\":\"2009\",\"3\":\"May\",\"4\":\"2.48000\"},{\"1\":\"Whole\",\"2\":\"2009\",\"3\":\"June\",\"4\":\"2.48000\"},{\"1\":\"Whole\",\"2\":\"2009\",\"3\":\"July\",\"4\":\"2.48000\"},{\"1\":\"Whole\",\"2\":\"2009\",\"3\":\"August\",\"4\":\"2.48000\"},{\"1\":\"Whole\",\"2\":\"2009\",\"3\":\"September\",\"4\":\"2.48000\"},{\"1\":\"Whole\",\"2\":\"2009\",\"3\":\"October\",\"4\":\"2.48000\"},{\"1\":\"Whole\",\"2\":\"2009\",\"3\":\"November\",\"4\":\"2.48000\"},{\"1\":\"Whole\",\"2\":\"2009\",\"3\":\"December\",\"4\":\"2.48000\"},{\"1\":\"B/S Breast\",\"2\":\"2009\",\"3\":\"January\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2009\",\"3\":\"February\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2009\",\"3\":\"March\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2009\",\"3\":\"April\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2009\",\"3\":\"May\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2009\",\"3\":\"June\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2009\",\"3\":\"July\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2009\",\"3\":\"August\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2009\",\"3\":\"September\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2009\",\"3\":\"October\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2009\",\"3\":\"November\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2009\",\"3\":\"December\",\"4\":\"6.45500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2009\",\"3\":\"January\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2009\",\"3\":\"February\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2009\",\"3\":\"March\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2009\",\"3\":\"April\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2009\",\"3\":\"May\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2009\",\"3\":\"June\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2009\",\"3\":\"July\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2009\",\"3\":\"August\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2009\",\"3\":\"September\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2009\",\"3\":\"October\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2009\",\"3\":\"November\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2009\",\"3\":\"December\",\"4\":\"3.90500\"},{\"1\":\"Whole Legs\",\"2\":\"2009\",\"3\":\"January\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2009\",\"3\":\"February\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2009\",\"3\":\"March\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2009\",\"3\":\"April\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2009\",\"3\":\"May\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2009\",\"3\":\"June\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2009\",\"3\":\"July\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2009\",\"3\":\"August\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2009\",\"3\":\"September\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2009\",\"3\":\"October\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2009\",\"3\":\"November\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2009\",\"3\":\"December\",\"4\":\"2.03500\"},{\"1\":\"Thighs\",\"2\":\"2009\",\"3\":\"January\",\"4\":\"2.22000\"},{\"1\":\"Thighs\",\"2\":\"2009\",\"3\":\"February\",\"4\":\"2.22000\"},{\"1\":\"Thighs\",\"2\":\"2009\",\"3\":\"March\",\"4\":\"2.22000\"},{\"1\":\"Thighs\",\"2\":\"2009\",\"3\":\"April\",\"4\":\"2.22000\"},{\"1\":\"Thighs\",\"2\":\"2009\",\"3\":\"May\",\"4\":\"2.22000\"},{\"1\":\"Thighs\",\"2\":\"2009\",\"3\":\"June\",\"4\":\"2.22000\"},{\"1\":\"Thighs\",\"2\":\"2009\",\"3\":\"July\",\"4\":\"2.22000\"},{\"1\":\"Thighs\",\"2\":\"2009\",\"3\":\"August\",\"4\":\"2.22000\"},{\"1\":\"Thighs\",\"2\":\"2009\",\"3\":\"September\",\"4\":\"2.22000\"},{\"1\":\"Thighs\",\"2\":\"2009\",\"3\":\"October\",\"4\":\"2.22000\"},{\"1\":\"Thighs\",\"2\":\"2009\",\"3\":\"November\",\"4\":\"2.22000\"},{\"1\":\"Thighs\",\"2\":\"2009\",\"3\":\"December\",\"4\":\"2.22000\"},{\"1\":\"Whole\",\"2\":\"2008\",\"3\":\"January\",\"4\":\"2.20500\"},{\"1\":\"Whole\",\"2\":\"2008\",\"3\":\"February\",\"4\":\"2.20500\"},{\"1\":\"Whole\",\"2\":\"2008\",\"3\":\"March\",\"4\":\"2.20500\"},{\"1\":\"Whole\",\"2\":\"2008\",\"3\":\"April\",\"4\":\"2.20500\"},{\"1\":\"Whole\",\"2\":\"2008\",\"3\":\"May\",\"4\":\"2.20500\"},{\"1\":\"Whole\",\"2\":\"2008\",\"3\":\"June\",\"4\":\"2.48000\"},{\"1\":\"Whole\",\"2\":\"2008\",\"3\":\"July\",\"4\":\"2.48000\"},{\"1\":\"Whole\",\"2\":\"2008\",\"3\":\"August\",\"4\":\"2.48000\"},{\"1\":\"Whole\",\"2\":\"2008\",\"3\":\"September\",\"4\":\"2.48000\"},{\"1\":\"Whole\",\"2\":\"2008\",\"3\":\"October\",\"4\":\"2.48000\"},{\"1\":\"Whole\",\"2\":\"2008\",\"3\":\"November\",\"4\":\"2.48000\"},{\"1\":\"Whole\",\"2\":\"2008\",\"3\":\"December\",\"4\":\"2.48000\"},{\"1\":\"B/S Breast\",\"2\":\"2008\",\"3\":\"January\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2008\",\"3\":\"February\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2008\",\"3\":\"March\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2008\",\"3\":\"April\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2008\",\"3\":\"May\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2008\",\"3\":\"June\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2008\",\"3\":\"July\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2008\",\"3\":\"August\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2008\",\"3\":\"September\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2008\",\"3\":\"October\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2008\",\"3\":\"November\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2008\",\"3\":\"December\",\"4\":\"6.45500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2008\",\"3\":\"January\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2008\",\"3\":\"February\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2008\",\"3\":\"March\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2008\",\"3\":\"April\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2008\",\"3\":\"May\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2008\",\"3\":\"June\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2008\",\"3\":\"July\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2008\",\"3\":\"August\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2008\",\"3\":\"September\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2008\",\"3\":\"October\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2008\",\"3\":\"November\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2008\",\"3\":\"December\",\"4\":\"3.90500\"},{\"1\":\"Whole Legs\",\"2\":\"2008\",\"3\":\"January\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2008\",\"3\":\"February\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2008\",\"3\":\"March\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2008\",\"3\":\"April\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2008\",\"3\":\"May\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2008\",\"3\":\"June\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2008\",\"3\":\"July\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2008\",\"3\":\"August\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2008\",\"3\":\"September\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2008\",\"3\":\"October\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2008\",\"3\":\"November\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2008\",\"3\":\"December\",\"4\":\"2.03500\"},{\"1\":\"Thighs\",\"2\":\"2008\",\"3\":\"January\",\"4\":\"2.22000\"},{\"1\":\"Thighs\",\"2\":\"2008\",\"3\":\"February\",\"4\":\"2.22000\"},{\"1\":\"Thighs\",\"2\":\"2008\",\"3\":\"March\",\"4\":\"2.22000\"},{\"1\":\"Thighs\",\"2\":\"2008\",\"3\":\"April\",\"4\":\"2.22000\"},{\"1\":\"Thighs\",\"2\":\"2008\",\"3\":\"May\",\"4\":\"2.22000\"},{\"1\":\"Thighs\",\"2\":\"2008\",\"3\":\"June\",\"4\":\"2.22000\"},{\"1\":\"Thighs\",\"2\":\"2008\",\"3\":\"July\",\"4\":\"2.22000\"},{\"1\":\"Thighs\",\"2\":\"2008\",\"3\":\"August\",\"4\":\"2.22000\"},{\"1\":\"Thighs\",\"2\":\"2008\",\"3\":\"September\",\"4\":\"2.22000\"},{\"1\":\"Thighs\",\"2\":\"2008\",\"3\":\"October\",\"4\":\"2.22000\"},{\"1\":\"Thighs\",\"2\":\"2008\",\"3\":\"November\",\"4\":\"2.22000\"},{\"1\":\"Thighs\",\"2\":\"2008\",\"3\":\"December\",\"4\":\"2.22000\"},{\"1\":\"Whole\",\"2\":\"2007\",\"3\":\"January\",\"4\":\"2.20500\"},{\"1\":\"Whole\",\"2\":\"2007\",\"3\":\"February\",\"4\":\"2.20500\"},{\"1\":\"Whole\",\"2\":\"2007\",\"3\":\"March\",\"4\":\"2.20500\"},{\"1\":\"Whole\",\"2\":\"2007\",\"3\":\"April\",\"4\":\"2.20500\"},{\"1\":\"Whole\",\"2\":\"2007\",\"3\":\"May\",\"4\":\"2.20500\"},{\"1\":\"Whole\",\"2\":\"2007\",\"3\":\"June\",\"4\":\"2.20500\"},{\"1\":\"Whole\",\"2\":\"2007\",\"3\":\"July\",\"4\":\"2.20500\"},{\"1\":\"Whole\",\"2\":\"2007\",\"3\":\"August\",\"4\":\"2.20500\"},{\"1\":\"Whole\",\"2\":\"2007\",\"3\":\"September\",\"4\":\"2.20500\"},{\"1\":\"Whole\",\"2\":\"2007\",\"3\":\"October\",\"4\":\"2.20500\"},{\"1\":\"Whole\",\"2\":\"2007\",\"3\":\"November\",\"4\":\"2.20500\"},{\"1\":\"Whole\",\"2\":\"2007\",\"3\":\"December\",\"4\":\"2.20500\"},{\"1\":\"B/S Breast\",\"2\":\"2007\",\"3\":\"January\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2007\",\"3\":\"February\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2007\",\"3\":\"March\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2007\",\"3\":\"April\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2007\",\"3\":\"May\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2007\",\"3\":\"June\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2007\",\"3\":\"July\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2007\",\"3\":\"August\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2007\",\"3\":\"September\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2007\",\"3\":\"October\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2007\",\"3\":\"November\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2007\",\"3\":\"December\",\"4\":\"6.45500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2007\",\"3\":\"January\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2007\",\"3\":\"February\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2007\",\"3\":\"March\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2007\",\"3\":\"April\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2007\",\"3\":\"May\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2007\",\"3\":\"June\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2007\",\"3\":\"July\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2007\",\"3\":\"August\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2007\",\"3\":\"September\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2007\",\"3\":\"October\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2007\",\"3\":\"November\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2007\",\"3\":\"December\",\"4\":\"3.90500\"},{\"1\":\"Whole Legs\",\"2\":\"2007\",\"3\":\"January\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2007\",\"3\":\"February\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2007\",\"3\":\"March\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2007\",\"3\":\"April\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2007\",\"3\":\"May\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2007\",\"3\":\"June\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2007\",\"3\":\"July\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2007\",\"3\":\"August\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2007\",\"3\":\"September\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2007\",\"3\":\"October\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2007\",\"3\":\"November\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2007\",\"3\":\"December\",\"4\":\"2.03500\"},{\"1\":\"Thighs\",\"2\":\"2007\",\"3\":\"January\",\"4\":\"2.22000\"},{\"1\":\"Thighs\",\"2\":\"2007\",\"3\":\"February\",\"4\":\"2.22000\"},{\"1\":\"Thighs\",\"2\":\"2007\",\"3\":\"March\",\"4\":\"2.22000\"},{\"1\":\"Thighs\",\"2\":\"2007\",\"3\":\"April\",\"4\":\"2.22000\"},{\"1\":\"Thighs\",\"2\":\"2007\",\"3\":\"May\",\"4\":\"2.22000\"},{\"1\":\"Thighs\",\"2\":\"2007\",\"3\":\"June\",\"4\":\"2.22000\"},{\"1\":\"Thighs\",\"2\":\"2007\",\"3\":\"July\",\"4\":\"2.22000\"},{\"1\":\"Thighs\",\"2\":\"2007\",\"3\":\"August\",\"4\":\"2.22000\"},{\"1\":\"Thighs\",\"2\":\"2007\",\"3\":\"September\",\"4\":\"2.22000\"},{\"1\":\"Thighs\",\"2\":\"2007\",\"3\":\"October\",\"4\":\"2.22000\"},{\"1\":\"Thighs\",\"2\":\"2007\",\"3\":\"November\",\"4\":\"2.22000\"},{\"1\":\"Thighs\",\"2\":\"2007\",\"3\":\"December\",\"4\":\"2.22000\"},{\"1\":\"Whole\",\"2\":\"2006\",\"3\":\"January\",\"4\":\"2.17000\"},{\"1\":\"Whole\",\"2\":\"2006\",\"3\":\"February\",\"4\":\"2.17000\"},{\"1\":\"Whole\",\"2\":\"2006\",\"3\":\"March\",\"4\":\"2.19625\"},{\"1\":\"Whole\",\"2\":\"2006\",\"3\":\"April\",\"4\":\"2.20500\"},{\"1\":\"Whole\",\"2\":\"2006\",\"3\":\"May\",\"4\":\"2.20500\"},{\"1\":\"Whole\",\"2\":\"2006\",\"3\":\"June\",\"4\":\"2.20500\"},{\"1\":\"Whole\",\"2\":\"2006\",\"3\":\"July\",\"4\":\"2.20500\"},{\"1\":\"Whole\",\"2\":\"2006\",\"3\":\"August\",\"4\":\"2.20500\"},{\"1\":\"Whole\",\"2\":\"2006\",\"3\":\"September\",\"4\":\"2.20500\"},{\"1\":\"Whole\",\"2\":\"2006\",\"3\":\"October\",\"4\":\"2.20500\"},{\"1\":\"Whole\",\"2\":\"2006\",\"3\":\"November\",\"4\":\"2.20500\"},{\"1\":\"Whole\",\"2\":\"2006\",\"3\":\"December\",\"4\":\"2.20500\"},{\"1\":\"B/S Breast\",\"2\":\"2006\",\"3\":\"January\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2006\",\"3\":\"February\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2006\",\"3\":\"March\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2006\",\"3\":\"April\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2006\",\"3\":\"May\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2006\",\"3\":\"June\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2006\",\"3\":\"July\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2006\",\"3\":\"August\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2006\",\"3\":\"September\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2006\",\"3\":\"October\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2006\",\"3\":\"November\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2006\",\"3\":\"December\",\"4\":\"6.45500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2006\",\"3\":\"January\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2006\",\"3\":\"February\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2006\",\"3\":\"March\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2006\",\"3\":\"April\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2006\",\"3\":\"May\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2006\",\"3\":\"June\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2006\",\"3\":\"July\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2006\",\"3\":\"August\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2006\",\"3\":\"September\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2006\",\"3\":\"October\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2006\",\"3\":\"November\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2006\",\"3\":\"December\",\"4\":\"3.90500\"},{\"1\":\"Whole Legs\",\"2\":\"2006\",\"3\":\"January\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2006\",\"3\":\"February\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2006\",\"3\":\"March\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2006\",\"3\":\"April\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2006\",\"3\":\"May\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2006\",\"3\":\"June\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2006\",\"3\":\"July\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2006\",\"3\":\"August\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2006\",\"3\":\"September\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2006\",\"3\":\"October\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2006\",\"3\":\"November\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2006\",\"3\":\"December\",\"4\":\"2.03500\"},{\"1\":\"Thighs\",\"2\":\"2006\",\"3\":\"January\",\"4\":\"2.22000\"},{\"1\":\"Thighs\",\"2\":\"2006\",\"3\":\"February\",\"4\":\"2.22000\"},{\"1\":\"Thighs\",\"2\":\"2006\",\"3\":\"March\",\"4\":\"2.22000\"},{\"1\":\"Thighs\",\"2\":\"2006\",\"3\":\"April\",\"4\":\"2.22000\"},{\"1\":\"Thighs\",\"2\":\"2006\",\"3\":\"May\",\"4\":\"2.22000\"},{\"1\":\"Thighs\",\"2\":\"2006\",\"3\":\"June\",\"4\":\"2.22000\"},{\"1\":\"Thighs\",\"2\":\"2006\",\"3\":\"July\",\"4\":\"2.22000\"},{\"1\":\"Thighs\",\"2\":\"2006\",\"3\":\"August\",\"4\":\"2.22000\"},{\"1\":\"Thighs\",\"2\":\"2006\",\"3\":\"September\",\"4\":\"2.22000\"},{\"1\":\"Thighs\",\"2\":\"2006\",\"3\":\"October\",\"4\":\"2.22000\"},{\"1\":\"Thighs\",\"2\":\"2006\",\"3\":\"November\",\"4\":\"2.22000\"},{\"1\":\"Thighs\",\"2\":\"2006\",\"3\":\"December\",\"4\":\"2.22000\"},{\"1\":\"Whole\",\"2\":\"2005\",\"3\":\"January\",\"4\":\"2.17000\"},{\"1\":\"Whole\",\"2\":\"2005\",\"3\":\"February\",\"4\":\"2.17000\"},{\"1\":\"Whole\",\"2\":\"2005\",\"3\":\"March\",\"4\":\"2.17000\"},{\"1\":\"Whole\",\"2\":\"2005\",\"3\":\"April\",\"4\":\"2.17000\"},{\"1\":\"Whole\",\"2\":\"2005\",\"3\":\"May\",\"4\":\"2.17000\"},{\"1\":\"Whole\",\"2\":\"2005\",\"3\":\"June\",\"4\":\"2.17000\"},{\"1\":\"Whole\",\"2\":\"2005\",\"3\":\"July\",\"4\":\"2.17000\"},{\"1\":\"Whole\",\"2\":\"2005\",\"3\":\"August\",\"4\":\"2.17000\"},{\"1\":\"Whole\",\"2\":\"2005\",\"3\":\"September\",\"4\":\"2.17000\"},{\"1\":\"Whole\",\"2\":\"2005\",\"3\":\"October\",\"4\":\"2.17000\"},{\"1\":\"Whole\",\"2\":\"2005\",\"3\":\"November\",\"4\":\"2.17000\"},{\"1\":\"Whole\",\"2\":\"2005\",\"3\":\"December\",\"4\":\"2.17000\"},{\"1\":\"B/S Breast\",\"2\":\"2005\",\"3\":\"January\",\"4\":\"6.44000\"},{\"1\":\"B/S Breast\",\"2\":\"2005\",\"3\":\"February\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2005\",\"3\":\"March\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2005\",\"3\":\"April\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2005\",\"3\":\"May\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2005\",\"3\":\"June\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2005\",\"3\":\"July\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2005\",\"3\":\"August\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2005\",\"3\":\"September\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2005\",\"3\":\"October\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2005\",\"3\":\"November\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2005\",\"3\":\"December\",\"4\":\"6.45500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2005\",\"3\":\"January\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2005\",\"3\":\"February\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2005\",\"3\":\"March\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2005\",\"3\":\"April\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2005\",\"3\":\"May\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2005\",\"3\":\"June\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2005\",\"3\":\"July\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2005\",\"3\":\"August\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2005\",\"3\":\"September\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2005\",\"3\":\"October\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2005\",\"3\":\"November\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2005\",\"3\":\"December\",\"4\":\"3.90500\"},{\"1\":\"Whole Legs\",\"2\":\"2005\",\"3\":\"January\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2005\",\"3\":\"February\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2005\",\"3\":\"March\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2005\",\"3\":\"April\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2005\",\"3\":\"May\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2005\",\"3\":\"June\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2005\",\"3\":\"July\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2005\",\"3\":\"August\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2005\",\"3\":\"September\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2005\",\"3\":\"October\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2005\",\"3\":\"November\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2005\",\"3\":\"December\",\"4\":\"2.03500\"},{\"1\":\"Thighs\",\"2\":\"2005\",\"3\":\"January\",\"4\":\"2.13000\"},{\"1\":\"Thighs\",\"2\":\"2005\",\"3\":\"February\",\"4\":\"2.22000\"},{\"1\":\"Thighs\",\"2\":\"2005\",\"3\":\"March\",\"4\":\"2.22000\"},{\"1\":\"Thighs\",\"2\":\"2005\",\"3\":\"April\",\"4\":\"2.22000\"},{\"1\":\"Thighs\",\"2\":\"2005\",\"3\":\"May\",\"4\":\"2.22000\"},{\"1\":\"Thighs\",\"2\":\"2005\",\"3\":\"June\",\"4\":\"2.22000\"},{\"1\":\"Thighs\",\"2\":\"2005\",\"3\":\"July\",\"4\":\"2.22000\"},{\"1\":\"Thighs\",\"2\":\"2005\",\"3\":\"August\",\"4\":\"2.22000\"},{\"1\":\"Thighs\",\"2\":\"2005\",\"3\":\"September\",\"4\":\"2.22000\"},{\"1\":\"Thighs\",\"2\":\"2005\",\"3\":\"October\",\"4\":\"2.22000\"},{\"1\":\"Thighs\",\"2\":\"2005\",\"3\":\"November\",\"4\":\"2.22000\"},{\"1\":\"Thighs\",\"2\":\"2005\",\"3\":\"December\",\"4\":\"2.22000\"},{\"1\":\"Whole\",\"2\":\"2004\",\"3\":\"January\",\"4\":\"1.97500\"},{\"1\":\"Whole\",\"2\":\"2004\",\"3\":\"February\",\"4\":\"1.97500\"},{\"1\":\"Whole\",\"2\":\"2004\",\"3\":\"March\",\"4\":\"2.09000\"},{\"1\":\"Whole\",\"2\":\"2004\",\"3\":\"April\",\"4\":\"2.12000\"},{\"1\":\"Whole\",\"2\":\"2004\",\"3\":\"May\",\"4\":\"2.14500\"},{\"1\":\"Whole\",\"2\":\"2004\",\"3\":\"June\",\"4\":\"2.16375\"},{\"1\":\"Whole\",\"2\":\"2004\",\"3\":\"July\",\"4\":\"2.17000\"},{\"1\":\"Whole\",\"2\":\"2004\",\"3\":\"August\",\"4\":\"2.17000\"},{\"1\":\"Whole\",\"2\":\"2004\",\"3\":\"September\",\"4\":\"2.17000\"},{\"1\":\"Whole\",\"2\":\"2004\",\"3\":\"October\",\"4\":\"2.17000\"},{\"1\":\"Whole\",\"2\":\"2004\",\"3\":\"November\",\"4\":\"2.17000\"},{\"1\":\"Whole\",\"2\":\"2004\",\"3\":\"December\",\"4\":\"2.17000\"},{\"1\":\"B/S Breast\",\"2\":\"2004\",\"3\":\"January\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2004\",\"3\":\"February\",\"4\":\"6.42500\"},{\"1\":\"B/S Breast\",\"2\":\"2004\",\"3\":\"March\",\"4\":\"6.42500\"},{\"1\":\"B/S Breast\",\"2\":\"2004\",\"3\":\"April\",\"4\":\"6.42500\"},{\"1\":\"B/S Breast\",\"2\":\"2004\",\"3\":\"May\",\"4\":\"6.42500\"},{\"1\":\"B/S Breast\",\"2\":\"2004\",\"3\":\"June\",\"4\":\"6.41000\"},{\"1\":\"B/S Breast\",\"2\":\"2004\",\"3\":\"July\",\"4\":\"6.42500\"},{\"1\":\"B/S Breast\",\"2\":\"2004\",\"3\":\"August\",\"4\":\"6.42500\"},{\"1\":\"B/S Breast\",\"2\":\"2004\",\"3\":\"September\",\"4\":\"6.42500\"},{\"1\":\"B/S Breast\",\"2\":\"2004\",\"3\":\"October\",\"4\":\"6.42500\"},{\"1\":\"B/S Breast\",\"2\":\"2004\",\"3\":\"November\",\"4\":\"6.42500\"},{\"1\":\"B/S Breast\",\"2\":\"2004\",\"3\":\"December\",\"4\":\"6.42500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2004\",\"3\":\"January\",\"4\":\"NA\"},{\"1\":\"Bone-in Breast\",\"2\":\"2004\",\"3\":\"February\",\"4\":\"NA\"},{\"1\":\"Bone-in Breast\",\"2\":\"2004\",\"3\":\"March\",\"4\":\"NA\"},{\"1\":\"Bone-in Breast\",\"2\":\"2004\",\"3\":\"April\",\"4\":\"NA\"},{\"1\":\"Bone-in Breast\",\"2\":\"2004\",\"3\":\"May\",\"4\":\"NA\"},{\"1\":\"Bone-in Breast\",\"2\":\"2004\",\"3\":\"June\",\"4\":\"NA\"},{\"1\":\"Bone-in Breast\",\"2\":\"2004\",\"3\":\"July\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2004\",\"3\":\"August\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2004\",\"3\":\"September\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2004\",\"3\":\"October\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2004\",\"3\":\"November\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2004\",\"3\":\"December\",\"4\":\"3.90500\"},{\"1\":\"Whole Legs\",\"2\":\"2004\",\"3\":\"January\",\"4\":\"1.93500\"},{\"1\":\"Whole Legs\",\"2\":\"2004\",\"3\":\"February\",\"4\":\"1.93500\"},{\"1\":\"Whole Legs\",\"2\":\"2004\",\"3\":\"March\",\"4\":\"1.93500\"},{\"1\":\"Whole Legs\",\"2\":\"2004\",\"3\":\"April\",\"4\":\"1.93500\"},{\"1\":\"Whole Legs\",\"2\":\"2004\",\"3\":\"May\",\"4\":\"1.93500\"},{\"1\":\"Whole Legs\",\"2\":\"2004\",\"3\":\"June\",\"4\":\"2.01875\"},{\"1\":\"Whole Legs\",\"2\":\"2004\",\"3\":\"July\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2004\",\"3\":\"August\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2004\",\"3\":\"September\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2004\",\"3\":\"October\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2004\",\"3\":\"November\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2004\",\"3\":\"December\",\"4\":\"2.03500\"},{\"1\":\"Thighs\",\"2\":\"2004\",\"3\":\"January\",\"4\":\"NA\"},{\"1\":\"Thighs\",\"2\":\"2004\",\"3\":\"February\",\"4\":\"2.03000\"},{\"1\":\"Thighs\",\"2\":\"2004\",\"3\":\"March\",\"4\":\"2.03000\"},{\"1\":\"Thighs\",\"2\":\"2004\",\"3\":\"April\",\"4\":\"2.03000\"},{\"1\":\"Thighs\",\"2\":\"2004\",\"3\":\"May\",\"4\":\"2.03000\"},{\"1\":\"Thighs\",\"2\":\"2004\",\"3\":\"June\",\"4\":\"2.00375\"},{\"1\":\"Thighs\",\"2\":\"2004\",\"3\":\"July\",\"4\":\"1.99500\"},{\"1\":\"Thighs\",\"2\":\"2004\",\"3\":\"August\",\"4\":\"1.99500\"},{\"1\":\"Thighs\",\"2\":\"2004\",\"3\":\"September\",\"4\":\"1.99500\"},{\"1\":\"Thighs\",\"2\":\"2004\",\"3\":\"October\",\"4\":\"1.99500\"},{\"1\":\"Thighs\",\"2\":\"2004\",\"3\":\"November\",\"4\":\"1.99500\"},{\"1\":\"Thighs\",\"2\":\"2004\",\"3\":\"December\",\"4\":\"1.99500\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n\n```{.r .cell-code}\nsummary(data)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   Product               Year         Month            Price_Dollar  \n Length:600         Min.   :2004   Length:600         Min.   :1.935  \n Class :character   1st Qu.:2006   Class :character   1st Qu.:2.150  \n Mode  :character   Median :2008   Mode  :character   Median :2.350  \n                    Mean   :2008                      Mean   :3.390  \n                    3rd Qu.:2011                      3rd Qu.:3.905  \n                    Max.   :2013                      Max.   :7.037  \n                                                      NA's   :7      \n```\n:::\n:::\n\nHere's what each column tells us:\n\n-   Product: This is a character type of data, which basically means it's text. It tells us the type of chicken product. We don't know exactly what types of chicken products are in the data set from this summary alone, so we would need to check the unique values or look at the original data documentation to get that info.\n\n-   Year: This is a numeric variable and it's pretty straightforward - it's the year of the observation. The years in this data set run from 2004 to 2013.\n\n-   Month: This is also a character type of data, and it tells us the month of the observation.\n\n-   Price_Dollar: This is a numeric variable that tells us the price of the chicken, in dollars. The price ranges from $1.935 to $7.037. Note that there are 7 prices missing in the data set, so we'd have to keep that in mind if we were analyzing the data.\n\n## Tidy Data (as needed)\n\nIs your data already tidy, or is there work to be done? Be sure to anticipate your end result to provide a sanity check, and document your work here.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Removing rows with missing Price_Dollar\ndata_clean <- data %>%\n  filter(!is.na(Price_Dollar))\n\n# View the cleaned data\ndata_clean\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"Product\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Year\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Month\"],\"name\":[3],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Price_Dollar\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"Whole\",\"2\":\"2013\",\"3\":\"January\",\"4\":\"2.38500\"},{\"1\":\"Whole\",\"2\":\"2013\",\"3\":\"February\",\"4\":\"2.38500\"},{\"1\":\"Whole\",\"2\":\"2013\",\"3\":\"March\",\"4\":\"2.38500\"},{\"1\":\"Whole\",\"2\":\"2013\",\"3\":\"April\",\"4\":\"2.38500\"},{\"1\":\"Whole\",\"2\":\"2013\",\"3\":\"May\",\"4\":\"2.38500\"},{\"1\":\"Whole\",\"2\":\"2013\",\"3\":\"June\",\"4\":\"2.38500\"},{\"1\":\"Whole\",\"2\":\"2013\",\"3\":\"July\",\"4\":\"2.38500\"},{\"1\":\"Whole\",\"2\":\"2013\",\"3\":\"August\",\"4\":\"2.38500\"},{\"1\":\"Whole\",\"2\":\"2013\",\"3\":\"September\",\"4\":\"2.38500\"},{\"1\":\"Whole\",\"2\":\"2013\",\"3\":\"October\",\"4\":\"2.38500\"},{\"1\":\"Whole\",\"2\":\"2013\",\"3\":\"November\",\"4\":\"2.38500\"},{\"1\":\"Whole\",\"2\":\"2013\",\"3\":\"December\",\"4\":\"2.38500\"},{\"1\":\"B/S Breast\",\"2\":\"2013\",\"3\":\"January\",\"4\":\"7.03750\"},{\"1\":\"B/S Breast\",\"2\":\"2013\",\"3\":\"February\",\"4\":\"7.03750\"},{\"1\":\"B/S Breast\",\"2\":\"2013\",\"3\":\"March\",\"4\":\"7.03750\"},{\"1\":\"B/S Breast\",\"2\":\"2013\",\"3\":\"April\",\"4\":\"7.03750\"},{\"1\":\"B/S Breast\",\"2\":\"2013\",\"3\":\"May\",\"4\":\"7.03750\"},{\"1\":\"B/S Breast\",\"2\":\"2013\",\"3\":\"June\",\"4\":\"7.03750\"},{\"1\":\"B/S Breast\",\"2\":\"2013\",\"3\":\"July\",\"4\":\"7.03750\"},{\"1\":\"B/S Breast\",\"2\":\"2013\",\"3\":\"August\",\"4\":\"7.03750\"},{\"1\":\"B/S Breast\",\"2\":\"2013\",\"3\":\"September\",\"4\":\"7.03750\"},{\"1\":\"B/S Breast\",\"2\":\"2013\",\"3\":\"October\",\"4\":\"7.03750\"},{\"1\":\"B/S Breast\",\"2\":\"2013\",\"3\":\"November\",\"4\":\"7.03750\"},{\"1\":\"B/S Breast\",\"2\":\"2013\",\"3\":\"December\",\"4\":\"7.03750\"},{\"1\":\"Bone-in Breast\",\"2\":\"2013\",\"3\":\"January\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2013\",\"3\":\"February\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2013\",\"3\":\"March\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2013\",\"3\":\"April\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2013\",\"3\":\"May\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2013\",\"3\":\"June\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2013\",\"3\":\"July\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2013\",\"3\":\"August\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2013\",\"3\":\"September\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2013\",\"3\":\"October\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2013\",\"3\":\"November\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2013\",\"3\":\"December\",\"4\":\"3.90500\"},{\"1\":\"Whole Legs\",\"2\":\"2013\",\"3\":\"January\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2013\",\"3\":\"February\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2013\",\"3\":\"March\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2013\",\"3\":\"April\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2013\",\"3\":\"May\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2013\",\"3\":\"June\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2013\",\"3\":\"July\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2013\",\"3\":\"August\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2013\",\"3\":\"September\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2013\",\"3\":\"October\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2013\",\"3\":\"November\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2013\",\"3\":\"December\",\"4\":\"2.03500\"},{\"1\":\"Thighs\",\"2\":\"2013\",\"3\":\"January\",\"4\":\"2.16250\"},{\"1\":\"Thighs\",\"2\":\"2013\",\"3\":\"February\",\"4\":\"2.16250\"},{\"1\":\"Thighs\",\"2\":\"2013\",\"3\":\"March\",\"4\":\"2.16250\"},{\"1\":\"Thighs\",\"2\":\"2013\",\"3\":\"April\",\"4\":\"2.16250\"},{\"1\":\"Thighs\",\"2\":\"2013\",\"3\":\"May\",\"4\":\"2.16250\"},{\"1\":\"Thighs\",\"2\":\"2013\",\"3\":\"June\",\"4\":\"2.16250\"},{\"1\":\"Thighs\",\"2\":\"2013\",\"3\":\"July\",\"4\":\"2.16250\"},{\"1\":\"Thighs\",\"2\":\"2013\",\"3\":\"August\",\"4\":\"2.16250\"},{\"1\":\"Thighs\",\"2\":\"2013\",\"3\":\"September\",\"4\":\"2.16250\"},{\"1\":\"Thighs\",\"2\":\"2013\",\"3\":\"October\",\"4\":\"2.16250\"},{\"1\":\"Thighs\",\"2\":\"2013\",\"3\":\"November\",\"4\":\"2.16250\"},{\"1\":\"Thighs\",\"2\":\"2013\",\"3\":\"December\",\"4\":\"2.16250\"},{\"1\":\"Whole\",\"2\":\"2012\",\"3\":\"January\",\"4\":\"2.35000\"},{\"1\":\"Whole\",\"2\":\"2012\",\"3\":\"February\",\"4\":\"2.38500\"},{\"1\":\"Whole\",\"2\":\"2012\",\"3\":\"March\",\"4\":\"2.38500\"},{\"1\":\"Whole\",\"2\":\"2012\",\"3\":\"April\",\"4\":\"2.38500\"},{\"1\":\"Whole\",\"2\":\"2012\",\"3\":\"May\",\"4\":\"2.38500\"},{\"1\":\"Whole\",\"2\":\"2012\",\"3\":\"June\",\"4\":\"2.38500\"},{\"1\":\"Whole\",\"2\":\"2012\",\"3\":\"July\",\"4\":\"2.38500\"},{\"1\":\"Whole\",\"2\":\"2012\",\"3\":\"August\",\"4\":\"2.38500\"},{\"1\":\"Whole\",\"2\":\"2012\",\"3\":\"September\",\"4\":\"2.38500\"},{\"1\":\"Whole\",\"2\":\"2012\",\"3\":\"October\",\"4\":\"2.38500\"},{\"1\":\"Whole\",\"2\":\"2012\",\"3\":\"November\",\"4\":\"2.38500\"},{\"1\":\"Whole\",\"2\":\"2012\",\"3\":\"December\",\"4\":\"2.38500\"},{\"1\":\"B/S Breast\",\"2\":\"2012\",\"3\":\"January\",\"4\":\"6.37500\"},{\"1\":\"B/S Breast\",\"2\":\"2012\",\"3\":\"February\",\"4\":\"7.00000\"},{\"1\":\"B/S Breast\",\"2\":\"2012\",\"3\":\"March\",\"4\":\"7.00000\"},{\"1\":\"B/S Breast\",\"2\":\"2012\",\"3\":\"April\",\"4\":\"7.00000\"},{\"1\":\"B/S Breast\",\"2\":\"2012\",\"3\":\"May\",\"4\":\"7.00000\"},{\"1\":\"B/S Breast\",\"2\":\"2012\",\"3\":\"June\",\"4\":\"7.00000\"},{\"1\":\"B/S Breast\",\"2\":\"2012\",\"3\":\"July\",\"4\":\"7.00000\"},{\"1\":\"B/S Breast\",\"2\":\"2012\",\"3\":\"August\",\"4\":\"7.00000\"},{\"1\":\"B/S Breast\",\"2\":\"2012\",\"3\":\"September\",\"4\":\"7.00000\"},{\"1\":\"B/S Breast\",\"2\":\"2012\",\"3\":\"October\",\"4\":\"7.00000\"},{\"1\":\"B/S Breast\",\"2\":\"2012\",\"3\":\"November\",\"4\":\"7.03750\"},{\"1\":\"B/S Breast\",\"2\":\"2012\",\"3\":\"December\",\"4\":\"7.03750\"},{\"1\":\"Bone-in Breast\",\"2\":\"2012\",\"3\":\"January\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2012\",\"3\":\"February\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2012\",\"3\":\"March\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2012\",\"3\":\"April\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2012\",\"3\":\"May\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2012\",\"3\":\"June\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2012\",\"3\":\"July\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2012\",\"3\":\"August\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2012\",\"3\":\"September\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2012\",\"3\":\"October\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2012\",\"3\":\"November\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2012\",\"3\":\"December\",\"4\":\"3.90500\"},{\"1\":\"Whole Legs\",\"2\":\"2012\",\"3\":\"January\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2012\",\"3\":\"February\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2012\",\"3\":\"March\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2012\",\"3\":\"April\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2012\",\"3\":\"May\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2012\",\"3\":\"June\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2012\",\"3\":\"July\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2012\",\"3\":\"August\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2012\",\"3\":\"September\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2012\",\"3\":\"October\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2012\",\"3\":\"November\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2012\",\"3\":\"December\",\"4\":\"2.03500\"},{\"1\":\"Thighs\",\"2\":\"2012\",\"3\":\"January\",\"4\":\"2.15000\"},{\"1\":\"Thighs\",\"2\":\"2012\",\"3\":\"February\",\"4\":\"2.15000\"},{\"1\":\"Thighs\",\"2\":\"2012\",\"3\":\"March\",\"4\":\"2.15000\"},{\"1\":\"Thighs\",\"2\":\"2012\",\"3\":\"April\",\"4\":\"2.15000\"},{\"1\":\"Thighs\",\"2\":\"2012\",\"3\":\"May\",\"4\":\"2.15000\"},{\"1\":\"Thighs\",\"2\":\"2012\",\"3\":\"June\",\"4\":\"2.15000\"},{\"1\":\"Thighs\",\"2\":\"2012\",\"3\":\"July\",\"4\":\"2.15000\"},{\"1\":\"Thighs\",\"2\":\"2012\",\"3\":\"August\",\"4\":\"2.16250\"},{\"1\":\"Thighs\",\"2\":\"2012\",\"3\":\"September\",\"4\":\"2.16250\"},{\"1\":\"Thighs\",\"2\":\"2012\",\"3\":\"October\",\"4\":\"2.16250\"},{\"1\":\"Thighs\",\"2\":\"2012\",\"3\":\"November\",\"4\":\"2.16250\"},{\"1\":\"Thighs\",\"2\":\"2012\",\"3\":\"December\",\"4\":\"2.16250\"},{\"1\":\"Whole\",\"2\":\"2011\",\"3\":\"January\",\"4\":\"2.35000\"},{\"1\":\"Whole\",\"2\":\"2011\",\"3\":\"February\",\"4\":\"2.35000\"},{\"1\":\"Whole\",\"2\":\"2011\",\"3\":\"March\",\"4\":\"2.35000\"},{\"1\":\"Whole\",\"2\":\"2011\",\"3\":\"April\",\"4\":\"2.35000\"},{\"1\":\"Whole\",\"2\":\"2011\",\"3\":\"May\",\"4\":\"2.35000\"},{\"1\":\"Whole\",\"2\":\"2011\",\"3\":\"June\",\"4\":\"2.35000\"},{\"1\":\"Whole\",\"2\":\"2011\",\"3\":\"July\",\"4\":\"2.35000\"},{\"1\":\"Whole\",\"2\":\"2011\",\"3\":\"August\",\"4\":\"2.35000\"},{\"1\":\"Whole\",\"2\":\"2011\",\"3\":\"September\",\"4\":\"2.35000\"},{\"1\":\"Whole\",\"2\":\"2011\",\"3\":\"October\",\"4\":\"2.35000\"},{\"1\":\"Whole\",\"2\":\"2011\",\"3\":\"November\",\"4\":\"2.35000\"},{\"1\":\"Whole\",\"2\":\"2011\",\"3\":\"December\",\"4\":\"2.35000\"},{\"1\":\"B/S Breast\",\"2\":\"2011\",\"3\":\"January\",\"4\":\"6.37500\"},{\"1\":\"B/S Breast\",\"2\":\"2011\",\"3\":\"February\",\"4\":\"6.37500\"},{\"1\":\"B/S Breast\",\"2\":\"2011\",\"3\":\"March\",\"4\":\"6.37500\"},{\"1\":\"B/S Breast\",\"2\":\"2011\",\"3\":\"April\",\"4\":\"6.37500\"},{\"1\":\"B/S Breast\",\"2\":\"2011\",\"3\":\"May\",\"4\":\"6.37500\"},{\"1\":\"B/S Breast\",\"2\":\"2011\",\"3\":\"June\",\"4\":\"6.37500\"},{\"1\":\"B/S Breast\",\"2\":\"2011\",\"3\":\"July\",\"4\":\"6.37500\"},{\"1\":\"B/S Breast\",\"2\":\"2011\",\"3\":\"August\",\"4\":\"6.37500\"},{\"1\":\"B/S Breast\",\"2\":\"2011\",\"3\":\"September\",\"4\":\"6.37500\"},{\"1\":\"B/S Breast\",\"2\":\"2011\",\"3\":\"October\",\"4\":\"6.37500\"},{\"1\":\"B/S Breast\",\"2\":\"2011\",\"3\":\"November\",\"4\":\"6.37500\"},{\"1\":\"B/S Breast\",\"2\":\"2011\",\"3\":\"December\",\"4\":\"6.37500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2011\",\"3\":\"January\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2011\",\"3\":\"February\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2011\",\"3\":\"March\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2011\",\"3\":\"April\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2011\",\"3\":\"May\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2011\",\"3\":\"June\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2011\",\"3\":\"July\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2011\",\"3\":\"August\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2011\",\"3\":\"September\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2011\",\"3\":\"October\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2011\",\"3\":\"November\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2011\",\"3\":\"December\",\"4\":\"3.90500\"},{\"1\":\"Whole Legs\",\"2\":\"2011\",\"3\":\"January\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2011\",\"3\":\"February\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2011\",\"3\":\"March\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2011\",\"3\":\"April\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2011\",\"3\":\"May\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2011\",\"3\":\"June\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2011\",\"3\":\"July\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2011\",\"3\":\"August\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2011\",\"3\":\"September\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2011\",\"3\":\"October\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2011\",\"3\":\"November\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2011\",\"3\":\"December\",\"4\":\"2.03500\"},{\"1\":\"Thighs\",\"2\":\"2011\",\"3\":\"January\",\"4\":\"2.15000\"},{\"1\":\"Thighs\",\"2\":\"2011\",\"3\":\"February\",\"4\":\"2.15000\"},{\"1\":\"Thighs\",\"2\":\"2011\",\"3\":\"March\",\"4\":\"2.15000\"},{\"1\":\"Thighs\",\"2\":\"2011\",\"3\":\"April\",\"4\":\"2.15000\"},{\"1\":\"Thighs\",\"2\":\"2011\",\"3\":\"May\",\"4\":\"2.15000\"},{\"1\":\"Thighs\",\"2\":\"2011\",\"3\":\"June\",\"4\":\"2.15000\"},{\"1\":\"Thighs\",\"2\":\"2011\",\"3\":\"July\",\"4\":\"2.15000\"},{\"1\":\"Thighs\",\"2\":\"2011\",\"3\":\"August\",\"4\":\"2.15000\"},{\"1\":\"Thighs\",\"2\":\"2011\",\"3\":\"September\",\"4\":\"2.15000\"},{\"1\":\"Thighs\",\"2\":\"2011\",\"3\":\"October\",\"4\":\"2.15000\"},{\"1\":\"Thighs\",\"2\":\"2011\",\"3\":\"November\",\"4\":\"2.15000\"},{\"1\":\"Thighs\",\"2\":\"2011\",\"3\":\"December\",\"4\":\"2.15000\"},{\"1\":\"Whole\",\"2\":\"2010\",\"3\":\"January\",\"4\":\"2.48000\"},{\"1\":\"Whole\",\"2\":\"2010\",\"3\":\"February\",\"4\":\"2.48000\"},{\"1\":\"Whole\",\"2\":\"2010\",\"3\":\"March\",\"4\":\"2.48000\"},{\"1\":\"Whole\",\"2\":\"2010\",\"3\":\"April\",\"4\":\"2.41500\"},{\"1\":\"Whole\",\"2\":\"2010\",\"3\":\"May\",\"4\":\"2.35000\"},{\"1\":\"Whole\",\"2\":\"2010\",\"3\":\"June\",\"4\":\"2.35000\"},{\"1\":\"Whole\",\"2\":\"2010\",\"3\":\"July\",\"4\":\"2.41500\"},{\"1\":\"Whole\",\"2\":\"2010\",\"3\":\"August\",\"4\":\"2.35000\"},{\"1\":\"Whole\",\"2\":\"2010\",\"3\":\"September\",\"4\":\"2.35000\"},{\"1\":\"Whole\",\"2\":\"2010\",\"3\":\"October\",\"4\":\"2.35000\"},{\"1\":\"Whole\",\"2\":\"2010\",\"3\":\"November\",\"4\":\"2.35000\"},{\"1\":\"Whole\",\"2\":\"2010\",\"3\":\"December\",\"4\":\"2.35000\"},{\"1\":\"B/S Breast\",\"2\":\"2010\",\"3\":\"January\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2010\",\"3\":\"February\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2010\",\"3\":\"March\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2010\",\"3\":\"April\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2010\",\"3\":\"May\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2010\",\"3\":\"June\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2010\",\"3\":\"July\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2010\",\"3\":\"August\",\"4\":\"6.42300\"},{\"1\":\"B/S Breast\",\"2\":\"2010\",\"3\":\"September\",\"4\":\"6.37500\"},{\"1\":\"B/S Breast\",\"2\":\"2010\",\"3\":\"October\",\"4\":\"6.37500\"},{\"1\":\"B/S Breast\",\"2\":\"2010\",\"3\":\"November\",\"4\":\"6.37500\"},{\"1\":\"B/S Breast\",\"2\":\"2010\",\"3\":\"December\",\"4\":\"6.37500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2010\",\"3\":\"January\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2010\",\"3\":\"February\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2010\",\"3\":\"March\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2010\",\"3\":\"April\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2010\",\"3\":\"May\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2010\",\"3\":\"June\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2010\",\"3\":\"July\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2010\",\"3\":\"August\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2010\",\"3\":\"September\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2010\",\"3\":\"October\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2010\",\"3\":\"November\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2010\",\"3\":\"December\",\"4\":\"3.90500\"},{\"1\":\"Whole Legs\",\"2\":\"2010\",\"3\":\"January\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2010\",\"3\":\"February\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2010\",\"3\":\"March\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2010\",\"3\":\"April\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2010\",\"3\":\"May\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2010\",\"3\":\"June\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2010\",\"3\":\"July\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2010\",\"3\":\"August\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2010\",\"3\":\"September\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2010\",\"3\":\"October\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2010\",\"3\":\"November\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2010\",\"3\":\"December\",\"4\":\"2.03500\"},{\"1\":\"Thighs\",\"2\":\"2010\",\"3\":\"January\",\"4\":\"2.22000\"},{\"1\":\"Thighs\",\"2\":\"2010\",\"3\":\"February\",\"4\":\"2.22000\"},{\"1\":\"Thighs\",\"2\":\"2010\",\"3\":\"March\",\"4\":\"2.22000\"},{\"1\":\"Thighs\",\"2\":\"2010\",\"3\":\"April\",\"4\":\"2.22000\"},{\"1\":\"Thighs\",\"2\":\"2010\",\"3\":\"May\",\"4\":\"2.22000\"},{\"1\":\"Thighs\",\"2\":\"2010\",\"3\":\"June\",\"4\":\"2.22000\"},{\"1\":\"Thighs\",\"2\":\"2010\",\"3\":\"July\",\"4\":\"2.22000\"},{\"1\":\"Thighs\",\"2\":\"2010\",\"3\":\"August\",\"4\":\"2.19200\"},{\"1\":\"Thighs\",\"2\":\"2010\",\"3\":\"September\",\"4\":\"2.15000\"},{\"1\":\"Thighs\",\"2\":\"2010\",\"3\":\"October\",\"4\":\"2.15000\"},{\"1\":\"Thighs\",\"2\":\"2010\",\"3\":\"November\",\"4\":\"2.15000\"},{\"1\":\"Thighs\",\"2\":\"2010\",\"3\":\"December\",\"4\":\"2.15000\"},{\"1\":\"Whole\",\"2\":\"2009\",\"3\":\"January\",\"4\":\"2.48000\"},{\"1\":\"Whole\",\"2\":\"2009\",\"3\":\"February\",\"4\":\"2.48000\"},{\"1\":\"Whole\",\"2\":\"2009\",\"3\":\"March\",\"4\":\"2.48000\"},{\"1\":\"Whole\",\"2\":\"2009\",\"3\":\"April\",\"4\":\"2.48000\"},{\"1\":\"Whole\",\"2\":\"2009\",\"3\":\"May\",\"4\":\"2.48000\"},{\"1\":\"Whole\",\"2\":\"2009\",\"3\":\"June\",\"4\":\"2.48000\"},{\"1\":\"Whole\",\"2\":\"2009\",\"3\":\"July\",\"4\":\"2.48000\"},{\"1\":\"Whole\",\"2\":\"2009\",\"3\":\"August\",\"4\":\"2.48000\"},{\"1\":\"Whole\",\"2\":\"2009\",\"3\":\"September\",\"4\":\"2.48000\"},{\"1\":\"Whole\",\"2\":\"2009\",\"3\":\"October\",\"4\":\"2.48000\"},{\"1\":\"Whole\",\"2\":\"2009\",\"3\":\"November\",\"4\":\"2.48000\"},{\"1\":\"Whole\",\"2\":\"2009\",\"3\":\"December\",\"4\":\"2.48000\"},{\"1\":\"B/S Breast\",\"2\":\"2009\",\"3\":\"January\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2009\",\"3\":\"February\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2009\",\"3\":\"March\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2009\",\"3\":\"April\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2009\",\"3\":\"May\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2009\",\"3\":\"June\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2009\",\"3\":\"July\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2009\",\"3\":\"August\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2009\",\"3\":\"September\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2009\",\"3\":\"October\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2009\",\"3\":\"November\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2009\",\"3\":\"December\",\"4\":\"6.45500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2009\",\"3\":\"January\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2009\",\"3\":\"February\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2009\",\"3\":\"March\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2009\",\"3\":\"April\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2009\",\"3\":\"May\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2009\",\"3\":\"June\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2009\",\"3\":\"July\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2009\",\"3\":\"August\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2009\",\"3\":\"September\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2009\",\"3\":\"October\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2009\",\"3\":\"November\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2009\",\"3\":\"December\",\"4\":\"3.90500\"},{\"1\":\"Whole Legs\",\"2\":\"2009\",\"3\":\"January\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2009\",\"3\":\"February\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2009\",\"3\":\"March\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2009\",\"3\":\"April\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2009\",\"3\":\"May\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2009\",\"3\":\"June\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2009\",\"3\":\"July\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2009\",\"3\":\"August\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2009\",\"3\":\"September\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2009\",\"3\":\"October\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2009\",\"3\":\"November\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2009\",\"3\":\"December\",\"4\":\"2.03500\"},{\"1\":\"Thighs\",\"2\":\"2009\",\"3\":\"January\",\"4\":\"2.22000\"},{\"1\":\"Thighs\",\"2\":\"2009\",\"3\":\"February\",\"4\":\"2.22000\"},{\"1\":\"Thighs\",\"2\":\"2009\",\"3\":\"March\",\"4\":\"2.22000\"},{\"1\":\"Thighs\",\"2\":\"2009\",\"3\":\"April\",\"4\":\"2.22000\"},{\"1\":\"Thighs\",\"2\":\"2009\",\"3\":\"May\",\"4\":\"2.22000\"},{\"1\":\"Thighs\",\"2\":\"2009\",\"3\":\"June\",\"4\":\"2.22000\"},{\"1\":\"Thighs\",\"2\":\"2009\",\"3\":\"July\",\"4\":\"2.22000\"},{\"1\":\"Thighs\",\"2\":\"2009\",\"3\":\"August\",\"4\":\"2.22000\"},{\"1\":\"Thighs\",\"2\":\"2009\",\"3\":\"September\",\"4\":\"2.22000\"},{\"1\":\"Thighs\",\"2\":\"2009\",\"3\":\"October\",\"4\":\"2.22000\"},{\"1\":\"Thighs\",\"2\":\"2009\",\"3\":\"November\",\"4\":\"2.22000\"},{\"1\":\"Thighs\",\"2\":\"2009\",\"3\":\"December\",\"4\":\"2.22000\"},{\"1\":\"Whole\",\"2\":\"2008\",\"3\":\"January\",\"4\":\"2.20500\"},{\"1\":\"Whole\",\"2\":\"2008\",\"3\":\"February\",\"4\":\"2.20500\"},{\"1\":\"Whole\",\"2\":\"2008\",\"3\":\"March\",\"4\":\"2.20500\"},{\"1\":\"Whole\",\"2\":\"2008\",\"3\":\"April\",\"4\":\"2.20500\"},{\"1\":\"Whole\",\"2\":\"2008\",\"3\":\"May\",\"4\":\"2.20500\"},{\"1\":\"Whole\",\"2\":\"2008\",\"3\":\"June\",\"4\":\"2.48000\"},{\"1\":\"Whole\",\"2\":\"2008\",\"3\":\"July\",\"4\":\"2.48000\"},{\"1\":\"Whole\",\"2\":\"2008\",\"3\":\"August\",\"4\":\"2.48000\"},{\"1\":\"Whole\",\"2\":\"2008\",\"3\":\"September\",\"4\":\"2.48000\"},{\"1\":\"Whole\",\"2\":\"2008\",\"3\":\"October\",\"4\":\"2.48000\"},{\"1\":\"Whole\",\"2\":\"2008\",\"3\":\"November\",\"4\":\"2.48000\"},{\"1\":\"Whole\",\"2\":\"2008\",\"3\":\"December\",\"4\":\"2.48000\"},{\"1\":\"B/S Breast\",\"2\":\"2008\",\"3\":\"January\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2008\",\"3\":\"February\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2008\",\"3\":\"March\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2008\",\"3\":\"April\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2008\",\"3\":\"May\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2008\",\"3\":\"June\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2008\",\"3\":\"July\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2008\",\"3\":\"August\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2008\",\"3\":\"September\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2008\",\"3\":\"October\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2008\",\"3\":\"November\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2008\",\"3\":\"December\",\"4\":\"6.45500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2008\",\"3\":\"January\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2008\",\"3\":\"February\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2008\",\"3\":\"March\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2008\",\"3\":\"April\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2008\",\"3\":\"May\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2008\",\"3\":\"June\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2008\",\"3\":\"July\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2008\",\"3\":\"August\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2008\",\"3\":\"September\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2008\",\"3\":\"October\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2008\",\"3\":\"November\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2008\",\"3\":\"December\",\"4\":\"3.90500\"},{\"1\":\"Whole Legs\",\"2\":\"2008\",\"3\":\"January\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2008\",\"3\":\"February\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2008\",\"3\":\"March\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2008\",\"3\":\"April\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2008\",\"3\":\"May\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2008\",\"3\":\"June\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2008\",\"3\":\"July\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2008\",\"3\":\"August\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2008\",\"3\":\"September\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2008\",\"3\":\"October\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2008\",\"3\":\"November\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2008\",\"3\":\"December\",\"4\":\"2.03500\"},{\"1\":\"Thighs\",\"2\":\"2008\",\"3\":\"January\",\"4\":\"2.22000\"},{\"1\":\"Thighs\",\"2\":\"2008\",\"3\":\"February\",\"4\":\"2.22000\"},{\"1\":\"Thighs\",\"2\":\"2008\",\"3\":\"March\",\"4\":\"2.22000\"},{\"1\":\"Thighs\",\"2\":\"2008\",\"3\":\"April\",\"4\":\"2.22000\"},{\"1\":\"Thighs\",\"2\":\"2008\",\"3\":\"May\",\"4\":\"2.22000\"},{\"1\":\"Thighs\",\"2\":\"2008\",\"3\":\"June\",\"4\":\"2.22000\"},{\"1\":\"Thighs\",\"2\":\"2008\",\"3\":\"July\",\"4\":\"2.22000\"},{\"1\":\"Thighs\",\"2\":\"2008\",\"3\":\"August\",\"4\":\"2.22000\"},{\"1\":\"Thighs\",\"2\":\"2008\",\"3\":\"September\",\"4\":\"2.22000\"},{\"1\":\"Thighs\",\"2\":\"2008\",\"3\":\"October\",\"4\":\"2.22000\"},{\"1\":\"Thighs\",\"2\":\"2008\",\"3\":\"November\",\"4\":\"2.22000\"},{\"1\":\"Thighs\",\"2\":\"2008\",\"3\":\"December\",\"4\":\"2.22000\"},{\"1\":\"Whole\",\"2\":\"2007\",\"3\":\"January\",\"4\":\"2.20500\"},{\"1\":\"Whole\",\"2\":\"2007\",\"3\":\"February\",\"4\":\"2.20500\"},{\"1\":\"Whole\",\"2\":\"2007\",\"3\":\"March\",\"4\":\"2.20500\"},{\"1\":\"Whole\",\"2\":\"2007\",\"3\":\"April\",\"4\":\"2.20500\"},{\"1\":\"Whole\",\"2\":\"2007\",\"3\":\"May\",\"4\":\"2.20500\"},{\"1\":\"Whole\",\"2\":\"2007\",\"3\":\"June\",\"4\":\"2.20500\"},{\"1\":\"Whole\",\"2\":\"2007\",\"3\":\"July\",\"4\":\"2.20500\"},{\"1\":\"Whole\",\"2\":\"2007\",\"3\":\"August\",\"4\":\"2.20500\"},{\"1\":\"Whole\",\"2\":\"2007\",\"3\":\"September\",\"4\":\"2.20500\"},{\"1\":\"Whole\",\"2\":\"2007\",\"3\":\"October\",\"4\":\"2.20500\"},{\"1\":\"Whole\",\"2\":\"2007\",\"3\":\"November\",\"4\":\"2.20500\"},{\"1\":\"Whole\",\"2\":\"2007\",\"3\":\"December\",\"4\":\"2.20500\"},{\"1\":\"B/S Breast\",\"2\":\"2007\",\"3\":\"January\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2007\",\"3\":\"February\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2007\",\"3\":\"March\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2007\",\"3\":\"April\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2007\",\"3\":\"May\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2007\",\"3\":\"June\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2007\",\"3\":\"July\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2007\",\"3\":\"August\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2007\",\"3\":\"September\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2007\",\"3\":\"October\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2007\",\"3\":\"November\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2007\",\"3\":\"December\",\"4\":\"6.45500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2007\",\"3\":\"January\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2007\",\"3\":\"February\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2007\",\"3\":\"March\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2007\",\"3\":\"April\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2007\",\"3\":\"May\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2007\",\"3\":\"June\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2007\",\"3\":\"July\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2007\",\"3\":\"August\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2007\",\"3\":\"September\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2007\",\"3\":\"October\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2007\",\"3\":\"November\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2007\",\"3\":\"December\",\"4\":\"3.90500\"},{\"1\":\"Whole Legs\",\"2\":\"2007\",\"3\":\"January\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2007\",\"3\":\"February\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2007\",\"3\":\"March\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2007\",\"3\":\"April\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2007\",\"3\":\"May\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2007\",\"3\":\"June\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2007\",\"3\":\"July\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2007\",\"3\":\"August\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2007\",\"3\":\"September\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2007\",\"3\":\"October\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2007\",\"3\":\"November\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2007\",\"3\":\"December\",\"4\":\"2.03500\"},{\"1\":\"Thighs\",\"2\":\"2007\",\"3\":\"January\",\"4\":\"2.22000\"},{\"1\":\"Thighs\",\"2\":\"2007\",\"3\":\"February\",\"4\":\"2.22000\"},{\"1\":\"Thighs\",\"2\":\"2007\",\"3\":\"March\",\"4\":\"2.22000\"},{\"1\":\"Thighs\",\"2\":\"2007\",\"3\":\"April\",\"4\":\"2.22000\"},{\"1\":\"Thighs\",\"2\":\"2007\",\"3\":\"May\",\"4\":\"2.22000\"},{\"1\":\"Thighs\",\"2\":\"2007\",\"3\":\"June\",\"4\":\"2.22000\"},{\"1\":\"Thighs\",\"2\":\"2007\",\"3\":\"July\",\"4\":\"2.22000\"},{\"1\":\"Thighs\",\"2\":\"2007\",\"3\":\"August\",\"4\":\"2.22000\"},{\"1\":\"Thighs\",\"2\":\"2007\",\"3\":\"September\",\"4\":\"2.22000\"},{\"1\":\"Thighs\",\"2\":\"2007\",\"3\":\"October\",\"4\":\"2.22000\"},{\"1\":\"Thighs\",\"2\":\"2007\",\"3\":\"November\",\"4\":\"2.22000\"},{\"1\":\"Thighs\",\"2\":\"2007\",\"3\":\"December\",\"4\":\"2.22000\"},{\"1\":\"Whole\",\"2\":\"2006\",\"3\":\"January\",\"4\":\"2.17000\"},{\"1\":\"Whole\",\"2\":\"2006\",\"3\":\"February\",\"4\":\"2.17000\"},{\"1\":\"Whole\",\"2\":\"2006\",\"3\":\"March\",\"4\":\"2.19625\"},{\"1\":\"Whole\",\"2\":\"2006\",\"3\":\"April\",\"4\":\"2.20500\"},{\"1\":\"Whole\",\"2\":\"2006\",\"3\":\"May\",\"4\":\"2.20500\"},{\"1\":\"Whole\",\"2\":\"2006\",\"3\":\"June\",\"4\":\"2.20500\"},{\"1\":\"Whole\",\"2\":\"2006\",\"3\":\"July\",\"4\":\"2.20500\"},{\"1\":\"Whole\",\"2\":\"2006\",\"3\":\"August\",\"4\":\"2.20500\"},{\"1\":\"Whole\",\"2\":\"2006\",\"3\":\"September\",\"4\":\"2.20500\"},{\"1\":\"Whole\",\"2\":\"2006\",\"3\":\"October\",\"4\":\"2.20500\"},{\"1\":\"Whole\",\"2\":\"2006\",\"3\":\"November\",\"4\":\"2.20500\"},{\"1\":\"Whole\",\"2\":\"2006\",\"3\":\"December\",\"4\":\"2.20500\"},{\"1\":\"B/S Breast\",\"2\":\"2006\",\"3\":\"January\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2006\",\"3\":\"February\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2006\",\"3\":\"March\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2006\",\"3\":\"April\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2006\",\"3\":\"May\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2006\",\"3\":\"June\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2006\",\"3\":\"July\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2006\",\"3\":\"August\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2006\",\"3\":\"September\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2006\",\"3\":\"October\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2006\",\"3\":\"November\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2006\",\"3\":\"December\",\"4\":\"6.45500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2006\",\"3\":\"January\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2006\",\"3\":\"February\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2006\",\"3\":\"March\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2006\",\"3\":\"April\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2006\",\"3\":\"May\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2006\",\"3\":\"June\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2006\",\"3\":\"July\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2006\",\"3\":\"August\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2006\",\"3\":\"September\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2006\",\"3\":\"October\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2006\",\"3\":\"November\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2006\",\"3\":\"December\",\"4\":\"3.90500\"},{\"1\":\"Whole Legs\",\"2\":\"2006\",\"3\":\"January\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2006\",\"3\":\"February\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2006\",\"3\":\"March\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2006\",\"3\":\"April\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2006\",\"3\":\"May\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2006\",\"3\":\"June\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2006\",\"3\":\"July\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2006\",\"3\":\"August\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2006\",\"3\":\"September\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2006\",\"3\":\"October\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2006\",\"3\":\"November\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2006\",\"3\":\"December\",\"4\":\"2.03500\"},{\"1\":\"Thighs\",\"2\":\"2006\",\"3\":\"January\",\"4\":\"2.22000\"},{\"1\":\"Thighs\",\"2\":\"2006\",\"3\":\"February\",\"4\":\"2.22000\"},{\"1\":\"Thighs\",\"2\":\"2006\",\"3\":\"March\",\"4\":\"2.22000\"},{\"1\":\"Thighs\",\"2\":\"2006\",\"3\":\"April\",\"4\":\"2.22000\"},{\"1\":\"Thighs\",\"2\":\"2006\",\"3\":\"May\",\"4\":\"2.22000\"},{\"1\":\"Thighs\",\"2\":\"2006\",\"3\":\"June\",\"4\":\"2.22000\"},{\"1\":\"Thighs\",\"2\":\"2006\",\"3\":\"July\",\"4\":\"2.22000\"},{\"1\":\"Thighs\",\"2\":\"2006\",\"3\":\"August\",\"4\":\"2.22000\"},{\"1\":\"Thighs\",\"2\":\"2006\",\"3\":\"September\",\"4\":\"2.22000\"},{\"1\":\"Thighs\",\"2\":\"2006\",\"3\":\"October\",\"4\":\"2.22000\"},{\"1\":\"Thighs\",\"2\":\"2006\",\"3\":\"November\",\"4\":\"2.22000\"},{\"1\":\"Thighs\",\"2\":\"2006\",\"3\":\"December\",\"4\":\"2.22000\"},{\"1\":\"Whole\",\"2\":\"2005\",\"3\":\"January\",\"4\":\"2.17000\"},{\"1\":\"Whole\",\"2\":\"2005\",\"3\":\"February\",\"4\":\"2.17000\"},{\"1\":\"Whole\",\"2\":\"2005\",\"3\":\"March\",\"4\":\"2.17000\"},{\"1\":\"Whole\",\"2\":\"2005\",\"3\":\"April\",\"4\":\"2.17000\"},{\"1\":\"Whole\",\"2\":\"2005\",\"3\":\"May\",\"4\":\"2.17000\"},{\"1\":\"Whole\",\"2\":\"2005\",\"3\":\"June\",\"4\":\"2.17000\"},{\"1\":\"Whole\",\"2\":\"2005\",\"3\":\"July\",\"4\":\"2.17000\"},{\"1\":\"Whole\",\"2\":\"2005\",\"3\":\"August\",\"4\":\"2.17000\"},{\"1\":\"Whole\",\"2\":\"2005\",\"3\":\"September\",\"4\":\"2.17000\"},{\"1\":\"Whole\",\"2\":\"2005\",\"3\":\"October\",\"4\":\"2.17000\"},{\"1\":\"Whole\",\"2\":\"2005\",\"3\":\"November\",\"4\":\"2.17000\"},{\"1\":\"Whole\",\"2\":\"2005\",\"3\":\"December\",\"4\":\"2.17000\"},{\"1\":\"B/S Breast\",\"2\":\"2005\",\"3\":\"January\",\"4\":\"6.44000\"},{\"1\":\"B/S Breast\",\"2\":\"2005\",\"3\":\"February\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2005\",\"3\":\"March\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2005\",\"3\":\"April\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2005\",\"3\":\"May\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2005\",\"3\":\"June\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2005\",\"3\":\"July\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2005\",\"3\":\"August\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2005\",\"3\":\"September\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2005\",\"3\":\"October\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2005\",\"3\":\"November\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2005\",\"3\":\"December\",\"4\":\"6.45500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2005\",\"3\":\"January\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2005\",\"3\":\"February\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2005\",\"3\":\"March\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2005\",\"3\":\"April\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2005\",\"3\":\"May\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2005\",\"3\":\"June\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2005\",\"3\":\"July\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2005\",\"3\":\"August\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2005\",\"3\":\"September\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2005\",\"3\":\"October\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2005\",\"3\":\"November\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2005\",\"3\":\"December\",\"4\":\"3.90500\"},{\"1\":\"Whole Legs\",\"2\":\"2005\",\"3\":\"January\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2005\",\"3\":\"February\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2005\",\"3\":\"March\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2005\",\"3\":\"April\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2005\",\"3\":\"May\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2005\",\"3\":\"June\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2005\",\"3\":\"July\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2005\",\"3\":\"August\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2005\",\"3\":\"September\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2005\",\"3\":\"October\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2005\",\"3\":\"November\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2005\",\"3\":\"December\",\"4\":\"2.03500\"},{\"1\":\"Thighs\",\"2\":\"2005\",\"3\":\"January\",\"4\":\"2.13000\"},{\"1\":\"Thighs\",\"2\":\"2005\",\"3\":\"February\",\"4\":\"2.22000\"},{\"1\":\"Thighs\",\"2\":\"2005\",\"3\":\"March\",\"4\":\"2.22000\"},{\"1\":\"Thighs\",\"2\":\"2005\",\"3\":\"April\",\"4\":\"2.22000\"},{\"1\":\"Thighs\",\"2\":\"2005\",\"3\":\"May\",\"4\":\"2.22000\"},{\"1\":\"Thighs\",\"2\":\"2005\",\"3\":\"June\",\"4\":\"2.22000\"},{\"1\":\"Thighs\",\"2\":\"2005\",\"3\":\"July\",\"4\":\"2.22000\"},{\"1\":\"Thighs\",\"2\":\"2005\",\"3\":\"August\",\"4\":\"2.22000\"},{\"1\":\"Thighs\",\"2\":\"2005\",\"3\":\"September\",\"4\":\"2.22000\"},{\"1\":\"Thighs\",\"2\":\"2005\",\"3\":\"October\",\"4\":\"2.22000\"},{\"1\":\"Thighs\",\"2\":\"2005\",\"3\":\"November\",\"4\":\"2.22000\"},{\"1\":\"Thighs\",\"2\":\"2005\",\"3\":\"December\",\"4\":\"2.22000\"},{\"1\":\"Whole\",\"2\":\"2004\",\"3\":\"January\",\"4\":\"1.97500\"},{\"1\":\"Whole\",\"2\":\"2004\",\"3\":\"February\",\"4\":\"1.97500\"},{\"1\":\"Whole\",\"2\":\"2004\",\"3\":\"March\",\"4\":\"2.09000\"},{\"1\":\"Whole\",\"2\":\"2004\",\"3\":\"April\",\"4\":\"2.12000\"},{\"1\":\"Whole\",\"2\":\"2004\",\"3\":\"May\",\"4\":\"2.14500\"},{\"1\":\"Whole\",\"2\":\"2004\",\"3\":\"June\",\"4\":\"2.16375\"},{\"1\":\"Whole\",\"2\":\"2004\",\"3\":\"July\",\"4\":\"2.17000\"},{\"1\":\"Whole\",\"2\":\"2004\",\"3\":\"August\",\"4\":\"2.17000\"},{\"1\":\"Whole\",\"2\":\"2004\",\"3\":\"September\",\"4\":\"2.17000\"},{\"1\":\"Whole\",\"2\":\"2004\",\"3\":\"October\",\"4\":\"2.17000\"},{\"1\":\"Whole\",\"2\":\"2004\",\"3\":\"November\",\"4\":\"2.17000\"},{\"1\":\"Whole\",\"2\":\"2004\",\"3\":\"December\",\"4\":\"2.17000\"},{\"1\":\"B/S Breast\",\"2\":\"2004\",\"3\":\"January\",\"4\":\"6.45500\"},{\"1\":\"B/S Breast\",\"2\":\"2004\",\"3\":\"February\",\"4\":\"6.42500\"},{\"1\":\"B/S Breast\",\"2\":\"2004\",\"3\":\"March\",\"4\":\"6.42500\"},{\"1\":\"B/S Breast\",\"2\":\"2004\",\"3\":\"April\",\"4\":\"6.42500\"},{\"1\":\"B/S Breast\",\"2\":\"2004\",\"3\":\"May\",\"4\":\"6.42500\"},{\"1\":\"B/S Breast\",\"2\":\"2004\",\"3\":\"June\",\"4\":\"6.41000\"},{\"1\":\"B/S Breast\",\"2\":\"2004\",\"3\":\"July\",\"4\":\"6.42500\"},{\"1\":\"B/S Breast\",\"2\":\"2004\",\"3\":\"August\",\"4\":\"6.42500\"},{\"1\":\"B/S Breast\",\"2\":\"2004\",\"3\":\"September\",\"4\":\"6.42500\"},{\"1\":\"B/S Breast\",\"2\":\"2004\",\"3\":\"October\",\"4\":\"6.42500\"},{\"1\":\"B/S Breast\",\"2\":\"2004\",\"3\":\"November\",\"4\":\"6.42500\"},{\"1\":\"B/S Breast\",\"2\":\"2004\",\"3\":\"December\",\"4\":\"6.42500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2004\",\"3\":\"July\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2004\",\"3\":\"August\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2004\",\"3\":\"September\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2004\",\"3\":\"October\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2004\",\"3\":\"November\",\"4\":\"3.90500\"},{\"1\":\"Bone-in Breast\",\"2\":\"2004\",\"3\":\"December\",\"4\":\"3.90500\"},{\"1\":\"Whole Legs\",\"2\":\"2004\",\"3\":\"January\",\"4\":\"1.93500\"},{\"1\":\"Whole Legs\",\"2\":\"2004\",\"3\":\"February\",\"4\":\"1.93500\"},{\"1\":\"Whole Legs\",\"2\":\"2004\",\"3\":\"March\",\"4\":\"1.93500\"},{\"1\":\"Whole Legs\",\"2\":\"2004\",\"3\":\"April\",\"4\":\"1.93500\"},{\"1\":\"Whole Legs\",\"2\":\"2004\",\"3\":\"May\",\"4\":\"1.93500\"},{\"1\":\"Whole Legs\",\"2\":\"2004\",\"3\":\"June\",\"4\":\"2.01875\"},{\"1\":\"Whole Legs\",\"2\":\"2004\",\"3\":\"July\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2004\",\"3\":\"August\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2004\",\"3\":\"September\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2004\",\"3\":\"October\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2004\",\"3\":\"November\",\"4\":\"2.03500\"},{\"1\":\"Whole Legs\",\"2\":\"2004\",\"3\":\"December\",\"4\":\"2.03500\"},{\"1\":\"Thighs\",\"2\":\"2004\",\"3\":\"February\",\"4\":\"2.03000\"},{\"1\":\"Thighs\",\"2\":\"2004\",\"3\":\"March\",\"4\":\"2.03000\"},{\"1\":\"Thighs\",\"2\":\"2004\",\"3\":\"April\",\"4\":\"2.03000\"},{\"1\":\"Thighs\",\"2\":\"2004\",\"3\":\"May\",\"4\":\"2.03000\"},{\"1\":\"Thighs\",\"2\":\"2004\",\"3\":\"June\",\"4\":\"2.00375\"},{\"1\":\"Thighs\",\"2\":\"2004\",\"3\":\"July\",\"4\":\"1.99500\"},{\"1\":\"Thighs\",\"2\":\"2004\",\"3\":\"August\",\"4\":\"1.99500\"},{\"1\":\"Thighs\",\"2\":\"2004\",\"3\":\"September\",\"4\":\"1.99500\"},{\"1\":\"Thighs\",\"2\":\"2004\",\"3\":\"October\",\"4\":\"1.99500\"},{\"1\":\"Thighs\",\"2\":\"2004\",\"3\":\"November\",\"4\":\"1.99500\"},{\"1\":\"Thighs\",\"2\":\"2004\",\"3\":\"December\",\"4\":\"1.99500\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\nLooking at the summary of our data. It seems that our data alreaady be in a tidy format. Howere, we have some missing valuees in the \"price_Dollar\" column that we want to handle. we use code: $!is.na$ to remove the missing data, now we only have 593 more rows.\n\n\n## Identify variables that need to be mutated\n\nAre there any variables that require mutation to be usable in your analysis stream? For example, are all time variables correctly coded as dates? Are all string variables reduced and cleaned to sensible categories? Do you need to turn any variables into factors and reorder for ease of graphics and visualization?\n\nDocument your work here.\n\n## Mutate variable\n\nFirst off, we've got two time-related columns: Year and Month. Right now, Year is a number and Month is a string (basically text). But if we're gonna do some cool stuff like look at trends over time, it might be easier if we can smush these two together into one handy \"date\" type of variable.\n\nSecond, we've got this Product column. Now, this one is also text right now, but depending on what we wanna do, we might want to change this to what R calls a \"factor.\" Factors are pretty neat because they let R know that this is a categorical variable. This can make creating plots or doing stats stuff a bit smoother.\n\nSo, let's do this! Let's make these changes to our data!\n\n::: {.cell}\n\n```{.r .cell-code}\n# Combine Year and Month into a single Date variable\n# Note: we assume the day of each observation to be the 1st\ndata <- data %>% mutate(Date = ymd(paste(Year, Month, \"01\", sep = \"-\")))\n\n# Convert Product to a factor\ndata$Product <- as.factor(data$Product)\n\n#drop the original Year and Month columns\ndata <- data %>% select(-Year, -Month)\n\n# Display the data\ndata\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"Product\"],\"name\":[1],\"type\":[\"fct\"],\"align\":[\"left\"]},{\"label\":[\"Price_Dollar\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Date\"],\"name\":[3],\"type\":[\"date\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"Whole\",\"2\":\"2.38500\",\"3\":\"2013-01-01\"},{\"1\":\"Whole\",\"2\":\"2.38500\",\"3\":\"2013-02-01\"},{\"1\":\"Whole\",\"2\":\"2.38500\",\"3\":\"2013-03-01\"},{\"1\":\"Whole\",\"2\":\"2.38500\",\"3\":\"2013-04-01\"},{\"1\":\"Whole\",\"2\":\"2.38500\",\"3\":\"2013-05-01\"},{\"1\":\"Whole\",\"2\":\"2.38500\",\"3\":\"2013-06-01\"},{\"1\":\"Whole\",\"2\":\"2.38500\",\"3\":\"2013-07-01\"},{\"1\":\"Whole\",\"2\":\"2.38500\",\"3\":\"2013-08-01\"},{\"1\":\"Whole\",\"2\":\"2.38500\",\"3\":\"2013-09-01\"},{\"1\":\"Whole\",\"2\":\"2.38500\",\"3\":\"2013-10-01\"},{\"1\":\"Whole\",\"2\":\"2.38500\",\"3\":\"2013-11-01\"},{\"1\":\"Whole\",\"2\":\"2.38500\",\"3\":\"2013-12-01\"},{\"1\":\"B/S Breast\",\"2\":\"7.03750\",\"3\":\"2013-01-01\"},{\"1\":\"B/S Breast\",\"2\":\"7.03750\",\"3\":\"2013-02-01\"},{\"1\":\"B/S Breast\",\"2\":\"7.03750\",\"3\":\"2013-03-01\"},{\"1\":\"B/S Breast\",\"2\":\"7.03750\",\"3\":\"2013-04-01\"},{\"1\":\"B/S Breast\",\"2\":\"7.03750\",\"3\":\"2013-05-01\"},{\"1\":\"B/S Breast\",\"2\":\"7.03750\",\"3\":\"2013-06-01\"},{\"1\":\"B/S Breast\",\"2\":\"7.03750\",\"3\":\"2013-07-01\"},{\"1\":\"B/S Breast\",\"2\":\"7.03750\",\"3\":\"2013-08-01\"},{\"1\":\"B/S Breast\",\"2\":\"7.03750\",\"3\":\"2013-09-01\"},{\"1\":\"B/S Breast\",\"2\":\"7.03750\",\"3\":\"2013-10-01\"},{\"1\":\"B/S Breast\",\"2\":\"7.03750\",\"3\":\"2013-11-01\"},{\"1\":\"B/S Breast\",\"2\":\"7.03750\",\"3\":\"2013-12-01\"},{\"1\":\"Bone-in Breast\",\"2\":\"3.90500\",\"3\":\"2013-01-01\"},{\"1\":\"Bone-in Breast\",\"2\":\"3.90500\",\"3\":\"2013-02-01\"},{\"1\":\"Bone-in Breast\",\"2\":\"3.90500\",\"3\":\"2013-03-01\"},{\"1\":\"Bone-in Breast\",\"2\":\"3.90500\",\"3\":\"2013-04-01\"},{\"1\":\"Bone-in Breast\",\"2\":\"3.90500\",\"3\":\"2013-05-01\"},{\"1\":\"Bone-in Breast\",\"2\":\"3.90500\",\"3\":\"2013-06-01\"},{\"1\":\"Bone-in Breast\",\"2\":\"3.90500\",\"3\":\"2013-07-01\"},{\"1\":\"Bone-in Breast\",\"2\":\"3.90500\",\"3\":\"2013-08-01\"},{\"1\":\"Bone-in Breast\",\"2\":\"3.90500\",\"3\":\"2013-09-01\"},{\"1\":\"Bone-in Breast\",\"2\":\"3.90500\",\"3\":\"2013-10-01\"},{\"1\":\"Bone-in Breast\",\"2\":\"3.90500\",\"3\":\"2013-11-01\"},{\"1\":\"Bone-in Breast\",\"2\":\"3.90500\",\"3\":\"2013-12-01\"},{\"1\":\"Whole Legs\",\"2\":\"2.03500\",\"3\":\"2013-01-01\"},{\"1\":\"Whole Legs\",\"2\":\"2.03500\",\"3\":\"2013-02-01\"},{\"1\":\"Whole Legs\",\"2\":\"2.03500\",\"3\":\"2013-03-01\"},{\"1\":\"Whole Legs\",\"2\":\"2.03500\",\"3\":\"2013-04-01\"},{\"1\":\"Whole Legs\",\"2\":\"2.03500\",\"3\":\"2013-05-01\"},{\"1\":\"Whole Legs\",\"2\":\"2.03500\",\"3\":\"2013-06-01\"},{\"1\":\"Whole Legs\",\"2\":\"2.03500\",\"3\":\"2013-07-01\"},{\"1\":\"Whole Legs\",\"2\":\"2.03500\",\"3\":\"2013-08-01\"},{\"1\":\"Whole Legs\",\"2\":\"2.03500\",\"3\":\"2013-09-01\"},{\"1\":\"Whole Legs\",\"2\":\"2.03500\",\"3\":\"2013-10-01\"},{\"1\":\"Whole Legs\",\"2\":\"2.03500\",\"3\":\"2013-11-01\"},{\"1\":\"Whole Legs\",\"2\":\"2.03500\",\"3\":\"2013-12-01\"},{\"1\":\"Thighs\",\"2\":\"2.16250\",\"3\":\"2013-01-01\"},{\"1\":\"Thighs\",\"2\":\"2.16250\",\"3\":\"2013-02-01\"},{\"1\":\"Thighs\",\"2\":\"2.16250\",\"3\":\"2013-03-01\"},{\"1\":\"Thighs\",\"2\":\"2.16250\",\"3\":\"2013-04-01\"},{\"1\":\"Thighs\",\"2\":\"2.16250\",\"3\":\"2013-05-01\"},{\"1\":\"Thighs\",\"2\":\"2.16250\",\"3\":\"2013-06-01\"},{\"1\":\"Thighs\",\"2\":\"2.16250\",\"3\":\"2013-07-01\"},{\"1\":\"Thighs\",\"2\":\"2.16250\",\"3\":\"2013-08-01\"},{\"1\":\"Thighs\",\"2\":\"2.16250\",\"3\":\"2013-09-01\"},{\"1\":\"Thighs\",\"2\":\"2.16250\",\"3\":\"2013-10-01\"},{\"1\":\"Thighs\",\"2\":\"2.16250\",\"3\":\"2013-11-01\"},{\"1\":\"Thighs\",\"2\":\"2.16250\",\"3\":\"2013-12-01\"},{\"1\":\"Whole\",\"2\":\"2.35000\",\"3\":\"2012-01-01\"},{\"1\":\"Whole\",\"2\":\"2.38500\",\"3\":\"2012-02-01\"},{\"1\":\"Whole\",\"2\":\"2.38500\",\"3\":\"2012-03-01\"},{\"1\":\"Whole\",\"2\":\"2.38500\",\"3\":\"2012-04-01\"},{\"1\":\"Whole\",\"2\":\"2.38500\",\"3\":\"2012-05-01\"},{\"1\":\"Whole\",\"2\":\"2.38500\",\"3\":\"2012-06-01\"},{\"1\":\"Whole\",\"2\":\"2.38500\",\"3\":\"2012-07-01\"},{\"1\":\"Whole\",\"2\":\"2.38500\",\"3\":\"2012-08-01\"},{\"1\":\"Whole\",\"2\":\"2.38500\",\"3\":\"2012-09-01\"},{\"1\":\"Whole\",\"2\":\"2.38500\",\"3\":\"2012-10-01\"},{\"1\":\"Whole\",\"2\":\"2.38500\",\"3\":\"2012-11-01\"},{\"1\":\"Whole\",\"2\":\"2.38500\",\"3\":\"2012-12-01\"},{\"1\":\"B/S Breast\",\"2\":\"6.37500\",\"3\":\"2012-01-01\"},{\"1\":\"B/S Breast\",\"2\":\"7.00000\",\"3\":\"2012-02-01\"},{\"1\":\"B/S Breast\",\"2\":\"7.00000\",\"3\":\"2012-03-01\"},{\"1\":\"B/S Breast\",\"2\":\"7.00000\",\"3\":\"2012-04-01\"},{\"1\":\"B/S Breast\",\"2\":\"7.00000\",\"3\":\"2012-05-01\"},{\"1\":\"B/S Breast\",\"2\":\"7.00000\",\"3\":\"2012-06-01\"},{\"1\":\"B/S Breast\",\"2\":\"7.00000\",\"3\":\"2012-07-01\"},{\"1\":\"B/S Breast\",\"2\":\"7.00000\",\"3\":\"2012-08-01\"},{\"1\":\"B/S Breast\",\"2\":\"7.00000\",\"3\":\"2012-09-01\"},{\"1\":\"B/S Breast\",\"2\":\"7.00000\",\"3\":\"2012-10-01\"},{\"1\":\"B/S Breast\",\"2\":\"7.03750\",\"3\":\"2012-11-01\"},{\"1\":\"B/S Breast\",\"2\":\"7.03750\",\"3\":\"2012-12-01\"},{\"1\":\"Bone-in Breast\",\"2\":\"3.90500\",\"3\":\"2012-01-01\"},{\"1\":\"Bone-in Breast\",\"2\":\"3.90500\",\"3\":\"2012-02-01\"},{\"1\":\"Bone-in Breast\",\"2\":\"3.90500\",\"3\":\"2012-03-01\"},{\"1\":\"Bone-in Breast\",\"2\":\"3.90500\",\"3\":\"2012-04-01\"},{\"1\":\"Bone-in Breast\",\"2\":\"3.90500\",\"3\":\"2012-05-01\"},{\"1\":\"Bone-in Breast\",\"2\":\"3.90500\",\"3\":\"2012-06-01\"},{\"1\":\"Bone-in Breast\",\"2\":\"3.90500\",\"3\":\"2012-07-01\"},{\"1\":\"Bone-in Breast\",\"2\":\"3.90500\",\"3\":\"2012-08-01\"},{\"1\":\"Bone-in Breast\",\"2\":\"3.90500\",\"3\":\"2012-09-01\"},{\"1\":\"Bone-in Breast\",\"2\":\"3.90500\",\"3\":\"2012-10-01\"},{\"1\":\"Bone-in Breast\",\"2\":\"3.90500\",\"3\":\"2012-11-01\"},{\"1\":\"Bone-in Breast\",\"2\":\"3.90500\",\"3\":\"2012-12-01\"},{\"1\":\"Whole Legs\",\"2\":\"2.03500\",\"3\":\"2012-01-01\"},{\"1\":\"Whole Legs\",\"2\":\"2.03500\",\"3\":\"2012-02-01\"},{\"1\":\"Whole Legs\",\"2\":\"2.03500\",\"3\":\"2012-03-01\"},{\"1\":\"Whole Legs\",\"2\":\"2.03500\",\"3\":\"2012-04-01\"},{\"1\":\"Whole Legs\",\"2\":\"2.03500\",\"3\":\"2012-05-01\"},{\"1\":\"Whole Legs\",\"2\":\"2.03500\",\"3\":\"2012-06-01\"},{\"1\":\"Whole Legs\",\"2\":\"2.03500\",\"3\":\"2012-07-01\"},{\"1\":\"Whole Legs\",\"2\":\"2.03500\",\"3\":\"2012-08-01\"},{\"1\":\"Whole Legs\",\"2\":\"2.03500\",\"3\":\"2012-09-01\"},{\"1\":\"Whole Legs\",\"2\":\"2.03500\",\"3\":\"2012-10-01\"},{\"1\":\"Whole Legs\",\"2\":\"2.03500\",\"3\":\"2012-11-01\"},{\"1\":\"Whole Legs\",\"2\":\"2.03500\",\"3\":\"2012-12-01\"},{\"1\":\"Thighs\",\"2\":\"2.15000\",\"3\":\"2012-01-01\"},{\"1\":\"Thighs\",\"2\":\"2.15000\",\"3\":\"2012-02-01\"},{\"1\":\"Thighs\",\"2\":\"2.15000\",\"3\":\"2012-03-01\"},{\"1\":\"Thighs\",\"2\":\"2.15000\",\"3\":\"2012-04-01\"},{\"1\":\"Thighs\",\"2\":\"2.15000\",\"3\":\"2012-05-01\"},{\"1\":\"Thighs\",\"2\":\"2.15000\",\"3\":\"2012-06-01\"},{\"1\":\"Thighs\",\"2\":\"2.15000\",\"3\":\"2012-07-01\"},{\"1\":\"Thighs\",\"2\":\"2.16250\",\"3\":\"2012-08-01\"},{\"1\":\"Thighs\",\"2\":\"2.16250\",\"3\":\"2012-09-01\"},{\"1\":\"Thighs\",\"2\":\"2.16250\",\"3\":\"2012-10-01\"},{\"1\":\"Thighs\",\"2\":\"2.16250\",\"3\":\"2012-11-01\"},{\"1\":\"Thighs\",\"2\":\"2.16250\",\"3\":\"2012-12-01\"},{\"1\":\"Whole\",\"2\":\"2.35000\",\"3\":\"2011-01-01\"},{\"1\":\"Whole\",\"2\":\"2.35000\",\"3\":\"2011-02-01\"},{\"1\":\"Whole\",\"2\":\"2.35000\",\"3\":\"2011-03-01\"},{\"1\":\"Whole\",\"2\":\"2.35000\",\"3\":\"2011-04-01\"},{\"1\":\"Whole\",\"2\":\"2.35000\",\"3\":\"2011-05-01\"},{\"1\":\"Whole\",\"2\":\"2.35000\",\"3\":\"2011-06-01\"},{\"1\":\"Whole\",\"2\":\"2.35000\",\"3\":\"2011-07-01\"},{\"1\":\"Whole\",\"2\":\"2.35000\",\"3\":\"2011-08-01\"},{\"1\":\"Whole\",\"2\":\"2.35000\",\"3\":\"2011-09-01\"},{\"1\":\"Whole\",\"2\":\"2.35000\",\"3\":\"2011-10-01\"},{\"1\":\"Whole\",\"2\":\"2.35000\",\"3\":\"2011-11-01\"},{\"1\":\"Whole\",\"2\":\"2.35000\",\"3\":\"2011-12-01\"},{\"1\":\"B/S Breast\",\"2\":\"6.37500\",\"3\":\"2011-01-01\"},{\"1\":\"B/S Breast\",\"2\":\"6.37500\",\"3\":\"2011-02-01\"},{\"1\":\"B/S Breast\",\"2\":\"6.37500\",\"3\":\"2011-03-01\"},{\"1\":\"B/S Breast\",\"2\":\"6.37500\",\"3\":\"2011-04-01\"},{\"1\":\"B/S Breast\",\"2\":\"6.37500\",\"3\":\"2011-05-01\"},{\"1\":\"B/S Breast\",\"2\":\"6.37500\",\"3\":\"2011-06-01\"},{\"1\":\"B/S Breast\",\"2\":\"6.37500\",\"3\":\"2011-07-01\"},{\"1\":\"B/S Breast\",\"2\":\"6.37500\",\"3\":\"2011-08-01\"},{\"1\":\"B/S Breast\",\"2\":\"6.37500\",\"3\":\"2011-09-01\"},{\"1\":\"B/S Breast\",\"2\":\"6.37500\",\"3\":\"2011-10-01\"},{\"1\":\"B/S Breast\",\"2\":\"6.37500\",\"3\":\"2011-11-01\"},{\"1\":\"B/S Breast\",\"2\":\"6.37500\",\"3\":\"2011-12-01\"},{\"1\":\"Bone-in Breast\",\"2\":\"3.90500\",\"3\":\"2011-01-01\"},{\"1\":\"Bone-in Breast\",\"2\":\"3.90500\",\"3\":\"2011-02-01\"},{\"1\":\"Bone-in Breast\",\"2\":\"3.90500\",\"3\":\"2011-03-01\"},{\"1\":\"Bone-in Breast\",\"2\":\"3.90500\",\"3\":\"2011-04-01\"},{\"1\":\"Bone-in Breast\",\"2\":\"3.90500\",\"3\":\"2011-05-01\"},{\"1\":\"Bone-in Breast\",\"2\":\"3.90500\",\"3\":\"2011-06-01\"},{\"1\":\"Bone-in Breast\",\"2\":\"3.90500\",\"3\":\"2011-07-01\"},{\"1\":\"Bone-in Breast\",\"2\":\"3.90500\",\"3\":\"2011-08-01\"},{\"1\":\"Bone-in Breast\",\"2\":\"3.90500\",\"3\":\"2011-09-01\"},{\"1\":\"Bone-in Breast\",\"2\":\"3.90500\",\"3\":\"2011-10-01\"},{\"1\":\"Bone-in Breast\",\"2\":\"3.90500\",\"3\":\"2011-11-01\"},{\"1\":\"Bone-in Breast\",\"2\":\"3.90500\",\"3\":\"2011-12-01\"},{\"1\":\"Whole Legs\",\"2\":\"2.03500\",\"3\":\"2011-01-01\"},{\"1\":\"Whole Legs\",\"2\":\"2.03500\",\"3\":\"2011-02-01\"},{\"1\":\"Whole Legs\",\"2\":\"2.03500\",\"3\":\"2011-03-01\"},{\"1\":\"Whole Legs\",\"2\":\"2.03500\",\"3\":\"2011-04-01\"},{\"1\":\"Whole Legs\",\"2\":\"2.03500\",\"3\":\"2011-05-01\"},{\"1\":\"Whole Legs\",\"2\":\"2.03500\",\"3\":\"2011-06-01\"},{\"1\":\"Whole Legs\",\"2\":\"2.03500\",\"3\":\"2011-07-01\"},{\"1\":\"Whole Legs\",\"2\":\"2.03500\",\"3\":\"2011-08-01\"},{\"1\":\"Whole Legs\",\"2\":\"2.03500\",\"3\":\"2011-09-01\"},{\"1\":\"Whole Legs\",\"2\":\"2.03500\",\"3\":\"2011-10-01\"},{\"1\":\"Whole Legs\",\"2\":\"2.03500\",\"3\":\"2011-11-01\"},{\"1\":\"Whole Legs\",\"2\":\"2.03500\",\"3\":\"2011-12-01\"},{\"1\":\"Thighs\",\"2\":\"2.15000\",\"3\":\"2011-01-01\"},{\"1\":\"Thighs\",\"2\":\"2.15000\",\"3\":\"2011-02-01\"},{\"1\":\"Thighs\",\"2\":\"2.15000\",\"3\":\"2011-03-01\"},{\"1\":\"Thighs\",\"2\":\"2.15000\",\"3\":\"2011-04-01\"},{\"1\":\"Thighs\",\"2\":\"2.15000\",\"3\":\"2011-05-01\"},{\"1\":\"Thighs\",\"2\":\"2.15000\",\"3\":\"2011-06-01\"},{\"1\":\"Thighs\",\"2\":\"2.15000\",\"3\":\"2011-07-01\"},{\"1\":\"Thighs\",\"2\":\"2.15000\",\"3\":\"2011-08-01\"},{\"1\":\"Thighs\",\"2\":\"2.15000\",\"3\":\"2011-09-01\"},{\"1\":\"Thighs\",\"2\":\"2.15000\",\"3\":\"2011-10-01\"},{\"1\":\"Thighs\",\"2\":\"2.15000\",\"3\":\"2011-11-01\"},{\"1\":\"Thighs\",\"2\":\"2.15000\",\"3\":\"2011-12-01\"},{\"1\":\"Whole\",\"2\":\"2.48000\",\"3\":\"2010-01-01\"},{\"1\":\"Whole\",\"2\":\"2.48000\",\"3\":\"2010-02-01\"},{\"1\":\"Whole\",\"2\":\"2.48000\",\"3\":\"2010-03-01\"},{\"1\":\"Whole\",\"2\":\"2.41500\",\"3\":\"2010-04-01\"},{\"1\":\"Whole\",\"2\":\"2.35000\",\"3\":\"2010-05-01\"},{\"1\":\"Whole\",\"2\":\"2.35000\",\"3\":\"2010-06-01\"},{\"1\":\"Whole\",\"2\":\"2.41500\",\"3\":\"2010-07-01\"},{\"1\":\"Whole\",\"2\":\"2.35000\",\"3\":\"2010-08-01\"},{\"1\":\"Whole\",\"2\":\"2.35000\",\"3\":\"2010-09-01\"},{\"1\":\"Whole\",\"2\":\"2.35000\",\"3\":\"2010-10-01\"},{\"1\":\"Whole\",\"2\":\"2.35000\",\"3\":\"2010-11-01\"},{\"1\":\"Whole\",\"2\":\"2.35000\",\"3\":\"2010-12-01\"},{\"1\":\"B/S Breast\",\"2\":\"6.45500\",\"3\":\"2010-01-01\"},{\"1\":\"B/S Breast\",\"2\":\"6.45500\",\"3\":\"2010-02-01\"},{\"1\":\"B/S Breast\",\"2\":\"6.45500\",\"3\":\"2010-03-01\"},{\"1\":\"B/S Breast\",\"2\":\"6.45500\",\"3\":\"2010-04-01\"},{\"1\":\"B/S Breast\",\"2\":\"6.45500\",\"3\":\"2010-05-01\"},{\"1\":\"B/S Breast\",\"2\":\"6.45500\",\"3\":\"2010-06-01\"},{\"1\":\"B/S Breast\",\"2\":\"6.45500\",\"3\":\"2010-07-01\"},{\"1\":\"B/S Breast\",\"2\":\"6.42300\",\"3\":\"2010-08-01\"},{\"1\":\"B/S Breast\",\"2\":\"6.37500\",\"3\":\"2010-09-01\"},{\"1\":\"B/S Breast\",\"2\":\"6.37500\",\"3\":\"2010-10-01\"},{\"1\":\"B/S Breast\",\"2\":\"6.37500\",\"3\":\"2010-11-01\"},{\"1\":\"B/S Breast\",\"2\":\"6.37500\",\"3\":\"2010-12-01\"},{\"1\":\"Bone-in Breast\",\"2\":\"3.90500\",\"3\":\"2010-01-01\"},{\"1\":\"Bone-in Breast\",\"2\":\"3.90500\",\"3\":\"2010-02-01\"},{\"1\":\"Bone-in Breast\",\"2\":\"3.90500\",\"3\":\"2010-03-01\"},{\"1\":\"Bone-in Breast\",\"2\":\"3.90500\",\"3\":\"2010-04-01\"},{\"1\":\"Bone-in Breast\",\"2\":\"3.90500\",\"3\":\"2010-05-01\"},{\"1\":\"Bone-in Breast\",\"2\":\"3.90500\",\"3\":\"2010-06-01\"},{\"1\":\"Bone-in Breast\",\"2\":\"3.90500\",\"3\":\"2010-07-01\"},{\"1\":\"Bone-in Breast\",\"2\":\"3.90500\",\"3\":\"2010-08-01\"},{\"1\":\"Bone-in Breast\",\"2\":\"3.90500\",\"3\":\"2010-09-01\"},{\"1\":\"Bone-in Breast\",\"2\":\"3.90500\",\"3\":\"2010-10-01\"},{\"1\":\"Bone-in Breast\",\"2\":\"3.90500\",\"3\":\"2010-11-01\"},{\"1\":\"Bone-in Breast\",\"2\":\"3.90500\",\"3\":\"2010-12-01\"},{\"1\":\"Whole Legs\",\"2\":\"2.03500\",\"3\":\"2010-01-01\"},{\"1\":\"Whole Legs\",\"2\":\"2.03500\",\"3\":\"2010-02-01\"},{\"1\":\"Whole Legs\",\"2\":\"2.03500\",\"3\":\"2010-03-01\"},{\"1\":\"Whole Legs\",\"2\":\"2.03500\",\"3\":\"2010-04-01\"},{\"1\":\"Whole Legs\",\"2\":\"2.03500\",\"3\":\"2010-05-01\"},{\"1\":\"Whole Legs\",\"2\":\"2.03500\",\"3\":\"2010-06-01\"},{\"1\":\"Whole Legs\",\"2\":\"2.03500\",\"3\":\"2010-07-01\"},{\"1\":\"Whole Legs\",\"2\":\"2.03500\",\"3\":\"2010-08-01\"},{\"1\":\"Whole Legs\",\"2\":\"2.03500\",\"3\":\"2010-09-01\"},{\"1\":\"Whole Legs\",\"2\":\"2.03500\",\"3\":\"2010-10-01\"},{\"1\":\"Whole Legs\",\"2\":\"2.03500\",\"3\":\"2010-11-01\"},{\"1\":\"Whole Legs\",\"2\":\"2.03500\",\"3\":\"2010-12-01\"},{\"1\":\"Thighs\",\"2\":\"2.22000\",\"3\":\"2010-01-01\"},{\"1\":\"Thighs\",\"2\":\"2.22000\",\"3\":\"2010-02-01\"},{\"1\":\"Thighs\",\"2\":\"2.22000\",\"3\":\"2010-03-01\"},{\"1\":\"Thighs\",\"2\":\"2.22000\",\"3\":\"2010-04-01\"},{\"1\":\"Thighs\",\"2\":\"2.22000\",\"3\":\"2010-05-01\"},{\"1\":\"Thighs\",\"2\":\"2.22000\",\"3\":\"2010-06-01\"},{\"1\":\"Thighs\",\"2\":\"2.22000\",\"3\":\"2010-07-01\"},{\"1\":\"Thighs\",\"2\":\"2.19200\",\"3\":\"2010-08-01\"},{\"1\":\"Thighs\",\"2\":\"2.15000\",\"3\":\"2010-09-01\"},{\"1\":\"Thighs\",\"2\":\"2.15000\",\"3\":\"2010-10-01\"},{\"1\":\"Thighs\",\"2\":\"2.15000\",\"3\":\"2010-11-01\"},{\"1\":\"Thighs\",\"2\":\"2.15000\",\"3\":\"2010-12-01\"},{\"1\":\"Whole\",\"2\":\"2.48000\",\"3\":\"2009-01-01\"},{\"1\":\"Whole\",\"2\":\"2.48000\",\"3\":\"2009-02-01\"},{\"1\":\"Whole\",\"2\":\"2.48000\",\"3\":\"2009-03-01\"},{\"1\":\"Whole\",\"2\":\"2.48000\",\"3\":\"2009-04-01\"},{\"1\":\"Whole\",\"2\":\"2.48000\",\"3\":\"2009-05-01\"},{\"1\":\"Whole\",\"2\":\"2.48000\",\"3\":\"2009-06-01\"},{\"1\":\"Whole\",\"2\":\"2.48000\",\"3\":\"2009-07-01\"},{\"1\":\"Whole\",\"2\":\"2.48000\",\"3\":\"2009-08-01\"},{\"1\":\"Whole\",\"2\":\"2.48000\",\"3\":\"2009-09-01\"},{\"1\":\"Whole\",\"2\":\"2.48000\",\"3\":\"2009-10-01\"},{\"1\":\"Whole\",\"2\":\"2.48000\",\"3\":\"2009-11-01\"},{\"1\":\"Whole\",\"2\":\"2.48000\",\"3\":\"2009-12-01\"},{\"1\":\"B/S Breast\",\"2\":\"6.45500\",\"3\":\"2009-01-01\"},{\"1\":\"B/S Breast\",\"2\":\"6.45500\",\"3\":\"2009-02-01\"},{\"1\":\"B/S Breast\",\"2\":\"6.45500\",\"3\":\"2009-03-01\"},{\"1\":\"B/S Breast\",\"2\":\"6.45500\",\"3\":\"2009-04-01\"},{\"1\":\"B/S Breast\",\"2\":\"6.45500\",\"3\":\"2009-05-01\"},{\"1\":\"B/S Breast\",\"2\":\"6.45500\",\"3\":\"2009-06-01\"},{\"1\":\"B/S Breast\",\"2\":\"6.45500\",\"3\":\"2009-07-01\"},{\"1\":\"B/S Breast\",\"2\":\"6.45500\",\"3\":\"2009-08-01\"},{\"1\":\"B/S Breast\",\"2\":\"6.45500\",\"3\":\"2009-09-01\"},{\"1\":\"B/S Breast\",\"2\":\"6.45500\",\"3\":\"2009-10-01\"},{\"1\":\"B/S Breast\",\"2\":\"6.45500\",\"3\":\"2009-11-01\"},{\"1\":\"B/S Breast\",\"2\":\"6.45500\",\"3\":\"2009-12-01\"},{\"1\":\"Bone-in Breast\",\"2\":\"3.90500\",\"3\":\"2009-01-01\"},{\"1\":\"Bone-in Breast\",\"2\":\"3.90500\",\"3\":\"2009-02-01\"},{\"1\":\"Bone-in Breast\",\"2\":\"3.90500\",\"3\":\"2009-03-01\"},{\"1\":\"Bone-in Breast\",\"2\":\"3.90500\",\"3\":\"2009-04-01\"},{\"1\":\"Bone-in Breast\",\"2\":\"3.90500\",\"3\":\"2009-05-01\"},{\"1\":\"Bone-in Breast\",\"2\":\"3.90500\",\"3\":\"2009-06-01\"},{\"1\":\"Bone-in Breast\",\"2\":\"3.90500\",\"3\":\"2009-07-01\"},{\"1\":\"Bone-in Breast\",\"2\":\"3.90500\",\"3\":\"2009-08-01\"},{\"1\":\"Bone-in Breast\",\"2\":\"3.90500\",\"3\":\"2009-09-01\"},{\"1\":\"Bone-in Breast\",\"2\":\"3.90500\",\"3\":\"2009-10-01\"},{\"1\":\"Bone-in Breast\",\"2\":\"3.90500\",\"3\":\"2009-11-01\"},{\"1\":\"Bone-in Breast\",\"2\":\"3.90500\",\"3\":\"2009-12-01\"},{\"1\":\"Whole Legs\",\"2\":\"2.03500\",\"3\":\"2009-01-01\"},{\"1\":\"Whole Legs\",\"2\":\"2.03500\",\"3\":\"2009-02-01\"},{\"1\":\"Whole Legs\",\"2\":\"2.03500\",\"3\":\"2009-03-01\"},{\"1\":\"Whole Legs\",\"2\":\"2.03500\",\"3\":\"2009-04-01\"},{\"1\":\"Whole Legs\",\"2\":\"2.03500\",\"3\":\"2009-05-01\"},{\"1\":\"Whole Legs\",\"2\":\"2.03500\",\"3\":\"2009-06-01\"},{\"1\":\"Whole Legs\",\"2\":\"2.03500\",\"3\":\"2009-07-01\"},{\"1\":\"Whole Legs\",\"2\":\"2.03500\",\"3\":\"2009-08-01\"},{\"1\":\"Whole Legs\",\"2\":\"2.03500\",\"3\":\"2009-09-01\"},{\"1\":\"Whole Legs\",\"2\":\"2.03500\",\"3\":\"2009-10-01\"},{\"1\":\"Whole Legs\",\"2\":\"2.03500\",\"3\":\"2009-11-01\"},{\"1\":\"Whole Legs\",\"2\":\"2.03500\",\"3\":\"2009-12-01\"},{\"1\":\"Thighs\",\"2\":\"2.22000\",\"3\":\"2009-01-01\"},{\"1\":\"Thighs\",\"2\":\"2.22000\",\"3\":\"2009-02-01\"},{\"1\":\"Thighs\",\"2\":\"2.22000\",\"3\":\"2009-03-01\"},{\"1\":\"Thighs\",\"2\":\"2.22000\",\"3\":\"2009-04-01\"},{\"1\":\"Thighs\",\"2\":\"2.22000\",\"3\":\"2009-05-01\"},{\"1\":\"Thighs\",\"2\":\"2.22000\",\"3\":\"2009-06-01\"},{\"1\":\"Thighs\",\"2\":\"2.22000\",\"3\":\"2009-07-01\"},{\"1\":\"Thighs\",\"2\":\"2.22000\",\"3\":\"2009-08-01\"},{\"1\":\"Thighs\",\"2\":\"2.22000\",\"3\":\"2009-09-01\"},{\"1\":\"Thighs\",\"2\":\"2.22000\",\"3\":\"2009-10-01\"},{\"1\":\"Thighs\",\"2\":\"2.22000\",\"3\":\"2009-11-01\"},{\"1\":\"Thighs\",\"2\":\"2.22000\",\"3\":\"2009-12-01\"},{\"1\":\"Whole\",\"2\":\"2.20500\",\"3\":\"2008-01-01\"},{\"1\":\"Whole\",\"2\":\"2.20500\",\"3\":\"2008-02-01\"},{\"1\":\"Whole\",\"2\":\"2.20500\",\"3\":\"2008-03-01\"},{\"1\":\"Whole\",\"2\":\"2.20500\",\"3\":\"2008-04-01\"},{\"1\":\"Whole\",\"2\":\"2.20500\",\"3\":\"2008-05-01\"},{\"1\":\"Whole\",\"2\":\"2.48000\",\"3\":\"2008-06-01\"},{\"1\":\"Whole\",\"2\":\"2.48000\",\"3\":\"2008-07-01\"},{\"1\":\"Whole\",\"2\":\"2.48000\",\"3\":\"2008-08-01\"},{\"1\":\"Whole\",\"2\":\"2.48000\",\"3\":\"2008-09-01\"},{\"1\":\"Whole\",\"2\":\"2.48000\",\"3\":\"2008-10-01\"},{\"1\":\"Whole\",\"2\":\"2.48000\",\"3\":\"2008-11-01\"},{\"1\":\"Whole\",\"2\":\"2.48000\",\"3\":\"2008-12-01\"},{\"1\":\"B/S Breast\",\"2\":\"6.45500\",\"3\":\"2008-01-01\"},{\"1\":\"B/S Breast\",\"2\":\"6.45500\",\"3\":\"2008-02-01\"},{\"1\":\"B/S Breast\",\"2\":\"6.45500\",\"3\":\"2008-03-01\"},{\"1\":\"B/S Breast\",\"2\":\"6.45500\",\"3\":\"2008-04-01\"},{\"1\":\"B/S Breast\",\"2\":\"6.45500\",\"3\":\"2008-05-01\"},{\"1\":\"B/S Breast\",\"2\":\"6.45500\",\"3\":\"2008-06-01\"},{\"1\":\"B/S Breast\",\"2\":\"6.45500\",\"3\":\"2008-07-01\"},{\"1\":\"B/S Breast\",\"2\":\"6.45500\",\"3\":\"2008-08-01\"},{\"1\":\"B/S Breast\",\"2\":\"6.45500\",\"3\":\"2008-09-01\"},{\"1\":\"B/S Breast\",\"2\":\"6.45500\",\"3\":\"2008-10-01\"},{\"1\":\"B/S Breast\",\"2\":\"6.45500\",\"3\":\"2008-11-01\"},{\"1\":\"B/S Breast\",\"2\":\"6.45500\",\"3\":\"2008-12-01\"},{\"1\":\"Bone-in Breast\",\"2\":\"3.90500\",\"3\":\"2008-01-01\"},{\"1\":\"Bone-in Breast\",\"2\":\"3.90500\",\"3\":\"2008-02-01\"},{\"1\":\"Bone-in Breast\",\"2\":\"3.90500\",\"3\":\"2008-03-01\"},{\"1\":\"Bone-in Breast\",\"2\":\"3.90500\",\"3\":\"2008-04-01\"},{\"1\":\"Bone-in Breast\",\"2\":\"3.90500\",\"3\":\"2008-05-01\"},{\"1\":\"Bone-in Breast\",\"2\":\"3.90500\",\"3\":\"2008-06-01\"},{\"1\":\"Bone-in Breast\",\"2\":\"3.90500\",\"3\":\"2008-07-01\"},{\"1\":\"Bone-in Breast\",\"2\":\"3.90500\",\"3\":\"2008-08-01\"},{\"1\":\"Bone-in Breast\",\"2\":\"3.90500\",\"3\":\"2008-09-01\"},{\"1\":\"Bone-in Breast\",\"2\":\"3.90500\",\"3\":\"2008-10-01\"},{\"1\":\"Bone-in Breast\",\"2\":\"3.90500\",\"3\":\"2008-11-01\"},{\"1\":\"Bone-in Breast\",\"2\":\"3.90500\",\"3\":\"2008-12-01\"},{\"1\":\"Whole Legs\",\"2\":\"2.03500\",\"3\":\"2008-01-01\"},{\"1\":\"Whole Legs\",\"2\":\"2.03500\",\"3\":\"2008-02-01\"},{\"1\":\"Whole Legs\",\"2\":\"2.03500\",\"3\":\"2008-03-01\"},{\"1\":\"Whole Legs\",\"2\":\"2.03500\",\"3\":\"2008-04-01\"},{\"1\":\"Whole Legs\",\"2\":\"2.03500\",\"3\":\"2008-05-01\"},{\"1\":\"Whole Legs\",\"2\":\"2.03500\",\"3\":\"2008-06-01\"},{\"1\":\"Whole Legs\",\"2\":\"2.03500\",\"3\":\"2008-07-01\"},{\"1\":\"Whole Legs\",\"2\":\"2.03500\",\"3\":\"2008-08-01\"},{\"1\":\"Whole Legs\",\"2\":\"2.03500\",\"3\":\"2008-09-01\"},{\"1\":\"Whole Legs\",\"2\":\"2.03500\",\"3\":\"2008-10-01\"},{\"1\":\"Whole Legs\",\"2\":\"2.03500\",\"3\":\"2008-11-01\"},{\"1\":\"Whole Legs\",\"2\":\"2.03500\",\"3\":\"2008-12-01\"},{\"1\":\"Thighs\",\"2\":\"2.22000\",\"3\":\"2008-01-01\"},{\"1\":\"Thighs\",\"2\":\"2.22000\",\"3\":\"2008-02-01\"},{\"1\":\"Thighs\",\"2\":\"2.22000\",\"3\":\"2008-03-01\"},{\"1\":\"Thighs\",\"2\":\"2.22000\",\"3\":\"2008-04-01\"},{\"1\":\"Thighs\",\"2\":\"2.22000\",\"3\":\"2008-05-01\"},{\"1\":\"Thighs\",\"2\":\"2.22000\",\"3\":\"2008-06-01\"},{\"1\":\"Thighs\",\"2\":\"2.22000\",\"3\":\"2008-07-01\"},{\"1\":\"Thighs\",\"2\":\"2.22000\",\"3\":\"2008-08-01\"},{\"1\":\"Thighs\",\"2\":\"2.22000\",\"3\":\"2008-09-01\"},{\"1\":\"Thighs\",\"2\":\"2.22000\",\"3\":\"2008-10-01\"},{\"1\":\"Thighs\",\"2\":\"2.22000\",\"3\":\"2008-11-01\"},{\"1\":\"Thighs\",\"2\":\"2.22000\",\"3\":\"2008-12-01\"},{\"1\":\"Whole\",\"2\":\"2.20500\",\"3\":\"2007-01-01\"},{\"1\":\"Whole\",\"2\":\"2.20500\",\"3\":\"2007-02-01\"},{\"1\":\"Whole\",\"2\":\"2.20500\",\"3\":\"2007-03-01\"},{\"1\":\"Whole\",\"2\":\"2.20500\",\"3\":\"2007-04-01\"},{\"1\":\"Whole\",\"2\":\"2.20500\",\"3\":\"2007-05-01\"},{\"1\":\"Whole\",\"2\":\"2.20500\",\"3\":\"2007-06-01\"},{\"1\":\"Whole\",\"2\":\"2.20500\",\"3\":\"2007-07-01\"},{\"1\":\"Whole\",\"2\":\"2.20500\",\"3\":\"2007-08-01\"},{\"1\":\"Whole\",\"2\":\"2.20500\",\"3\":\"2007-09-01\"},{\"1\":\"Whole\",\"2\":\"2.20500\",\"3\":\"2007-10-01\"},{\"1\":\"Whole\",\"2\":\"2.20500\",\"3\":\"2007-11-01\"},{\"1\":\"Whole\",\"2\":\"2.20500\",\"3\":\"2007-12-01\"},{\"1\":\"B/S Breast\",\"2\":\"6.45500\",\"3\":\"2007-01-01\"},{\"1\":\"B/S Breast\",\"2\":\"6.45500\",\"3\":\"2007-02-01\"},{\"1\":\"B/S Breast\",\"2\":\"6.45500\",\"3\":\"2007-03-01\"},{\"1\":\"B/S Breast\",\"2\":\"6.45500\",\"3\":\"2007-04-01\"},{\"1\":\"B/S Breast\",\"2\":\"6.45500\",\"3\":\"2007-05-01\"},{\"1\":\"B/S Breast\",\"2\":\"6.45500\",\"3\":\"2007-06-01\"},{\"1\":\"B/S Breast\",\"2\":\"6.45500\",\"3\":\"2007-07-01\"},{\"1\":\"B/S Breast\",\"2\":\"6.45500\",\"3\":\"2007-08-01\"},{\"1\":\"B/S Breast\",\"2\":\"6.45500\",\"3\":\"2007-09-01\"},{\"1\":\"B/S Breast\",\"2\":\"6.45500\",\"3\":\"2007-10-01\"},{\"1\":\"B/S Breast\",\"2\":\"6.45500\",\"3\":\"2007-11-01\"},{\"1\":\"B/S Breast\",\"2\":\"6.45500\",\"3\":\"2007-12-01\"},{\"1\":\"Bone-in Breast\",\"2\":\"3.90500\",\"3\":\"2007-01-01\"},{\"1\":\"Bone-in Breast\",\"2\":\"3.90500\",\"3\":\"2007-02-01\"},{\"1\":\"Bone-in Breast\",\"2\":\"3.90500\",\"3\":\"2007-03-01\"},{\"1\":\"Bone-in Breast\",\"2\":\"3.90500\",\"3\":\"2007-04-01\"},{\"1\":\"Bone-in Breast\",\"2\":\"3.90500\",\"3\":\"2007-05-01\"},{\"1\":\"Bone-in Breast\",\"2\":\"3.90500\",\"3\":\"2007-06-01\"},{\"1\":\"Bone-in Breast\",\"2\":\"3.90500\",\"3\":\"2007-07-01\"},{\"1\":\"Bone-in Breast\",\"2\":\"3.90500\",\"3\":\"2007-08-01\"},{\"1\":\"Bone-in Breast\",\"2\":\"3.90500\",\"3\":\"2007-09-01\"},{\"1\":\"Bone-in Breast\",\"2\":\"3.90500\",\"3\":\"2007-10-01\"},{\"1\":\"Bone-in Breast\",\"2\":\"3.90500\",\"3\":\"2007-11-01\"},{\"1\":\"Bone-in Breast\",\"2\":\"3.90500\",\"3\":\"2007-12-01\"},{\"1\":\"Whole Legs\",\"2\":\"2.03500\",\"3\":\"2007-01-01\"},{\"1\":\"Whole Legs\",\"2\":\"2.03500\",\"3\":\"2007-02-01\"},{\"1\":\"Whole Legs\",\"2\":\"2.03500\",\"3\":\"2007-03-01\"},{\"1\":\"Whole Legs\",\"2\":\"2.03500\",\"3\":\"2007-04-01\"},{\"1\":\"Whole Legs\",\"2\":\"2.03500\",\"3\":\"2007-05-01\"},{\"1\":\"Whole Legs\",\"2\":\"2.03500\",\"3\":\"2007-06-01\"},{\"1\":\"Whole Legs\",\"2\":\"2.03500\",\"3\":\"2007-07-01\"},{\"1\":\"Whole Legs\",\"2\":\"2.03500\",\"3\":\"2007-08-01\"},{\"1\":\"Whole Legs\",\"2\":\"2.03500\",\"3\":\"2007-09-01\"},{\"1\":\"Whole Legs\",\"2\":\"2.03500\",\"3\":\"2007-10-01\"},{\"1\":\"Whole Legs\",\"2\":\"2.03500\",\"3\":\"2007-11-01\"},{\"1\":\"Whole Legs\",\"2\":\"2.03500\",\"3\":\"2007-12-01\"},{\"1\":\"Thighs\",\"2\":\"2.22000\",\"3\":\"2007-01-01\"},{\"1\":\"Thighs\",\"2\":\"2.22000\",\"3\":\"2007-02-01\"},{\"1\":\"Thighs\",\"2\":\"2.22000\",\"3\":\"2007-03-01\"},{\"1\":\"Thighs\",\"2\":\"2.22000\",\"3\":\"2007-04-01\"},{\"1\":\"Thighs\",\"2\":\"2.22000\",\"3\":\"2007-05-01\"},{\"1\":\"Thighs\",\"2\":\"2.22000\",\"3\":\"2007-06-01\"},{\"1\":\"Thighs\",\"2\":\"2.22000\",\"3\":\"2007-07-01\"},{\"1\":\"Thighs\",\"2\":\"2.22000\",\"3\":\"2007-08-01\"},{\"1\":\"Thighs\",\"2\":\"2.22000\",\"3\":\"2007-09-01\"},{\"1\":\"Thighs\",\"2\":\"2.22000\",\"3\":\"2007-10-01\"},{\"1\":\"Thighs\",\"2\":\"2.22000\",\"3\":\"2007-11-01\"},{\"1\":\"Thighs\",\"2\":\"2.22000\",\"3\":\"2007-12-01\"},{\"1\":\"Whole\",\"2\":\"2.17000\",\"3\":\"2006-01-01\"},{\"1\":\"Whole\",\"2\":\"2.17000\",\"3\":\"2006-02-01\"},{\"1\":\"Whole\",\"2\":\"2.19625\",\"3\":\"2006-03-01\"},{\"1\":\"Whole\",\"2\":\"2.20500\",\"3\":\"2006-04-01\"},{\"1\":\"Whole\",\"2\":\"2.20500\",\"3\":\"2006-05-01\"},{\"1\":\"Whole\",\"2\":\"2.20500\",\"3\":\"2006-06-01\"},{\"1\":\"Whole\",\"2\":\"2.20500\",\"3\":\"2006-07-01\"},{\"1\":\"Whole\",\"2\":\"2.20500\",\"3\":\"2006-08-01\"},{\"1\":\"Whole\",\"2\":\"2.20500\",\"3\":\"2006-09-01\"},{\"1\":\"Whole\",\"2\":\"2.20500\",\"3\":\"2006-10-01\"},{\"1\":\"Whole\",\"2\":\"2.20500\",\"3\":\"2006-11-01\"},{\"1\":\"Whole\",\"2\":\"2.20500\",\"3\":\"2006-12-01\"},{\"1\":\"B/S Breast\",\"2\":\"6.45500\",\"3\":\"2006-01-01\"},{\"1\":\"B/S Breast\",\"2\":\"6.45500\",\"3\":\"2006-02-01\"},{\"1\":\"B/S Breast\",\"2\":\"6.45500\",\"3\":\"2006-03-01\"},{\"1\":\"B/S Breast\",\"2\":\"6.45500\",\"3\":\"2006-04-01\"},{\"1\":\"B/S Breast\",\"2\":\"6.45500\",\"3\":\"2006-05-01\"},{\"1\":\"B/S Breast\",\"2\":\"6.45500\",\"3\":\"2006-06-01\"},{\"1\":\"B/S Breast\",\"2\":\"6.45500\",\"3\":\"2006-07-01\"},{\"1\":\"B/S Breast\",\"2\":\"6.45500\",\"3\":\"2006-08-01\"},{\"1\":\"B/S Breast\",\"2\":\"6.45500\",\"3\":\"2006-09-01\"},{\"1\":\"B/S Breast\",\"2\":\"6.45500\",\"3\":\"2006-10-01\"},{\"1\":\"B/S Breast\",\"2\":\"6.45500\",\"3\":\"2006-11-01\"},{\"1\":\"B/S Breast\",\"2\":\"6.45500\",\"3\":\"2006-12-01\"},{\"1\":\"Bone-in Breast\",\"2\":\"3.90500\",\"3\":\"2006-01-01\"},{\"1\":\"Bone-in Breast\",\"2\":\"3.90500\",\"3\":\"2006-02-01\"},{\"1\":\"Bone-in Breast\",\"2\":\"3.90500\",\"3\":\"2006-03-01\"},{\"1\":\"Bone-in Breast\",\"2\":\"3.90500\",\"3\":\"2006-04-01\"},{\"1\":\"Bone-in Breast\",\"2\":\"3.90500\",\"3\":\"2006-05-01\"},{\"1\":\"Bone-in Breast\",\"2\":\"3.90500\",\"3\":\"2006-06-01\"},{\"1\":\"Bone-in Breast\",\"2\":\"3.90500\",\"3\":\"2006-07-01\"},{\"1\":\"Bone-in Breast\",\"2\":\"3.90500\",\"3\":\"2006-08-01\"},{\"1\":\"Bone-in Breast\",\"2\":\"3.90500\",\"3\":\"2006-09-01\"},{\"1\":\"Bone-in Breast\",\"2\":\"3.90500\",\"3\":\"2006-10-01\"},{\"1\":\"Bone-in Breast\",\"2\":\"3.90500\",\"3\":\"2006-11-01\"},{\"1\":\"Bone-in Breast\",\"2\":\"3.90500\",\"3\":\"2006-12-01\"},{\"1\":\"Whole Legs\",\"2\":\"2.03500\",\"3\":\"2006-01-01\"},{\"1\":\"Whole Legs\",\"2\":\"2.03500\",\"3\":\"2006-02-01\"},{\"1\":\"Whole Legs\",\"2\":\"2.03500\",\"3\":\"2006-03-01\"},{\"1\":\"Whole Legs\",\"2\":\"2.03500\",\"3\":\"2006-04-01\"},{\"1\":\"Whole Legs\",\"2\":\"2.03500\",\"3\":\"2006-05-01\"},{\"1\":\"Whole Legs\",\"2\":\"2.03500\",\"3\":\"2006-06-01\"},{\"1\":\"Whole Legs\",\"2\":\"2.03500\",\"3\":\"2006-07-01\"},{\"1\":\"Whole Legs\",\"2\":\"2.03500\",\"3\":\"2006-08-01\"},{\"1\":\"Whole Legs\",\"2\":\"2.03500\",\"3\":\"2006-09-01\"},{\"1\":\"Whole Legs\",\"2\":\"2.03500\",\"3\":\"2006-10-01\"},{\"1\":\"Whole Legs\",\"2\":\"2.03500\",\"3\":\"2006-11-01\"},{\"1\":\"Whole Legs\",\"2\":\"2.03500\",\"3\":\"2006-12-01\"},{\"1\":\"Thighs\",\"2\":\"2.22000\",\"3\":\"2006-01-01\"},{\"1\":\"Thighs\",\"2\":\"2.22000\",\"3\":\"2006-02-01\"},{\"1\":\"Thighs\",\"2\":\"2.22000\",\"3\":\"2006-03-01\"},{\"1\":\"Thighs\",\"2\":\"2.22000\",\"3\":\"2006-04-01\"},{\"1\":\"Thighs\",\"2\":\"2.22000\",\"3\":\"2006-05-01\"},{\"1\":\"Thighs\",\"2\":\"2.22000\",\"3\":\"2006-06-01\"},{\"1\":\"Thighs\",\"2\":\"2.22000\",\"3\":\"2006-07-01\"},{\"1\":\"Thighs\",\"2\":\"2.22000\",\"3\":\"2006-08-01\"},{\"1\":\"Thighs\",\"2\":\"2.22000\",\"3\":\"2006-09-01\"},{\"1\":\"Thighs\",\"2\":\"2.22000\",\"3\":\"2006-10-01\"},{\"1\":\"Thighs\",\"2\":\"2.22000\",\"3\":\"2006-11-01\"},{\"1\":\"Thighs\",\"2\":\"2.22000\",\"3\":\"2006-12-01\"},{\"1\":\"Whole\",\"2\":\"2.17000\",\"3\":\"2005-01-01\"},{\"1\":\"Whole\",\"2\":\"2.17000\",\"3\":\"2005-02-01\"},{\"1\":\"Whole\",\"2\":\"2.17000\",\"3\":\"2005-03-01\"},{\"1\":\"Whole\",\"2\":\"2.17000\",\"3\":\"2005-04-01\"},{\"1\":\"Whole\",\"2\":\"2.17000\",\"3\":\"2005-05-01\"},{\"1\":\"Whole\",\"2\":\"2.17000\",\"3\":\"2005-06-01\"},{\"1\":\"Whole\",\"2\":\"2.17000\",\"3\":\"2005-07-01\"},{\"1\":\"Whole\",\"2\":\"2.17000\",\"3\":\"2005-08-01\"},{\"1\":\"Whole\",\"2\":\"2.17000\",\"3\":\"2005-09-01\"},{\"1\":\"Whole\",\"2\":\"2.17000\",\"3\":\"2005-10-01\"},{\"1\":\"Whole\",\"2\":\"2.17000\",\"3\":\"2005-11-01\"},{\"1\":\"Whole\",\"2\":\"2.17000\",\"3\":\"2005-12-01\"},{\"1\":\"B/S Breast\",\"2\":\"6.44000\",\"3\":\"2005-01-01\"},{\"1\":\"B/S Breast\",\"2\":\"6.45500\",\"3\":\"2005-02-01\"},{\"1\":\"B/S Breast\",\"2\":\"6.45500\",\"3\":\"2005-03-01\"},{\"1\":\"B/S Breast\",\"2\":\"6.45500\",\"3\":\"2005-04-01\"},{\"1\":\"B/S Breast\",\"2\":\"6.45500\",\"3\":\"2005-05-01\"},{\"1\":\"B/S Breast\",\"2\":\"6.45500\",\"3\":\"2005-06-01\"},{\"1\":\"B/S Breast\",\"2\":\"6.45500\",\"3\":\"2005-07-01\"},{\"1\":\"B/S Breast\",\"2\":\"6.45500\",\"3\":\"2005-08-01\"},{\"1\":\"B/S Breast\",\"2\":\"6.45500\",\"3\":\"2005-09-01\"},{\"1\":\"B/S Breast\",\"2\":\"6.45500\",\"3\":\"2005-10-01\"},{\"1\":\"B/S Breast\",\"2\":\"6.45500\",\"3\":\"2005-11-01\"},{\"1\":\"B/S Breast\",\"2\":\"6.45500\",\"3\":\"2005-12-01\"},{\"1\":\"Bone-in Breast\",\"2\":\"3.90500\",\"3\":\"2005-01-01\"},{\"1\":\"Bone-in Breast\",\"2\":\"3.90500\",\"3\":\"2005-02-01\"},{\"1\":\"Bone-in Breast\",\"2\":\"3.90500\",\"3\":\"2005-03-01\"},{\"1\":\"Bone-in Breast\",\"2\":\"3.90500\",\"3\":\"2005-04-01\"},{\"1\":\"Bone-in Breast\",\"2\":\"3.90500\",\"3\":\"2005-05-01\"},{\"1\":\"Bone-in Breast\",\"2\":\"3.90500\",\"3\":\"2005-06-01\"},{\"1\":\"Bone-in Breast\",\"2\":\"3.90500\",\"3\":\"2005-07-01\"},{\"1\":\"Bone-in Breast\",\"2\":\"3.90500\",\"3\":\"2005-08-01\"},{\"1\":\"Bone-in Breast\",\"2\":\"3.90500\",\"3\":\"2005-09-01\"},{\"1\":\"Bone-in Breast\",\"2\":\"3.90500\",\"3\":\"2005-10-01\"},{\"1\":\"Bone-in Breast\",\"2\":\"3.90500\",\"3\":\"2005-11-01\"},{\"1\":\"Bone-in Breast\",\"2\":\"3.90500\",\"3\":\"2005-12-01\"},{\"1\":\"Whole Legs\",\"2\":\"2.03500\",\"3\":\"2005-01-01\"},{\"1\":\"Whole Legs\",\"2\":\"2.03500\",\"3\":\"2005-02-01\"},{\"1\":\"Whole Legs\",\"2\":\"2.03500\",\"3\":\"2005-03-01\"},{\"1\":\"Whole Legs\",\"2\":\"2.03500\",\"3\":\"2005-04-01\"},{\"1\":\"Whole Legs\",\"2\":\"2.03500\",\"3\":\"2005-05-01\"},{\"1\":\"Whole Legs\",\"2\":\"2.03500\",\"3\":\"2005-06-01\"},{\"1\":\"Whole Legs\",\"2\":\"2.03500\",\"3\":\"2005-07-01\"},{\"1\":\"Whole Legs\",\"2\":\"2.03500\",\"3\":\"2005-08-01\"},{\"1\":\"Whole Legs\",\"2\":\"2.03500\",\"3\":\"2005-09-01\"},{\"1\":\"Whole Legs\",\"2\":\"2.03500\",\"3\":\"2005-10-01\"},{\"1\":\"Whole Legs\",\"2\":\"2.03500\",\"3\":\"2005-11-01\"},{\"1\":\"Whole Legs\",\"2\":\"2.03500\",\"3\":\"2005-12-01\"},{\"1\":\"Thighs\",\"2\":\"2.13000\",\"3\":\"2005-01-01\"},{\"1\":\"Thighs\",\"2\":\"2.22000\",\"3\":\"2005-02-01\"},{\"1\":\"Thighs\",\"2\":\"2.22000\",\"3\":\"2005-03-01\"},{\"1\":\"Thighs\",\"2\":\"2.22000\",\"3\":\"2005-04-01\"},{\"1\":\"Thighs\",\"2\":\"2.22000\",\"3\":\"2005-05-01\"},{\"1\":\"Thighs\",\"2\":\"2.22000\",\"3\":\"2005-06-01\"},{\"1\":\"Thighs\",\"2\":\"2.22000\",\"3\":\"2005-07-01\"},{\"1\":\"Thighs\",\"2\":\"2.22000\",\"3\":\"2005-08-01\"},{\"1\":\"Thighs\",\"2\":\"2.22000\",\"3\":\"2005-09-01\"},{\"1\":\"Thighs\",\"2\":\"2.22000\",\"3\":\"2005-10-01\"},{\"1\":\"Thighs\",\"2\":\"2.22000\",\"3\":\"2005-11-01\"},{\"1\":\"Thighs\",\"2\":\"2.22000\",\"3\":\"2005-12-01\"},{\"1\":\"Whole\",\"2\":\"1.97500\",\"3\":\"2004-01-01\"},{\"1\":\"Whole\",\"2\":\"1.97500\",\"3\":\"2004-02-01\"},{\"1\":\"Whole\",\"2\":\"2.09000\",\"3\":\"2004-03-01\"},{\"1\":\"Whole\",\"2\":\"2.12000\",\"3\":\"2004-04-01\"},{\"1\":\"Whole\",\"2\":\"2.14500\",\"3\":\"2004-05-01\"},{\"1\":\"Whole\",\"2\":\"2.16375\",\"3\":\"2004-06-01\"},{\"1\":\"Whole\",\"2\":\"2.17000\",\"3\":\"2004-07-01\"},{\"1\":\"Whole\",\"2\":\"2.17000\",\"3\":\"2004-08-01\"},{\"1\":\"Whole\",\"2\":\"2.17000\",\"3\":\"2004-09-01\"},{\"1\":\"Whole\",\"2\":\"2.17000\",\"3\":\"2004-10-01\"},{\"1\":\"Whole\",\"2\":\"2.17000\",\"3\":\"2004-11-01\"},{\"1\":\"Whole\",\"2\":\"2.17000\",\"3\":\"2004-12-01\"},{\"1\":\"B/S Breast\",\"2\":\"6.45500\",\"3\":\"2004-01-01\"},{\"1\":\"B/S Breast\",\"2\":\"6.42500\",\"3\":\"2004-02-01\"},{\"1\":\"B/S Breast\",\"2\":\"6.42500\",\"3\":\"2004-03-01\"},{\"1\":\"B/S Breast\",\"2\":\"6.42500\",\"3\":\"2004-04-01\"},{\"1\":\"B/S Breast\",\"2\":\"6.42500\",\"3\":\"2004-05-01\"},{\"1\":\"B/S Breast\",\"2\":\"6.41000\",\"3\":\"2004-06-01\"},{\"1\":\"B/S Breast\",\"2\":\"6.42500\",\"3\":\"2004-07-01\"},{\"1\":\"B/S Breast\",\"2\":\"6.42500\",\"3\":\"2004-08-01\"},{\"1\":\"B/S Breast\",\"2\":\"6.42500\",\"3\":\"2004-09-01\"},{\"1\":\"B/S Breast\",\"2\":\"6.42500\",\"3\":\"2004-10-01\"},{\"1\":\"B/S Breast\",\"2\":\"6.42500\",\"3\":\"2004-11-01\"},{\"1\":\"B/S Breast\",\"2\":\"6.42500\",\"3\":\"2004-12-01\"},{\"1\":\"Bone-in Breast\",\"2\":\"NA\",\"3\":\"2004-01-01\"},{\"1\":\"Bone-in Breast\",\"2\":\"NA\",\"3\":\"2004-02-01\"},{\"1\":\"Bone-in Breast\",\"2\":\"NA\",\"3\":\"2004-03-01\"},{\"1\":\"Bone-in Breast\",\"2\":\"NA\",\"3\":\"2004-04-01\"},{\"1\":\"Bone-in Breast\",\"2\":\"NA\",\"3\":\"2004-05-01\"},{\"1\":\"Bone-in Breast\",\"2\":\"NA\",\"3\":\"2004-06-01\"},{\"1\":\"Bone-in Breast\",\"2\":\"3.90500\",\"3\":\"2004-07-01\"},{\"1\":\"Bone-in Breast\",\"2\":\"3.90500\",\"3\":\"2004-08-01\"},{\"1\":\"Bone-in Breast\",\"2\":\"3.90500\",\"3\":\"2004-09-01\"},{\"1\":\"Bone-in Breast\",\"2\":\"3.90500\",\"3\":\"2004-10-01\"},{\"1\":\"Bone-in Breast\",\"2\":\"3.90500\",\"3\":\"2004-11-01\"},{\"1\":\"Bone-in Breast\",\"2\":\"3.90500\",\"3\":\"2004-12-01\"},{\"1\":\"Whole Legs\",\"2\":\"1.93500\",\"3\":\"2004-01-01\"},{\"1\":\"Whole Legs\",\"2\":\"1.93500\",\"3\":\"2004-02-01\"},{\"1\":\"Whole Legs\",\"2\":\"1.93500\",\"3\":\"2004-03-01\"},{\"1\":\"Whole Legs\",\"2\":\"1.93500\",\"3\":\"2004-04-01\"},{\"1\":\"Whole Legs\",\"2\":\"1.93500\",\"3\":\"2004-05-01\"},{\"1\":\"Whole Legs\",\"2\":\"2.01875\",\"3\":\"2004-06-01\"},{\"1\":\"Whole Legs\",\"2\":\"2.03500\",\"3\":\"2004-07-01\"},{\"1\":\"Whole Legs\",\"2\":\"2.03500\",\"3\":\"2004-08-01\"},{\"1\":\"Whole Legs\",\"2\":\"2.03500\",\"3\":\"2004-09-01\"},{\"1\":\"Whole Legs\",\"2\":\"2.03500\",\"3\":\"2004-10-01\"},{\"1\":\"Whole Legs\",\"2\":\"2.03500\",\"3\":\"2004-11-01\"},{\"1\":\"Whole Legs\",\"2\":\"2.03500\",\"3\":\"2004-12-01\"},{\"1\":\"Thighs\",\"2\":\"NA\",\"3\":\"2004-01-01\"},{\"1\":\"Thighs\",\"2\":\"2.03000\",\"3\":\"2004-02-01\"},{\"1\":\"Thighs\",\"2\":\"2.03000\",\"3\":\"2004-03-01\"},{\"1\":\"Thighs\",\"2\":\"2.03000\",\"3\":\"2004-04-01\"},{\"1\":\"Thighs\",\"2\":\"2.03000\",\"3\":\"2004-05-01\"},{\"1\":\"Thighs\",\"2\":\"2.00375\",\"3\":\"2004-06-01\"},{\"1\":\"Thighs\",\"2\":\"1.99500\",\"3\":\"2004-07-01\"},{\"1\":\"Thighs\",\"2\":\"1.99500\",\"3\":\"2004-08-01\"},{\"1\":\"Thighs\",\"2\":\"1.99500\",\"3\":\"2004-09-01\"},{\"1\":\"Thighs\",\"2\":\"1.99500\",\"3\":\"2004-10-01\"},{\"1\":\"Thighs\",\"2\":\"1.99500\",\"3\":\"2004-11-01\"},{\"1\":\"Thighs\",\"2\":\"1.99500\",\"3\":\"2004-12-01\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\r\n<script src=\"../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\r\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}