{
  "hash": "4327570581a532593fdb43918a405ed8",
  "result": {
    "markdown": "---\ntitle: \"Challenge 3 Instructions\"\nauthor: \"Danny Holt\"\ndescription: \"Tidy Data: Pivoting\"\ndate: \"6/7/2023\"\nformat:\n  html:\n    df-print: paged\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - challenge_3\n  - eggs\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n\nknitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)\n```\n:::\n\n\n## Challenge Overview\n\n2.  identify what needs to be done to tidy the current data\n3.  anticipate the shape of pivoted data\n4.  pivot the data into tidy format using `pivot_longer`\n\n## Read in data\n\nFirst, we'll read in the data set eggs_tidy.csv\n\n\n::: {.cell}\n\n```{.r .cell-code}\n  #Read in data\n  eggs <- readr::read_csv(\"_data/eggs_tidy.csv\")\n  #Number of rows and columns:\n  nrow(eggs)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 120\n```\n:::\n\n```{.r .cell-code}\n  ncol(eggs)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 6\n```\n:::\n\n```{.r .cell-code}\n  #Data:\n  eggs\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"month\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"year\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"large_half_dozen\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"large_dozen\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"extra_large_half_dozen\"],\"name\":[5],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"extra_large_dozen\"],\"name\":[6],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"January\",\"2\":\"2004\",\"3\":\"126.000\",\"4\":\"230.000\",\"5\":\"132.000\",\"6\":\"230.000\"},{\"1\":\"February\",\"2\":\"2004\",\"3\":\"128.500\",\"4\":\"226.250\",\"5\":\"134.500\",\"6\":\"230.000\"},{\"1\":\"March\",\"2\":\"2004\",\"3\":\"131.000\",\"4\":\"225.000\",\"5\":\"137.000\",\"6\":\"230.000\"},{\"1\":\"April\",\"2\":\"2004\",\"3\":\"131.000\",\"4\":\"225.000\",\"5\":\"137.000\",\"6\":\"234.500\"},{\"1\":\"May\",\"2\":\"2004\",\"3\":\"131.000\",\"4\":\"225.000\",\"5\":\"137.000\",\"6\":\"236.000\"},{\"1\":\"June\",\"2\":\"2004\",\"3\":\"133.500\",\"4\":\"231.375\",\"5\":\"137.000\",\"6\":\"241.000\"},{\"1\":\"July\",\"2\":\"2004\",\"3\":\"133.500\",\"4\":\"233.500\",\"5\":\"137.000\",\"6\":\"241.000\"},{\"1\":\"August\",\"2\":\"2004\",\"3\":\"133.500\",\"4\":\"233.500\",\"5\":\"137.000\",\"6\":\"241.000\"},{\"1\":\"September\",\"2\":\"2004\",\"3\":\"129.750\",\"4\":\"233.500\",\"5\":\"135.875\",\"6\":\"241.000\"},{\"1\":\"October\",\"2\":\"2004\",\"3\":\"128.500\",\"4\":\"233.500\",\"5\":\"135.500\",\"6\":\"241.000\"},{\"1\":\"November\",\"2\":\"2004\",\"3\":\"128.500\",\"4\":\"233.500\",\"5\":\"135.500\",\"6\":\"241.000\"},{\"1\":\"December\",\"2\":\"2004\",\"3\":\"128.500\",\"4\":\"233.500\",\"5\":\"135.500\",\"6\":\"241.000\"},{\"1\":\"January\",\"2\":\"2005\",\"3\":\"128.500\",\"4\":\"233.500\",\"5\":\"135.500\",\"6\":\"241.000\"},{\"1\":\"February\",\"2\":\"2005\",\"3\":\"128.500\",\"4\":\"233.500\",\"5\":\"135.500\",\"6\":\"241.000\"},{\"1\":\"March\",\"2\":\"2005\",\"3\":\"128.500\",\"4\":\"233.500\",\"5\":\"135.500\",\"6\":\"241.000\"},{\"1\":\"April\",\"2\":\"2005\",\"3\":\"128.500\",\"4\":\"233.500\",\"5\":\"135.500\",\"6\":\"241.000\"},{\"1\":\"May\",\"2\":\"2005\",\"3\":\"128.500\",\"4\":\"233.500\",\"5\":\"135.500\",\"6\":\"241.000\"},{\"1\":\"June\",\"2\":\"2005\",\"3\":\"128.500\",\"4\":\"233.500\",\"5\":\"135.500\",\"6\":\"241.000\"},{\"1\":\"July\",\"2\":\"2005\",\"3\":\"128.500\",\"4\":\"233.500\",\"5\":\"135.500\",\"6\":\"241.000\"},{\"1\":\"August\",\"2\":\"2005\",\"3\":\"128.500\",\"4\":\"233.500\",\"5\":\"135.500\",\"6\":\"241.000\"},{\"1\":\"September\",\"2\":\"2005\",\"3\":\"128.500\",\"4\":\"233.500\",\"5\":\"135.500\",\"6\":\"241.000\"},{\"1\":\"October\",\"2\":\"2005\",\"3\":\"128.500\",\"4\":\"233.500\",\"5\":\"135.500\",\"6\":\"241.000\"},{\"1\":\"November\",\"2\":\"2005\",\"3\":\"128.500\",\"4\":\"233.500\",\"5\":\"135.500\",\"6\":\"241.000\"},{\"1\":\"December\",\"2\":\"2005\",\"3\":\"128.500\",\"4\":\"233.500\",\"5\":\"135.500\",\"6\":\"241.000\"},{\"1\":\"January\",\"2\":\"2006\",\"3\":\"128.500\",\"4\":\"233.500\",\"5\":\"135.500\",\"6\":\"241.000\"},{\"1\":\"February\",\"2\":\"2006\",\"3\":\"128.500\",\"4\":\"233.500\",\"5\":\"135.500\",\"6\":\"241.000\"},{\"1\":\"March\",\"2\":\"2006\",\"3\":\"128.500\",\"4\":\"233.500\",\"5\":\"135.500\",\"6\":\"241.375\"},{\"1\":\"April\",\"2\":\"2006\",\"3\":\"128.500\",\"4\":\"233.500\",\"5\":\"135.500\",\"6\":\"241.500\"},{\"1\":\"May\",\"2\":\"2006\",\"3\":\"128.500\",\"4\":\"233.500\",\"5\":\"135.500\",\"6\":\"241.500\"},{\"1\":\"June\",\"2\":\"2006\",\"3\":\"128.500\",\"4\":\"233.500\",\"5\":\"135.500\",\"6\":\"241.500\"},{\"1\":\"July\",\"2\":\"2006\",\"3\":\"128.500\",\"4\":\"233.500\",\"5\":\"135.500\",\"6\":\"241.500\"},{\"1\":\"August\",\"2\":\"2006\",\"3\":\"128.500\",\"4\":\"233.500\",\"5\":\"135.500\",\"6\":\"241.500\"},{\"1\":\"September\",\"2\":\"2006\",\"3\":\"128.500\",\"4\":\"233.500\",\"5\":\"135.500\",\"6\":\"241.500\"},{\"1\":\"October\",\"2\":\"2006\",\"3\":\"128.500\",\"4\":\"233.500\",\"5\":\"135.500\",\"6\":\"241.500\"},{\"1\":\"November\",\"2\":\"2006\",\"3\":\"128.500\",\"4\":\"233.500\",\"5\":\"135.500\",\"6\":\"241.500\"},{\"1\":\"December\",\"2\":\"2006\",\"3\":\"128.500\",\"4\":\"233.500\",\"5\":\"135.500\",\"6\":\"241.500\"},{\"1\":\"January\",\"2\":\"2007\",\"3\":\"128.500\",\"4\":\"233.500\",\"5\":\"135.500\",\"6\":\"241.500\"},{\"1\":\"February\",\"2\":\"2007\",\"3\":\"131.125\",\"4\":\"236.125\",\"5\":\"138.125\",\"6\":\"244.125\"},{\"1\":\"March\",\"2\":\"2007\",\"3\":\"132.000\",\"4\":\"237.000\",\"5\":\"139.000\",\"6\":\"245.000\"},{\"1\":\"April\",\"2\":\"2007\",\"3\":\"132.000\",\"4\":\"237.000\",\"5\":\"139.000\",\"6\":\"245.000\"},{\"1\":\"May\",\"2\":\"2007\",\"3\":\"132.000\",\"4\":\"237.000\",\"5\":\"139.000\",\"6\":\"245.000\"},{\"1\":\"June\",\"2\":\"2007\",\"3\":\"132.000\",\"4\":\"237.000\",\"5\":\"139.000\",\"6\":\"245.000\"},{\"1\":\"July\",\"2\":\"2007\",\"3\":\"132.000\",\"4\":\"237.000\",\"5\":\"139.000\",\"6\":\"245.000\"},{\"1\":\"August\",\"2\":\"2007\",\"3\":\"132.000\",\"4\":\"237.000\",\"5\":\"139.000\",\"6\":\"245.000\"},{\"1\":\"September\",\"2\":\"2007\",\"3\":\"132.000\",\"4\":\"237.000\",\"5\":\"139.000\",\"6\":\"245.000\"},{\"1\":\"October\",\"2\":\"2007\",\"3\":\"132.000\",\"4\":\"237.000\",\"5\":\"139.000\",\"6\":\"245.000\"},{\"1\":\"November\",\"2\":\"2007\",\"3\":\"132.000\",\"4\":\"237.000\",\"5\":\"139.000\",\"6\":\"245.000\"},{\"1\":\"December\",\"2\":\"2007\",\"3\":\"132.000\",\"4\":\"237.000\",\"5\":\"139.000\",\"6\":\"245.000\"},{\"1\":\"January\",\"2\":\"2008\",\"3\":\"132.000\",\"4\":\"237.000\",\"5\":\"139.000\",\"6\":\"245.000\"},{\"1\":\"February\",\"2\":\"2008\",\"3\":\"132.000\",\"4\":\"237.000\",\"5\":\"139.000\",\"6\":\"245.000\"},{\"1\":\"March\",\"2\":\"2008\",\"3\":\"132.000\",\"4\":\"237.000\",\"5\":\"139.000\",\"6\":\"245.000\"},{\"1\":\"April\",\"2\":\"2008\",\"3\":\"132.000\",\"4\":\"237.000\",\"5\":\"139.000\",\"6\":\"245.000\"},{\"1\":\"May\",\"2\":\"2008\",\"3\":\"132.000\",\"4\":\"237.000\",\"5\":\"139.000\",\"6\":\"245.000\"},{\"1\":\"June\",\"2\":\"2008\",\"3\":\"174.500\",\"4\":\"277.500\",\"5\":\"185.500\",\"6\":\"285.500\"},{\"1\":\"July\",\"2\":\"2008\",\"3\":\"174.500\",\"4\":\"277.500\",\"5\":\"185.500\",\"6\":\"285.500\"},{\"1\":\"August\",\"2\":\"2008\",\"3\":\"174.500\",\"4\":\"277.500\",\"5\":\"185.500\",\"6\":\"285.500\"},{\"1\":\"September\",\"2\":\"2008\",\"3\":\"174.500\",\"4\":\"277.500\",\"5\":\"185.500\",\"6\":\"285.500\"},{\"1\":\"October\",\"2\":\"2008\",\"3\":\"174.500\",\"4\":\"277.500\",\"5\":\"185.500\",\"6\":\"285.500\"},{\"1\":\"November\",\"2\":\"2008\",\"3\":\"174.500\",\"4\":\"277.500\",\"5\":\"185.500\",\"6\":\"285.500\"},{\"1\":\"December\",\"2\":\"2008\",\"3\":\"174.500\",\"4\":\"277.500\",\"5\":\"185.500\",\"6\":\"285.500\"},{\"1\":\"January\",\"2\":\"2009\",\"3\":\"174.500\",\"4\":\"277.500\",\"5\":\"185.500\",\"6\":\"285.500\"},{\"1\":\"February\",\"2\":\"2009\",\"3\":\"174.500\",\"4\":\"277.500\",\"5\":\"185.500\",\"6\":\"285.500\"},{\"1\":\"March\",\"2\":\"2009\",\"3\":\"174.500\",\"4\":\"277.500\",\"5\":\"185.500\",\"6\":\"285.500\"},{\"1\":\"April\",\"2\":\"2009\",\"3\":\"174.500\",\"4\":\"277.500\",\"5\":\"185.500\",\"6\":\"285.500\"},{\"1\":\"May\",\"2\":\"2009\",\"3\":\"174.500\",\"4\":\"277.500\",\"5\":\"185.500\",\"6\":\"285.500\"},{\"1\":\"June\",\"2\":\"2009\",\"3\":\"174.500\",\"4\":\"277.500\",\"5\":\"185.500\",\"6\":\"285.500\"},{\"1\":\"July\",\"2\":\"2009\",\"3\":\"174.500\",\"4\":\"277.500\",\"5\":\"185.500\",\"6\":\"285.500\"},{\"1\":\"August\",\"2\":\"2009\",\"3\":\"174.500\",\"4\":\"271.500\",\"5\":\"185.500\",\"6\":\"285.500\"},{\"1\":\"September\",\"2\":\"2009\",\"3\":\"174.500\",\"4\":\"271.500\",\"5\":\"185.500\",\"6\":\"285.500\"},{\"1\":\"October\",\"2\":\"2009\",\"3\":\"174.500\",\"4\":\"271.500\",\"5\":\"185.500\",\"6\":\"285.500\"},{\"1\":\"November\",\"2\":\"2009\",\"3\":\"174.500\",\"4\":\"271.500\",\"5\":\"185.500\",\"6\":\"285.500\"},{\"1\":\"December\",\"2\":\"2009\",\"3\":\"174.500\",\"4\":\"271.500\",\"5\":\"185.500\",\"6\":\"285.500\"},{\"1\":\"January\",\"2\":\"2010\",\"3\":\"174.500\",\"4\":\"271.500\",\"5\":\"185.500\",\"6\":\"285.500\"},{\"1\":\"February\",\"2\":\"2010\",\"3\":\"174.500\",\"4\":\"271.500\",\"5\":\"185.500\",\"6\":\"285.500\"},{\"1\":\"March\",\"2\":\"2010\",\"3\":\"174.500\",\"4\":\"268.000\",\"5\":\"185.500\",\"6\":\"285.500\"},{\"1\":\"April\",\"2\":\"2010\",\"3\":\"174.500\",\"4\":\"268.000\",\"5\":\"185.500\",\"6\":\"285.500\"},{\"1\":\"May\",\"2\":\"2010\",\"3\":\"174.500\",\"4\":\"268.000\",\"5\":\"185.500\",\"6\":\"285.500\"},{\"1\":\"June\",\"2\":\"2010\",\"3\":\"174.500\",\"4\":\"268.000\",\"5\":\"185.500\",\"6\":\"285.500\"},{\"1\":\"July\",\"2\":\"2010\",\"3\":\"174.500\",\"4\":\"268.000\",\"5\":\"185.500\",\"6\":\"285.500\"},{\"1\":\"August\",\"2\":\"2010\",\"3\":\"174.500\",\"4\":\"268.000\",\"5\":\"185.500\",\"6\":\"285.500\"},{\"1\":\"September\",\"2\":\"2010\",\"3\":\"174.500\",\"4\":\"268.000\",\"5\":\"185.500\",\"6\":\"285.500\"},{\"1\":\"October\",\"2\":\"2010\",\"3\":\"174.500\",\"4\":\"267.500\",\"5\":\"185.500\",\"6\":\"285.500\"},{\"1\":\"November\",\"2\":\"2010\",\"3\":\"174.500\",\"4\":\"267.500\",\"5\":\"185.500\",\"6\":\"285.500\"},{\"1\":\"December\",\"2\":\"2010\",\"3\":\"174.500\",\"4\":\"267.500\",\"5\":\"185.500\",\"6\":\"285.500\"},{\"1\":\"January\",\"2\":\"2011\",\"3\":\"174.500\",\"4\":\"267.500\",\"5\":\"185.500\",\"6\":\"285.500\"},{\"1\":\"February\",\"2\":\"2011\",\"3\":\"174.500\",\"4\":\"267.500\",\"5\":\"185.500\",\"6\":\"285.500\"},{\"1\":\"March\",\"2\":\"2011\",\"3\":\"174.500\",\"4\":\"267.500\",\"5\":\"185.500\",\"6\":\"285.500\"},{\"1\":\"April\",\"2\":\"2011\",\"3\":\"174.500\",\"4\":\"267.500\",\"5\":\"185.500\",\"6\":\"285.500\"},{\"1\":\"May\",\"2\":\"2011\",\"3\":\"174.500\",\"4\":\"267.500\",\"5\":\"185.500\",\"6\":\"285.500\"},{\"1\":\"June\",\"2\":\"2011\",\"3\":\"174.500\",\"4\":\"270.000\",\"5\":\"185.500\",\"6\":\"285.500\"},{\"1\":\"July\",\"2\":\"2011\",\"3\":\"174.500\",\"4\":\"270.000\",\"5\":\"185.500\",\"6\":\"285.500\"},{\"1\":\"August\",\"2\":\"2011\",\"3\":\"174.500\",\"4\":\"270.000\",\"5\":\"185.500\",\"6\":\"285.500\"},{\"1\":\"September\",\"2\":\"2011\",\"3\":\"174.500\",\"4\":\"270.000\",\"5\":\"185.500\",\"6\":\"285.500\"},{\"1\":\"October\",\"2\":\"2011\",\"3\":\"174.500\",\"4\":\"270.000\",\"5\":\"185.500\",\"6\":\"285.500\"},{\"1\":\"November\",\"2\":\"2011\",\"3\":\"174.500\",\"4\":\"270.000\",\"5\":\"185.500\",\"6\":\"285.500\"},{\"1\":\"December\",\"2\":\"2011\",\"3\":\"174.500\",\"4\":\"270.000\",\"5\":\"185.500\",\"6\":\"285.500\"},{\"1\":\"January\",\"2\":\"2012\",\"3\":\"174.500\",\"4\":\"267.500\",\"5\":\"185.500\",\"6\":\"285.500\"},{\"1\":\"February\",\"2\":\"2012\",\"3\":\"174.500\",\"4\":\"267.500\",\"5\":\"185.500\",\"6\":\"288.500\"},{\"1\":\"March\",\"2\":\"2012\",\"3\":\"174.500\",\"4\":\"267.500\",\"5\":\"185.500\",\"6\":\"288.500\"},{\"1\":\"April\",\"2\":\"2012\",\"3\":\"174.500\",\"4\":\"267.500\",\"5\":\"185.500\",\"6\":\"288.500\"},{\"1\":\"May\",\"2\":\"2012\",\"3\":\"173.250\",\"4\":\"267.500\",\"5\":\"185.500\",\"6\":\"288.500\"},{\"1\":\"June\",\"2\":\"2012\",\"3\":\"173.250\",\"4\":\"267.500\",\"5\":\"185.500\",\"6\":\"288.500\"},{\"1\":\"July\",\"2\":\"2012\",\"3\":\"173.250\",\"4\":\"267.500\",\"5\":\"185.500\",\"6\":\"288.500\"},{\"1\":\"August\",\"2\":\"2012\",\"3\":\"173.250\",\"4\":\"267.500\",\"5\":\"185.500\",\"6\":\"288.500\"},{\"1\":\"September\",\"2\":\"2012\",\"3\":\"173.250\",\"4\":\"267.500\",\"5\":\"185.500\",\"6\":\"288.500\"},{\"1\":\"October\",\"2\":\"2012\",\"3\":\"173.250\",\"4\":\"267.500\",\"5\":\"185.500\",\"6\":\"288.500\"},{\"1\":\"November\",\"2\":\"2012\",\"3\":\"178.000\",\"4\":\"267.500\",\"5\":\"188.130\",\"6\":\"290.000\"},{\"1\":\"December\",\"2\":\"2012\",\"3\":\"178.000\",\"4\":\"267.500\",\"5\":\"188.130\",\"6\":\"290.000\"},{\"1\":\"January\",\"2\":\"2013\",\"3\":\"178.000\",\"4\":\"267.500\",\"5\":\"188.130\",\"6\":\"290.000\"},{\"1\":\"February\",\"2\":\"2013\",\"3\":\"178.000\",\"4\":\"267.500\",\"5\":\"188.130\",\"6\":\"290.000\"},{\"1\":\"March\",\"2\":\"2013\",\"3\":\"178.000\",\"4\":\"267.500\",\"5\":\"188.130\",\"6\":\"290.000\"},{\"1\":\"April\",\"2\":\"2013\",\"3\":\"178.000\",\"4\":\"267.500\",\"5\":\"188.130\",\"6\":\"290.000\"},{\"1\":\"May\",\"2\":\"2013\",\"3\":\"178.000\",\"4\":\"267.500\",\"5\":\"188.130\",\"6\":\"290.000\"},{\"1\":\"June\",\"2\":\"2013\",\"3\":\"178.000\",\"4\":\"267.500\",\"5\":\"188.130\",\"6\":\"290.000\"},{\"1\":\"July\",\"2\":\"2013\",\"3\":\"178.000\",\"4\":\"267.500\",\"5\":\"188.130\",\"6\":\"290.000\"},{\"1\":\"August\",\"2\":\"2013\",\"3\":\"178.000\",\"4\":\"267.500\",\"5\":\"188.130\",\"6\":\"290.000\"},{\"1\":\"September\",\"2\":\"2013\",\"3\":\"178.000\",\"4\":\"267.500\",\"5\":\"188.130\",\"6\":\"290.000\"},{\"1\":\"October\",\"2\":\"2013\",\"3\":\"178.000\",\"4\":\"267.500\",\"5\":\"188.130\",\"6\":\"290.000\"},{\"1\":\"November\",\"2\":\"2013\",\"3\":\"178.000\",\"4\":\"267.500\",\"5\":\"188.130\",\"6\":\"290.000\"},{\"1\":\"December\",\"2\":\"2013\",\"3\":\"178.000\",\"4\":\"267.500\",\"5\":\"188.130\",\"6\":\"290.000\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n### Briefly describe the data\n\nThe data set appears to show the number of sets of a dozen and half dozen large and extra large eggs, likely on a specific farm. Each observation/row shows data from a specific month. The data has 120 rows and 6 columns.\n\nBecause the columns other than `year` and `month` all measure number of eggs, we can pivot the data to combine the eggs together, and add the new columns `type` and `amount` to maintain the dozen/half dozen information and the amount information. Based on this, we know that the pivot will have four (2+2) columns.\n\nWe are effectively turning the existing columns `large_half_dozen`, `large_dozen`, `extra_large_half_dozen`, and `extra_large_dozen` into rows with the resulting rate of four rows in the pivot to one row in the existing data (four rows for a given month). This means that our data should have the following number of rows:\n\n::: {.cell}\n\n```{.r .cell-code}\nnrow(eggs)*4\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 480\n```\n:::\n:::\n\n\n## Pivot the Data\n\nNow we will pivot the data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\neggs<-\n  eggs%>%\n    pivot_longer(col=c(large_half_dozen,large_dozen,extra_large_half_dozen,extra_large_dozen),\n                                 names_to=\"type\",\n                                 values_to=\"amount\")\neggs\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"month\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"year\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"type\"],\"name\":[3],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"amount\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"January\",\"2\":\"2004\",\"3\":\"large_half_dozen\",\"4\":\"126.000\"},{\"1\":\"January\",\"2\":\"2004\",\"3\":\"large_dozen\",\"4\":\"230.000\"},{\"1\":\"January\",\"2\":\"2004\",\"3\":\"extra_large_half_dozen\",\"4\":\"132.000\"},{\"1\":\"January\",\"2\":\"2004\",\"3\":\"extra_large_dozen\",\"4\":\"230.000\"},{\"1\":\"February\",\"2\":\"2004\",\"3\":\"large_half_dozen\",\"4\":\"128.500\"},{\"1\":\"February\",\"2\":\"2004\",\"3\":\"large_dozen\",\"4\":\"226.250\"},{\"1\":\"February\",\"2\":\"2004\",\"3\":\"extra_large_half_dozen\",\"4\":\"134.500\"},{\"1\":\"February\",\"2\":\"2004\",\"3\":\"extra_large_dozen\",\"4\":\"230.000\"},{\"1\":\"March\",\"2\":\"2004\",\"3\":\"large_half_dozen\",\"4\":\"131.000\"},{\"1\":\"March\",\"2\":\"2004\",\"3\":\"large_dozen\",\"4\":\"225.000\"},{\"1\":\"March\",\"2\":\"2004\",\"3\":\"extra_large_half_dozen\",\"4\":\"137.000\"},{\"1\":\"March\",\"2\":\"2004\",\"3\":\"extra_large_dozen\",\"4\":\"230.000\"},{\"1\":\"April\",\"2\":\"2004\",\"3\":\"large_half_dozen\",\"4\":\"131.000\"},{\"1\":\"April\",\"2\":\"2004\",\"3\":\"large_dozen\",\"4\":\"225.000\"},{\"1\":\"April\",\"2\":\"2004\",\"3\":\"extra_large_half_dozen\",\"4\":\"137.000\"},{\"1\":\"April\",\"2\":\"2004\",\"3\":\"extra_large_dozen\",\"4\":\"234.500\"},{\"1\":\"May\",\"2\":\"2004\",\"3\":\"large_half_dozen\",\"4\":\"131.000\"},{\"1\":\"May\",\"2\":\"2004\",\"3\":\"large_dozen\",\"4\":\"225.000\"},{\"1\":\"May\",\"2\":\"2004\",\"3\":\"extra_large_half_dozen\",\"4\":\"137.000\"},{\"1\":\"May\",\"2\":\"2004\",\"3\":\"extra_large_dozen\",\"4\":\"236.000\"},{\"1\":\"June\",\"2\":\"2004\",\"3\":\"large_half_dozen\",\"4\":\"133.500\"},{\"1\":\"June\",\"2\":\"2004\",\"3\":\"large_dozen\",\"4\":\"231.375\"},{\"1\":\"June\",\"2\":\"2004\",\"3\":\"extra_large_half_dozen\",\"4\":\"137.000\"},{\"1\":\"June\",\"2\":\"2004\",\"3\":\"extra_large_dozen\",\"4\":\"241.000\"},{\"1\":\"July\",\"2\":\"2004\",\"3\":\"large_half_dozen\",\"4\":\"133.500\"},{\"1\":\"July\",\"2\":\"2004\",\"3\":\"large_dozen\",\"4\":\"233.500\"},{\"1\":\"July\",\"2\":\"2004\",\"3\":\"extra_large_half_dozen\",\"4\":\"137.000\"},{\"1\":\"July\",\"2\":\"2004\",\"3\":\"extra_large_dozen\",\"4\":\"241.000\"},{\"1\":\"August\",\"2\":\"2004\",\"3\":\"large_half_dozen\",\"4\":\"133.500\"},{\"1\":\"August\",\"2\":\"2004\",\"3\":\"large_dozen\",\"4\":\"233.500\"},{\"1\":\"August\",\"2\":\"2004\",\"3\":\"extra_large_half_dozen\",\"4\":\"137.000\"},{\"1\":\"August\",\"2\":\"2004\",\"3\":\"extra_large_dozen\",\"4\":\"241.000\"},{\"1\":\"September\",\"2\":\"2004\",\"3\":\"large_half_dozen\",\"4\":\"129.750\"},{\"1\":\"September\",\"2\":\"2004\",\"3\":\"large_dozen\",\"4\":\"233.500\"},{\"1\":\"September\",\"2\":\"2004\",\"3\":\"extra_large_half_dozen\",\"4\":\"135.875\"},{\"1\":\"September\",\"2\":\"2004\",\"3\":\"extra_large_dozen\",\"4\":\"241.000\"},{\"1\":\"October\",\"2\":\"2004\",\"3\":\"large_half_dozen\",\"4\":\"128.500\"},{\"1\":\"October\",\"2\":\"2004\",\"3\":\"large_dozen\",\"4\":\"233.500\"},{\"1\":\"October\",\"2\":\"2004\",\"3\":\"extra_large_half_dozen\",\"4\":\"135.500\"},{\"1\":\"October\",\"2\":\"2004\",\"3\":\"extra_large_dozen\",\"4\":\"241.000\"},{\"1\":\"November\",\"2\":\"2004\",\"3\":\"large_half_dozen\",\"4\":\"128.500\"},{\"1\":\"November\",\"2\":\"2004\",\"3\":\"large_dozen\",\"4\":\"233.500\"},{\"1\":\"November\",\"2\":\"2004\",\"3\":\"extra_large_half_dozen\",\"4\":\"135.500\"},{\"1\":\"November\",\"2\":\"2004\",\"3\":\"extra_large_dozen\",\"4\":\"241.000\"},{\"1\":\"December\",\"2\":\"2004\",\"3\":\"large_half_dozen\",\"4\":\"128.500\"},{\"1\":\"December\",\"2\":\"2004\",\"3\":\"large_dozen\",\"4\":\"233.500\"},{\"1\":\"December\",\"2\":\"2004\",\"3\":\"extra_large_half_dozen\",\"4\":\"135.500\"},{\"1\":\"December\",\"2\":\"2004\",\"3\":\"extra_large_dozen\",\"4\":\"241.000\"},{\"1\":\"January\",\"2\":\"2005\",\"3\":\"large_half_dozen\",\"4\":\"128.500\"},{\"1\":\"January\",\"2\":\"2005\",\"3\":\"large_dozen\",\"4\":\"233.500\"},{\"1\":\"January\",\"2\":\"2005\",\"3\":\"extra_large_half_dozen\",\"4\":\"135.500\"},{\"1\":\"January\",\"2\":\"2005\",\"3\":\"extra_large_dozen\",\"4\":\"241.000\"},{\"1\":\"February\",\"2\":\"2005\",\"3\":\"large_half_dozen\",\"4\":\"128.500\"},{\"1\":\"February\",\"2\":\"2005\",\"3\":\"large_dozen\",\"4\":\"233.500\"},{\"1\":\"February\",\"2\":\"2005\",\"3\":\"extra_large_half_dozen\",\"4\":\"135.500\"},{\"1\":\"February\",\"2\":\"2005\",\"3\":\"extra_large_dozen\",\"4\":\"241.000\"},{\"1\":\"March\",\"2\":\"2005\",\"3\":\"large_half_dozen\",\"4\":\"128.500\"},{\"1\":\"March\",\"2\":\"2005\",\"3\":\"large_dozen\",\"4\":\"233.500\"},{\"1\":\"March\",\"2\":\"2005\",\"3\":\"extra_large_half_dozen\",\"4\":\"135.500\"},{\"1\":\"March\",\"2\":\"2005\",\"3\":\"extra_large_dozen\",\"4\":\"241.000\"},{\"1\":\"April\",\"2\":\"2005\",\"3\":\"large_half_dozen\",\"4\":\"128.500\"},{\"1\":\"April\",\"2\":\"2005\",\"3\":\"large_dozen\",\"4\":\"233.500\"},{\"1\":\"April\",\"2\":\"2005\",\"3\":\"extra_large_half_dozen\",\"4\":\"135.500\"},{\"1\":\"April\",\"2\":\"2005\",\"3\":\"extra_large_dozen\",\"4\":\"241.000\"},{\"1\":\"May\",\"2\":\"2005\",\"3\":\"large_half_dozen\",\"4\":\"128.500\"},{\"1\":\"May\",\"2\":\"2005\",\"3\":\"large_dozen\",\"4\":\"233.500\"},{\"1\":\"May\",\"2\":\"2005\",\"3\":\"extra_large_half_dozen\",\"4\":\"135.500\"},{\"1\":\"May\",\"2\":\"2005\",\"3\":\"extra_large_dozen\",\"4\":\"241.000\"},{\"1\":\"June\",\"2\":\"2005\",\"3\":\"large_half_dozen\",\"4\":\"128.500\"},{\"1\":\"June\",\"2\":\"2005\",\"3\":\"large_dozen\",\"4\":\"233.500\"},{\"1\":\"June\",\"2\":\"2005\",\"3\":\"extra_large_half_dozen\",\"4\":\"135.500\"},{\"1\":\"June\",\"2\":\"2005\",\"3\":\"extra_large_dozen\",\"4\":\"241.000\"},{\"1\":\"July\",\"2\":\"2005\",\"3\":\"large_half_dozen\",\"4\":\"128.500\"},{\"1\":\"July\",\"2\":\"2005\",\"3\":\"large_dozen\",\"4\":\"233.500\"},{\"1\":\"July\",\"2\":\"2005\",\"3\":\"extra_large_half_dozen\",\"4\":\"135.500\"},{\"1\":\"July\",\"2\":\"2005\",\"3\":\"extra_large_dozen\",\"4\":\"241.000\"},{\"1\":\"August\",\"2\":\"2005\",\"3\":\"large_half_dozen\",\"4\":\"128.500\"},{\"1\":\"August\",\"2\":\"2005\",\"3\":\"large_dozen\",\"4\":\"233.500\"},{\"1\":\"August\",\"2\":\"2005\",\"3\":\"extra_large_half_dozen\",\"4\":\"135.500\"},{\"1\":\"August\",\"2\":\"2005\",\"3\":\"extra_large_dozen\",\"4\":\"241.000\"},{\"1\":\"September\",\"2\":\"2005\",\"3\":\"large_half_dozen\",\"4\":\"128.500\"},{\"1\":\"September\",\"2\":\"2005\",\"3\":\"large_dozen\",\"4\":\"233.500\"},{\"1\":\"September\",\"2\":\"2005\",\"3\":\"extra_large_half_dozen\",\"4\":\"135.500\"},{\"1\":\"September\",\"2\":\"2005\",\"3\":\"extra_large_dozen\",\"4\":\"241.000\"},{\"1\":\"October\",\"2\":\"2005\",\"3\":\"large_half_dozen\",\"4\":\"128.500\"},{\"1\":\"October\",\"2\":\"2005\",\"3\":\"large_dozen\",\"4\":\"233.500\"},{\"1\":\"October\",\"2\":\"2005\",\"3\":\"extra_large_half_dozen\",\"4\":\"135.500\"},{\"1\":\"October\",\"2\":\"2005\",\"3\":\"extra_large_dozen\",\"4\":\"241.000\"},{\"1\":\"November\",\"2\":\"2005\",\"3\":\"large_half_dozen\",\"4\":\"128.500\"},{\"1\":\"November\",\"2\":\"2005\",\"3\":\"large_dozen\",\"4\":\"233.500\"},{\"1\":\"November\",\"2\":\"2005\",\"3\":\"extra_large_half_dozen\",\"4\":\"135.500\"},{\"1\":\"November\",\"2\":\"2005\",\"3\":\"extra_large_dozen\",\"4\":\"241.000\"},{\"1\":\"December\",\"2\":\"2005\",\"3\":\"large_half_dozen\",\"4\":\"128.500\"},{\"1\":\"December\",\"2\":\"2005\",\"3\":\"large_dozen\",\"4\":\"233.500\"},{\"1\":\"December\",\"2\":\"2005\",\"3\":\"extra_large_half_dozen\",\"4\":\"135.500\"},{\"1\":\"December\",\"2\":\"2005\",\"3\":\"extra_large_dozen\",\"4\":\"241.000\"},{\"1\":\"January\",\"2\":\"2006\",\"3\":\"large_half_dozen\",\"4\":\"128.500\"},{\"1\":\"January\",\"2\":\"2006\",\"3\":\"large_dozen\",\"4\":\"233.500\"},{\"1\":\"January\",\"2\":\"2006\",\"3\":\"extra_large_half_dozen\",\"4\":\"135.500\"},{\"1\":\"January\",\"2\":\"2006\",\"3\":\"extra_large_dozen\",\"4\":\"241.000\"},{\"1\":\"February\",\"2\":\"2006\",\"3\":\"large_half_dozen\",\"4\":\"128.500\"},{\"1\":\"February\",\"2\":\"2006\",\"3\":\"large_dozen\",\"4\":\"233.500\"},{\"1\":\"February\",\"2\":\"2006\",\"3\":\"extra_large_half_dozen\",\"4\":\"135.500\"},{\"1\":\"February\",\"2\":\"2006\",\"3\":\"extra_large_dozen\",\"4\":\"241.000\"},{\"1\":\"March\",\"2\":\"2006\",\"3\":\"large_half_dozen\",\"4\":\"128.500\"},{\"1\":\"March\",\"2\":\"2006\",\"3\":\"large_dozen\",\"4\":\"233.500\"},{\"1\":\"March\",\"2\":\"2006\",\"3\":\"extra_large_half_dozen\",\"4\":\"135.500\"},{\"1\":\"March\",\"2\":\"2006\",\"3\":\"extra_large_dozen\",\"4\":\"241.375\"},{\"1\":\"April\",\"2\":\"2006\",\"3\":\"large_half_dozen\",\"4\":\"128.500\"},{\"1\":\"April\",\"2\":\"2006\",\"3\":\"large_dozen\",\"4\":\"233.500\"},{\"1\":\"April\",\"2\":\"2006\",\"3\":\"extra_large_half_dozen\",\"4\":\"135.500\"},{\"1\":\"April\",\"2\":\"2006\",\"3\":\"extra_large_dozen\",\"4\":\"241.500\"},{\"1\":\"May\",\"2\":\"2006\",\"3\":\"large_half_dozen\",\"4\":\"128.500\"},{\"1\":\"May\",\"2\":\"2006\",\"3\":\"large_dozen\",\"4\":\"233.500\"},{\"1\":\"May\",\"2\":\"2006\",\"3\":\"extra_large_half_dozen\",\"4\":\"135.500\"},{\"1\":\"May\",\"2\":\"2006\",\"3\":\"extra_large_dozen\",\"4\":\"241.500\"},{\"1\":\"June\",\"2\":\"2006\",\"3\":\"large_half_dozen\",\"4\":\"128.500\"},{\"1\":\"June\",\"2\":\"2006\",\"3\":\"large_dozen\",\"4\":\"233.500\"},{\"1\":\"June\",\"2\":\"2006\",\"3\":\"extra_large_half_dozen\",\"4\":\"135.500\"},{\"1\":\"June\",\"2\":\"2006\",\"3\":\"extra_large_dozen\",\"4\":\"241.500\"},{\"1\":\"July\",\"2\":\"2006\",\"3\":\"large_half_dozen\",\"4\":\"128.500\"},{\"1\":\"July\",\"2\":\"2006\",\"3\":\"large_dozen\",\"4\":\"233.500\"},{\"1\":\"July\",\"2\":\"2006\",\"3\":\"extra_large_half_dozen\",\"4\":\"135.500\"},{\"1\":\"July\",\"2\":\"2006\",\"3\":\"extra_large_dozen\",\"4\":\"241.500\"},{\"1\":\"August\",\"2\":\"2006\",\"3\":\"large_half_dozen\",\"4\":\"128.500\"},{\"1\":\"August\",\"2\":\"2006\",\"3\":\"large_dozen\",\"4\":\"233.500\"},{\"1\":\"August\",\"2\":\"2006\",\"3\":\"extra_large_half_dozen\",\"4\":\"135.500\"},{\"1\":\"August\",\"2\":\"2006\",\"3\":\"extra_large_dozen\",\"4\":\"241.500\"},{\"1\":\"September\",\"2\":\"2006\",\"3\":\"large_half_dozen\",\"4\":\"128.500\"},{\"1\":\"September\",\"2\":\"2006\",\"3\":\"large_dozen\",\"4\":\"233.500\"},{\"1\":\"September\",\"2\":\"2006\",\"3\":\"extra_large_half_dozen\",\"4\":\"135.500\"},{\"1\":\"September\",\"2\":\"2006\",\"3\":\"extra_large_dozen\",\"4\":\"241.500\"},{\"1\":\"October\",\"2\":\"2006\",\"3\":\"large_half_dozen\",\"4\":\"128.500\"},{\"1\":\"October\",\"2\":\"2006\",\"3\":\"large_dozen\",\"4\":\"233.500\"},{\"1\":\"October\",\"2\":\"2006\",\"3\":\"extra_large_half_dozen\",\"4\":\"135.500\"},{\"1\":\"October\",\"2\":\"2006\",\"3\":\"extra_large_dozen\",\"4\":\"241.500\"},{\"1\":\"November\",\"2\":\"2006\",\"3\":\"large_half_dozen\",\"4\":\"128.500\"},{\"1\":\"November\",\"2\":\"2006\",\"3\":\"large_dozen\",\"4\":\"233.500\"},{\"1\":\"November\",\"2\":\"2006\",\"3\":\"extra_large_half_dozen\",\"4\":\"135.500\"},{\"1\":\"November\",\"2\":\"2006\",\"3\":\"extra_large_dozen\",\"4\":\"241.500\"},{\"1\":\"December\",\"2\":\"2006\",\"3\":\"large_half_dozen\",\"4\":\"128.500\"},{\"1\":\"December\",\"2\":\"2006\",\"3\":\"large_dozen\",\"4\":\"233.500\"},{\"1\":\"December\",\"2\":\"2006\",\"3\":\"extra_large_half_dozen\",\"4\":\"135.500\"},{\"1\":\"December\",\"2\":\"2006\",\"3\":\"extra_large_dozen\",\"4\":\"241.500\"},{\"1\":\"January\",\"2\":\"2007\",\"3\":\"large_half_dozen\",\"4\":\"128.500\"},{\"1\":\"January\",\"2\":\"2007\",\"3\":\"large_dozen\",\"4\":\"233.500\"},{\"1\":\"January\",\"2\":\"2007\",\"3\":\"extra_large_half_dozen\",\"4\":\"135.500\"},{\"1\":\"January\",\"2\":\"2007\",\"3\":\"extra_large_dozen\",\"4\":\"241.500\"},{\"1\":\"February\",\"2\":\"2007\",\"3\":\"large_half_dozen\",\"4\":\"131.125\"},{\"1\":\"February\",\"2\":\"2007\",\"3\":\"large_dozen\",\"4\":\"236.125\"},{\"1\":\"February\",\"2\":\"2007\",\"3\":\"extra_large_half_dozen\",\"4\":\"138.125\"},{\"1\":\"February\",\"2\":\"2007\",\"3\":\"extra_large_dozen\",\"4\":\"244.125\"},{\"1\":\"March\",\"2\":\"2007\",\"3\":\"large_half_dozen\",\"4\":\"132.000\"},{\"1\":\"March\",\"2\":\"2007\",\"3\":\"large_dozen\",\"4\":\"237.000\"},{\"1\":\"March\",\"2\":\"2007\",\"3\":\"extra_large_half_dozen\",\"4\":\"139.000\"},{\"1\":\"March\",\"2\":\"2007\",\"3\":\"extra_large_dozen\",\"4\":\"245.000\"},{\"1\":\"April\",\"2\":\"2007\",\"3\":\"large_half_dozen\",\"4\":\"132.000\"},{\"1\":\"April\",\"2\":\"2007\",\"3\":\"large_dozen\",\"4\":\"237.000\"},{\"1\":\"April\",\"2\":\"2007\",\"3\":\"extra_large_half_dozen\",\"4\":\"139.000\"},{\"1\":\"April\",\"2\":\"2007\",\"3\":\"extra_large_dozen\",\"4\":\"245.000\"},{\"1\":\"May\",\"2\":\"2007\",\"3\":\"large_half_dozen\",\"4\":\"132.000\"},{\"1\":\"May\",\"2\":\"2007\",\"3\":\"large_dozen\",\"4\":\"237.000\"},{\"1\":\"May\",\"2\":\"2007\",\"3\":\"extra_large_half_dozen\",\"4\":\"139.000\"},{\"1\":\"May\",\"2\":\"2007\",\"3\":\"extra_large_dozen\",\"4\":\"245.000\"},{\"1\":\"June\",\"2\":\"2007\",\"3\":\"large_half_dozen\",\"4\":\"132.000\"},{\"1\":\"June\",\"2\":\"2007\",\"3\":\"large_dozen\",\"4\":\"237.000\"},{\"1\":\"June\",\"2\":\"2007\",\"3\":\"extra_large_half_dozen\",\"4\":\"139.000\"},{\"1\":\"June\",\"2\":\"2007\",\"3\":\"extra_large_dozen\",\"4\":\"245.000\"},{\"1\":\"July\",\"2\":\"2007\",\"3\":\"large_half_dozen\",\"4\":\"132.000\"},{\"1\":\"July\",\"2\":\"2007\",\"3\":\"large_dozen\",\"4\":\"237.000\"},{\"1\":\"July\",\"2\":\"2007\",\"3\":\"extra_large_half_dozen\",\"4\":\"139.000\"},{\"1\":\"July\",\"2\":\"2007\",\"3\":\"extra_large_dozen\",\"4\":\"245.000\"},{\"1\":\"August\",\"2\":\"2007\",\"3\":\"large_half_dozen\",\"4\":\"132.000\"},{\"1\":\"August\",\"2\":\"2007\",\"3\":\"large_dozen\",\"4\":\"237.000\"},{\"1\":\"August\",\"2\":\"2007\",\"3\":\"extra_large_half_dozen\",\"4\":\"139.000\"},{\"1\":\"August\",\"2\":\"2007\",\"3\":\"extra_large_dozen\",\"4\":\"245.000\"},{\"1\":\"September\",\"2\":\"2007\",\"3\":\"large_half_dozen\",\"4\":\"132.000\"},{\"1\":\"September\",\"2\":\"2007\",\"3\":\"large_dozen\",\"4\":\"237.000\"},{\"1\":\"September\",\"2\":\"2007\",\"3\":\"extra_large_half_dozen\",\"4\":\"139.000\"},{\"1\":\"September\",\"2\":\"2007\",\"3\":\"extra_large_dozen\",\"4\":\"245.000\"},{\"1\":\"October\",\"2\":\"2007\",\"3\":\"large_half_dozen\",\"4\":\"132.000\"},{\"1\":\"October\",\"2\":\"2007\",\"3\":\"large_dozen\",\"4\":\"237.000\"},{\"1\":\"October\",\"2\":\"2007\",\"3\":\"extra_large_half_dozen\",\"4\":\"139.000\"},{\"1\":\"October\",\"2\":\"2007\",\"3\":\"extra_large_dozen\",\"4\":\"245.000\"},{\"1\":\"November\",\"2\":\"2007\",\"3\":\"large_half_dozen\",\"4\":\"132.000\"},{\"1\":\"November\",\"2\":\"2007\",\"3\":\"large_dozen\",\"4\":\"237.000\"},{\"1\":\"November\",\"2\":\"2007\",\"3\":\"extra_large_half_dozen\",\"4\":\"139.000\"},{\"1\":\"November\",\"2\":\"2007\",\"3\":\"extra_large_dozen\",\"4\":\"245.000\"},{\"1\":\"December\",\"2\":\"2007\",\"3\":\"large_half_dozen\",\"4\":\"132.000\"},{\"1\":\"December\",\"2\":\"2007\",\"3\":\"large_dozen\",\"4\":\"237.000\"},{\"1\":\"December\",\"2\":\"2007\",\"3\":\"extra_large_half_dozen\",\"4\":\"139.000\"},{\"1\":\"December\",\"2\":\"2007\",\"3\":\"extra_large_dozen\",\"4\":\"245.000\"},{\"1\":\"January\",\"2\":\"2008\",\"3\":\"large_half_dozen\",\"4\":\"132.000\"},{\"1\":\"January\",\"2\":\"2008\",\"3\":\"large_dozen\",\"4\":\"237.000\"},{\"1\":\"January\",\"2\":\"2008\",\"3\":\"extra_large_half_dozen\",\"4\":\"139.000\"},{\"1\":\"January\",\"2\":\"2008\",\"3\":\"extra_large_dozen\",\"4\":\"245.000\"},{\"1\":\"February\",\"2\":\"2008\",\"3\":\"large_half_dozen\",\"4\":\"132.000\"},{\"1\":\"February\",\"2\":\"2008\",\"3\":\"large_dozen\",\"4\":\"237.000\"},{\"1\":\"February\",\"2\":\"2008\",\"3\":\"extra_large_half_dozen\",\"4\":\"139.000\"},{\"1\":\"February\",\"2\":\"2008\",\"3\":\"extra_large_dozen\",\"4\":\"245.000\"},{\"1\":\"March\",\"2\":\"2008\",\"3\":\"large_half_dozen\",\"4\":\"132.000\"},{\"1\":\"March\",\"2\":\"2008\",\"3\":\"large_dozen\",\"4\":\"237.000\"},{\"1\":\"March\",\"2\":\"2008\",\"3\":\"extra_large_half_dozen\",\"4\":\"139.000\"},{\"1\":\"March\",\"2\":\"2008\",\"3\":\"extra_large_dozen\",\"4\":\"245.000\"},{\"1\":\"April\",\"2\":\"2008\",\"3\":\"large_half_dozen\",\"4\":\"132.000\"},{\"1\":\"April\",\"2\":\"2008\",\"3\":\"large_dozen\",\"4\":\"237.000\"},{\"1\":\"April\",\"2\":\"2008\",\"3\":\"extra_large_half_dozen\",\"4\":\"139.000\"},{\"1\":\"April\",\"2\":\"2008\",\"3\":\"extra_large_dozen\",\"4\":\"245.000\"},{\"1\":\"May\",\"2\":\"2008\",\"3\":\"large_half_dozen\",\"4\":\"132.000\"},{\"1\":\"May\",\"2\":\"2008\",\"3\":\"large_dozen\",\"4\":\"237.000\"},{\"1\":\"May\",\"2\":\"2008\",\"3\":\"extra_large_half_dozen\",\"4\":\"139.000\"},{\"1\":\"May\",\"2\":\"2008\",\"3\":\"extra_large_dozen\",\"4\":\"245.000\"},{\"1\":\"June\",\"2\":\"2008\",\"3\":\"large_half_dozen\",\"4\":\"174.500\"},{\"1\":\"June\",\"2\":\"2008\",\"3\":\"large_dozen\",\"4\":\"277.500\"},{\"1\":\"June\",\"2\":\"2008\",\"3\":\"extra_large_half_dozen\",\"4\":\"185.500\"},{\"1\":\"June\",\"2\":\"2008\",\"3\":\"extra_large_dozen\",\"4\":\"285.500\"},{\"1\":\"July\",\"2\":\"2008\",\"3\":\"large_half_dozen\",\"4\":\"174.500\"},{\"1\":\"July\",\"2\":\"2008\",\"3\":\"large_dozen\",\"4\":\"277.500\"},{\"1\":\"July\",\"2\":\"2008\",\"3\":\"extra_large_half_dozen\",\"4\":\"185.500\"},{\"1\":\"July\",\"2\":\"2008\",\"3\":\"extra_large_dozen\",\"4\":\"285.500\"},{\"1\":\"August\",\"2\":\"2008\",\"3\":\"large_half_dozen\",\"4\":\"174.500\"},{\"1\":\"August\",\"2\":\"2008\",\"3\":\"large_dozen\",\"4\":\"277.500\"},{\"1\":\"August\",\"2\":\"2008\",\"3\":\"extra_large_half_dozen\",\"4\":\"185.500\"},{\"1\":\"August\",\"2\":\"2008\",\"3\":\"extra_large_dozen\",\"4\":\"285.500\"},{\"1\":\"September\",\"2\":\"2008\",\"3\":\"large_half_dozen\",\"4\":\"174.500\"},{\"1\":\"September\",\"2\":\"2008\",\"3\":\"large_dozen\",\"4\":\"277.500\"},{\"1\":\"September\",\"2\":\"2008\",\"3\":\"extra_large_half_dozen\",\"4\":\"185.500\"},{\"1\":\"September\",\"2\":\"2008\",\"3\":\"extra_large_dozen\",\"4\":\"285.500\"},{\"1\":\"October\",\"2\":\"2008\",\"3\":\"large_half_dozen\",\"4\":\"174.500\"},{\"1\":\"October\",\"2\":\"2008\",\"3\":\"large_dozen\",\"4\":\"277.500\"},{\"1\":\"October\",\"2\":\"2008\",\"3\":\"extra_large_half_dozen\",\"4\":\"185.500\"},{\"1\":\"October\",\"2\":\"2008\",\"3\":\"extra_large_dozen\",\"4\":\"285.500\"},{\"1\":\"November\",\"2\":\"2008\",\"3\":\"large_half_dozen\",\"4\":\"174.500\"},{\"1\":\"November\",\"2\":\"2008\",\"3\":\"large_dozen\",\"4\":\"277.500\"},{\"1\":\"November\",\"2\":\"2008\",\"3\":\"extra_large_half_dozen\",\"4\":\"185.500\"},{\"1\":\"November\",\"2\":\"2008\",\"3\":\"extra_large_dozen\",\"4\":\"285.500\"},{\"1\":\"December\",\"2\":\"2008\",\"3\":\"large_half_dozen\",\"4\":\"174.500\"},{\"1\":\"December\",\"2\":\"2008\",\"3\":\"large_dozen\",\"4\":\"277.500\"},{\"1\":\"December\",\"2\":\"2008\",\"3\":\"extra_large_half_dozen\",\"4\":\"185.500\"},{\"1\":\"December\",\"2\":\"2008\",\"3\":\"extra_large_dozen\",\"4\":\"285.500\"},{\"1\":\"January\",\"2\":\"2009\",\"3\":\"large_half_dozen\",\"4\":\"174.500\"},{\"1\":\"January\",\"2\":\"2009\",\"3\":\"large_dozen\",\"4\":\"277.500\"},{\"1\":\"January\",\"2\":\"2009\",\"3\":\"extra_large_half_dozen\",\"4\":\"185.500\"},{\"1\":\"January\",\"2\":\"2009\",\"3\":\"extra_large_dozen\",\"4\":\"285.500\"},{\"1\":\"February\",\"2\":\"2009\",\"3\":\"large_half_dozen\",\"4\":\"174.500\"},{\"1\":\"February\",\"2\":\"2009\",\"3\":\"large_dozen\",\"4\":\"277.500\"},{\"1\":\"February\",\"2\":\"2009\",\"3\":\"extra_large_half_dozen\",\"4\":\"185.500\"},{\"1\":\"February\",\"2\":\"2009\",\"3\":\"extra_large_dozen\",\"4\":\"285.500\"},{\"1\":\"March\",\"2\":\"2009\",\"3\":\"large_half_dozen\",\"4\":\"174.500\"},{\"1\":\"March\",\"2\":\"2009\",\"3\":\"large_dozen\",\"4\":\"277.500\"},{\"1\":\"March\",\"2\":\"2009\",\"3\":\"extra_large_half_dozen\",\"4\":\"185.500\"},{\"1\":\"March\",\"2\":\"2009\",\"3\":\"extra_large_dozen\",\"4\":\"285.500\"},{\"1\":\"April\",\"2\":\"2009\",\"3\":\"large_half_dozen\",\"4\":\"174.500\"},{\"1\":\"April\",\"2\":\"2009\",\"3\":\"large_dozen\",\"4\":\"277.500\"},{\"1\":\"April\",\"2\":\"2009\",\"3\":\"extra_large_half_dozen\",\"4\":\"185.500\"},{\"1\":\"April\",\"2\":\"2009\",\"3\":\"extra_large_dozen\",\"4\":\"285.500\"},{\"1\":\"May\",\"2\":\"2009\",\"3\":\"large_half_dozen\",\"4\":\"174.500\"},{\"1\":\"May\",\"2\":\"2009\",\"3\":\"large_dozen\",\"4\":\"277.500\"},{\"1\":\"May\",\"2\":\"2009\",\"3\":\"extra_large_half_dozen\",\"4\":\"185.500\"},{\"1\":\"May\",\"2\":\"2009\",\"3\":\"extra_large_dozen\",\"4\":\"285.500\"},{\"1\":\"June\",\"2\":\"2009\",\"3\":\"large_half_dozen\",\"4\":\"174.500\"},{\"1\":\"June\",\"2\":\"2009\",\"3\":\"large_dozen\",\"4\":\"277.500\"},{\"1\":\"June\",\"2\":\"2009\",\"3\":\"extra_large_half_dozen\",\"4\":\"185.500\"},{\"1\":\"June\",\"2\":\"2009\",\"3\":\"extra_large_dozen\",\"4\":\"285.500\"},{\"1\":\"July\",\"2\":\"2009\",\"3\":\"large_half_dozen\",\"4\":\"174.500\"},{\"1\":\"July\",\"2\":\"2009\",\"3\":\"large_dozen\",\"4\":\"277.500\"},{\"1\":\"July\",\"2\":\"2009\",\"3\":\"extra_large_half_dozen\",\"4\":\"185.500\"},{\"1\":\"July\",\"2\":\"2009\",\"3\":\"extra_large_dozen\",\"4\":\"285.500\"},{\"1\":\"August\",\"2\":\"2009\",\"3\":\"large_half_dozen\",\"4\":\"174.500\"},{\"1\":\"August\",\"2\":\"2009\",\"3\":\"large_dozen\",\"4\":\"271.500\"},{\"1\":\"August\",\"2\":\"2009\",\"3\":\"extra_large_half_dozen\",\"4\":\"185.500\"},{\"1\":\"August\",\"2\":\"2009\",\"3\":\"extra_large_dozen\",\"4\":\"285.500\"},{\"1\":\"September\",\"2\":\"2009\",\"3\":\"large_half_dozen\",\"4\":\"174.500\"},{\"1\":\"September\",\"2\":\"2009\",\"3\":\"large_dozen\",\"4\":\"271.500\"},{\"1\":\"September\",\"2\":\"2009\",\"3\":\"extra_large_half_dozen\",\"4\":\"185.500\"},{\"1\":\"September\",\"2\":\"2009\",\"3\":\"extra_large_dozen\",\"4\":\"285.500\"},{\"1\":\"October\",\"2\":\"2009\",\"3\":\"large_half_dozen\",\"4\":\"174.500\"},{\"1\":\"October\",\"2\":\"2009\",\"3\":\"large_dozen\",\"4\":\"271.500\"},{\"1\":\"October\",\"2\":\"2009\",\"3\":\"extra_large_half_dozen\",\"4\":\"185.500\"},{\"1\":\"October\",\"2\":\"2009\",\"3\":\"extra_large_dozen\",\"4\":\"285.500\"},{\"1\":\"November\",\"2\":\"2009\",\"3\":\"large_half_dozen\",\"4\":\"174.500\"},{\"1\":\"November\",\"2\":\"2009\",\"3\":\"large_dozen\",\"4\":\"271.500\"},{\"1\":\"November\",\"2\":\"2009\",\"3\":\"extra_large_half_dozen\",\"4\":\"185.500\"},{\"1\":\"November\",\"2\":\"2009\",\"3\":\"extra_large_dozen\",\"4\":\"285.500\"},{\"1\":\"December\",\"2\":\"2009\",\"3\":\"large_half_dozen\",\"4\":\"174.500\"},{\"1\":\"December\",\"2\":\"2009\",\"3\":\"large_dozen\",\"4\":\"271.500\"},{\"1\":\"December\",\"2\":\"2009\",\"3\":\"extra_large_half_dozen\",\"4\":\"185.500\"},{\"1\":\"December\",\"2\":\"2009\",\"3\":\"extra_large_dozen\",\"4\":\"285.500\"},{\"1\":\"January\",\"2\":\"2010\",\"3\":\"large_half_dozen\",\"4\":\"174.500\"},{\"1\":\"January\",\"2\":\"2010\",\"3\":\"large_dozen\",\"4\":\"271.500\"},{\"1\":\"January\",\"2\":\"2010\",\"3\":\"extra_large_half_dozen\",\"4\":\"185.500\"},{\"1\":\"January\",\"2\":\"2010\",\"3\":\"extra_large_dozen\",\"4\":\"285.500\"},{\"1\":\"February\",\"2\":\"2010\",\"3\":\"large_half_dozen\",\"4\":\"174.500\"},{\"1\":\"February\",\"2\":\"2010\",\"3\":\"large_dozen\",\"4\":\"271.500\"},{\"1\":\"February\",\"2\":\"2010\",\"3\":\"extra_large_half_dozen\",\"4\":\"185.500\"},{\"1\":\"February\",\"2\":\"2010\",\"3\":\"extra_large_dozen\",\"4\":\"285.500\"},{\"1\":\"March\",\"2\":\"2010\",\"3\":\"large_half_dozen\",\"4\":\"174.500\"},{\"1\":\"March\",\"2\":\"2010\",\"3\":\"large_dozen\",\"4\":\"268.000\"},{\"1\":\"March\",\"2\":\"2010\",\"3\":\"extra_large_half_dozen\",\"4\":\"185.500\"},{\"1\":\"March\",\"2\":\"2010\",\"3\":\"extra_large_dozen\",\"4\":\"285.500\"},{\"1\":\"April\",\"2\":\"2010\",\"3\":\"large_half_dozen\",\"4\":\"174.500\"},{\"1\":\"April\",\"2\":\"2010\",\"3\":\"large_dozen\",\"4\":\"268.000\"},{\"1\":\"April\",\"2\":\"2010\",\"3\":\"extra_large_half_dozen\",\"4\":\"185.500\"},{\"1\":\"April\",\"2\":\"2010\",\"3\":\"extra_large_dozen\",\"4\":\"285.500\"},{\"1\":\"May\",\"2\":\"2010\",\"3\":\"large_half_dozen\",\"4\":\"174.500\"},{\"1\":\"May\",\"2\":\"2010\",\"3\":\"large_dozen\",\"4\":\"268.000\"},{\"1\":\"May\",\"2\":\"2010\",\"3\":\"extra_large_half_dozen\",\"4\":\"185.500\"},{\"1\":\"May\",\"2\":\"2010\",\"3\":\"extra_large_dozen\",\"4\":\"285.500\"},{\"1\":\"June\",\"2\":\"2010\",\"3\":\"large_half_dozen\",\"4\":\"174.500\"},{\"1\":\"June\",\"2\":\"2010\",\"3\":\"large_dozen\",\"4\":\"268.000\"},{\"1\":\"June\",\"2\":\"2010\",\"3\":\"extra_large_half_dozen\",\"4\":\"185.500\"},{\"1\":\"June\",\"2\":\"2010\",\"3\":\"extra_large_dozen\",\"4\":\"285.500\"},{\"1\":\"July\",\"2\":\"2010\",\"3\":\"large_half_dozen\",\"4\":\"174.500\"},{\"1\":\"July\",\"2\":\"2010\",\"3\":\"large_dozen\",\"4\":\"268.000\"},{\"1\":\"July\",\"2\":\"2010\",\"3\":\"extra_large_half_dozen\",\"4\":\"185.500\"},{\"1\":\"July\",\"2\":\"2010\",\"3\":\"extra_large_dozen\",\"4\":\"285.500\"},{\"1\":\"August\",\"2\":\"2010\",\"3\":\"large_half_dozen\",\"4\":\"174.500\"},{\"1\":\"August\",\"2\":\"2010\",\"3\":\"large_dozen\",\"4\":\"268.000\"},{\"1\":\"August\",\"2\":\"2010\",\"3\":\"extra_large_half_dozen\",\"4\":\"185.500\"},{\"1\":\"August\",\"2\":\"2010\",\"3\":\"extra_large_dozen\",\"4\":\"285.500\"},{\"1\":\"September\",\"2\":\"2010\",\"3\":\"large_half_dozen\",\"4\":\"174.500\"},{\"1\":\"September\",\"2\":\"2010\",\"3\":\"large_dozen\",\"4\":\"268.000\"},{\"1\":\"September\",\"2\":\"2010\",\"3\":\"extra_large_half_dozen\",\"4\":\"185.500\"},{\"1\":\"September\",\"2\":\"2010\",\"3\":\"extra_large_dozen\",\"4\":\"285.500\"},{\"1\":\"October\",\"2\":\"2010\",\"3\":\"large_half_dozen\",\"4\":\"174.500\"},{\"1\":\"October\",\"2\":\"2010\",\"3\":\"large_dozen\",\"4\":\"267.500\"},{\"1\":\"October\",\"2\":\"2010\",\"3\":\"extra_large_half_dozen\",\"4\":\"185.500\"},{\"1\":\"October\",\"2\":\"2010\",\"3\":\"extra_large_dozen\",\"4\":\"285.500\"},{\"1\":\"November\",\"2\":\"2010\",\"3\":\"large_half_dozen\",\"4\":\"174.500\"},{\"1\":\"November\",\"2\":\"2010\",\"3\":\"large_dozen\",\"4\":\"267.500\"},{\"1\":\"November\",\"2\":\"2010\",\"3\":\"extra_large_half_dozen\",\"4\":\"185.500\"},{\"1\":\"November\",\"2\":\"2010\",\"3\":\"extra_large_dozen\",\"4\":\"285.500\"},{\"1\":\"December\",\"2\":\"2010\",\"3\":\"large_half_dozen\",\"4\":\"174.500\"},{\"1\":\"December\",\"2\":\"2010\",\"3\":\"large_dozen\",\"4\":\"267.500\"},{\"1\":\"December\",\"2\":\"2010\",\"3\":\"extra_large_half_dozen\",\"4\":\"185.500\"},{\"1\":\"December\",\"2\":\"2010\",\"3\":\"extra_large_dozen\",\"4\":\"285.500\"},{\"1\":\"January\",\"2\":\"2011\",\"3\":\"large_half_dozen\",\"4\":\"174.500\"},{\"1\":\"January\",\"2\":\"2011\",\"3\":\"large_dozen\",\"4\":\"267.500\"},{\"1\":\"January\",\"2\":\"2011\",\"3\":\"extra_large_half_dozen\",\"4\":\"185.500\"},{\"1\":\"January\",\"2\":\"2011\",\"3\":\"extra_large_dozen\",\"4\":\"285.500\"},{\"1\":\"February\",\"2\":\"2011\",\"3\":\"large_half_dozen\",\"4\":\"174.500\"},{\"1\":\"February\",\"2\":\"2011\",\"3\":\"large_dozen\",\"4\":\"267.500\"},{\"1\":\"February\",\"2\":\"2011\",\"3\":\"extra_large_half_dozen\",\"4\":\"185.500\"},{\"1\":\"February\",\"2\":\"2011\",\"3\":\"extra_large_dozen\",\"4\":\"285.500\"},{\"1\":\"March\",\"2\":\"2011\",\"3\":\"large_half_dozen\",\"4\":\"174.500\"},{\"1\":\"March\",\"2\":\"2011\",\"3\":\"large_dozen\",\"4\":\"267.500\"},{\"1\":\"March\",\"2\":\"2011\",\"3\":\"extra_large_half_dozen\",\"4\":\"185.500\"},{\"1\":\"March\",\"2\":\"2011\",\"3\":\"extra_large_dozen\",\"4\":\"285.500\"},{\"1\":\"April\",\"2\":\"2011\",\"3\":\"large_half_dozen\",\"4\":\"174.500\"},{\"1\":\"April\",\"2\":\"2011\",\"3\":\"large_dozen\",\"4\":\"267.500\"},{\"1\":\"April\",\"2\":\"2011\",\"3\":\"extra_large_half_dozen\",\"4\":\"185.500\"},{\"1\":\"April\",\"2\":\"2011\",\"3\":\"extra_large_dozen\",\"4\":\"285.500\"},{\"1\":\"May\",\"2\":\"2011\",\"3\":\"large_half_dozen\",\"4\":\"174.500\"},{\"1\":\"May\",\"2\":\"2011\",\"3\":\"large_dozen\",\"4\":\"267.500\"},{\"1\":\"May\",\"2\":\"2011\",\"3\":\"extra_large_half_dozen\",\"4\":\"185.500\"},{\"1\":\"May\",\"2\":\"2011\",\"3\":\"extra_large_dozen\",\"4\":\"285.500\"},{\"1\":\"June\",\"2\":\"2011\",\"3\":\"large_half_dozen\",\"4\":\"174.500\"},{\"1\":\"June\",\"2\":\"2011\",\"3\":\"large_dozen\",\"4\":\"270.000\"},{\"1\":\"June\",\"2\":\"2011\",\"3\":\"extra_large_half_dozen\",\"4\":\"185.500\"},{\"1\":\"June\",\"2\":\"2011\",\"3\":\"extra_large_dozen\",\"4\":\"285.500\"},{\"1\":\"July\",\"2\":\"2011\",\"3\":\"large_half_dozen\",\"4\":\"174.500\"},{\"1\":\"July\",\"2\":\"2011\",\"3\":\"large_dozen\",\"4\":\"270.000\"},{\"1\":\"July\",\"2\":\"2011\",\"3\":\"extra_large_half_dozen\",\"4\":\"185.500\"},{\"1\":\"July\",\"2\":\"2011\",\"3\":\"extra_large_dozen\",\"4\":\"285.500\"},{\"1\":\"August\",\"2\":\"2011\",\"3\":\"large_half_dozen\",\"4\":\"174.500\"},{\"1\":\"August\",\"2\":\"2011\",\"3\":\"large_dozen\",\"4\":\"270.000\"},{\"1\":\"August\",\"2\":\"2011\",\"3\":\"extra_large_half_dozen\",\"4\":\"185.500\"},{\"1\":\"August\",\"2\":\"2011\",\"3\":\"extra_large_dozen\",\"4\":\"285.500\"},{\"1\":\"September\",\"2\":\"2011\",\"3\":\"large_half_dozen\",\"4\":\"174.500\"},{\"1\":\"September\",\"2\":\"2011\",\"3\":\"large_dozen\",\"4\":\"270.000\"},{\"1\":\"September\",\"2\":\"2011\",\"3\":\"extra_large_half_dozen\",\"4\":\"185.500\"},{\"1\":\"September\",\"2\":\"2011\",\"3\":\"extra_large_dozen\",\"4\":\"285.500\"},{\"1\":\"October\",\"2\":\"2011\",\"3\":\"large_half_dozen\",\"4\":\"174.500\"},{\"1\":\"October\",\"2\":\"2011\",\"3\":\"large_dozen\",\"4\":\"270.000\"},{\"1\":\"October\",\"2\":\"2011\",\"3\":\"extra_large_half_dozen\",\"4\":\"185.500\"},{\"1\":\"October\",\"2\":\"2011\",\"3\":\"extra_large_dozen\",\"4\":\"285.500\"},{\"1\":\"November\",\"2\":\"2011\",\"3\":\"large_half_dozen\",\"4\":\"174.500\"},{\"1\":\"November\",\"2\":\"2011\",\"3\":\"large_dozen\",\"4\":\"270.000\"},{\"1\":\"November\",\"2\":\"2011\",\"3\":\"extra_large_half_dozen\",\"4\":\"185.500\"},{\"1\":\"November\",\"2\":\"2011\",\"3\":\"extra_large_dozen\",\"4\":\"285.500\"},{\"1\":\"December\",\"2\":\"2011\",\"3\":\"large_half_dozen\",\"4\":\"174.500\"},{\"1\":\"December\",\"2\":\"2011\",\"3\":\"large_dozen\",\"4\":\"270.000\"},{\"1\":\"December\",\"2\":\"2011\",\"3\":\"extra_large_half_dozen\",\"4\":\"185.500\"},{\"1\":\"December\",\"2\":\"2011\",\"3\":\"extra_large_dozen\",\"4\":\"285.500\"},{\"1\":\"January\",\"2\":\"2012\",\"3\":\"large_half_dozen\",\"4\":\"174.500\"},{\"1\":\"January\",\"2\":\"2012\",\"3\":\"large_dozen\",\"4\":\"267.500\"},{\"1\":\"January\",\"2\":\"2012\",\"3\":\"extra_large_half_dozen\",\"4\":\"185.500\"},{\"1\":\"January\",\"2\":\"2012\",\"3\":\"extra_large_dozen\",\"4\":\"285.500\"},{\"1\":\"February\",\"2\":\"2012\",\"3\":\"large_half_dozen\",\"4\":\"174.500\"},{\"1\":\"February\",\"2\":\"2012\",\"3\":\"large_dozen\",\"4\":\"267.500\"},{\"1\":\"February\",\"2\":\"2012\",\"3\":\"extra_large_half_dozen\",\"4\":\"185.500\"},{\"1\":\"February\",\"2\":\"2012\",\"3\":\"extra_large_dozen\",\"4\":\"288.500\"},{\"1\":\"March\",\"2\":\"2012\",\"3\":\"large_half_dozen\",\"4\":\"174.500\"},{\"1\":\"March\",\"2\":\"2012\",\"3\":\"large_dozen\",\"4\":\"267.500\"},{\"1\":\"March\",\"2\":\"2012\",\"3\":\"extra_large_half_dozen\",\"4\":\"185.500\"},{\"1\":\"March\",\"2\":\"2012\",\"3\":\"extra_large_dozen\",\"4\":\"288.500\"},{\"1\":\"April\",\"2\":\"2012\",\"3\":\"large_half_dozen\",\"4\":\"174.500\"},{\"1\":\"April\",\"2\":\"2012\",\"3\":\"large_dozen\",\"4\":\"267.500\"},{\"1\":\"April\",\"2\":\"2012\",\"3\":\"extra_large_half_dozen\",\"4\":\"185.500\"},{\"1\":\"April\",\"2\":\"2012\",\"3\":\"extra_large_dozen\",\"4\":\"288.500\"},{\"1\":\"May\",\"2\":\"2012\",\"3\":\"large_half_dozen\",\"4\":\"173.250\"},{\"1\":\"May\",\"2\":\"2012\",\"3\":\"large_dozen\",\"4\":\"267.500\"},{\"1\":\"May\",\"2\":\"2012\",\"3\":\"extra_large_half_dozen\",\"4\":\"185.500\"},{\"1\":\"May\",\"2\":\"2012\",\"3\":\"extra_large_dozen\",\"4\":\"288.500\"},{\"1\":\"June\",\"2\":\"2012\",\"3\":\"large_half_dozen\",\"4\":\"173.250\"},{\"1\":\"June\",\"2\":\"2012\",\"3\":\"large_dozen\",\"4\":\"267.500\"},{\"1\":\"June\",\"2\":\"2012\",\"3\":\"extra_large_half_dozen\",\"4\":\"185.500\"},{\"1\":\"June\",\"2\":\"2012\",\"3\":\"extra_large_dozen\",\"4\":\"288.500\"},{\"1\":\"July\",\"2\":\"2012\",\"3\":\"large_half_dozen\",\"4\":\"173.250\"},{\"1\":\"July\",\"2\":\"2012\",\"3\":\"large_dozen\",\"4\":\"267.500\"},{\"1\":\"July\",\"2\":\"2012\",\"3\":\"extra_large_half_dozen\",\"4\":\"185.500\"},{\"1\":\"July\",\"2\":\"2012\",\"3\":\"extra_large_dozen\",\"4\":\"288.500\"},{\"1\":\"August\",\"2\":\"2012\",\"3\":\"large_half_dozen\",\"4\":\"173.250\"},{\"1\":\"August\",\"2\":\"2012\",\"3\":\"large_dozen\",\"4\":\"267.500\"},{\"1\":\"August\",\"2\":\"2012\",\"3\":\"extra_large_half_dozen\",\"4\":\"185.500\"},{\"1\":\"August\",\"2\":\"2012\",\"3\":\"extra_large_dozen\",\"4\":\"288.500\"},{\"1\":\"September\",\"2\":\"2012\",\"3\":\"large_half_dozen\",\"4\":\"173.250\"},{\"1\":\"September\",\"2\":\"2012\",\"3\":\"large_dozen\",\"4\":\"267.500\"},{\"1\":\"September\",\"2\":\"2012\",\"3\":\"extra_large_half_dozen\",\"4\":\"185.500\"},{\"1\":\"September\",\"2\":\"2012\",\"3\":\"extra_large_dozen\",\"4\":\"288.500\"},{\"1\":\"October\",\"2\":\"2012\",\"3\":\"large_half_dozen\",\"4\":\"173.250\"},{\"1\":\"October\",\"2\":\"2012\",\"3\":\"large_dozen\",\"4\":\"267.500\"},{\"1\":\"October\",\"2\":\"2012\",\"3\":\"extra_large_half_dozen\",\"4\":\"185.500\"},{\"1\":\"October\",\"2\":\"2012\",\"3\":\"extra_large_dozen\",\"4\":\"288.500\"},{\"1\":\"November\",\"2\":\"2012\",\"3\":\"large_half_dozen\",\"4\":\"178.000\"},{\"1\":\"November\",\"2\":\"2012\",\"3\":\"large_dozen\",\"4\":\"267.500\"},{\"1\":\"November\",\"2\":\"2012\",\"3\":\"extra_large_half_dozen\",\"4\":\"188.130\"},{\"1\":\"November\",\"2\":\"2012\",\"3\":\"extra_large_dozen\",\"4\":\"290.000\"},{\"1\":\"December\",\"2\":\"2012\",\"3\":\"large_half_dozen\",\"4\":\"178.000\"},{\"1\":\"December\",\"2\":\"2012\",\"3\":\"large_dozen\",\"4\":\"267.500\"},{\"1\":\"December\",\"2\":\"2012\",\"3\":\"extra_large_half_dozen\",\"4\":\"188.130\"},{\"1\":\"December\",\"2\":\"2012\",\"3\":\"extra_large_dozen\",\"4\":\"290.000\"},{\"1\":\"January\",\"2\":\"2013\",\"3\":\"large_half_dozen\",\"4\":\"178.000\"},{\"1\":\"January\",\"2\":\"2013\",\"3\":\"large_dozen\",\"4\":\"267.500\"},{\"1\":\"January\",\"2\":\"2013\",\"3\":\"extra_large_half_dozen\",\"4\":\"188.130\"},{\"1\":\"January\",\"2\":\"2013\",\"3\":\"extra_large_dozen\",\"4\":\"290.000\"},{\"1\":\"February\",\"2\":\"2013\",\"3\":\"large_half_dozen\",\"4\":\"178.000\"},{\"1\":\"February\",\"2\":\"2013\",\"3\":\"large_dozen\",\"4\":\"267.500\"},{\"1\":\"February\",\"2\":\"2013\",\"3\":\"extra_large_half_dozen\",\"4\":\"188.130\"},{\"1\":\"February\",\"2\":\"2013\",\"3\":\"extra_large_dozen\",\"4\":\"290.000\"},{\"1\":\"March\",\"2\":\"2013\",\"3\":\"large_half_dozen\",\"4\":\"178.000\"},{\"1\":\"March\",\"2\":\"2013\",\"3\":\"large_dozen\",\"4\":\"267.500\"},{\"1\":\"March\",\"2\":\"2013\",\"3\":\"extra_large_half_dozen\",\"4\":\"188.130\"},{\"1\":\"March\",\"2\":\"2013\",\"3\":\"extra_large_dozen\",\"4\":\"290.000\"},{\"1\":\"April\",\"2\":\"2013\",\"3\":\"large_half_dozen\",\"4\":\"178.000\"},{\"1\":\"April\",\"2\":\"2013\",\"3\":\"large_dozen\",\"4\":\"267.500\"},{\"1\":\"April\",\"2\":\"2013\",\"3\":\"extra_large_half_dozen\",\"4\":\"188.130\"},{\"1\":\"April\",\"2\":\"2013\",\"3\":\"extra_large_dozen\",\"4\":\"290.000\"},{\"1\":\"May\",\"2\":\"2013\",\"3\":\"large_half_dozen\",\"4\":\"178.000\"},{\"1\":\"May\",\"2\":\"2013\",\"3\":\"large_dozen\",\"4\":\"267.500\"},{\"1\":\"May\",\"2\":\"2013\",\"3\":\"extra_large_half_dozen\",\"4\":\"188.130\"},{\"1\":\"May\",\"2\":\"2013\",\"3\":\"extra_large_dozen\",\"4\":\"290.000\"},{\"1\":\"June\",\"2\":\"2013\",\"3\":\"large_half_dozen\",\"4\":\"178.000\"},{\"1\":\"June\",\"2\":\"2013\",\"3\":\"large_dozen\",\"4\":\"267.500\"},{\"1\":\"June\",\"2\":\"2013\",\"3\":\"extra_large_half_dozen\",\"4\":\"188.130\"},{\"1\":\"June\",\"2\":\"2013\",\"3\":\"extra_large_dozen\",\"4\":\"290.000\"},{\"1\":\"July\",\"2\":\"2013\",\"3\":\"large_half_dozen\",\"4\":\"178.000\"},{\"1\":\"July\",\"2\":\"2013\",\"3\":\"large_dozen\",\"4\":\"267.500\"},{\"1\":\"July\",\"2\":\"2013\",\"3\":\"extra_large_half_dozen\",\"4\":\"188.130\"},{\"1\":\"July\",\"2\":\"2013\",\"3\":\"extra_large_dozen\",\"4\":\"290.000\"},{\"1\":\"August\",\"2\":\"2013\",\"3\":\"large_half_dozen\",\"4\":\"178.000\"},{\"1\":\"August\",\"2\":\"2013\",\"3\":\"large_dozen\",\"4\":\"267.500\"},{\"1\":\"August\",\"2\":\"2013\",\"3\":\"extra_large_half_dozen\",\"4\":\"188.130\"},{\"1\":\"August\",\"2\":\"2013\",\"3\":\"extra_large_dozen\",\"4\":\"290.000\"},{\"1\":\"September\",\"2\":\"2013\",\"3\":\"large_half_dozen\",\"4\":\"178.000\"},{\"1\":\"September\",\"2\":\"2013\",\"3\":\"large_dozen\",\"4\":\"267.500\"},{\"1\":\"September\",\"2\":\"2013\",\"3\":\"extra_large_half_dozen\",\"4\":\"188.130\"},{\"1\":\"September\",\"2\":\"2013\",\"3\":\"extra_large_dozen\",\"4\":\"290.000\"},{\"1\":\"October\",\"2\":\"2013\",\"3\":\"large_half_dozen\",\"4\":\"178.000\"},{\"1\":\"October\",\"2\":\"2013\",\"3\":\"large_dozen\",\"4\":\"267.500\"},{\"1\":\"October\",\"2\":\"2013\",\"3\":\"extra_large_half_dozen\",\"4\":\"188.130\"},{\"1\":\"October\",\"2\":\"2013\",\"3\":\"extra_large_dozen\",\"4\":\"290.000\"},{\"1\":\"November\",\"2\":\"2013\",\"3\":\"large_half_dozen\",\"4\":\"178.000\"},{\"1\":\"November\",\"2\":\"2013\",\"3\":\"large_dozen\",\"4\":\"267.500\"},{\"1\":\"November\",\"2\":\"2013\",\"3\":\"extra_large_half_dozen\",\"4\":\"188.130\"},{\"1\":\"November\",\"2\":\"2013\",\"3\":\"extra_large_dozen\",\"4\":\"290.000\"},{\"1\":\"December\",\"2\":\"2013\",\"3\":\"large_half_dozen\",\"4\":\"178.000\"},{\"1\":\"December\",\"2\":\"2013\",\"3\":\"large_dozen\",\"4\":\"267.500\"},{\"1\":\"December\",\"2\":\"2013\",\"3\":\"extra_large_half_dozen\",\"4\":\"188.130\"},{\"1\":\"December\",\"2\":\"2013\",\"3\":\"extra_large_dozen\",\"4\":\"290.000\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\nHere, we see that we do indeed have 480 rows and 4 columns.\n\nA new \"case\" in the pivoted data will contain month and year data, as well as the type (dozen/half dozen and large/extra large) and amount.\n\nIn our pivoted data, each variable forms a column and each observation forms a row. All values have their own cells. The data is easier to examine because of this.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\n<script src=\"../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}