{
  "hash": "4ae4ef1382fc8f57b9e7a598c3201b03",
  "result": {
    "markdown": "---\ntitle: \"Challenge 2 - Matt Zambetti\"\nauthor: \"Matt Zambetti\"\ndescription: \"Data wrangling: using group() and summarise()\"\ndate: \"6/5/2023\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - challenge_2\n  - railroads\n  - faostat\n  - hotel_bookings\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(readxl)\nlibrary(dplyr)\nknitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)\n```\n:::\n\n\n## Challenge Overview\n\nToday's challenge is to\n\n1)  read in a data set, and describe the data using both words and any supporting information (e.g., tables, etc)\n2)  provide summary statistics for different interesting groups within the data, and interpret those statistics\n\n## Read in the Data\n\nRead in one (or more) of the following data sets, available in the `posts/_data` folder, using the correct R package and command.\n\n-   railroad\\*.csv or StateCounty2012.xls ⭐\n-   FAOstat\\*.csv or birds.csv ⭐⭐⭐\n-   hotel_bookings.csv ⭐⭐⭐⭐\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# getting the data with the read.csv command\nrailroad_data <- read.csv(\"_data/railroad_2012_clean_county.csv\")\n\n# printing the first 10 rows\nhead(railroad_data, 10)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   state               county total_employees\n1     AE                  APO               2\n2     AK            ANCHORAGE               7\n3     AK FAIRBANKS NORTH STAR               2\n4     AK               JUNEAU               3\n5     AK    MATANUSKA-SUSITNA               2\n6     AK                SITKA               1\n7     AK SKAGWAY MUNICIPALITY              88\n8     AL              AUTAUGA             102\n9     AL              BALDWIN             143\n10    AL              BARBOUR               1\n```\n:::\n:::\n\n\nAdd any comments or documentation as needed. More challenging data may require additional code chunks and documentation.\n\n## Describe the data\n\nUsing a combination of words and results of R commands, can you provide a high level description of the data? Describe as efficiently as possible where/how the data was (likely) gathered, indicate the cases and variables (both the interpretation and any details you deem useful to the reader to fully understand your chosen data).\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Using the comments Sidharth gave to me.\nrailroad_data %>%\n  arrange(desc(total_employees)) %>%\n            head()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  state           county total_employees\n1    IL             COOK            8207\n2    TX          TARRANT            4235\n3    NE          DOUGLAS            3797\n4    NY          SUFFOLK            3685\n5    VA INDEPENDENT CITY            3249\n6    FL            DUVAL            3073\n```\n:::\n\n```{.r .cell-code}\nrailroad_data %>%\n  arrange(total_employees) %>%\n            head()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  state  county total_employees\n1    AK   SITKA               1\n2    AL BARBOUR               1\n3    AL   HENRY               1\n4    AP     APO               1\n5    AR  NEWTON               1\n6    CA    MONO               1\n```\n:::\n:::\n\n\nHere, I do the same analysis as in Challenge 1, but I use a better technique of piping the results from arrange into head, instead of creating a new object.\n\nIn the first, we are able to see the ten stations with the most employees and in the second we see the 10 with the least.\n\nAs I mentioned in the previous assignment, sorting the data based on total number of employees can be useful to figure out which stations to distributed funds to. Stations with a larger employee base will more likely have a larger payroll.\n\nThen another source of funding is upkeep. If a station has more employees this is most likely because it is a larger station, which means the cost of maintenance will be greater than that of a smaller station.\n\n## Provide Grouped Summary Statistics\n\nConduct some exploratory data analysis, using dplyr commands such as `group_by()`, `select()`, `filter()`, and `summarise()`. Find the central tendency (mean, median, mode) and dispersion (standard deviation, mix/max/quantile) for different subgroups within the data set.\n\nI did not see a useful case of `group_by` other than to organize the data by state, which I think filter was more useful for analysis.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# DOING SOME CENTRAL TENDENCY ANALYSIS\n# Finding the mean\nsummarize(railroad_data, mean = mean(total_employees,na.rm=TRUE))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n      mean\n1 87.17816\n```\n:::\n\n```{.r .cell-code}\n# Finding the median\nsummarize(railroad_data, median = median(total_employees,na.rm=TRUE))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  median\n1     21\n```\n:::\n\n```{.r .cell-code}\n# DOING SOME DISPESION ANAYLSYS\n# Finding the sd\nsummarize(railroad_data, sd = sd(total_employees,na.rm=TRUE))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n        sd\n1 283.6359\n```\n:::\n\n```{.r .cell-code}\n# Finding the max\nsummarize(railroad_data, max = max(total_employees,na.rm=TRUE))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   max\n1 8207\n```\n:::\n\n```{.r .cell-code}\n# Finding the min\nsummarize(railroad_data, min = min(total_employees,na.rm=TRUE))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  min\n1   1\n```\n:::\n:::\n\n\nIf we take a look at the commands we use within summarize we can state some obvious things, such as the mean is ~87, the median is 21, the max and min are 8207 and 1 respectively with a standard deviation of ~284.\n\nWhat I concluded from this data was that to have a median and mean so low, there have to be a lot more towns with the total number of employees being very low. I say this because there is a station with 8207 employees and the mean is only 87, and the median is only 21. This means that There have to be a lot more values in the lower range (less than 100) to keep those numbers so low.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Finding all the stations in Wyoming\nfilter(railroad_data, state == \"WY\") %>%\n  pull(total_employees) %>%\n  sum \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 2876\n```\n:::\n\n```{.r .cell-code}\n# Finding all the stations in CA\nfilter(railroad_data, state == \"CA\") %>%\n  pull(total_employees) %>%\n  sum\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 13137\n```\n:::\n\n```{.r .cell-code}\n# Finding all the stations in AK\nfilter(railroad_data, state == \"AK\") %>%\n  pull(total_employees) %>%\n  sum\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 103\n```\n:::\n:::\n\n\nIf we look at the next set of numbers I wanted to compare the number of railroad employees in the least populated state, versus the number of railroad employees in most populated state. Using Google, I found the least populated state is Wyoming, which has 2876 employees, and California is the most populated state and has 13137 total employees. This is a pretty significant number.\n\nBut, what I also found interesting was that even though Wyoming is the least populated state is does not have the least number of employees. An example of a state that has less is Alaska with 103 employees. This might have something to do with geographical location, or this might have something to do with history and maybe the importance of railroads in the development of both. \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Total Number of counties in the data\nselect(railroad_data, county) %>% nrow()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 2930\n```\n:::\n:::\n\n\nThe final piece of analysis I did was to get familiar with select, so I selected the column of counties and observes how many counties there were in the data set. Interestingly enough, 2930 different counties have railroad stations.\n\n\n### Explain and Interpret\n\nBe sure to explain why you choose a specific group. Comment on the interpretation of any interesting differences between groups that you uncover. This section can be integrated with the exploratory data analysis, just be sure it is included.\n\nThis is included in the sectoin above.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}