{
  "hash": "4ebb1677c1ff5c410d357b8b5ee2a3a0",
  "result": {
    "markdown": "---\ntitle: \"Challenge 1 Submission\"\nauthor: \"Xinpeng Liu\"\ndescription: \"Reading in data and creating a post\"\ndate: \"5/30/2023\"\nformat:\n  html:\n    df-print: paged\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\n    css: \"styles.css\"\ncategories:\n  - challenge_1\n  - railroads\n  - faostat\n  - wildbirds\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n\nknitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)\n```\n:::\n\n\n## Challenge Overview\n\nToday's challenge is to\n\n1)  read in a dataset, and\n\n2)  describe the dataset using both words and any supporting information (e.g., tables, etc)\n\n## Read in the Data\n\nRead in one (or more) of the following data sets, using the correct R package and command.\n\n-   railroad_2012_clean_county.csv ⭐\n-   birds.csv ⭐⭐\n-   FAOstat\\*.csv ⭐⭐\n-   wild_bird_data.xlsx ⭐⭐⭐\n-   StateCounty2012.xls ⭐⭐⭐⭐\n\nFind the `_data` folder, located inside the `posts` folder. Then you can read in the data, using either one of the `readr` standard tidy read commands, or a specialized package such as `readxl`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata_railroad <- read_csv(\"_data/railroad_2012_clean_county.csv\")\n```\n:::\n\n\nAdd any comments or documentation as needed. More challenging data sets may require additional code chunks and documentation.\n\n## Describe the data\n\nUsing a combination of words and results of R commands, can you provide a high level description of the data? Describe as efficiently as possible where/how the data was (likely) gathered, indicate the cases and variables (both the interpretation and any details you deem useful to the reader to fully understand your chosen data).\n\nwe choose -   railroad_2012_clean_county.csv ⭐\n\n::: {.cell}\n\n```{.r .cell-code}\ndata <- read.csv(\"_data/railroad_2012_clean_county.csv\")\nhead(data)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"state\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"county\"],\"name\":[2],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"total_employees\"],\"name\":[3],\"type\":[\"int\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"AE\",\"2\":\"APO\",\"3\":\"2\",\"_rn_\":\"1\"},{\"1\":\"AK\",\"2\":\"ANCHORAGE\",\"3\":\"7\",\"_rn_\":\"2\"},{\"1\":\"AK\",\"2\":\"FAIRBANKS NORTH STAR\",\"3\":\"2\",\"_rn_\":\"3\"},{\"1\":\"AK\",\"2\":\"JUNEAU\",\"3\":\"3\",\"_rn_\":\"4\"},{\"1\":\"AK\",\"2\":\"MATANUSKA-SUSITNA\",\"3\":\"2\",\"_rn_\":\"5\"},{\"1\":\"AK\",\"2\":\"SITKA\",\"3\":\"1\",\"_rn_\":\"6\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n\n```{.r .cell-code}\nsummary(data)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n    state              county          total_employees  \n Length:2930        Length:2930        Min.   :   1.00  \n Class :character   Class :character   1st Qu.:   7.00  \n Mode  :character   Mode  :character   Median :  21.00  \n                                       Mean   :  87.18  \n                                       3rd Qu.:  65.00  \n                                       Max.   :8207.00  \n```\n:::\n:::\n\n\nThe summary indicates that the dataset comprises 2930 observations each with three variables: state, county, and total_employees.\n\nstate and county are both of character class, indicating that they hold textual information. They represent the US states and counties, respectively.\n\ntotal_employees is of integer class and represents the total number of employees in each county. The key statistics of this variable are:\n\nMinimum: 1 - This is the smallest number of total employees in a county within the dataset.\n1st Quartile (25th percentile): 7 - 25% of the counties have 7 or fewer employees.\nMedian (50th percentile): 21 - Half of the counties have 21 or fewer employees.\nMean: 87.18 - On average, a county has approximately 87 employees.\n3rd Quartile (75th percentile): 65 - 75% of the counties have 65 or fewer employees.\nMaximum: 8207 - This is the largest number of total employees in a county within the datase\n\n::: {.cell}\n\n```{.r .cell-code}\n#National total number of employees\nsum(data$total_employees)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 255432\n```\n:::\n\n```{.r .cell-code}\n# Total number of employees in each state\naggregate(total_employees ~ state, data = data, sum)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"state\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"total_employees\"],\"name\":[2],\"type\":[\"int\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"AE\",\"2\":\"2\"},{\"1\":\"AK\",\"2\":\"103\"},{\"1\":\"AL\",\"2\":\"4257\"},{\"1\":\"AP\",\"2\":\"1\"},{\"1\":\"AR\",\"2\":\"3871\"},{\"1\":\"AZ\",\"2\":\"3153\"},{\"1\":\"CA\",\"2\":\"13137\"},{\"1\":\"CO\",\"2\":\"3650\"},{\"1\":\"CT\",\"2\":\"2592\"},{\"1\":\"DC\",\"2\":\"279\"},{\"1\":\"DE\",\"2\":\"1495\"},{\"1\":\"FL\",\"2\":\"7419\"},{\"1\":\"GA\",\"2\":\"8605\"},{\"1\":\"HI\",\"2\":\"4\"},{\"1\":\"IA\",\"2\":\"4019\"},{\"1\":\"ID\",\"2\":\"1563\"},{\"1\":\"IL\",\"2\":\"19131\"},{\"1\":\"IN\",\"2\":\"8537\"},{\"1\":\"KS\",\"2\":\"6092\"},{\"1\":\"KY\",\"2\":\"4811\"},{\"1\":\"LA\",\"2\":\"3915\"},{\"1\":\"MA\",\"2\":\"3379\"},{\"1\":\"MD\",\"2\":\"4709\"},{\"1\":\"ME\",\"2\":\"654\"},{\"1\":\"MI\",\"2\":\"3932\"},{\"1\":\"MN\",\"2\":\"5467\"},{\"1\":\"MO\",\"2\":\"8419\"},{\"1\":\"MS\",\"2\":\"2111\"},{\"1\":\"MT\",\"2\":\"3327\"},{\"1\":\"NC\",\"2\":\"3143\"},{\"1\":\"ND\",\"2\":\"2204\"},{\"1\":\"NE\",\"2\":\"13176\"},{\"1\":\"NH\",\"2\":\"393\"},{\"1\":\"NJ\",\"2\":\"8329\"},{\"1\":\"NM\",\"2\":\"1958\"},{\"1\":\"NV\",\"2\":\"746\"},{\"1\":\"NY\",\"2\":\"17050\"},{\"1\":\"OH\",\"2\":\"9056\"},{\"1\":\"OK\",\"2\":\"2318\"},{\"1\":\"OR\",\"2\":\"2322\"},{\"1\":\"PA\",\"2\":\"12769\"},{\"1\":\"RI\",\"2\":\"487\"},{\"1\":\"SC\",\"2\":\"2296\"},{\"1\":\"SD\",\"2\":\"949\"},{\"1\":\"TN\",\"2\":\"4952\"},{\"1\":\"TX\",\"2\":\"19839\"},{\"1\":\"UT\",\"2\":\"1917\"},{\"1\":\"VA\",\"2\":\"7551\"},{\"1\":\"VT\",\"2\":\"259\"},{\"1\":\"WA\",\"2\":\"5222\"},{\"1\":\"WI\",\"2\":\"3773\"},{\"1\":\"WV\",\"2\":\"3213\"},{\"1\":\"WY\",\"2\":\"2876\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\nThe above two tables are the total number of employees in the country and the total number of employees in each state. We can see that most of the employees are located in the east.\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\n\n# Histogram of the total number of employees in each state\nstate_summary <- aggregate(total_employees ~ state, data = data, sum)\nggplot(state_summary, aes(x = state, y = total_employees)) +\n  geom_bar(stat = \"identity\") +\n  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +\n  labs(x = \"State\", y = \"Total Employees\", title = \"Total Employees by State\")\n```\n\n::: {.cell-output-display}\n![](challenge1_solution_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\nThis is a histogram visualization of the total number of employees by state, which is the same as the above graph to analyze. The visualization chart can let us know more clearly the distribution of employees in different regions. Among them, TN, NY, and IL have the largest number of employees, and AE, VT, and CD have the least number of employees",
    "supporting": [
      "challenge1_solution_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\r\n<script src=\"../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\r\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}