{
  "hash": "6e9e7772cc76c14dd2a25ade2f2fa4e9",
  "result": {
    "markdown": "---\ntitle: \"Challenge 1\"\nauthor: \"Audrey Bertin\"\ndescription: \"Reading in csv and excel data\"\ndate: \"5/30/2023\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - challenge_1\n  - birds\n  - wildbirds\n  - csv\n  - excel\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nknitr::opts_chunk$set(echo = TRUE)\n```\n:::\n\n\nFor this challenge, I'll be reading in the following datasets:\n\n-   birds.csv ⭐⭐\n-   wild_bird_data.xlsx ⭐⭐⭐\n\n## `birds.csv`\n\nFirst, we start with `birds.csv`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbirds <- readr::read_csv(\"_data/birds.csv\")\n```\n:::\n\n\nA sample of this data can be seen below:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(birds)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 14\n  `Domain Code` Domain      `Area Code` Area  `Element Code` Element `Item Code`\n  <chr>         <chr>             <dbl> <chr>          <dbl> <chr>         <dbl>\n1 QA            Live Anima…           2 Afgh…           5112 Stocks         1057\n2 QA            Live Anima…           2 Afgh…           5112 Stocks         1057\n3 QA            Live Anima…           2 Afgh…           5112 Stocks         1057\n4 QA            Live Anima…           2 Afgh…           5112 Stocks         1057\n5 QA            Live Anima…           2 Afgh…           5112 Stocks         1057\n6 QA            Live Anima…           2 Afgh…           5112 Stocks         1057\n# ℹ 7 more variables: Item <chr>, `Year Code` <dbl>, Year <dbl>, Unit <chr>,\n#   Value <dbl>, Flag <chr>, `Flag Description` <chr>\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nstr(birds)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nspc_tbl_ [30,977 × 14] (S3: spec_tbl_df/tbl_df/tbl/data.frame)\n $ Domain Code     : chr [1:30977] \"QA\" \"QA\" \"QA\" \"QA\" ...\n $ Domain          : chr [1:30977] \"Live Animals\" \"Live Animals\" \"Live Animals\" \"Live Animals\" ...\n $ Area Code       : num [1:30977] 2 2 2 2 2 2 2 2 2 2 ...\n $ Area            : chr [1:30977] \"Afghanistan\" \"Afghanistan\" \"Afghanistan\" \"Afghanistan\" ...\n $ Element Code    : num [1:30977] 5112 5112 5112 5112 5112 ...\n $ Element         : chr [1:30977] \"Stocks\" \"Stocks\" \"Stocks\" \"Stocks\" ...\n $ Item Code       : num [1:30977] 1057 1057 1057 1057 1057 ...\n $ Item            : chr [1:30977] \"Chickens\" \"Chickens\" \"Chickens\" \"Chickens\" ...\n $ Year Code       : num [1:30977] 1961 1962 1963 1964 1965 ...\n $ Year            : num [1:30977] 1961 1962 1963 1964 1965 ...\n $ Unit            : chr [1:30977] \"1000 Head\" \"1000 Head\" \"1000 Head\" \"1000 Head\" ...\n $ Value           : num [1:30977] 4700 4900 5000 5300 5500 5800 6600 6290 6300 6000 ...\n $ Flag            : chr [1:30977] \"F\" \"F\" \"F\" \"F\" ...\n $ Flag Description: chr [1:30977] \"FAO estimate\" \"FAO estimate\" \"FAO estimate\" \"FAO estimate\" ...\n - attr(*, \"spec\")=\n  .. cols(\n  ..   `Domain Code` = col_character(),\n  ..   Domain = col_character(),\n  ..   `Area Code` = col_double(),\n  ..   Area = col_character(),\n  ..   `Element Code` = col_double(),\n  ..   Element = col_character(),\n  ..   `Item Code` = col_double(),\n  ..   Item = col_character(),\n  ..   `Year Code` = col_double(),\n  ..   Year = col_double(),\n  ..   Unit = col_character(),\n  ..   Value = col_double(),\n  ..   Flag = col_character(),\n  ..   `Flag Description` = col_character()\n  .. )\n - attr(*, \"problems\")=<externalptr> \n```\n:::\n:::\n\n\n\nAs we can see, we appear to have information on the number of different types of birds in different areas around the world, based on different data sources and estimates. The data appears to be measuring birds in captivity, rather than wild birds.\n\nWe have 8 categorical variables and 6 numeric. The numeric variables appear to be discrete in that they can only have whole integer values.\n\nThe different types of birds we are tracking are as follows. We have the most data on chickens and the least on pigeons and other birds.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(birds$Item)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n              Chickens                  Ducks Geese and guinea fowls \n                 13074                   6909                   4136 \n  Pigeons, other birds                Turkeys \n                  1165                   5693 \n```\n:::\n:::\n\n\nThe different type of measurements we have are:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(birds$`Flag Description`)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nAggregate, may include official, semi-official, estimated or calculated data \n                                                                        6488 \n                                                          Data not available \n                                                                        1002 \n                                    FAO data based on imputation methodology \n                                                                        1213 \n                                                                FAO estimate \n                                                                       10007 \n                                                               Official data \n                                                                       10773 \n                                                           Unofficial figure \n                                                                        1494 \n```\n:::\n:::\n\nThere appears to be a strange duplicate variable. Both `Year` and `Year Code` have identical values.\n\n\nThe birds data has 30,977 rows and 14 columns:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndim(birds)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 30977    14\n```\n:::\n:::\n\n\nLooking at missing data, most of our variables have records for every row. There are only two that have missing values, `Value` and `Flag`. About 1/30 of the Values are missing and about 1/3 of the flags.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncolSums(is.na(birds))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n     Domain Code           Domain        Area Code             Area \n               0                0                0                0 \n    Element Code          Element        Item Code             Item \n               0                0                0                0 \n       Year Code             Year             Unit            Value \n               0                0                0             1036 \n            Flag Flag Description \n           10773                0 \n```\n:::\n:::\n\n\n## `wild_bird_data.xlsx`\n\nWe read this in using `read_excel`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# We need to add skip=1 to skip the first row and get rid of duplicate header labels\nwild_birds <- readxl::read_excel(\"_data/wild_bird_data.xlsx\", skip = 1)\n```\n:::\n\n\n\nA sample of this data can be seen below:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(wild_birds)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 2\n  `Wet body weight [g]` `Population size`\n                  <dbl>             <dbl>\n1                  5.46           532194.\n2                  7.76          3165107.\n3                  8.64          2592997.\n4                 10.7           3524193.\n5                  7.42           389806.\n6                  9.12           604766.\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nstr(wild_birds)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\ntibble [146 × 2] (S3: tbl_df/tbl/data.frame)\n $ Wet body weight [g]: num [1:146] 5.46 7.76 8.64 10.69 7.42 ...\n $ Population size    : num [1:146] 532194 3165107 2592997 3524193 389806 ...\n```\n:::\n:::\n\n\n\nAs we can see, we just have two variables here, the wet body weight (in grams) and the size of the population.\n\nWe can calculate some summary statistics about each of these variables:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(wild_birds)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n Wet body weight [g] Population size  \n Min.   :   5.459    Min.   :      5  \n 1st Qu.:  18.620    1st Qu.:   1821  \n Median :  69.232    Median :  24353  \n Mean   : 363.694    Mean   : 382874  \n 3rd Qu.: 309.826    3rd Qu.: 198515  \n Max.   :9639.845    Max.   :5093378  \n```\n:::\n:::\n\nBody weight ranges from ~5.5 grams to ~9640 grams. Population size ranges from 5 to 5,093,378, and we can see the means/medians/quartiles above as well.\n\n\nThere are 146 rows and none of the data appears to be missing.\n\n::: {.cell}\n\n```{.r .cell-code}\ndim(wild_birds)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 146   2\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ncolSums(is.na(wild_birds))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nWet body weight [g]     Population size \n                  0                   0 \n```\n:::\n:::\n\n\nIt is difficult just from the dataset itself to understand the context of this data. Is the \"Wet body weight [g]\" the combined wet weight of the whole population?  The average weight of birds in that population? It is unclear how the two columns are related.\n\nAlso, what type of birds are these? What does a row represent? We would need more information from the source to be able to understand this data further.",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}