{
  "hash": "9fbe25229f2bd5a9701d6c478cb73f8f",
  "result": {
    "markdown": "---\ntitle: \"Matt Zambetti: Final Project Submission\"\nauthor: \"Matt Zambetti\"\ndate: \"2023-07-05\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - Final_Project\n---\n\n# Final Project\n\n\n\n\n\n## Choosing the Data Set\n\nThe data set that I chose pertains to salary data for various careers, education levels, gender, and experience. I am interested in investigating this data, as it would allow people to see how their salary compares to people with similar age, job titles, education and experience level.\n\nLooking into the authors' process to gathering this data, they do not provide much. They state that this data is gathered from surveys, job posting sites, and \"other publicly available sources\". These sources can come with uncertainty as people could lie on surveys as they could be uncomfortable with sharing their real salary. We also do not know what is included in \"publicly available sources\". But assuming that these sources are trust worthy, pairing this with job posting sites can be very useful in creating numerous data points. Another area this source is lacking is the type of companies they are sampling from, again another assumption is that they are surveying people from various companies and the data from job posting websites contains multiple employers/types of employers so we have a breadth of data.\n\nWhen looking into what region this data came from, I could not find anything. So, I looked and compared this to the salaries of similar jobs with similar experience in the United States, and they were similar. With that, I believe that although this may not be perfect, it is certainly sufficient for someone to use this data in the US to compare their salary to.\n\nI gathered the data at: (https://www.kaggle.com/datasets/mohithsairamreddy/salary-data?resource=download)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nworkers_tidy <- read_csv(\"_data/Salary_Data.csv\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nRows: 6704 Columns: 6\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\nchr (3): Gender, Education Level, Job Title\ndbl (3): Age, Years of Experience, Salary\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n:::\n\n```{.r .cell-code}\nworkers_tidy\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6,704 × 6\n     Age Gender `Education Level` `Job Title`       `Years of Experience` Salary\n   <dbl> <chr>  <chr>             <chr>                             <dbl>  <dbl>\n 1    32 Male   Bachelor's        Software Engineer                     5  90000\n 2    28 Female Master's          Data Analyst                          3  65000\n 3    45 Male   PhD               Senior Manager                       15 150000\n 4    36 Female Bachelor's        Sales Associate                       7  60000\n 5    52 Male   Master's          Director                             20 200000\n 6    29 Male   Bachelor's        Marketing Analyst                     2  55000\n 7    42 Female Master's          Product Manager                      12 120000\n 8    31 Male   Bachelor's        Sales Manager                         4  80000\n 9    26 Female Bachelor's        Marketing Coordi…                     1  45000\n10    38 Male   PhD               Senior Scientist                     10 110000\n# ℹ 6,694 more rows\n```\n:::\n:::\n\n\n## Cleaning the Data Set\n\nOriginally, I did not find anything wrong with the data in terms of tidying it up or formatting it. But when doing further analysis I found that some entries in `Education Level` were recorded as 'phD' instead of 'PhD', so I went ahead and fixed that.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nworkers_tidy$`Education Level`[workers_tidy$`Education Level`=='phD'] <- 'PhD'\n```\n:::\n\n\n## Narrative About the Data Set\n\nIf we want to look deeper into this data set to see what it contains, we can examining each variable represented and their domains.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmax(workers_tidy$Age, na.rm=TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 62\n```\n:::\n\n```{.r .cell-code}\nmin(workers_tidy$Age, na.rm=TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 21\n```\n:::\n:::\n\n\nThe first variable is `Age`, which is simply the age of the employee, this variable is quite self explanatory so I will leave it at that. From above we can see the minimum age is 21, and the maximum age is 62.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(workers_tidy$`Years of Experience`, na.rm=TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 8.094687\n```\n:::\n:::\n\n\nSecond, we have `Experience Level`, which is pretty similar to age, just that this is the number of years someone has been working. By simple analysis we can see that the average is around 8 years.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(workers_tidy$`Gender`)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nFemale   Male  Other \n  3014   3674     14 \n```\n:::\n:::\n\n\nNext, `Gender` is split into three categories: Male, Female, or Other. Above we can see the exact count for both, with it coming out to be around 54% for males, and 45% for females and 0.2% for Other.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(workers_tidy$`Education Level`)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n       Bachelor's Bachelor's Degree       High School          Master's \n              756              2267               448               288 \n  Master's Degree               PhD \n             1573              1369 \n```\n:::\n:::\n\n\n`Education Level` is spread out between High School Diploma, Bachelor's, Master's and PhD. Similarly we can see that distribution above.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlength(unique(workers_tidy$`Job Title`))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 194\n```\n:::\n\n```{.r .cell-code}\ntitle_count = table(workers_tidy$`Job Title`)\ntitle_count <- title_count[order(title_count, decreasing = TRUE)]\nhead(title_count)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n        Software Engineer            Data Scientist Software Engineer Manager \n                      518                       453                       376 \n             Data Analyst   Senior Project Engineer           Product Manager \n                      363                       318                       313 \n```\n:::\n:::\n\n\nThe final variable `Job Title` is where we can start to see more variance. From the above command, we see that there are around 194 different jobs represented out of the 6700 total samples. From the analysis above, we can see that Software Engineer, Data Scientist, Software Engineer Manager, Data Analyst, Senior Project Engineer, and Product Engineer are the six most popular jobs in the data set.\n\n## Research Questions\n\nThis data has plenty to offer in terms of analysis. I want to focus on how Age and Experience affect the salary of an individual. First, I will look into the entire data set of all professions. Then I will look into how this compares to jobs in my field (Computer Science, Data Science, etc.). In addition to focusing on jobs, I will also focus on those with advanced degrees (Master's and PhDs) as I will come out of school with one of those.\n\n### General Analysis\n\nAs aforementioned, the first two plots will showcase any correlation between Age and Salary, and Years of Experience and Salary. From my general understanding of salaries, I predict that there will be a positive correlation between both of these variables and salaries, but I will be curious to see if there are any points in one's career that this plateaus.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nworkers_tidy %>% ggplot(aes(x=`Years of Experience`, y=`Salary`)) +\n  geom_point(color='Blue') + \n  geom_smooth(color='Red')\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n`geom_smooth()` using method = 'gam' and formula = 'y ~ s(x, bs = \"cs\")'\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: Removed 5 rows containing non-finite values (`stat_smooth()`).\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: Removed 5 rows containing missing values (`geom_point()`).\n```\n:::\n\n::: {.cell-output-display}\n![](Matt_Zambetti_FinalProject_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\nFrom the plot above, we can see some very interesting points. If we focus on zero to twenty years of experience we see a fairly steady growth of salary. Another interesting point about this section is that there are a large range of salaries for people with the same years of experience, the difference is that the majority of salaries are increasing in this area.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncount_years <- as.data.frame(table(workers_tidy$`Years of Experience`))\ncount_years$Var1 <- as.numeric(as.character(count_years$Var1))\ntotal <- sum(count_years[which(count_years$Var1 > 20),2])\ntotal\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 244\n```\n:::\n:::\n\n\nLooking on from twenty years of experience and onward, we notice the curve flattening out. I belive that this is due to multiple factors. The first is that people are not job switching as much, so there is less competition between companies to pay employees better. People are not job hopping as frequently in this age range because they more than likely have a family or are committed to living in a specific area. \n\nAlso, there may not have been enough data gathered on this particular group. From the small snippet above, we can see only 244 entries are for this particular age group. If these jobs were sampled from a similar company/demographic that may be the reason we see such similarities in the data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nworkers_tidy %>% ggplot(aes(x=`Age`, y=`Salary`)) +\n  geom_point(color='Blue') + \n  geom_smooth(color='Red')\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n`geom_smooth()` using method = 'gam' and formula = 'y ~ s(x, bs = \"cs\")'\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: Removed 5 rows containing non-finite values (`stat_smooth()`).\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: Removed 5 rows containing missing values (`geom_point()`).\n```\n:::\n\n::: {.cell-output-display}\n![](Matt_Zambetti_FinalProject_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\nIn this data we can see a very similar plot as the Years of Experience versus Salary plot. One key difference is that this one seems to plateau around 52 years of age which seems to be a bit later in the distribution than the plateau of the experience plot.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncount_years2 <- as.data.frame(table(workers_tidy$`Age`))\ncount_years2$Var1 <- as.numeric(as.character(count_years2$Var1))\ntotal <- sum(count_years2[which(count_years2$Var1 > 50),2])\ntotal\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 189\n```\n:::\n:::\n\n\nSimilarly to the previous plot there are a lot less samples around where this plateau takes place. But there is even a smaller portion of samples for workers over 50. I think this is due to the fact that people are close to retiring and that people are getting promoted less and less as they approach this age. In my experience young professionals are able to make higher increases in pay more quickly the earlier they are in their career, then as they get olders, these promotions are harder to come by.\n\n### Industry Specific Analysis\n\nNow, I want to focus on jobs that pertain to my career. I looked through all the jobs and picked out key words that were related to my career path. Below I have listed all of these.\n\nKey words are:\n- Software\n- Engineer\n- Developer\n- Data\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfield_jobs <- workers_tidy[grepl(\"software|engineer|developer|data\",tolower(workers_tidy$`Job Title`)),]\nfield_jobs\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 3,628 × 6\n     Age Gender `Education Level` `Job Title`       `Years of Experience` Salary\n   <dbl> <chr>  <chr>             <chr>                             <dbl>  <dbl>\n 1    32 Male   Bachelor's        Software Engineer                     5  90000\n 2    28 Female Master's          Data Analyst                          3  65000\n 3    29 Male   Master's          Software Develop…                     3  75000\n 4    39 Male   PhD               Senior Engineer                      12 115000\n 5    25 Female Bachelor's        Data Entry Clerk                      0  35000\n 6    37 Female Master's          Software Manager                     11 110000\n 7    24 Male   Bachelor's        Junior Developer                      1  40000\n 8    29 Male   Master's          Data Scientist                        3  75000\n 9    42 Male   Master's          Project Engineer                     14 115000\n10    30 Male   Bachelor's        Network Engineer                      3  60000\n# ℹ 3,618 more rows\n```\n:::\n:::\n\n\nFrom the results above, we can see that there are plenty of data points in this data set for us to base our analysis on.\n\nBelow we will recreate both graphs above. Starting with years of experience.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfield_jobs %>% ggplot(aes(x=`Years of Experience`, y=`Salary`)) +\n  geom_point(color='Blue') + \n  geom_smooth(color='Red')\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n`geom_smooth()` using method = 'gam' and formula = 'y ~ s(x, bs = \"cs\")'\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: Removed 1 rows containing non-finite values (`stat_smooth()`).\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: Removed 1 rows containing missing values (`geom_point()`).\n```\n:::\n\n::: {.cell-output-display}\n![](Matt_Zambetti_FinalProject_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\n\nComparing this graph to the complete data set graph on comparing salary to years of experience, we can see that there salary from 0-20 years of experience is slightly higher for my field, but about the same from onward. Below is a graph overlaying both of these plots\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Mean\ngeneral_mean <- workers_tidy %>%\n  group_by(`Years of Experience`) %>%\n  summarise(Salary=mean(Salary))\nfield_mean <- field_jobs %>%\n  group_by(`Years of Experience`) %>%\n  summarise(Salary=mean(Salary))\n\nggplot(NULL, aes(`Years of Experience`, `Salary`)) +\n  geom_point(data=workers_tidy, color=\"Red\") +\n  geom_line(data=general_mean, color=\"Red\") +\n  geom_point(data=field_jobs, color=\"Blue\") +\n  geom_line(data=field_mean, color=\"Blue\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: Removed 5 rows containing missing values (`geom_point()`).\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: Removed 1 row containing missing values (`geom_line()`).\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: Removed 1 rows containing missing values (`geom_point()`).\n```\n:::\n\n::: {.cell-output-display}\n![](Matt_Zambetti_FinalProject_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n\nAbove, in blue we have only the jobs that are in the disciplines I am interested in. In red, we have all jobs (including the ones in blue). The two colored lines correspond with corresponding colored plots.\n\nThis plot further confirms that the salary in my field is slightly higher than average, but this seems to be only up until about 15 years of experience. Then it starts to get very close.\n\nNext, we will look at comparing the age of people in the field I'm interested in and their salaries compared to the complete distribution.\n\nFirst, we will look at the specific field first, so we can get a good understanding of what we're looking at before we compare.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfield_jobs %>% ggplot(aes(x=`Age`, y=`Salary`)) +\n  geom_point(color='Blue') + \n  geom_smooth(color='Red')\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n`geom_smooth()` using method = 'gam' and formula = 'y ~ s(x, bs = \"cs\")'\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: Removed 1 rows containing non-finite values (`stat_smooth()`).\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: Removed 1 rows containing missing values (`geom_point()`).\n```\n:::\n\n::: {.cell-output-display}\n![](Matt_Zambetti_FinalProject_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n\nIn this plot, we have a very interesting curve. It seems that throughout one's career in the given fields, the salaries increase, then plateau, and repeat this behavior a few times. My hypothesis for this behavior is that many of the careers in these fields follow the same behavior. This behavior is a promotion every few years, then another promotion after a similar period. If these jobs were sampled from the same company or ones that operate in a similar manner, this would explain the deterministic behavior in the plot.\n\nNow, we will compare these jobs to all the sampled jobs, this plot can be seen below.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Mean\ngeneral_mean <- workers_tidy %>%\n  group_by(`Age`) %>%\n  summarise(Salary=mean(Salary))\nfield_mean <- field_jobs %>%\n  group_by(`Age`) %>%\n  summarise(Salary=mean(Salary))\n\nggplot(NULL, aes(`Age`, `Salary`)) +\n  geom_point(data=workers_tidy, color=\"Red\") +\n  geom_line(data=general_mean, color=\"Red\") +\n  geom_point(data=field_jobs, color=\"Blue\") +\n  geom_line(data=field_mean, color=\"Blue\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: Removed 5 rows containing missing values (`geom_point()`).\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: Removed 1 row containing missing values (`geom_line()`).\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: Removed 1 rows containing missing values (`geom_point()`).\n```\n:::\n\n::: {.cell-output-display}\n![](Matt_Zambetti_FinalProject_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n:::\n\n\nIn this plot, the colors represent the same distributions from the previous combined plot.\n\n## Conclusions\n\nFrom the two main analysis' of this data, I have found a few interesting points and confirmed a few previous thoughts.\n\nAlthough I was able to identify some patterns, there was still a lot left on the table to discover.\n\n### What I've Learned\n\nMy previous thoughts were (1) people in the Data and Software Fields would make slightly more than the average salary. This was confirmed for most ages and levels of experience, but seems to carry less weight as both age and experience grew. \n\n### Lingering Discussion\n\nWhat this data could not provide insight into was the types of companies are these jobs at and what trends can we see there. For example, there could be a software/data science job in a tech company, a finance company, or even an aerospace company and I believe that these would also have a heavy influence on the salary trends. Provided this data, I would use the many similar plots but color coordinate the points to be what category of company was hiring.\n\nThis data also cannot provide geographic data. Cost of living for various cities heavily influences salaries in my experience. Having all of these jobs combined into one plot can provide false insights about what job pays better if the higher paying job is mostly found in a city versus the lower paying one in a suburb.\n\n## Bibliography\n",
    "supporting": [
      "Matt_Zambetti_FinalProject_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}