{
  "hash": "82767d83904700209632bcc74833c6d3",
  "result": {
    "markdown": "---\ntitle: \"Challenge 2 Submission\"\nauthor: \"Xinpeng Liu\"\ndescription: \"Data wrangling: using group() and summarise()\"\ndate: \"5/30/2023\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - challenge_2\n  - railroads\n  - faostat\n  - hotel_bookings\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n\nknitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)\n```\n:::\n\n\n## Challenge Overview\n\nToday's challenge is to\n\n1)  read in a data set, and describe the data using both words and any supporting information (e.g., tables, etc)\n2)  provide summary statistics for different interesting groups within the data, and interpret those statistics\n\n## Read in the Data\n\nRead in one (or more) of the following data sets, available in the `posts/_data` folder, using the correct R package and command.\n\n-   railroad\\*.csv or StateCounty2012.xls ⭐\n-   FAOstat\\*.csv or birds.csv ⭐⭐⭐\n-   hotel_bookings.csv ⭐⭐⭐⭐\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata_railroad <- read_csv(\"_data/railroad_2012_clean_county.csv\")\n```\n:::\n\n\nAdd any comments or documentation as needed. More challenging data may require additional code chunks and documentation.\n\n## Describe the data\n\nUsing a combination of words and results of R commands, can you provide a high level description of the data? Describe as efficiently as possible where/how the data was (likely) gathered, indicate the cases and variables (both the interpretation and any details you deem useful to the reader to fully understand your chosen data).\n\nwe choose -   railroad_2012_clean_county.csv ⭐\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(dplyr)\nstr(data_railroad)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nspc_tbl_ [2,930 × 3] (S3: spec_tbl_df/tbl_df/tbl/data.frame)\n $ state          : chr [1:2930] \"AE\" \"AK\" \"AK\" \"AK\" ...\n $ county         : chr [1:2930] \"APO\" \"ANCHORAGE\" \"FAIRBANKS NORTH STAR\" \"JUNEAU\" ...\n $ total_employees: num [1:2930] 2 7 2 3 2 1 88 102 143 1 ...\n - attr(*, \"spec\")=\n  .. cols(\n  ..   state = col_character(),\n  ..   county = col_character(),\n  ..   total_employees = col_double()\n  .. )\n - attr(*, \"problems\")=<externalptr> \n```\n:::\n\n```{.r .cell-code}\nsummary(data_railroad$total_employees)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n   1.00    7.00   21.00   87.18   65.00 8207.00 \n```\n:::\n:::\n\nThis data set contains information about the total number of employees in different counties across states. The dataset consists of three variables: 'state', 'county', and 'total_employees'.\n\n-'state' (chr): This variable is a character type that represents the abbreviation of each state in the United States. This variable does not have missing values and covers all 50 states plus other regions.\n\n-'county' (chr): This variable is a character type that represents the names of the counties in each state. This variable does not have missing values, and there are multiple counties within each state.\n\n-'total_employees' (int): This variable is an integer type that represents the total number of employees in each county. The values range from a minimum of 1 to a maximum of 8207, with a median of 21 and a mean of 87.18. The standard deviation is high, suggesting a wide spread in the number of employees across counties.\n\nThe data was likely gathered through employment records or surveys in each county and compiled for the year of interest. Each row represents an observation for a specific county in a specific state.\n\n## Provide Grouped Summary Statistics\n\nConduct some exploratory data analysis, using dplyr commands such as `group_by()`, `select()`, `filter()`, and `summarise()`. Find the central tendency (mean, median, mode) and dispersion (standard deviation, mix/max/quantile) for different subgroups within the data set.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata_grouped_by_state <- data_railroad %>%\n  select(state,total_employees) %>%\n  group_by(state) %>%\n  summarize(\n    total_employees_by_state = sum(total_employees, na.rm = TRUE),\n    mean_number_of_employee_per_county = round(mean(total_employees, na.rm = TRUE), 2),\n    median_number_of_employee_per_county = round(median(total_employees, na.rm = TRUE), 2),\n    sd_employees_per_county = round(sd(total_employees, na.rm = TRUE), 2),\n    IQR_employees_per_county = round(IQR(total_employees, na.rm = TRUE),2),\n    min = min(total_employees, na.rm = TRUE),\n    max = max(total_employees, na.rm = TRUE)\n  )\n\n# convert to standard data frame\ndata_grouped_by_state_df <- as.data.frame(data_grouped_by_state)\n\n# print full data frame\nprint(data_grouped_by_state_df)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   state total_employees_by_state mean_number_of_employee_per_county\n1     AE                        2                               2.00\n2     AK                      103                              17.17\n3     AL                     4257                              63.54\n4     AP                        1                               1.00\n5     AR                     3871                              53.76\n6     AZ                     3153                             210.20\n7     CA                    13137                             238.85\n8     CO                     3650                              64.04\n9     CT                     2592                             324.00\n10    DC                      279                             279.00\n11    DE                     1495                             498.33\n12    FL                     7419                             110.73\n13    GA                     8605                              56.61\n14    HI                        4                               1.33\n15    IA                     4019                              40.60\n16    ID                     1563                              43.42\n17    IL                    19131                             185.74\n18    IN                     8537                              92.79\n19    KS                     6092                              64.13\n20    KY                     4811                              40.43\n21    LA                     3915                              62.14\n22    MA                     3379                             281.58\n23    MD                     4709                             196.21\n24    ME                      654                              40.88\n25    MI                     3932                              50.41\n26    MN                     5467                              63.57\n27    MO                     8419                              73.21\n28    MS                     2111                              27.06\n29    MT                     3327                              62.77\n30    NC                     3143                              33.44\n31    ND                     2204                              44.98\n32    NE                    13176                             148.04\n33    NH                      393                              39.30\n34    NJ                     8329                             396.62\n35    NM                     1958                              67.52\n36    NV                      746                              62.17\n37    NY                    17050                             279.51\n38    OH                     9056                             102.91\n39    OK                     2318                              31.75\n40    OR                     2322                              70.36\n41    PA                    12769                             196.45\n42    RI                      487                              97.40\n43    SC                     2296                              49.91\n44    SD                      949                              18.25\n45    TN                     4952                              54.42\n46    TX                    19839                              89.77\n47    UT                     1917                              76.68\n48    VA                     7551                              82.08\n49    VT                      259                              18.50\n50    WA                     5222                             133.90\n51    WI                     3773                              54.68\n52    WV                     3213                              60.62\n53    WY                     2876                             130.73\n   median_number_of_employee_per_county sd_employees_per_county\n1                                   2.0                      NA\n2                                   2.5                   34.76\n3                                  26.0                  130.17\n4                                   1.0                      NA\n5                                  16.5                  131.14\n6                                  94.0                  227.78\n7                                  61.0                  549.47\n8                                  10.0                  127.75\n9                                 125.0                  520.20\n10                                279.0                      NA\n11                                158.0                  674.32\n12                                 20.0                  386.01\n13                                 15.0                  113.13\n14                                  1.0                    0.58\n15                                 14.0                   76.80\n16                                 12.0                   95.55\n17                                 42.0                  829.15\n18                                 30.0                  233.06\n19                                 12.0                  167.36\n20                                 11.0                   76.91\n21                                 20.0                  101.48\n22                                271.0                  203.83\n23                                107.5                  233.28\n24                                 29.0                   38.12\n25                                 13.0                  109.76\n26                                 22.0                  122.39\n27                                 24.0                  208.12\n28                                 11.5                   46.69\n29                                 11.0                  122.95\n30                                 14.0                   58.59\n31                                  8.0                   92.47\n32                                 15.0                  511.58\n33                                 15.5                   54.33\n34                                296.0                  338.22\n35                                 26.0                  112.72\n36                                 19.0                   94.80\n37                                 71.0                  590.78\n38                                 41.0                  147.91\n39                                 14.0                   55.86\n40                                 30.0                  108.45\n41                                 85.0                  293.07\n42                                 48.0                  129.02\n43                                 25.0                   53.91\n44                                  5.0                   34.60\n45                                 26.0                   94.82\n46                                 17.0                  350.12\n47                                 16.0                  142.57\n48                                 25.5                  340.74\n49                                  8.5                   24.54\n50                                 29.0                  255.71\n51                                 23.0                   82.17\n52                                 33.0                   85.75\n53                                 60.5                  168.98\n   IQR_employees_per_county min  max\n1                      0.00   2    2\n2                      4.00   1   88\n3                     47.00   1  990\n4                      0.00   1    1\n5                     33.75   1  972\n6                    296.00   3  749\n7                    188.00   1 2888\n8                     39.00   1  553\n9                    167.25  26 1561\n10                     0.00 279  279\n11                   606.50  62 1275\n12                    57.50   1 3073\n13                    42.50   1  878\n14                     0.50   1    2\n15                    28.50   1  609\n16                    35.50   1  538\n17                    84.00   1 8207\n18                    55.00   3 1999\n19                    47.50   1 1286\n20                    33.50   1  483\n21                    64.00   1  546\n22                   295.00  44  673\n23                   313.75   1  809\n24                    60.25   2  117\n25                    41.00   1  849\n26                    43.75   1  651\n27                    41.00   1 2055\n28                    26.25   1  341\n29                    41.00   1  525\n30                    25.00   1  322\n31                    32.00   1  407\n32                    66.00   1 3797\n33                    20.25   2  146\n34                   474.00  19 1097\n35                    49.00   2  431\n36                    49.50   1  269\n37                   169.00   5 3685\n38                    97.25   3  842\n39                    25.00   1  377\n40                    77.00   2  467\n41                   171.00   3 1649\n42                    91.00   8  318\n43                    56.25   1  220\n44                     9.00   1  167\n45                    49.00   1  621\n46                    50.00   1 4235\n47                    44.00   1  580\n48                    33.25   1 3249\n49                     8.00   3   83\n50                    65.50   1 1039\n51                    45.00   2  465\n52                    68.00   1  406\n53                   159.00   3  737\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ndata <- read.csv(\"_data/railroad_2012_clean_county.csv\")\nlibrary(dplyr)\nlibrary(ggplot2)\n# Calculate the mean\nmean_total_employees <- mean(data$total_employees, na.rm = TRUE)\nprint(paste(\"The mean of total employees is\", mean_total_employees))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"The mean of total employees is 87.178156996587\"\n```\n:::\n\n```{.r .cell-code}\n# Calculate the median\nmedian_total_employees <- median(data$total_employees, na.rm = TRUE)\nprint(paste(\"The median of total employees is\", median_total_employees))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"The median of total employees is 21\"\n```\n:::\n\n```{.r .cell-code}\n# Define a function to calculate the mode\ngetmode <- function(v) {\n  uniqv <- unique(v)\n  uniqv[which.max(tabulate(match(v, uniqv)))]\n}\n\n# Calculate the mode\nmode_total_employees <- getmode(data$total_employees)\nprint(paste(\"The mode of total employees is\", mode_total_employees))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"The mode of total employees is 1\"\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(dplyr)\n\n# Calculate the standard deviation\nsd_total_employees <- sd(data$total_employees, na.rm = TRUE)\nprint(paste(\"The standard deviation of total employees is\", sd_total_employees))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"The standard deviation of total employees is 283.635890179709\"\n```\n:::\n\n```{.r .cell-code}\n# Calculate the minimum\nmin_total_employees <- min(data$total_employees, na.rm = TRUE)\nprint(paste(\"The minimum of total employees is\", min_total_employees))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"The minimum of total employees is 1\"\n```\n:::\n\n```{.r .cell-code}\n# Calculate the maximum\nmax_total_employees <- max(data$total_employees, na.rm = TRUE)\nprint(paste(\"The maximum of total employees is\", max_total_employees))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"The maximum of total employees is 8207\"\n```\n:::\n\n```{.r .cell-code}\n# Calculate the 1st quartile\nfirst_quartile <- quantile(data$total_employees, 0.25, na.rm = TRUE)\nprint(paste(\"The first quartile of total employees is\", first_quartile))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"The first quartile of total employees is 7\"\n```\n:::\n\n```{.r .cell-code}\n# Calculate the 3rd quartile\nthird_quartile <- quantile(data$total_employees, 0.75, na.rm = TRUE)\nprint(paste(\"The third quartile of total employees is\", third_quartile))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"The third quartile of total employees is 65\"\n```\n:::\n:::\n\n### Explain and Interpret\n\nBe sure to explain why you choose a specific group. Comment on the interpretation of any interesting differences between groups that you uncover. This section can be integrated with the exploratory data analysis, just be sure it is included.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Filter for Alabama (AL) and California (CA)\nalabama_data <- data_railroad[data_railroad$state == \"AL\",]\ncalifornia_data <- data_railroad[data_railroad$state == \"CA\",]\n# Display basic statistics for Alabama\nprint(paste(\"The summary of alabama\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"The summary of alabama\"\n```\n:::\n\n```{.r .cell-code}\nsummary(alabama_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n    state              county          total_employees \n Length:67          Length:67          Min.   :  1.00  \n Class :character   Class :character   1st Qu.: 10.50  \n Mode  :character   Mode  :character   Median : 26.00  \n                                       Mean   : 63.54  \n                                       3rd Qu.: 57.50  \n                                       Max.   :990.00  \n```\n:::\n\n```{.r .cell-code}\n# Display basic statistics for California\nprint(paste(\"The summary of California\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"The summary of California\"\n```\n:::\n\n```{.r .cell-code}\nsummary(california_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n    state              county          total_employees \n Length:55          Length:55          Min.   :   1.0  \n Class :character   Class :character   1st Qu.:  12.5  \n Mode  :character   Mode  :character   Median :  61.0  \n                                       Mean   : 238.9  \n                                       3rd Qu.: 200.5  \n                                       Max.   :2888.0  \n```\n:::\n:::\n\nAnalyzing data from different states - Alabama and California - reveals insightful patterns about the distribution of railroad employees across counties. I chose these states to compare given their distinct geographical sizes, population densities, and overall distinct regional characteristics.\n\nAlabama, known as \"The Heart of Dixie,\" has 4257 railroad employees. On average, there are about 63.54 employees in each county. This average might seem small at first, but considering the smaller size and lower population density of Alabama's counties, it makes sense. Interestingly, the median value is 26, suggesting that the number of employees is less evenly distributed, and there are outliers with significantly more employees. The broad standard deviation of 130.17 supports this idea, revealing a wide spread of values around the mean.\n\nOn the other side of the country, California, the \"Golden State,\" has a total of 13137 railroad employees, which is significantly higher than Alabama's. It's no surprise as California is the most populous U.S. state with larger and more urbanized counties. The mean number of employees per county is approximately 238.85, showing a higher overall density of railroad employment. The median is 61, higher than in Alabama, demonstrating that even the counties with fewer employees in California have a larger workforce than most in Alabama. The considerable standard deviation of 549.47 and the wide IQR of 188 tell us about the great variability in California's counties' employment numbers.\n\nThe comparison between these two states brings to light how geographical and demographic factors may impact the distribution and concentration of employment in the railroad industry. Understanding these patterns could be a stepping stone for further research into factors influencing the job market and economic conditions in these states.\n",
    "supporting": [
      "challenge2_solution_Xinpeng_Liu_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}