{
  "hash": "66e6acf3b38a33dfb4265e1dfdd54133",
  "result": {
    "markdown": "---\ntitle: \"Challenge 3 Post\"\nauthor: \"Hunter Major\"\ndescription: \"Tidy Data: Pivoting\"\ndate: \"6/8/2023\"\nformat:\n  html:\n    df-print: paged\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - challenge_3\n  - animal_weights\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(dplyr)\nlibrary(readr)\nlibrary(readxl)\n\n\nknitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)\n```\n:::\n\n\n## Challenge Overview\n\nToday's challenge is to:\n\n1.  read in a data set, and describe the data set using both words and any supporting information (e.g., tables, etc)\n2.  identify what needs to be done to tidy the current data\n3.  anticipate the shape of pivoted data\n4.  pivot the data into tidy format using `pivot_longer`\n\n## Read in data\n\nRead in one (or more) of the following datasets, using the correct R package and command.\n\n-  For challenge 3, I'll be reading in data from animal_weights.csv ⭐\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nread.csv(\"_data/animal_weight.csv\")\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"IPCC.Area\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Cattle...dairy\"],\"name\":[2],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"Cattle...non.dairy\"],\"name\":[3],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"Buffaloes\"],\"name\":[4],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"Swine...market\"],\"name\":[5],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"Swine...breeding\"],\"name\":[6],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"Chicken...Broilers\"],\"name\":[7],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Chicken...Layers\"],\"name\":[8],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Ducks\"],\"name\":[9],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Turkeys\"],\"name\":[10],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Sheep\"],\"name\":[11],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Goats\"],\"name\":[12],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Horses\"],\"name\":[13],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"Asses\"],\"name\":[14],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"Mules\"],\"name\":[15],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"Camels\"],\"name\":[16],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"Llamas\"],\"name\":[17],\"type\":[\"int\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"Indian Subcontinent\",\"2\":\"275\",\"3\":\"110\",\"4\":\"295\",\"5\":\"28\",\"6\":\"28\",\"7\":\"0.9\",\"8\":\"1.8\",\"9\":\"2.7\",\"10\":\"6.8\",\"11\":\"28.0\",\"12\":\"30.0\",\"13\":\"238\",\"14\":\"130\",\"15\":\"130\",\"16\":\"217\",\"17\":\"217\"},{\"1\":\"Eastern Europe\",\"2\":\"550\",\"3\":\"391\",\"4\":\"380\",\"5\":\"50\",\"6\":\"180\",\"7\":\"0.9\",\"8\":\"1.8\",\"9\":\"2.7\",\"10\":\"6.8\",\"11\":\"48.5\",\"12\":\"38.5\",\"13\":\"377\",\"14\":\"130\",\"15\":\"130\",\"16\":\"217\",\"17\":\"217\"},{\"1\":\"Africa\",\"2\":\"275\",\"3\":\"173\",\"4\":\"380\",\"5\":\"28\",\"6\":\"28\",\"7\":\"0.9\",\"8\":\"1.8\",\"9\":\"2.7\",\"10\":\"6.8\",\"11\":\"28.0\",\"12\":\"30.0\",\"13\":\"238\",\"14\":\"130\",\"15\":\"130\",\"16\":\"217\",\"17\":\"217\"},{\"1\":\"Oceania\",\"2\":\"500\",\"3\":\"330\",\"4\":\"380\",\"5\":\"45\",\"6\":\"180\",\"7\":\"0.9\",\"8\":\"1.8\",\"9\":\"2.7\",\"10\":\"6.8\",\"11\":\"48.5\",\"12\":\"38.5\",\"13\":\"377\",\"14\":\"130\",\"15\":\"130\",\"16\":\"217\",\"17\":\"217\"},{\"1\":\"Western Europe\",\"2\":\"600\",\"3\":\"420\",\"4\":\"380\",\"5\":\"50\",\"6\":\"198\",\"7\":\"0.9\",\"8\":\"1.8\",\"9\":\"2.7\",\"10\":\"6.8\",\"11\":\"48.5\",\"12\":\"38.5\",\"13\":\"377\",\"14\":\"130\",\"15\":\"130\",\"16\":\"217\",\"17\":\"217\"},{\"1\":\"Latin America\",\"2\":\"400\",\"3\":\"305\",\"4\":\"380\",\"5\":\"28\",\"6\":\"28\",\"7\":\"0.9\",\"8\":\"1.8\",\"9\":\"2.7\",\"10\":\"6.8\",\"11\":\"28.0\",\"12\":\"30.0\",\"13\":\"238\",\"14\":\"130\",\"15\":\"130\",\"16\":\"217\",\"17\":\"217\"},{\"1\":\"Asia\",\"2\":\"350\",\"3\":\"391\",\"4\":\"380\",\"5\":\"50\",\"6\":\"180\",\"7\":\"0.9\",\"8\":\"1.8\",\"9\":\"2.7\",\"10\":\"6.8\",\"11\":\"48.5\",\"12\":\"38.5\",\"13\":\"377\",\"14\":\"130\",\"15\":\"130\",\"16\":\"217\",\"17\":\"217\"},{\"1\":\"Middle east\",\"2\":\"275\",\"3\":\"173\",\"4\":\"380\",\"5\":\"28\",\"6\":\"28\",\"7\":\"0.9\",\"8\":\"1.8\",\"9\":\"2.7\",\"10\":\"6.8\",\"11\":\"28.0\",\"12\":\"30.0\",\"13\":\"238\",\"14\":\"130\",\"15\":\"130\",\"16\":\"217\",\"17\":\"217\"},{\"1\":\"Northern America\",\"2\":\"604\",\"3\":\"389\",\"4\":\"380\",\"5\":\"46\",\"6\":\"198\",\"7\":\"0.9\",\"8\":\"1.8\",\"9\":\"2.7\",\"10\":\"6.8\",\"11\":\"48.5\",\"12\":\"38.5\",\"13\":\"377\",\"14\":\"130\",\"15\":\"130\",\"16\":\"217\",\"17\":\"217\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nweights <- read.csv(\"_data/animal_weight.csv\")\n```\n:::\n\nI renamed \"animal_weight\" to \"weights\" for convenience.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(weights)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  IPCC.Area         Cattle...dairy  Cattle...non.dairy   Buffaloes    \n Length:9           Min.   :275.0   Min.   :110        Min.   :295.0  \n Class :character   1st Qu.:275.0   1st Qu.:173        1st Qu.:380.0  \n Mode  :character   Median :400.0   Median :330        Median :380.0  \n                    Mean   :425.4   Mean   :298        Mean   :370.6  \n                    3rd Qu.:550.0   3rd Qu.:391        3rd Qu.:380.0  \n                    Max.   :604.0   Max.   :420        Max.   :380.0  \n Swine...market  Swine...breeding Chicken...Broilers Chicken...Layers\n Min.   :28.00   Min.   : 28.0    Min.   :0.9        Min.   :1.8     \n 1st Qu.:28.00   1st Qu.: 28.0    1st Qu.:0.9        1st Qu.:1.8     \n Median :45.00   Median :180.0    Median :0.9        Median :1.8     \n Mean   :39.22   Mean   :116.4    Mean   :0.9        Mean   :1.8     \n 3rd Qu.:50.00   3rd Qu.:180.0    3rd Qu.:0.9        3rd Qu.:1.8     \n Max.   :50.00   Max.   :198.0    Max.   :0.9        Max.   :1.8     \n     Ducks        Turkeys        Sheep           Goats           Horses     \n Min.   :2.7   Min.   :6.8   Min.   :28.00   Min.   :30.00   Min.   :238.0  \n 1st Qu.:2.7   1st Qu.:6.8   1st Qu.:28.00   1st Qu.:30.00   1st Qu.:238.0  \n Median :2.7   Median :6.8   Median :48.50   Median :38.50   Median :377.0  \n Mean   :2.7   Mean   :6.8   Mean   :39.39   Mean   :34.72   Mean   :315.2  \n 3rd Qu.:2.7   3rd Qu.:6.8   3rd Qu.:48.50   3rd Qu.:38.50   3rd Qu.:377.0  \n Max.   :2.7   Max.   :6.8   Max.   :48.50   Max.   :38.50   Max.   :377.0  \n     Asses         Mules         Camels        Llamas   \n Min.   :130   Min.   :130   Min.   :217   Min.   :217  \n 1st Qu.:130   1st Qu.:130   1st Qu.:217   1st Qu.:217  \n Median :130   Median :130   Median :217   Median :217  \n Mean   :130   Mean   :130   Mean   :217   Mean   :217  \n 3rd Qu.:130   3rd Qu.:130   3rd Qu.:217   3rd Qu.:217  \n Max.   :130   Max.   :130   Max.   :217   Max.   :217  \n```\n:::\n\n```{.r .cell-code}\ndim(weights)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1]  9 17\n```\n:::\n:::\n\n\n\n### Briefly describe the data\n\nThis dataset provides information about animal weights by type of animal and region in the world in which they are found. From running the summary () and dim () functions, I determined that this dataset has  This dataset contains 9 rows and 17 columns. The IPCC Area column contains character values, listing global regions. On the other hand, all other columns, organized by animal type, have numeric values--the weight of the animals. IPCC stands for the Intergovernmental Panel on Climate Change, which is a panel within the United Nations, so this dataset sourced from research undertaken by this body within the UN. From the summary () function we can see that some animal types have more than one column--namely cattle (which has a dairy and non-dairy column), swine (which has a market and breeding column), and chicken (which has a broilers and layers column). Notwithstanding the animal types with 2 columns, because each animal type currently has its own column(s), each animal type is currently its own variable. In other words, the overarching category of animal/animal type is not currently a variable. The overarching category of animal weight is also not its own distinct column/variable currently. To tidy the data, I'd pivot it so that the variable of animal weight can be sorted alongside variables of animal type and IPCC Area/global region.\n\n## Anticipate the End Result\n\nThe first step in pivoting the data is to try to come up with a concrete vision of what the end product *should* look like - that way you will know whether or not your pivoting was successful.\n\nOne easy way to do this is to think about the dimensions of your current data (tibble, dataframe, or matrix), and then calculate what the dimensions of the pivoted data should be.\n\nSuppose you have a dataset with $n$ rows and $k$ variables. In our example, 3 of the variables are used to identify a case, so you will be pivoting $k-3$ variables into a longer format where the $k-3$ variable names will move into the `names_to` variable and the current values in each of those columns will move into the `values_to` variable. Therefore, we would expect $n * (k-3)$ rows in the pivoted dataframe!\n\n### Example: find current and future data dimensions\n\nLets see if this works with a simple example.\n\n\n::: {.cell tbl-cap='Example'}\n\n```{.r .cell-code}\ndf<-tibble(country = rep(c(\"Mexico\", \"USA\", \"France\"),2),\n           year = rep(c(1980,1990), 3), \n           trade = rep(c(\"NAFTA\", \"NAFTA\", \"EU\"),2),\n           outgoing = rnorm(6, mean=1000, sd=500),\n           incoming = rlogis(6, location=1000, \n                             scale = 400))\ndf\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"country\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"year\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"trade\"],\"name\":[3],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"outgoing\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"incoming\"],\"name\":[5],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"Mexico\",\"2\":\"1980\",\"3\":\"NAFTA\",\"4\":\"1233.3125\",\"5\":\"843.2405\"},{\"1\":\"USA\",\"2\":\"1990\",\"3\":\"NAFTA\",\"4\":\"1169.3320\",\"5\":\"1700.2579\"},{\"1\":\"France\",\"2\":\"1980\",\"3\":\"EU\",\"4\":\"1288.8642\",\"5\":\"1359.3727\"},{\"1\":\"Mexico\",\"2\":\"1990\",\"3\":\"NAFTA\",\"4\":\"1055.9538\",\"5\":\"1126.8965\"},{\"1\":\"USA\",\"2\":\"1980\",\"3\":\"NAFTA\",\"4\":\"936.3313\",\"5\":\"1376.5207\"},{\"1\":\"France\",\"2\":\"1990\",\"3\":\"EU\",\"4\":\"330.7682\",\"5\":\"2266.3367\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n\n```{.r .cell-code}\n#existing rows/cases\nnrow(df)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 6\n```\n:::\n\n```{.r .cell-code}\n#existing columns/cases\nncol(df)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 5\n```\n:::\n\n```{.r .cell-code}\n#expected rows/cases\nnrow(df) * (ncol(df)-3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 12\n```\n:::\n\n```{.r .cell-code}\n# expected columns \n3 + 2\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 5\n```\n:::\n:::\n\n\nOr simple example has $n = 6$ rows and $k - 3 = 2$ variables being pivoted, so we expect a new dataframe to have $n * 2 = 12$ rows x $3 + 2 = 5$ columns.\n\n### Challenge: Describe the final dimensions\n\n As stated previously, the original version of the dataset that I read in had 9 rows and 17 columns/variables. IPCC Area will remain a variable/column, whereas the other 16 variables I am pivoting will transform into two columns/variables animal type (which will list character values) and weights (which will list numerical values). So n= 9 rows and k= 17 variables, and I'll be pivoting 16 or (k-1) variables. The tidy version of this dataset should then have 144 rows, because of the 9 rows multiplied by the 16 variables pivoted and 3 columns/variables--one original variable-IPCC Area and two new ones.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# original rows\nnrow(weights)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 9\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# original columns\nncol(weights)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 17\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# expected rows\nnrow(weights) * (ncol(weights)-1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 144\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# expected columns\n1 + 1\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 2\n```\n:::\n:::\n\n\nThe calculations determined that the dataset will now have 144 rows as expected.\n\n## Pivot the Data\n\nNow we will pivot the data, and compare our pivoted data dimensions to the dimensions calculated above as a \"sanity\" check.\n\n### Example\n\n\n::: {.cell tbl-cap='Pivoted Example'}\n\n```{.r .cell-code}\ndf<-pivot_longer(df, col = c(outgoing, incoming),\n                 names_to=\"trade_direction\",\n                 values_to = \"trade_value\")\ndf\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"country\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"year\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"trade\"],\"name\":[3],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"trade_direction\"],\"name\":[4],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"trade_value\"],\"name\":[5],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"Mexico\",\"2\":\"1980\",\"3\":\"NAFTA\",\"4\":\"outgoing\",\"5\":\"1233.3125\"},{\"1\":\"Mexico\",\"2\":\"1980\",\"3\":\"NAFTA\",\"4\":\"incoming\",\"5\":\"843.2405\"},{\"1\":\"USA\",\"2\":\"1990\",\"3\":\"NAFTA\",\"4\":\"outgoing\",\"5\":\"1169.3320\"},{\"1\":\"USA\",\"2\":\"1990\",\"3\":\"NAFTA\",\"4\":\"incoming\",\"5\":\"1700.2579\"},{\"1\":\"France\",\"2\":\"1980\",\"3\":\"EU\",\"4\":\"outgoing\",\"5\":\"1288.8642\"},{\"1\":\"France\",\"2\":\"1980\",\"3\":\"EU\",\"4\":\"incoming\",\"5\":\"1359.3727\"},{\"1\":\"Mexico\",\"2\":\"1990\",\"3\":\"NAFTA\",\"4\":\"outgoing\",\"5\":\"1055.9538\"},{\"1\":\"Mexico\",\"2\":\"1990\",\"3\":\"NAFTA\",\"4\":\"incoming\",\"5\":\"1126.8965\"},{\"1\":\"USA\",\"2\":\"1980\",\"3\":\"NAFTA\",\"4\":\"outgoing\",\"5\":\"936.3313\"},{\"1\":\"USA\",\"2\":\"1980\",\"3\":\"NAFTA\",\"4\":\"incoming\",\"5\":\"1376.5207\"},{\"1\":\"France\",\"2\":\"1990\",\"3\":\"EU\",\"4\":\"outgoing\",\"5\":\"330.7682\"},{\"1\":\"France\",\"2\":\"1990\",\"3\":\"EU\",\"4\":\"incoming\",\"5\":\"2266.3367\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\nYes, once it is pivoted long, our resulting data are $12x5$ - exactly what we expected!\n\n### Challenge: Pivot the Chosen Data\n\nDocument your work here. What will a new \"case\" be once you have pivoted the data? How does it meet requirements for tidy data?\n\n\n::: {.cell}\n\n```{.r .cell-code}\npivot_longer(weights, \"Cattle...dairy\" : \"Llamas\",\n             names_to = \"animal_type\",\n             values_to = \"weights\")\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"IPCC.Area\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"animal_type\"],\"name\":[2],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"weights\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"Indian Subcontinent\",\"2\":\"Cattle...dairy\",\"3\":\"275.0\"},{\"1\":\"Indian Subcontinent\",\"2\":\"Cattle...non.dairy\",\"3\":\"110.0\"},{\"1\":\"Indian Subcontinent\",\"2\":\"Buffaloes\",\"3\":\"295.0\"},{\"1\":\"Indian Subcontinent\",\"2\":\"Swine...market\",\"3\":\"28.0\"},{\"1\":\"Indian Subcontinent\",\"2\":\"Swine...breeding\",\"3\":\"28.0\"},{\"1\":\"Indian Subcontinent\",\"2\":\"Chicken...Broilers\",\"3\":\"0.9\"},{\"1\":\"Indian Subcontinent\",\"2\":\"Chicken...Layers\",\"3\":\"1.8\"},{\"1\":\"Indian Subcontinent\",\"2\":\"Ducks\",\"3\":\"2.7\"},{\"1\":\"Indian Subcontinent\",\"2\":\"Turkeys\",\"3\":\"6.8\"},{\"1\":\"Indian Subcontinent\",\"2\":\"Sheep\",\"3\":\"28.0\"},{\"1\":\"Indian Subcontinent\",\"2\":\"Goats\",\"3\":\"30.0\"},{\"1\":\"Indian Subcontinent\",\"2\":\"Horses\",\"3\":\"238.0\"},{\"1\":\"Indian Subcontinent\",\"2\":\"Asses\",\"3\":\"130.0\"},{\"1\":\"Indian Subcontinent\",\"2\":\"Mules\",\"3\":\"130.0\"},{\"1\":\"Indian Subcontinent\",\"2\":\"Camels\",\"3\":\"217.0\"},{\"1\":\"Indian Subcontinent\",\"2\":\"Llamas\",\"3\":\"217.0\"},{\"1\":\"Eastern Europe\",\"2\":\"Cattle...dairy\",\"3\":\"550.0\"},{\"1\":\"Eastern Europe\",\"2\":\"Cattle...non.dairy\",\"3\":\"391.0\"},{\"1\":\"Eastern Europe\",\"2\":\"Buffaloes\",\"3\":\"380.0\"},{\"1\":\"Eastern Europe\",\"2\":\"Swine...market\",\"3\":\"50.0\"},{\"1\":\"Eastern Europe\",\"2\":\"Swine...breeding\",\"3\":\"180.0\"},{\"1\":\"Eastern Europe\",\"2\":\"Chicken...Broilers\",\"3\":\"0.9\"},{\"1\":\"Eastern Europe\",\"2\":\"Chicken...Layers\",\"3\":\"1.8\"},{\"1\":\"Eastern Europe\",\"2\":\"Ducks\",\"3\":\"2.7\"},{\"1\":\"Eastern Europe\",\"2\":\"Turkeys\",\"3\":\"6.8\"},{\"1\":\"Eastern Europe\",\"2\":\"Sheep\",\"3\":\"48.5\"},{\"1\":\"Eastern Europe\",\"2\":\"Goats\",\"3\":\"38.5\"},{\"1\":\"Eastern Europe\",\"2\":\"Horses\",\"3\":\"377.0\"},{\"1\":\"Eastern Europe\",\"2\":\"Asses\",\"3\":\"130.0\"},{\"1\":\"Eastern Europe\",\"2\":\"Mules\",\"3\":\"130.0\"},{\"1\":\"Eastern Europe\",\"2\":\"Camels\",\"3\":\"217.0\"},{\"1\":\"Eastern Europe\",\"2\":\"Llamas\",\"3\":\"217.0\"},{\"1\":\"Africa\",\"2\":\"Cattle...dairy\",\"3\":\"275.0\"},{\"1\":\"Africa\",\"2\":\"Cattle...non.dairy\",\"3\":\"173.0\"},{\"1\":\"Africa\",\"2\":\"Buffaloes\",\"3\":\"380.0\"},{\"1\":\"Africa\",\"2\":\"Swine...market\",\"3\":\"28.0\"},{\"1\":\"Africa\",\"2\":\"Swine...breeding\",\"3\":\"28.0\"},{\"1\":\"Africa\",\"2\":\"Chicken...Broilers\",\"3\":\"0.9\"},{\"1\":\"Africa\",\"2\":\"Chicken...Layers\",\"3\":\"1.8\"},{\"1\":\"Africa\",\"2\":\"Ducks\",\"3\":\"2.7\"},{\"1\":\"Africa\",\"2\":\"Turkeys\",\"3\":\"6.8\"},{\"1\":\"Africa\",\"2\":\"Sheep\",\"3\":\"28.0\"},{\"1\":\"Africa\",\"2\":\"Goats\",\"3\":\"30.0\"},{\"1\":\"Africa\",\"2\":\"Horses\",\"3\":\"238.0\"},{\"1\":\"Africa\",\"2\":\"Asses\",\"3\":\"130.0\"},{\"1\":\"Africa\",\"2\":\"Mules\",\"3\":\"130.0\"},{\"1\":\"Africa\",\"2\":\"Camels\",\"3\":\"217.0\"},{\"1\":\"Africa\",\"2\":\"Llamas\",\"3\":\"217.0\"},{\"1\":\"Oceania\",\"2\":\"Cattle...dairy\",\"3\":\"500.0\"},{\"1\":\"Oceania\",\"2\":\"Cattle...non.dairy\",\"3\":\"330.0\"},{\"1\":\"Oceania\",\"2\":\"Buffaloes\",\"3\":\"380.0\"},{\"1\":\"Oceania\",\"2\":\"Swine...market\",\"3\":\"45.0\"},{\"1\":\"Oceania\",\"2\":\"Swine...breeding\",\"3\":\"180.0\"},{\"1\":\"Oceania\",\"2\":\"Chicken...Broilers\",\"3\":\"0.9\"},{\"1\":\"Oceania\",\"2\":\"Chicken...Layers\",\"3\":\"1.8\"},{\"1\":\"Oceania\",\"2\":\"Ducks\",\"3\":\"2.7\"},{\"1\":\"Oceania\",\"2\":\"Turkeys\",\"3\":\"6.8\"},{\"1\":\"Oceania\",\"2\":\"Sheep\",\"3\":\"48.5\"},{\"1\":\"Oceania\",\"2\":\"Goats\",\"3\":\"38.5\"},{\"1\":\"Oceania\",\"2\":\"Horses\",\"3\":\"377.0\"},{\"1\":\"Oceania\",\"2\":\"Asses\",\"3\":\"130.0\"},{\"1\":\"Oceania\",\"2\":\"Mules\",\"3\":\"130.0\"},{\"1\":\"Oceania\",\"2\":\"Camels\",\"3\":\"217.0\"},{\"1\":\"Oceania\",\"2\":\"Llamas\",\"3\":\"217.0\"},{\"1\":\"Western Europe\",\"2\":\"Cattle...dairy\",\"3\":\"600.0\"},{\"1\":\"Western Europe\",\"2\":\"Cattle...non.dairy\",\"3\":\"420.0\"},{\"1\":\"Western Europe\",\"2\":\"Buffaloes\",\"3\":\"380.0\"},{\"1\":\"Western Europe\",\"2\":\"Swine...market\",\"3\":\"50.0\"},{\"1\":\"Western Europe\",\"2\":\"Swine...breeding\",\"3\":\"198.0\"},{\"1\":\"Western Europe\",\"2\":\"Chicken...Broilers\",\"3\":\"0.9\"},{\"1\":\"Western Europe\",\"2\":\"Chicken...Layers\",\"3\":\"1.8\"},{\"1\":\"Western Europe\",\"2\":\"Ducks\",\"3\":\"2.7\"},{\"1\":\"Western Europe\",\"2\":\"Turkeys\",\"3\":\"6.8\"},{\"1\":\"Western Europe\",\"2\":\"Sheep\",\"3\":\"48.5\"},{\"1\":\"Western Europe\",\"2\":\"Goats\",\"3\":\"38.5\"},{\"1\":\"Western Europe\",\"2\":\"Horses\",\"3\":\"377.0\"},{\"1\":\"Western Europe\",\"2\":\"Asses\",\"3\":\"130.0\"},{\"1\":\"Western Europe\",\"2\":\"Mules\",\"3\":\"130.0\"},{\"1\":\"Western Europe\",\"2\":\"Camels\",\"3\":\"217.0\"},{\"1\":\"Western Europe\",\"2\":\"Llamas\",\"3\":\"217.0\"},{\"1\":\"Latin America\",\"2\":\"Cattle...dairy\",\"3\":\"400.0\"},{\"1\":\"Latin America\",\"2\":\"Cattle...non.dairy\",\"3\":\"305.0\"},{\"1\":\"Latin America\",\"2\":\"Buffaloes\",\"3\":\"380.0\"},{\"1\":\"Latin America\",\"2\":\"Swine...market\",\"3\":\"28.0\"},{\"1\":\"Latin America\",\"2\":\"Swine...breeding\",\"3\":\"28.0\"},{\"1\":\"Latin America\",\"2\":\"Chicken...Broilers\",\"3\":\"0.9\"},{\"1\":\"Latin America\",\"2\":\"Chicken...Layers\",\"3\":\"1.8\"},{\"1\":\"Latin America\",\"2\":\"Ducks\",\"3\":\"2.7\"},{\"1\":\"Latin America\",\"2\":\"Turkeys\",\"3\":\"6.8\"},{\"1\":\"Latin America\",\"2\":\"Sheep\",\"3\":\"28.0\"},{\"1\":\"Latin America\",\"2\":\"Goats\",\"3\":\"30.0\"},{\"1\":\"Latin America\",\"2\":\"Horses\",\"3\":\"238.0\"},{\"1\":\"Latin America\",\"2\":\"Asses\",\"3\":\"130.0\"},{\"1\":\"Latin America\",\"2\":\"Mules\",\"3\":\"130.0\"},{\"1\":\"Latin America\",\"2\":\"Camels\",\"3\":\"217.0\"},{\"1\":\"Latin America\",\"2\":\"Llamas\",\"3\":\"217.0\"},{\"1\":\"Asia\",\"2\":\"Cattle...dairy\",\"3\":\"350.0\"},{\"1\":\"Asia\",\"2\":\"Cattle...non.dairy\",\"3\":\"391.0\"},{\"1\":\"Asia\",\"2\":\"Buffaloes\",\"3\":\"380.0\"},{\"1\":\"Asia\",\"2\":\"Swine...market\",\"3\":\"50.0\"},{\"1\":\"Asia\",\"2\":\"Swine...breeding\",\"3\":\"180.0\"},{\"1\":\"Asia\",\"2\":\"Chicken...Broilers\",\"3\":\"0.9\"},{\"1\":\"Asia\",\"2\":\"Chicken...Layers\",\"3\":\"1.8\"},{\"1\":\"Asia\",\"2\":\"Ducks\",\"3\":\"2.7\"},{\"1\":\"Asia\",\"2\":\"Turkeys\",\"3\":\"6.8\"},{\"1\":\"Asia\",\"2\":\"Sheep\",\"3\":\"48.5\"},{\"1\":\"Asia\",\"2\":\"Goats\",\"3\":\"38.5\"},{\"1\":\"Asia\",\"2\":\"Horses\",\"3\":\"377.0\"},{\"1\":\"Asia\",\"2\":\"Asses\",\"3\":\"130.0\"},{\"1\":\"Asia\",\"2\":\"Mules\",\"3\":\"130.0\"},{\"1\":\"Asia\",\"2\":\"Camels\",\"3\":\"217.0\"},{\"1\":\"Asia\",\"2\":\"Llamas\",\"3\":\"217.0\"},{\"1\":\"Middle east\",\"2\":\"Cattle...dairy\",\"3\":\"275.0\"},{\"1\":\"Middle east\",\"2\":\"Cattle...non.dairy\",\"3\":\"173.0\"},{\"1\":\"Middle east\",\"2\":\"Buffaloes\",\"3\":\"380.0\"},{\"1\":\"Middle east\",\"2\":\"Swine...market\",\"3\":\"28.0\"},{\"1\":\"Middle east\",\"2\":\"Swine...breeding\",\"3\":\"28.0\"},{\"1\":\"Middle east\",\"2\":\"Chicken...Broilers\",\"3\":\"0.9\"},{\"1\":\"Middle east\",\"2\":\"Chicken...Layers\",\"3\":\"1.8\"},{\"1\":\"Middle east\",\"2\":\"Ducks\",\"3\":\"2.7\"},{\"1\":\"Middle east\",\"2\":\"Turkeys\",\"3\":\"6.8\"},{\"1\":\"Middle east\",\"2\":\"Sheep\",\"3\":\"28.0\"},{\"1\":\"Middle east\",\"2\":\"Goats\",\"3\":\"30.0\"},{\"1\":\"Middle east\",\"2\":\"Horses\",\"3\":\"238.0\"},{\"1\":\"Middle east\",\"2\":\"Asses\",\"3\":\"130.0\"},{\"1\":\"Middle east\",\"2\":\"Mules\",\"3\":\"130.0\"},{\"1\":\"Middle east\",\"2\":\"Camels\",\"3\":\"217.0\"},{\"1\":\"Middle east\",\"2\":\"Llamas\",\"3\":\"217.0\"},{\"1\":\"Northern America\",\"2\":\"Cattle...dairy\",\"3\":\"604.0\"},{\"1\":\"Northern America\",\"2\":\"Cattle...non.dairy\",\"3\":\"389.0\"},{\"1\":\"Northern America\",\"2\":\"Buffaloes\",\"3\":\"380.0\"},{\"1\":\"Northern America\",\"2\":\"Swine...market\",\"3\":\"46.0\"},{\"1\":\"Northern America\",\"2\":\"Swine...breeding\",\"3\":\"198.0\"},{\"1\":\"Northern America\",\"2\":\"Chicken...Broilers\",\"3\":\"0.9\"},{\"1\":\"Northern America\",\"2\":\"Chicken...Layers\",\"3\":\"1.8\"},{\"1\":\"Northern America\",\"2\":\"Ducks\",\"3\":\"2.7\"},{\"1\":\"Northern America\",\"2\":\"Turkeys\",\"3\":\"6.8\"},{\"1\":\"Northern America\",\"2\":\"Sheep\",\"3\":\"48.5\"},{\"1\":\"Northern America\",\"2\":\"Goats\",\"3\":\"38.5\"},{\"1\":\"Northern America\",\"2\":\"Horses\",\"3\":\"377.0\"},{\"1\":\"Northern America\",\"2\":\"Asses\",\"3\":\"130.0\"},{\"1\":\"Northern America\",\"2\":\"Mules\",\"3\":\"130.0\"},{\"1\":\"Northern America\",\"2\":\"Camels\",\"3\":\"217.0\"},{\"1\":\"Northern America\",\"2\":\"Llamas\",\"3\":\"217.0\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\nThe final dataset has 3 columns and 144 rows, which aligns with my original expectations. Before a row/case listed IPCC Area and weights for each of the 16 animal types included in the study. Now a row/case includes the weight of the animal by the type of the animal and IPCC Area/global region. It is evident that this dataset now better adhere's to Wickham's conditions for tidy data: Now, each variable has a distinct column--for example, weight values are no longer spread across multiple columns. Furthermore, each observation now has its own row--for example, we now clearly read across from left to right that in the Indian Subcontinent, sheeps have a weight value of 28.0. Lastly, each value has its own cell--I believe this was the case in the original version and in the tidy version I created.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\r\n<script src=\"../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\r\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}