---
title: "Challenge 9 Instructions"
author: "Moira Chiong"
description: "Creating a function"
date: "7/4/2023"
format:
  html:
    toc: true
    code-copy: true
    code-tools: true
categories:
  - challenge_9
---

```{r}
#| label: setup
#| warning: false
#| message: false

library(tidyverse)
library(ggplot2)

knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)
```


```{r}

library(readxl)
setwd("C:/Users/chion/OneDrive/Desktop/DACSS 601/DACSS_601_Summer2023_Sec1/posts")
read_excel("datafolderMoiraChiong/pseo_ma_SANDBOX.xlsx")
View(pseo_ma_SANDBOX)
```


```{r}
pseo_ma_SANDBOX
y1_ipedscount<- as.numeric(pseo_ma_SANDBOX$y1_ipeds_count)
y1_gradsearn<- as.numeric(pseo_ma_SANDBOX$y1_grads_earn)
df1 <- data.frame(y1_ipedscount,y1_gradsearn)
```

```{r}
calculate_percent_employed <- function(y1_ipedscount, y1_gradsearn)
  {
    (df1$y1_gradsearn)/(df1$y1_ipedscount)
}
calculate_percent_employed()
```




## Challenge Overview

Today's challenge is simple. Create a function, and use it to perform a data analysis / cleaning / visualization task:

Examples of such functions are:
1) A function that reads in and cleans a dataset.  
2) A function that computes summary statistics (e.g., computes the z score for a variable).  
3) A function that plots a histogram.  

That's it!








